<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $rows */
?>
<?php use Phalcon\Tag; ?>
<?php $title = '構成部品在庫照会'; ?>
<div class="page-header">
    <h3>構成部品在庫照会</h3>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "zaiko_kakunin_azukari_vws/kouseibuhin_zaiko",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-8">
            <label for="fieldShouhin_mr_cd" class="col-sm-2 control-label">完成品コード ></label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("shouhin_mr_cd", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldShouhin_mr_cd")) ?>
            </div>
            <div class="col-sm-5">
                <?php echo $this->tag->textField(array("name", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldName", "readonly" => "readonly")) ?>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-4">
                <button id="dl-xlsx" class="submit btn btn-warning">EXCEL出力</button>
            </div>
            <div class="col-sm-4">
                <?php echo $this->tag->submitButton(array("集計　F12", "id" => "F12", "class" => "btn btn-success")) ?>
            </div>
        </div>
        <div class="col-sm-8">
            <label for="fieldSuuryou" class="col-sm-2 control-label">必要数量 ></label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("suuryou", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldSuuryou")) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
        <tr style="background-color: lavender;">
            <th nowrap style="text-align:center;">部品コード</th>
            <th nowrap style="text-align:center;">部品名</th>
            <th nowrap style="text-align:center;">単位</th>
            <th nowrap style="text-align:center;">現在庫量</th>
            <th nowrap style="text-align:center;">発注残量</th>
            <th nowrap style="text-align:center;">引当量</th>
            <th nowrap style="text-align:center;">受注残量</th>
            <th nowrap style="text-align:center;">予定在庫量</th>
            <th nowrap style="text-align:center;">必要数量</th>
            <th nowrap style="text-align:center;">構成数量</th>
            <th nowrap style="text-align:center;">過不足量</th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($rows) && count($rows) !== 0) : ?>
            <?php foreach ($rows as $row): ?>
                <tr>
                    <td style="text-align: center;"><?php echo $row['genryou_cd']; ?></td>
                    <td style="text-align: left;text-indent:1em;"><?php echo $row['genryou_name']; ?></td>
                    <td style="text-align:center;"><?php echo $row['tanni']; ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['zaiko2'] < 0 ? 'red' : 'black'; ?>;"><?php echo $row['zaiko_kbn'] === '1' ? number_format($row['zaiko1'],2) : number_format($row['zaiko2'], 2); ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['hacchuuzan2'] < 0 ? 'red' : 'black'; ?>;"><?php echo $row['zaiko_kbn'] === '1' ? number_format($row['hacchuuzan1'], 2) : number_format($row['hacchuuzan2'],2); ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['hikiate2'] < 0 ? 'red' : 'black'; ?>;"><?php echo $row['zaiko_kbn'] === '1' ? number_format($row['hikiate1'], 2) : number_format($row['hikiate2'],2); ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['juchuuzan2'] < 0 ? 'red' : 'black'; ?>;"><?php echo $row['zaiko_kbn'] === '1' ? number_format($row['juchuuzan1'], 2) : number_format($row['juchuuzan2'],2); ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['zaiko2'] < 0 ? 'red' : 'black'; ?>;"><?php
                        if ($row['zaiko_kbn'] === '1') {
                            $result = (float)$row['zaiko1'] + (float)$row['hacchuuzan1'] - (float)$row['hikiate1'] - (float)$row['juchuuzan1'];
                        } else {
                            $result = (float)$row['zaiko2'] + (float)$row['hacchuuzan2'] - (float)$row['hikiate2'] - (float)$row['juchuuzan2'];
                        }
                        echo number_format($result, 2);
                        ?>
                    </td>
                    <td style="text-align:right;"><?php
                        $num = $this->request->getPost('suuryou') ?? 0.0;
                        $hituyousuu = (float)$num * (float)$row['kousei_suuryou'];
                        echo number_format($hituyousuu,2);
                        ?>
                    </td>
                    <td style="text-align:right;"><?php echo $row['kousei_suuryou']; ?></td>
                    <td style="text-align:right;color:<?php echo ($result - $hituyousuu) < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($result - $hituyousuu,2); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        <span id="iframe-title"></span>
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>
<script>
    $(function () {
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script>
    var shouhin_mrs_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/ajaxGet') ?>";
    var shouhin_mrs_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/modal') ?>";
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/kouseibuhihn_zaiko.js'); ?>?var=20191113"></script>
