<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $rows */
?>
<?php use Phalcon\Tag; ?>
<?php $title = '滞留商品一覧表'; ?>
<div class="page-header">
    <h3>滞留商品一覧表</h3>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        [
            "zaiko_kakunin_azukari_vws/tairyuu_shouhin",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        ]);
    ?>
    <div class="form-group">
        <div class="col-sm-8">
            <label for="fieldLastNyuuko" class="col-sm-2 control-label">最終入庫日 ></label>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("last_nyuuko", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldLastNyuuko", "required" => "required", "value" => $this->request->getPost('last_nyuuko') ?? '')) ?>
            </div>
            <p>以前</p>
        </div>
        <div class="col-sm-8">
            <label for="fieldLastShukko" class="col-sm-2 control-label">最終出庫日 ></label>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("last_shukko", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldLastShukko", "value" => $this->request->getPost('last_shukko') ?? '')) ?>
            </div>
            <p>以前</p>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-4">
                <button id="dl-xlsx" class="submit btn btn-warning">EXCEL出力</button>
            </div>
            <div class="col-sm-4">
                <?php echo $this->tag->submitButton(array("集計F12", "id" => "F12", "class" => "btn btn-success")) ?>
            </div>
        </div>
        <div class="col-sm-8">
            <label for="fieldSuuryou" class="col-sm-2 control-label">在庫数 ></label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("suuryou", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldSuuryou", "required" => "required", "value" => $this->request->getPost('suuryou') ?? '')) ?>
            </div>
            <p>以上</p>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
        <tr style="background-color: lavender;">
            <th nowrap style="text-align:center;">商品コード</th>
            <th nowrap style="text-align:center;">商品名</th>
            <th nowrap style="text-align:center;">倉庫コード</th>
            <th nowrap style="text-align:center;">倉庫名</th>
            <th nowrap style="text-align:center;">在庫評価方法</th>
            <th nowrap style="text-align:center;">現在庫数</th>
            <th nowrap style="text-align:center;">単位</th>
            <th nowrap style="text-align:center;">現在庫量</th>
            <th nowrap style="text-align:center;">単位</th>
            <th nowrap style="text-align:center;">在庫単価</th>
            <th nowrap style="text-align:center;">在庫金額</th>
            <th nowrap style="text-align:center;">最終入庫日</th>
            <th nowrap style="text-align:center;">最終出庫日</th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($rows) && count($rows) !== 0) : ?>
            <?php $i = 0; ?>
            <?php foreach ($rows as $row): ?>
                <tr>
                    <td id="shouhin<?php echo $i; ?>" class="shouhin_cd" style="text-align:center;color: blue;cursor: pointer;"><?php echo $row['shouhin_mr_cd']; ?></td>
                    <td style="text-align: left;text-indent: 1em;"><?php echo $row['shouhin_name']; ?></td>
                    <td id="souko<?php echo $i; ?>" style="text-align:center;"><?php echo $row['souko_mr_cd']; ?></td>
                    <td style="text-align: left;text-indent:1em;"><?php echo $row['souko_name']; ?></td>
                    <td style="text-align:center;color:"><?php echo $row['zaiko_hyouka_kbn_cd']; ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['hikiate2'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['zaiko1']); ?></td>
                    <td style="text-align:center;"><?php echo $row['tanni1']; ?></td>
                    <td style="text-align:right;color:<?php echo (int)$row['zaiko2'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['zaiko2']); ?></td>
                    <td style="text-align:center;"><?php echo $row['tanni2']; ?></td>
                    <td style="text-align:right;"><?php echo number_format($row['tanka']); ?></td>
                    <td style="text-align:right;"><?php echo number_format($row['kingaku']); ?></td>
                    <td style="text-align:center;"><?php echo $row['last_nyuuko'] !== '0000-00-00' ? $row['last_nyuuko'] : ''; ?></td>
                    <td style="text-align:center;"><?php echo $row['last_shukko'] !== '0000-00-00' ? $row['last_shukko'] : ''; ?></td>
                </tr>
            <?php $i++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<script>
    $(function () {
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script>
    var nyuushukko_meisai = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('report_zaiko_vws/nyuushukko') ?>";
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script src="<?php echo $this->url->get('js/views/tairyuu_shouhin.js'); ?>?var=20191114"></script>
