<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php use Phalcon\Tag; ?>
<?php $title = "売上仕入比較表"; ?>
<div class="page-header">
    <h2>売上仕入比較表</h2>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "zaiko_kakunin_azukari_vws/uri_shiire_hikaku",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "id" => "form_urishiire_hikaku"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <h4 style="padding-left: 45px;">キーワード</h4>
        </div>
        <br />
        <div class="col-sm-8">

            <label for="fieldCd" class="col-sm-2 control-label">商品コード : </label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("shouhin_mr_cd", "class" => "form-control", "id" => "ShouhinMrsOptions")) ?>
            </div>
            <div><br /><br /></div>
            <label for="fieldCd" class="col-sm-2 control-label">商品名称 : </label>
            <div class="col-sm-7">
                <?php echo $this->tag->textField(array("name", "class" => "form-control", "id" => "fieldName1")) ?>
            </div>

            <div><br /><br /></div>

            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間 : </label>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom")) ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo")) ?>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-4">
                <button id="dl-xlsx" class="btn btn-lg btn-warning">EXCEL出力</button>
            </div>
            <div class="col-sm-4">
                <?php echo $this->tag->submitButton(array("集計F12", "id" => "F12", "class" => "btn btn-lg btn-success")) ?>
            </div>
        </div>
    </div>
</div>
<style scoped>
    th.ot-fixed, td.ot-fixed {
        position: absolute;
        padding-top: 50px;
        top: 500px;
    }
</style>

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
        <tr bgcolor="Lavender">
            <th nowrap style="text-align:center;">商品コード</th>
            <th nowrap style="text-align:center;">商品名称</th>
            <th nowrap style="text-align:center;">売上数</th>
            <th nowrap style="text-align:center;">仕入数</th>
            <th nowrap style="text-align:center;">差分</th>
            <th nowrap style="text-align:center;">対比</th>
            <th nowrap style="text-align:center;">売上額</th>
            <th nowrap style="text-align:center;">仕入額</th>
            <th nowrap style="text-align:center;">差分</th>
            <th nowrap style="text-align:center;">対比</th>
            <th nowrap style="text-align:center;">利益率</th>

        </tr>
        </thead>
        <?php foreach ($rows as $row): ?>
            <?php echo '<tr>'; ?>
            <td style="text-align:center;"><?php echo $row['shouhin_mr_cd']; ?></td>
            <td nowrap style="text-align:left;"><?php echo $row['shouhin_name']; ?></td>
            <td nowrap style="text-align:right;"><?php echo number_format($row['uriage_ryou2'], 2); ?></td>
            <td nowrap style="text-align:right;"><?php echo number_format($row['shiire_ryou2'], 2); ?></td>
            <td nowrap style="text-align:right;"><?php echo number_format($row['zaiko_sabun'], 2); ?></td>
            <?php if (is_nan((float)$row['uriage_ryou2']) || is_nan((float)$row['shiire_ryou2']) || $row['uriage_ryou2'] === '0' || $row['shiire_ryou2'] === '0') {
                echo "<td nowrap style='text-align:right;'>0.00</td>";
            } else {
                echo "<td nowrap style='text-align:right;'>" . @number_format(((float)$row['uriage_ryou2'] / (float)$row['shiire_ryou2']) * 100, 2) . "</td>";
            }
            ?>
            <td nowrap
                style="text-align:right;"><?php echo number_format($row['uriage_gaku'], 2); ?></td>
            <td nowrap style="text-align:right;"><?php echo number_format($row['shiire_gaku'], 2); ?></td>
            <td nowrap style="text-align:right;"><?php echo number_format($row['kingaku_sabun'], 2); ?></td>
            <?php if (is_nan((float)$row['uriage_gaku']) || is_nan((float)$row['shiire_gaku']) || $row['uriage_gaku'] === '0' || $row['shiire_gaku'] === '0') {
                echo "<td nowrap style='text-align:right;'>0.00</td>";
            } else {
                echo "<td nowrap style='text-align:right;'>" . @number_format(((float)$row['uriage_gaku'] / (float)$row['shiire_gaku']) * 100, 2) . "</td>";
            }
            ?>
            <?php if (is_nan((float)$row['kingaku_sabun']) || is_nan((float)$row['kingaku_sabun']) || $row['uriage_gaku'] === '0' || $row['kingaku_sabun'] === '0') {
                echo "<td nowrap style='text-align:right;'>0.00</td>";
            } else {
                $riekiritu = number_format(((float)$row['kingaku_sabun'] / (float)$row['uriage_gaku']) * 100, 2);
                if ($riekiritu >= 0) {
                    echo "<td nowrap style='text-align:right;'>" . $riekiritu . "</td>";
                } else {
                    echo "<td nowrap style='text-align:right;'>0.00</td>";
                }
            }
            ?>
            <?php echo '</tr>'; ?>
        <?php endforeach; ?>
    </table>
</div>

<!-- Modal -->
<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        <span id="iframe-title"></span>
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>
<!-- ======================================================== -->

<script type="text/javascript">
    $(function(){
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script>
    var shouhin_mrs_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/modal') ?>";
    var shouhin_mrs_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/ajaxGet') ?>";
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/uriage_shiire_hikaku.js'); ?>?var=20191105"></script>
