<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '担当者.新規'; ?>
<div class="page-header">
    <h3>担当者マスタ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "tantou_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">担当コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 3, "maxlength" => 3, "style" => "width: 39px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">担当者名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "maxlength" => 30, "style" => "width: 390px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKanaMei" class="col-sm-2 control-label">フリガナ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kana_mei", "size" => 30, "maxlength" => 30, "style" => "width: 390px;", "class" => "form-control", "id" => "fieldKanaMei")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBumonMrCd" class="col-sm-2 control-label">部門</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("bumon_mr_cd", bumonMrs::find(["columns" => "cd , CONCAT(cd , ':' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 390px;", "class" => "form-control", "id" => "fieldBumonMrCd")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
