<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "在庫.修正"; ?>
<div class="page-header">
    <h3>在庫変換伝票 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "zaiko_henkan_dts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "id" => "post_form",
        )
    );
?>

<div class="form-group">

    <?php $this->partial('zaiko_henkan_dts/inputfields'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" =>  'return final_check();')) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/denpyou/".$id."/20", "出荷案内書", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/new/".$id, "複写で新規へ", "class" => "btn btn-primary")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/delete/".$id, "伝票削除", "class" => "btn btn-danger", "onclick" => 'return before_delete_check();')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/zaiko_henkan_dts.js'); ?>?var=20200918"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/updnkey.js'); ?>?var=20191217"></script>
