<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "在変.一覧"; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/modalkanni",["table_id"=>"zaiko_henkan_dts","flds"=>[
        ["cd","fieldCd","伝票番号",14,14],["name","fieldName","摘要",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["cd","伝票番号(選択)"],
                    ["name","摘要"],
                    ["henkanbi","変換日"],
                    ["tantou_mr_cd","担当者"],
                    ["zaiko_henkan_kbn_cd","在庫変換区分"],
                    ["","商品1"],
                    ["","数量1"],
                ]]) ?>

            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $zaiko_henkan_dt): ?>
            <tr>
                <td align="right"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $zaiko_henkan_dt->cd ?></td>
                <td><?php echo $zaiko_henkan_dt->name ?></td>
                <td align="center"><?php echo $zaiko_henkan_dt->henkanbi ?></td>
                <td><?php echo $zaiko_henkan_dt->TantouMrs->name ?></td>
                <td><?php echo $zaiko_henkan_dt->ZaikoHenkanKbns->name ?></td>
                <td><?php echo $zaiko_henkan_dt->ZaikoHenkanMeisaiDts[0]->shouhin_mr_cd ?></td>
                <td align="right"><?php echo $zaiko_henkan_dt->ZaikoHenkanMeisaiDts[0]->suuryou .
                	$zaiko_henkan_dt->ZaikoHenkanMeisaiDts[0]->TanniMrs->name ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["index_or"=>"modal", "table_id"=>"zaiko_henkan_dts"]) ?>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
