<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "在庫.新規"; ?>
<div class="page-header">
    <h3>在庫変換伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "zaiko_henkan_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "id" => "post_form",
        )
    );
?>

<div class="form-group">

    <?php $this->partial('zaiko_henkan_dts/inputfields'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("zaiko_henkan_meisai_dts/search", "明細F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("zaiko_henkan_dts/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" =>  'return final_check();')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/zaiko_henkan_dts.js'); ?>?var=20200918"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/updnkey.js'); ?>?var=20191217"></script>
