<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "取引区分別見出.一覧"; ?>
<div class="page-header">
    <h3>取引区分別見出 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"torihiki_kbn_midasis","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","表示順"],
                    ["name","名称"],
                    ["torihiki_kbn_cd","取引区分"],
                    ["utiwake_kbn_cd","内訳区分"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $torihiki_kbn_midasi): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/edit/" . $torihiki_kbn_midasi->id, $torihiki_kbn_midasi->id)); ?></td>
                <td><?php echo $torihiki_kbn_midasi->cd ?></td>
                <td><?php echo $torihiki_kbn_midasi->name ?></td>
                <td><?php echo $torihiki_kbn_midasi->torihiki_kbn_cd ?></td>
                <td><?php echo $torihiki_kbn_midasi->utiwake_kbn_cd ?></td>
                <td><?php echo $torihiki_kbn_midasi->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/delete/" . $torihiki_kbn_midasi->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("torihiki_kbn_midasis/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("torihiki_kbn_midasis/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
