<style id="加工依頼書(撚糸)案　牧野_19815_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.font519815
	{color:windowtext;
	font-size:6.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"ＭＳ Ｐゴシック", monospace;
	mso-font-charset:128;}
.xl6419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:24.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:28.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt hairline windowtext;
	border-right:.5pt hairline windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl8919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:left;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl9319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl9619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt hairline windowtext;
	border-right:.5pt hairline windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt hairline windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl9919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:none;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl10919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl11619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl11919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:20.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl12919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.0pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt hairline windowtext;
	border-bottom:.5pt hairline windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt hairline windowtext;
	border-bottom:.5pt hairline windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt hairline windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl13919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt hairline windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt hairline windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt hairline windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl14919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.0pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.0pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl15919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:none;
	border-bottom:1.0pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.0pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl16919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl17219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl17419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl17819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl17919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	background:#EEECE1;
	mso-pattern:black none;
	white-space:nowrap;}
.xl18119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl18919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl19919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.0pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl20919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl21919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.0pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:1.0pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl22919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid white;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:1.5pt solid windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:none;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:none;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl23819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border-top:1.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl23919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:14.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24419815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24519815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:.5pt dotted windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24619815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:"m\0022月\0022d\0022日\0022";
	text-align:right;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:none;
	border-bottom:1.5pt solid windowtext;
	border-left:1.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24719815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:1.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24819815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt dotted windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl24919815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl25019815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl25119815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt dotted windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl25219815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt dotted windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl25319815
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Meiryo UI", monospace;
	mso-font-charset:128;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt dotted windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:1.5pt solid windowtext;
	border-left:.5pt dotted windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
ruby
	{ruby-align:left;}
rt
	{color:windowtext;
	font-size:6.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"ＭＳ Ｐゴシック", monospace;
	mso-font-charset:128;
	mso-char-type:katakana;}

.inputbig1
	{height:30pt!important;
	font-size:18pt;}
.inputbig2
	{height:25pt!important;
	font-size:14pt;}
.inputbig3
	{height:20pt!important;
	font-size:14pt;}
.inputbig4
	{height:20pt!important;
	font-size:12pt;}
.inputbig5
	{height:18pt!important;
	font-size:12pt;}
.inputhi1
	{height:40pt!important;}
.inputtokki
	{height:110pt!important;
	font-size:14pt;}

.inputedit
	{display:none;}
.showdisp
	{display:inline;}

body {
  padding-bottom: 20px;
}
-->
</style>

<br><?php $title = "加工依頼"; ?>

<!--[if !excel]>　　<![endif]-->
<!--次の情報は、Excel の Web ページとして発行ウィザードで生成されました。-->
<!--同じアイテムが Excel から再発行されるとき、DIV タグ間のすべての情報が置き換えられます。-->
<!----------------------------->
<!--Excel の Web ページとして発行 ウィザードのアウトプットの始まり-->
<!----------------------------->

<div id="加工依頼書(撚糸)案　牧野_19815" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1058 class=xl6419815
 style='border-collapse:collapse;table-layout:fixed;width:795pt'>
 <col class=xl6419815 width=101 style='mso-width-source:userset;mso-width-alt:
 3232;width:76pt'>
 <col class=xl6419815 width=25 style='mso-width-source:userset;mso-width-alt:
 800;width:19pt'>
 <col class=xl6419815 width=72 span=2 style='width:54pt'>
 <col class=xl6419815 width=68 style='mso-width-source:userset;mso-width-alt:
 2176;width:51pt'>
 <col class=xl6419815 width=25 span=2 style='mso-width-source:userset;
 mso-width-alt:800;width:19pt'>
 <col class=xl6419815 width=72 style='width:54pt'>
 <col class=xl6419815 width=25 style='mso-width-source:userset;mso-width-alt:
 800;width:19pt'>
 <col class=xl6419815 width=65 style='mso-width-source:userset;mso-width-alt:
 2080;width:49pt'>
 <col class=xl6419815 width=72 style='width:54pt'>
 <col class=xl6419815 width=25 style='mso-width-source:userset;mso-width-alt:
 800;width:19pt'>
 <col class=xl6419815 width=72 style='width:54pt'>
 <col class=xl6419815 width=71 style='mso-width-source:userset;mso-width-alt:
 2272;width:53pt'>
 <col class=xl6419815 width=27 style='mso-width-source:userset;mso-width-alt:
 864;width:20pt'>
 <col class=xl6419815 width=72 span=2 style='width:54pt'>
 <col class=xl6419815 width=25 style='mso-width-source:userset;mso-width-alt:
 800;width:19pt'>
 <col class=xl6419815 width=72 style='width:54pt'>
 <tr height=21 style='mso-height-source:userset;height:15.75pt'>
  <td colspan=12 rowspan=3 height=64 class=xl7919815 width=647
  style='height:48.0pt;width:487pt'>&#12314;　加　工　依　頼　書　&#12315;</td>
  <td class=xl6419815 width=72 style='width:54pt'></td>
  <td class=xl6419815 width=71 style='width:53pt'></td>
  <td class=xl6419815 width=27 style='width:20pt'></td>
  <td class=xl6419815 width=72 style='width:54pt'></td>
  <td class=xl6419815 width=72 style='width:54pt'></td>
  <td class=xl6419815 width=25 style='width:19pt'></td>
  <td class=xl6419815 width=72 style='width:54pt'></td>
 </tr>
 <tr height=21 style='mso-height-source:userset;height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td colspan=5 rowspan=2 class=xl8019815 style='border-bottom:1.5pt solid black'>
  	<span class='showdisp' id='dispHacchuubi'></span>
  	<?php echo $this->tag->telField(array("hacchuubi", "id" => "fieldHacchuubi", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig1")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td class=xl11019815>発行日</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=2 rowspan=2 height=44 class=xl10619815 style='border-bottom:1.5pt solid black;
  height:33.0pt'>加工依頼No</td>
  <td colspan=6 rowspan=2 class=xl10619815 style='border-bottom:1.5pt solid black'>
  	<span class='inputedit' id='dispCd' style='font-size: 18pt'></span>
  	<?php echo $this->tag->textField(array("cd", "id" => "fieldCd", "size" => 100, "maxlength" => 100, "class" => "showdisp form-control f-cent ime-d" ,"style" => "height:30pt!important;")) ?>
  </td>
  <td class=xl6519815></td>
  <td rowspan=2 class=xl6519815></td>
  <td rowspan=2 class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl22919815 style='height:16.5pt;border-left:none'>　</td>
  <!-- td class=xl6519815></td -->
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815 colspan=3>株式会社　シモムラ</td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td colspan=4 rowspan=2 class=xl8119815>
  	<span class='showdisp' id='dispTekiyou'></span>
  	<?php echo $this->tag->textField(array("tekiyou", "id" => "fieldTekiyou", "list" => "TekiyouOptions", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig1")) ?>
  </td>
  <td colspan=3 rowspan=2 class=xl8119815>御中</td>
  <td class=xl6519815></td>
  <td rowspan=2 class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815></td>
  <td class=xl6419815 colspan=5>石川県小松市南浅井町イ１０１－５</td>
  <td class=xl6419815></td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'>加工場</td>
  <td class=xl6519815></td>
  <!-- td class=xl6519815></td -->
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815></td>
  <td colspan=6 class=xl8219815>TEL　　０７６１－２１－２０１１</td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td height=22 class=xl10819815 style='height:16.5pt'>　</td>
  <td colspan=4 rowspan=2 class=xl10919815 style='border-bottom:1.5pt solid black'>
  	<span class='showdisp' id='dispGotantou'></span>
  	<?php echo $this->tag->textField(array("gotantou", "id" => "fieldGotantou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig1")) ?>
  </td>
  <td colspan=3 rowspan=2 class=xl10919815 style='border-bottom:1.5pt solid black'>
  	<span class='showdisp' id='dispKeishou'></span>
  	<?php echo $this->tag->textField(array("keishou", "id" => "fieldKeishou", "list" => "KeishouOptions", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig1")) ?>
  </td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815></td>
  <td colspan=6 class=xl8219815>FAX　　０７６１－２１－２０９９</td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td height=22 class=xl11019815 style='height:16.5pt'>ご担当者</td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6519815></td>
  <td class=xl6419815></td>
  <td colspan=6 class=xl8819815>当社担当</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td colspan=2 class=xl10219815>生産管理</td>
  <td colspan=4 class=xl10319815 style='border-left:none'>
  	<span class='showdisp' id='dispSeisanKanriUserName'></span>
  	<?php echo $this->tag->textField(array("seisan_kanri_user_name", "id" => "fieldSeisanKanriUserName", "list" => "UserNameOptions", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td colspan=2 class=xl10219815>営業</td>
  <td colspan=4 class=xl10319815 style='border-left:none'>
  	<span class='showdisp' id='dispTantouName'></span>
  	<?php echo $this->tag->select(array("tantou_mr_cd", TantouMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "id" => "fieldTantouMrCd", "class" => "inputedit form-control")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td colspan=2 class=xl23919815 style='border-right:.5pt dotted black'>営業アシスタント</td>
  <td colspan=4 class=xl10319815 style='border-left:none'>
  	<span class='showdisp' id='dispAssistantUserName'></span>
  	<?php echo $this->tag->textField(array("assistant_user_name", "id" => "fieldAssistantUserName", "list" => "UserNameOptions", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=62 style='mso-height-source:userset;height:46.5pt'>
  <td height=62 class=xl11219815 style='height:46.5pt'>製品名</td>
  <td colspan=11 class=xl11319815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMei0Tekiyou'></span>
  	<?php echo $this->tag->textField(array("mei[0]tekiyou", "id" => "fieldMei0Tekiyou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-i inputhi1")) ?>
  </td>
  <td class=xl11519815 width=72 style='border-left:none;width:54pt'>ロット<br>
    表示</td>
  <td colspan=6 class=xl11619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMei0Lot'></span>
  	<?php echo $this->tag->textField(array("mei[0]lot", "id" => "fieldMei0Lot", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-i inputhi1")) ?>
  </td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl11819815 style='height:30.0pt;border-top:none'>依頼数量</td>
  <td colspan=4 class=xl11919815>
  	<span class='showdisp' id='dispMei0Suuryou'></span>
  	<?php echo $this->tag->textField(array("mei[0]suuryou", "id" => "fieldMei0Suuryou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig1")) ?>
  </td>
  <td colspan=2 class=xl12019815 style='border-right:1.5pt solid black'>Ｋｇ</td>
  <td colspan=3 class=xl11719815>混率</td>
  <td colspan=3 class=xl10019815 style='border-left:none'>投入日</td>
  <td colspan=3 class=xl10019815 style='border-left:none'>投入数量</td>
  <td colspan=3 class=xl10019815 style='border-right:1.5pt solid black;
  border-left:none'>原糸巻量</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td rowspan=3 height=120 class=xl12319815 style='border-bottom:1.5pt solid black;
  height:90.0pt'>使用原糸</td>
  <td class=xl10019815 style='border-left:none'>①</td>
  <td colspan=5 class=xl10519815 style='border-left:none'>
  	<span class='showdisp' id='dispMei1Tekiyou'></span>
  	<?php echo $this->tag->textField(array("mei[1]tekiyou", "id" => "fieldMei1Tekiyou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig2")) ?>
  </td>
  <td colspan=2 class=xl10019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei1Keisu'></span>
  	<?php echo $this->tag->textField(array("mei[1]keisu", "id" => "fieldMei1Keisu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl10019815 style='border-left:none'>％</td>
  <td colspan=3 class=xl10119815 style='border-left:none'>
  	<span class='showdisp' id='dispMei1Nouki'></span>
  	<?php echo $this->tag->telField(array("mei[1]nouki", "id" => "fieldMei1Nouki", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td colspan=2 class=xl10019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei1Suuryou'></span>
  	<?php echo $this->tag->textField(array("mei[1]suuryou", "id" => "fieldMei1Suuryou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl10019815 style='border-left:none'>Kg</td>
  <td colspan=2 class=xl10019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei1Irisuu'></span>
  	<?php echo $this->tag->textField(array("mei[1]irisuu", "id" => "fieldMei1Irisuu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl12219815 style='border-left:none'>Kg</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl9019815 style='height:30.0pt;border-top:none;
  border-left:none'>②</td>
  <td colspan=5 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispMei2Tekiyou'></span>
  	<?php echo $this->tag->textField(array("mei[2]tekiyou", "id" => "fieldMei2Tekiyou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig2")) ?>
  </td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei2Keisu'></span>
  	<?php echo $this->tag->textField(array("mei[2]keisu", "id" => "fieldMei2Keisu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl9019815 style='border-top:none;border-left:none'>％</td>
  <td colspan=3 class=xl9919815 style='border-left:none'>
  	<span class='showdisp' id='dispMei2Nouki'></span>
  	<?php echo $this->tag->telField(array("mei[2]nouki", "id" => "fieldMei2Nouki", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei2Suuryou'></span>
  	<?php echo $this->tag->textField(array("mei[2]suuryou", "id" => "fieldMei2Suuryou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl9019815 style='border-top:none;border-left:none'>Kg</td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispMei2Irisuu'></span>
  	<?php echo $this->tag->textField(array("mei[2]irisuu", "id" => "fieldMei2Irisuu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl12519815 style='border-top:none;border-left:none'>Kg</td>
 </tr>
 <tr height=40 style='mso-height-source:userset;height:30.0pt'>
  <td height=40 class=xl12819815 style='height:30.0pt;border-top:none;
  border-left:none'>③</td>
  <td colspan=5 class=xl12719815 style='border-left:none'>
  	<span class='showdisp' id='dispMei3Tekiyou'></span>
  	<?php echo $this->tag->textField(array("mei[3]tekiyou", "id" => "fieldMei3Tekiyou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig2")) ?>
  </td>
  <td colspan=2 class=xl12819815 style='border-left:none'>
  	<span class='showdisp' id='dispMei3Keisu'></span>
  	<?php echo $this->tag->textField(array("mei[3]keisu", "id" => "fieldMei3Keisu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl12819815 style='border-top:none;border-left:none'>％</td>
  <td colspan=3 class=xl12919815 style='border-left:none'>
  	<span class='showdisp' id='dispMei3Nouki'></span>
  	<?php echo $this->tag->telField(array("mei[3]nouki", "id" => "fieldMei3Nouki", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td colspan=2 class=xl12819815 style='border-left:none'>
  	<span class='showdisp' id='dispMei3Suuryou'></span>
  	<?php echo $this->tag->textField(array("mei[3]suuryou", "id" => "fieldMei3Suuryou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl12819815 style='border-top:none;border-left:none'>Kg</td>
  <td colspan=2 class=xl12819815 style='border-left:none'>
  	<span class='showdisp' id='dispMei3Irisuu'></span>
  	<?php echo $this->tag->textField(array("mei[3]irisuu", "id" => "fieldMei3Irisuu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig2")) ?>
  </td>
  <td class=xl13019815 style='border-top:none;border-left:none'>Kg</td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl6419815 style='height:18.95pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.95pt'>
  <td rowspan=2 height=50 class=xl13119815 style='border-bottom:.5pt solid black;
  height:37.9pt'>加工賃</td>
  <td colspan=3 rowspan=2 class=xl13219815 style='border-right:.5pt dotted black;
  border-bottom:.5pt solid black'>
  	<span class='showdisp' id='dispMei0Tanka'></span>
  	<?php echo $this->tag->textField(array("mei[0]tanka", "id" => "fieldMei0Tanka", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig1")) ?>
  </td>
  <td colspan=2 rowspan=2 class=xl10919815>
  	<span class='showdisp' id='dispMei0TanniName'></span>
  	<?php echo $this->tag->select(array("mei[0]tanni", TanniMrs::find(["columns" => "cd , CONCAT('/',name) as cd_name"]), "using" => array("cd", "cd_name"), "id" => "fieldMei0Tanni", "class" => "inputedit form-control f-cent inputbig1")) ?>
  </td>
  <td colspan=2 rowspan=3 class=xl15219815 style='border-right:1.5pt solid black;
  border-bottom:1.5pt solid black'>希望納期</td>
  <td colspan=4 rowspan=3 class=xl14919815 style='border-bottom:1.5pt solid black'>
  	<span class='showdisp' id='dispKibouNouki'>
  	</span>
  	<?php echo $this->tag->telField(array("kibou_nouki", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig1", "id" => "fieldKibouNouki")) ?>
  </td>
  <td rowspan=2 class=xl16319815>返答納期</td>
  <td colspan=6 rowspan=2 class=xl16119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispNounyuuKijitu'>
  	</span>
  	<?php echo $this->tag->telField(array("nounyuu_kijitu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig1", "id" => "fieldNounyuuKijitu")) ?>
  </td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl14019815 style='height:18.95pt'>ロス率</td>
  <td colspan=3 class=xl14119815 style='border-right:.5pt dotted black'>
  	<span class='showdisp' id='dispLossRitu'></span>
  	<?php echo $this->tag->textField(array("loss_ritu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d", "id" => "fieldLossRitu")) ?>
  </td>
  <td colspan=2 class=xl14419815>％以下</td>
  <td class=xl16519815 style='border-top:none'>工期</td>
  <td colspan=6 class=xl14519815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispKouki'></span>
  	<?php echo $this->tag->textField(array("kouki", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-i", "id" => "fieldKouki")) ?>
  </td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl6419815 style='height:18.95pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td colspan=10 height=25 class=xl16619815 style='height:18.95pt'>加工内容</td>
  <td colspan=9 class=xl16919815 style='border-right:1.5pt solid black'>備考</td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17119815 style='height:18.95pt;border-top:none'>加工種</td>
  <td colspan=4 class=xl17219815 style='border-left:none'>
  	<span class='showdisp' id='dispKakouShu'></span>
  	<?php echo $this->tag->textField(array("kakou_shu", "id" => "fieldKakouShu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=2 class=xl17319815 style='border-left:none'>機種</td>
  <td colspan=3 class=xl17219815 style='border-left:none'>
  	<span class='showdisp' id='dispKishu'></span>
  	<?php echo $this->tag->textField(array("kishu", "id" => "fieldKishu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl17519815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouKa'></span>
  	<?php echo $this->tag->textField(array("bikou_ka", "id" => "fieldBikouKa", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>撚り数</td>
  <td colspan=9 class=xl9019815 style='border-left:none' nowarap>
  	<span class='showdisp' id='dispYori'></span>
  	<?php echo $this->tag->selectStatic(array("yori_houkou", array("S" => "S", "Z" => "Z"), "id" => "fieldYoriHoukou", "class" => "inputedit form-control f-cent inputbig3", "style" => "width:60px")) ?>
  	<?php echo $this->tag->textField(array("yorisuu", "id" => "fieldYorisuu", "size" => 5, "maxlength" => 5, "class" => "inputedit form-control f-cent ime-d inputbig3", "style" => "width:90px")) ?>
  	<?php echo $this->tag->textField(array("yoriTanni", "id" => "fieldYoriTanni", "size" => 4, "maxlength" => 4, "class" => "inputedit form-control f-cent ime-d inputbig3", "style" => "width:90px")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouYor'></span>
  	<?php echo $this->tag->textField(array("bikou_yor", "id" => "fieldBikouYor", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>巻量</td>
  <td colspan=4 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispMakiryou'></span>
  	<?php echo $this->tag->textField(array("makiryou", "id" => "fieldMakiryou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig3", "style" => "width:60px")) ?>
  	<?php echo $this->tag->textField(array("makiryou_tanni", "id" => "fieldMakiryouTanni", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-i inputbig3", "style" => "width:60px")) ?>
  </td>
  <td colspan=3 class=xl9219815 style='border-left:none'>正巻基準</td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSeimakiKijun'></span>
  	<?php echo $this->tag->textField(array("seimaki_mae", "id" => "fieldSeimakiMae", "size" => 100, "maxlength" => 100, "class" => "inputedit f-cent inputbig3", "style" => "width:20px")) ?>
  	<?php echo $this->tag->textField(array("seimaki_suu", "id" => "fieldSeimakiSuu", "size" => 100, "maxlength" => 100, "class" => "inputedit f-cent ime-d inputbig3", "style" => "width:30px")) ?>
  	<?php echo $this->tag->textField(array("seimaki_tanni", "id" => "fieldSeimakiTanni", "size" => 100, "maxlength" => 100, "class" => "inputedit f-cent inputbig3", "style" => "width:25px")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouMa'></span>
  	<?php echo $this->tag->textField(array("bikou_ma", "id" => "fieldBikouMa", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>紙管区分</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSikanSitei'></span>
  	<?php echo $this->tag->textField(array("sikan_sitei", "id" => "fieldSikanSitei", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSi'></span>
  	<?php echo $this->tag->textField(array("bikou_si", "id" => "fieldBikouSi", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>SET</td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSetUmu'></span>
  	<?php echo $this->tag->selectStatic(array("set_umu", array("0" => "0=無", "1" => "1=有"), "id" => "fieldSetUmu", "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td class=xl9219815 style='border-top:none;border-left:none'>条件</td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSetOndo'></span>
  	<?php echo $this->tag->textField(array("set_ondo", "id" => "fieldSetOndo", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig3")) ?>
  </td>
  <td class=xl9219815 style='border-top:none;border-left:none'>度</td>
  <td colspan=2 class=xl9319815 style='border-left:none'>
  	<span class='showdisp' id='dispSetHun'></span>
  	<?php echo $this->tag->textField(array("set_hun", "id" => "fieldSetHun", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig3")) ?>
  </td>
  <td class=xl9519815 style='border-top:none;border-left:none'>分</td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSe'></span>
  	<?php echo $this->tag->textField(array("bikou_se", "id" => "fieldBikouSe", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>テール</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispTailKbn'></span>
  	<?php echo $this->tag->selectStatic(array("tail_kbn", array("0" => "0=無", "1" => "1=有"), "id" => "fieldTailKbn", "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouTa'></span>
  	<?php echo $this->tag->textField(array("bikou_ta", "id" => "fieldBikouTa", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>小巻区分</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispKomakiKbn'></span>
  	<?php echo $this->tag->selectStatic(array("komaki_kbn", array("0" => "0=不可", "1" => "1=可"), "id" => "fieldKomakiKbn", "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouKo'></span>
  	<?php echo $this->tag->textField(array("bikou_ko", "id" => "fieldBikouKo", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl17819815 style='height:18.75pt;border-top:none'>繋区分</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispTunagiKbn'></span>
  	<?php echo $this->tag->selectStatic(array("tunagi_kbn", array("0" => "0=不可", "1" => "1=可"), "id" => "fieldTunagiKbn", "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouTu'></span>
  	<?php echo $this->tag->textField(array("bikou_tu", "id" => "fieldBikouTu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>用途</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispYouto'></span>
  	<?php echo $this->tag->textField(array("youto", "id" => "fieldYouto", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouYou'></span>
  	<?php echo $this->tag->textField(array("bikou_you", "id" => "fieldBikouYou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>ケース区分</td>
  <td colspan=4 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispCaseKbn'></span>
  	<?php echo $this->tag->textField(array("case_kbn", "id" => "fieldCaseKbn", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=3 class=xl9019815 style='border-left:none'>入り本数</td>
  <td colspan=2 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispIrihonsuu'></span>
  	<?php echo $this->tag->textField(array("irihonsuu", "id" => "fieldIrihonsuu", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent ime-d inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouCa'></span>
  	<?php echo $this->tag->textField(array("bikou_ca", "id" => "fieldBikouCa", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>残糸区分</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispZansiKbn'></span>
  	<?php echo $this->tag->textField(array("zansi_kbn", "id" => "fieldZansiKbn", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouZa'></span>
  	<?php echo $this->tag->textField(array("bikou_za", "id" => "fieldBikouZa", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>出荷区分</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispShukkaKbn'></span>
  	<?php echo $this->tag->textField(array("shukka_kbn", "id" => "fieldShukkaKbn", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSh'></span>
  	<?php echo $this->tag->textField(array("bikou_sh", "id" => "fieldBikouSh", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>その他1</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSonota1'></span>
  	<?php echo $this->tag->textField(array("sonota1", "id" => "fieldSonota1", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSo1'></span>
  	<?php echo $this->tag->textField(array("bikou_so1", "id" => "fieldBikouSo1", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl17819815 style='height:18.95pt;border-top:none'>その他2</td>
  <td colspan=9 class=xl9019815 style='border-left:none'>
  	<span class='showdisp' id='dispSonota2'></span>
  	<?php echo $this->tag->textField(array("sonota2", "id" => "fieldSonota2", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl9619815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSo2'></span>
  	<?php echo $this->tag->textField(array("bikou_so2", "id" => "fieldBikouSo2", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl18019815 style='height:18.95pt;border-top:none'>その他3</td>
  <td colspan=9 class=xl12819815 style='border-left:none'>
  	<span class='showdisp' id='dispSonota3'></span>
  	<?php echo $this->tag->textField(array("sonota3", "id" => "fieldSonota3", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent inputbig3")) ?>
  </td>
  <td colspan=9 class=xl18219815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispBikouSo3'></span>
  	<?php echo $this->tag->textField(array("bikou_so3", "id" => "fieldBikouSo3", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig4")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl6619815 style='height:18.95pt'></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td colspan=19 height=25 class=xl16619815 style='border-right:1.5pt solid black;
  height:18.95pt'>特記事項</td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td colspan=19 rowspan=6 height=150 class=xl23819815 width=1058
  style='border-right:1.5pt solid black;border-bottom:1.5pt solid black;
  height:113.7pt;width:795pt'>
  	<span class='showdisp' id='dispTokki'></span>
  	<?php echo $this->tag->textArea(array("tokki", "class" => "inputedit form-control inputtokki", "id" => "fieldTokki")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl6619815 style='height:18.95pt'></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
  <td class=xl6619815></td>
 </tr>


 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td colspan=19 height=25 class=xl6919815 style='height:18.95pt'>再ファックス追加連絡事項</td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl18819815 style='height:18.95pt'>日付</td>
  <td colspan=2 class=xl16919815 style='border-right:.5pt solid black'>連絡者</td>
  <td colspan=16 class=xl19019815 style='border-right:1.5pt solid black'>内容</td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl24319815 style='height:18.95pt'>
  	<span class='showdisp' id='dispFax0Hiduke'></span>
  	<?php echo $this->tag->telField(array("fax[0]hiduke", "id" => "fieldFax0Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl18519815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispFax0UserName'></span>
  	<?php echo $this->tag->textField(array("fax[0]user_name", "id" => "fieldFax0UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl18719815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispFax0Name'></span>
  	<?php echo $this->tag->textField(array("fax[0]name", "id" => "fieldFax0Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl24119815 style='height:18.95pt;border-top:none'>
  	<span class='showdisp' id='dispFax1Hiduke'></span>
  	<?php echo $this->tag->telField(array("fax[1]hiduke", "id" => "fieldFax1Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl7319815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispFax1UserName'></span>
  	<?php echo $this->tag->textField(array("fax[1]user_name", "id" => "fieldFax1UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7519815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispFax1Name'></span>
  	<?php echo $this->tag->textField(array("fax[1]name", "id" => "fieldFax1Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl24119815 style='height:18.95pt;border-top:none'>
  	<span class='showdisp' id='dispFax2Hiduke'></span>
  	<?php echo $this->tag->telField(array("fax[2]hiduke", "id" => "fieldFax2Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl7319815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispFax2UserName'></span>
  	<?php echo $this->tag->textField(array("fax[2]user_name", "id" => "fieldFax2UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7519815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispFax2Name'></span>
  	<?php echo $this->tag->textField(array("fax[2]name", "id" => "fieldFax2Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl24119815 style='height:18.95pt;border-top:none'>
  	<span class='showdisp' id='dispFax3Hiduke'></span>
  	<?php echo $this->tag->telField(array("fax[3]hiduke", "id" => "fieldFax3Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl7619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispFax3UserName'></span>
  	<?php echo $this->tag->textField(array("fax[3]user_name", "id" => "fieldFax3UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7819815 style='border-right:1.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispFax3Name'></span>
  	<?php echo $this->tag->textField(array("fax[3]name", "id" => "fieldFax3Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=25 style='mso-height-source:userset;height:18.95pt'>
  <td height=25 class=xl24219815 style='height:18.95pt;border-top:none'>
  	<span class='showdisp' id='dispFax4Hiduke'></span>
  	<?php echo $this->tag->telField(array("fax[4]hiduke", "id" => "fieldFax4Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl19519815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispFax4UserName'></span>
  	<?php echo $this->tag->textField(array("fax[4]user_name", "id" => "fieldFax4UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl19719815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispFax4Name'></span>
  	<?php echo $this->tag->textField(array("fax[4]name", "id" => "fieldFax4Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr class=xl6619815 height=27 style='page-break-before:always;height:20.25pt'>
  <td height=27 class=xl6719815 style='height:20.25pt'></td>
  <td class=xl6819815></td>
  <td class=xl6819815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
 </tr>
 <tr class=xl6619815 height=26 style='height:19.5pt'>
  <td height=26 class=xl6719815 style='height:19.5pt'></td>
  <td class=xl6819815></td>
  <td class=xl6819815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
 </tr>
 <tr class=xl6619815 height=26 style='height:19.5pt'>
  <td height=26 class=xl6719815 style='height:19.5pt'></td>
  <td class=xl6819815></td>
  <td class=xl6819815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
  <td class=xl6919815></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=19 rowspan=2 height=42 class=xl7219815 style='height:31.5pt'>【社内共有事項】</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 colspan=2 style='height:16.5pt'>加工場調整事項</td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=23 style='height:17.25pt'>
  <td height=23 class=xl22719815 style='height:17.25pt'>日付</td>
  <td colspan=2 class=xl20319815 style='border-right:.5pt solid black'>記入者</td>
  <td colspan=15 class=xl20519815 style='border-left:none'>内容</td>
  <td class=xl20719815>確認欄</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24419815 style='height:16.5pt'>
  	<span class='showdisp' id='dispCho0Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[0]hiduke", "id" => "fieldCho0Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl19919815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho0UserName'></span>
  	<?php echo $this->tag->textField(array("cho[0]user_name", "id" => "fieldCho0UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl20119815 style='border-left:none'>
  	<span class='showdisp' id='dispCho0Name'></span>
  	<?php echo $this->tag->textField(array("cho[0]name", "id" => "fieldCho0Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20819815>
  	<span class='showdisp' id='dispCho0KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[0]kakunin_kbn", "id" => "fieldCho0KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho1Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[1]hiduke", "id" => "fieldCho1Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho1UserName'></span>
  	<?php echo $this->tag->textField(array("cho[1]user_name", "id" => "fieldCho1UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho1Name'></span>
  	<?php echo $this->tag->textField(array("cho[1]name", "id" => "fieldCho1Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho1KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[1]kakunin_kbn", "id" => "fieldCho1KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho2Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[2]hiduke", "id" => "fieldCho2Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho2UserName'></span>
  	<?php echo $this->tag->textField(array("cho[2]user_name", "id" => "fieldCho2UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho2Name'></span>
  	<?php echo $this->tag->textField(array("cho[2]name", "id" => "fieldCho2Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho2KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[2]kakunin_kbn", "id" => "fieldCho2KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho3Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[3]hiduke", "id" => "fieldCho3Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho3UserName'></span>
  	<?php echo $this->tag->textField(array("cho[3]user_name", "id" => "fieldCho3UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho3Name'></span>
  	<?php echo $this->tag->textField(array("cho[3]name", "id" => "fieldCho3Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho3KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[3]kakunin_kbn", "id" => "fieldCho3KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho4Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[4]hiduke", "id" => "fieldCho4Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho4UserName'></span>
  	<?php echo $this->tag->textField(array("cho[4]user_name", "id" => "fieldCho4UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho4Name'></span>
  	<?php echo $this->tag->textField(array("cho[4]name", "id" => "fieldCho4Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho4KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[4]kakunin_kbn", "id" => "fieldCho4KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho5Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[5]hiduke", "id" => "fieldCho5Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho5UserName'></span>
  	<?php echo $this->tag->textField(array("cho[5]user_name", "id" => "fieldCho5UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho5Name'></span>
  	<?php echo $this->tag->textField(array("cho[5]name", "id" => "fieldCho5Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho5KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[5]kakunin_kbn", "id" => "fieldCho5KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho6Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[6]hiduke", "id" => "fieldCho6Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho6UserName'></span>
  	<?php echo $this->tag->textField(array("cho[6]user_name", "id" => "fieldCho6UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho6Name'></span>
  	<?php echo $this->tag->textField(array("cho[6]name", "id" => "fieldCho6Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho6KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[6]kakunin_kbn", "id" => "fieldCho6KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispCho7Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[7]hiduke", "id" => "fieldCho7Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho7UserName'></span>
  	<?php echo $this->tag->textField(array("cho[7]user_name", "id" => "fieldCho7UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl7019815 style='border-left:none'>
  	<span class='showdisp' id='dispCho7Name'></span>
  	<?php echo $this->tag->textField(array("cho[7]name", "id" => "fieldCho7Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none'>
  	<span class='showdisp' id='dispCho7KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[7]kakunin_kbn", "id" => "fieldCho7KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24619815 style='height:16.5pt;border-top:none'>
  	<span class='showdisp' id='dispCho8Hiduke'></span>
  	<?php echo $this->tag->telField(array("cho[8]hiduke", "id" => "fieldCho8Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb")) ?>
  </td>
  <td colspan=2 class=xl21019815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispCho8UserName'></span>
  	<?php echo $this->tag->textField(array("cho[8]user_name", "id" => "fieldCho8UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName")) ?>
  </td>
  <td colspan=15 class=xl21219815 style='border-left:none'>
  	<span class='showdisp' id='dispCho8Name'></span>
  	<?php echo $this->tag->textField(array("cho[8]name", "id" => "fieldCho8Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl24719815 style='border-top:none'>
  	<span class='showdisp' id='dispCho8KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("cho[8]kakunin_kbn", "id" => "fieldCho8KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'>加工流れ詳細</td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=23 style='height:17.25pt'>
  <td colspan=8 height=23 class=xl21419815 style='height:17.25pt'>内容</td>
  <td colspan=10 class=xl21519815 style='border-right:.5pt solid black;
  border-left:none'>備考</td>
  <td class=xl20719815 style='border-left:none'>確認欄</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=2 height=22 class=xl21719815 style='height:16.5pt'>
  	<span id='dispNag0Midasi'><?php echo $kakou_nagare_kbns[0]->name ?></span>
  </td>
  <td colspan=6 class=xl10519815 style='border-left:none'>
  	<span class='showdisp' id='dispNag0Name'></span>
  	<?php echo $this->tag->textField(array("nag[0]name", "id" => "fieldNag0Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl24819815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag0Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[0]bikou", "id" => "fieldNag0Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl22819815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag0KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[0]kakunin_kbn", "id" => "fieldNag0KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag1Midasi'><?php echo $kakou_nagare_kbns[1]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag1Name'></span>
  	<?php echo $this->tag->textField(array("nag[1]name", "id" => "fieldNag1Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag1Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[1]bikou", "id" => "fieldNag1Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag1KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[1]kakunin_kbn", "id" => "fieldNag1KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag2Midasi'><?php echo $kakou_nagare_kbns[2]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag2Name'></span>
  	<?php echo $this->tag->textField(array("nag[2]name", "id" => "fieldNag2Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag2Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[2]bikou", "id" => "fieldNag2Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag2KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[2]kakunin_kbn", "id" => "fieldNag2KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag3Midasi'><?php echo $kakou_nagare_kbns[3]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag3Name'></span>
  	<?php echo $this->tag->textField(array("nag[3]name", "id" => "fieldNag3Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag3Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[3]bikou", "id" => "fieldNag3Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag3KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[3]kakunin_kbn", "id" => "fieldNag3KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag4Midasi'><?php echo $kakou_nagare_kbns[4]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag4Name'></span>
  	<?php echo $this->tag->textField(array("nag[4]name", "id" => "fieldNag4Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag4Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[4]bikou", "id" => "fieldNag4Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag4KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[4]kakunin_kbn", "id" => "fieldNag4KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag5Midasi'><?php echo $kakou_nagare_kbns[5]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag5Name'></span>
  	<?php echo $this->tag->textField(array("nag[5]name", "id" => "fieldNag5Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag5Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[5]bikou", "id" => "fieldNag5Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag5KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[5]kakunin_kbn", "id" => "fieldNag5KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag6Midasi'><?php echo $kakou_nagare_kbns[6]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag6Name'></span>
  	<?php echo $this->tag->textField(array("nag[6]name", "id" => "fieldNag6Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag6Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[6]bikou", "id" => "fieldNag6Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag6KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[6]kakunin_kbn", "id" => "fieldNag6KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag7Midasi'><?php echo $kakou_nagare_kbns[7]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag7Name'></span>
  	<?php echo $this->tag->textField(array("nag[7]name", "id" => "fieldNag7Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag7Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[7]bikou", "id" => "fieldNag7Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag7KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[7]kakunin_kbn", "id" => "fieldNag7KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag8Midasi'><?php echo $kakou_nagare_kbns[8]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag8Name'></span>
  	<?php echo $this->tag->textField(array("nag[8]name", "id" => "fieldNag8Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag8Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[8]bikou", "id" => "fieldNag8Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag8KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[8]kakunin_kbn", "id" => "fieldNag8KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl21819815 style='height:15.75pt'>
  	<span id='dispNag9Midasi'><?php echo $kakou_nagare_kbns[9]->name ?></span>
  </td>
  <td colspan=6 class=xl8819815 style='border-left:none'>
  	<span class='showdisp' id='dispNag9Name'></span>
  	<?php echo $this->tag->textField(array("nag[9]name", "id" => "fieldNag9Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25019815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag9Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[9]bikou", "id" => "fieldNag9Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl20919815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag9KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[9]kakunin_kbn", "id" => "fieldNag9KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=2 height=22 class=xl21919815 style='height:16.5pt'>
  	<span id='dispNag10Midasi'><?php echo $kakou_nagare_kbns[10]->name ?></span>
  </td>
  <td colspan=6 class=xl12719815 style='border-left:none'>
  	<span class='showdisp' id='dispNag10Name'></span>
  	<?php echo $this->tag->textField(array("nag[10]name", "id" => "fieldNag10Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-cent")) ?>
  </td>
  <td colspan=10 class=xl25219815 style='border-right:.5pt solid black;
  border-left:none'>
  	<span class='showdisp' id='dispNag10Bikou'></span>
  	<?php echo $this->tag->textField(array("nag[10]bikou", "id" => "fieldNag10Bikou", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control")) ?>
  </td>
  <td class=xl24719815 style='border-top:none;border-left:none'>
  	<span class='showdisp' id='dispNag10KakuninKbn'></span>
  	<?php echo $this->tag->selectStatic(array("nag[10]kakunin_kbn", "id" => "fieldNag10KakuninKbn", array("0" => "0=－", "1" => "1=済"), 'useEmpty' => true, 'emptyText' => '', "class" => "inputedit form-control f-cent")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 style='height:16.5pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6419815 style='height:15.75pt'></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6419815 colspan=3 style='height:16.5pt'>前回加工時より申し送り事項</td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
  <td class=xl6419815></td>
 </tr>
 <tr height=23 style='height:17.25pt'>
  <td height=23 class=xl22719815 style='height:17.25pt'>日付</td>
  <td colspan=2 class=xl20319815 style='border-right:.5pt solid black'>記入者</td>
  <td colspan=16 class=xl22119815 style='border-right:1.5pt solid black'>内容</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24419815 style='height:16.5pt'>
  	<span class='showdisp' id='dispMok0Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[0]hiduke", "id" => "fieldMok0Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl19919815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok0UserName'></span>
  	<?php echo $this->tag->textField(array("mok[0]user_name", "id" => "fieldMok0UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl20219815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok0Name'></span>
  	<?php echo $this->tag->textField(array("mok[0]name", "id" => "fieldMok0Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok1Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[1]hiduke", "id" => "fieldMok1Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok1UserName'></span>
  	<?php echo $this->tag->textField(array("mok[1]user_name", "id" => "fieldMok1UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok1Name'></span>
  	<?php echo $this->tag->textField(array("mok[1]name", "id" => "fieldMok1Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok2Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[2]hiduke", "id" => "fieldMok2Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok2UserName'></span>
  	<?php echo $this->tag->textField(array("mok[2]user_name", "id" => "fieldMok2UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok2Name'></span>
  	<?php echo $this->tag->textField(array("mok[2]name", "id" => "fieldMok2Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok3Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[3]hiduke", "id" => "fieldMok3Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok3UserName'></span>
  	<?php echo $this->tag->textField(array("mok[3]user_name", "id" => "fieldMok3UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok3Name'></span>
  	<?php echo $this->tag->textField(array("mok[3]name", "id" => "fieldMok3Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok4Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[4]hiduke", "id" => "fieldMok4Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok4UserName'></span>
  	<?php echo $this->tag->textField(array("mok[4]user_name", "id" => "fieldMok4UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok4Name'></span>
  	<?php echo $this->tag->textField(array("mok[4]name", "id" => "fieldMok4Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok5Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[5]hiduke", "id" => "fieldMok5Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok5UserName'></span>
  	<?php echo $this->tag->textField(array("mok[5]user_name", "id" => "fieldMok5UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok5Name'></span>
  	<?php echo $this->tag->textField(array("mok[5]name", "id" => "fieldMok5Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok6Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[6]hiduke", "id" => "fieldMok6Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok6UserName'></span>
  	<?php echo $this->tag->textField(array("mok[6]user_name", "id" => "fieldMok6UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok6Name'></span>
  	<?php echo $this->tag->textField(array("mok[6]name", "id" => "fieldMok6Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl24519815 style='height:15.75pt;border-top:none'>
  	<span class='showdisp' id='dispMok7Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[7]hiduke", "id" => "fieldMok7Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl8619815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok7UserName'></span>
  	<?php echo $this->tag->textField(array("mok[7]user_name", "id" => "fieldMok7UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl7119815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok7Name'></span>
  	<?php echo $this->tag->textField(array("mok[7]name", "id" => "fieldMok7Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24619815 style='height:16.5pt;border-top:none'>
  	<span class='showdisp' id='dispMok8Hiduke'></span>
  	<?php echo $this->tag->telField(array("mok[8]hiduke", "id" => "fieldMok8Hiduke", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control f-numb inputbig5")) ?>
  </td>
  <td colspan=2 class=xl21019815 style='border-right:.5pt solid black'>
  	<span class='showdisp' id='dispMok8UserName'></span>
  	<?php echo $this->tag->textField(array("mok[8]user_name", "id" => "fieldMok8UserName", "list" => "UserNameOptions", "class" => "inputedit form-control f-cent UserName inputbig5")) ?>
  </td>
  <td colspan=16 class=xl21319815 style='border-right:1.5pt solid black'>
  	<span class='showdisp' id='dispMok8Name'></span>
  	<?php echo $this->tag->textField(array("mok[8]name", "id" => "fieldMok8Name", "size" => 100, "maxlength" => 100, "class" => "inputedit form-control inputbig5")) ?>
  </td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=101 style='width:76pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=65 style='width:49pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=71 style='width:53pt'></td>
  <td width=27 style='width:20pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=72 style='width:54pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--Excel の Web ページとして発行 ウィザードのアウトプットの終わり-->
<!----------------------------->
<?php echo $this->tag->hiddenField(array("id", "id"=>"fieldId")) ?>
<?php echo $this->tag->hiddenField(array("shiiresaki_mr_cd", "id"=>"fieldShiiresakiMrCd")) ?>
<?php echo $this->tag->hiddenField(array("kakou_kanri_user_cd", "id"=>"fieldSeisanKanriUserCd")) ?>
<?php echo $this->tag->hiddenField(array("assistant_user_cd", "id"=>"fieldAssistantUserCd")) ?>
<?php echo $this->tag->hiddenField(array("fax[0]user_cd", "id"=>"fieldFax0UserCd")) ?>
<?php echo $this->tag->hiddenField(array("fax[1]user_cd", "id"=>"fieldFax1UserCd")) ?>
<?php echo $this->tag->hiddenField(array("fax[2]user_cd", "id"=>"fieldFax2UserCd")) ?>
<?php echo $this->tag->hiddenField(array("fax[3]user_cd", "id"=>"fieldFax3UserCd")) ?>
<?php echo $this->tag->hiddenField(array("fax[4]user_cd", "id"=>"fieldFax4UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[0]user_cd", "id"=>"fieldCho0UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[1]user_cd", "id"=>"fieldCho1UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[2]user_cd", "id"=>"fieldCho2UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[3]user_cd", "id"=>"fieldCho3UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[4]user_cd", "id"=>"fieldCho4UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[5]user_cd", "id"=>"fieldCho5UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[6]user_cd", "id"=>"fieldCho6UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[7]user_cd", "id"=>"fieldCho7UserCd")) ?>
<?php echo $this->tag->hiddenField(array("cho[8]user_cd", "id"=>"fieldCho8UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[0]user_cd", "id"=>"fieldMok0UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[1]user_cd", "id"=>"fieldMok1UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[2]user_cd", "id"=>"fieldMok2UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[3]user_cd", "id"=>"fieldMok3UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[4]user_cd", "id"=>"fieldMok4UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[5]user_cd", "id"=>"fieldMok5UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[6]user_cd", "id"=>"fieldMok6UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[7]user_cd", "id"=>"fieldMok7UserCd")) ?>
<?php echo $this->tag->hiddenField(array("mok[8]user_cd", "id"=>"fieldMok8UserCd")) ?>

<datalist id="KeishouOptions">
	<option value="様"></option>
	<option value="御中"></option>
	<option value="宛"></option>
</datalist>

<datalist id="CdOptions">
</datalist>

<datalist id="TekiyouOptions">
</datalist>

<datalist id="SeisanKanriUserNameOptions">
</datalist>

<datalist id="UserNameOptions">
</datalist>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
	<div class="modal-header" style="padding: 5px; background-color: #ddd;">
		<span id="iframe-title"></span>
		<button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
	</div>
	<div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
	</div>
</div>

<div id="PgDn"></div><div id="PgUp"></div><div id="END"></div>

<div class="navbar navbar-default navbar-fixed-bottom" style="background-color:#e8e0d0;">
 <div class="container">
  <span class="navbar-text">
	<input type="button" value="－－F1" id="F1" class="btn btn-default" onclick="alert('F1');" title='ブラウザのHELP起動:F1キー' />
	<input type="button" value="新規F2" id="X2" class="btn btn-default" onclick="alert('F2');" title='新規入力用画面にします:F2キー' />
	<input type="button" value="前へF3" id="F3" class="btn btn-default" onclick="alert('F3');" title='前番号の伝票を表示します:F3キー' />
	<input type="button" value="次へF4" id="F4" class="btn btn-info" onclick="alert('F4');" title='次番号の伝票を表示します:F4キー' />　
	<input type="button" value="印刷F5" id="F5" class="btn btn-default" onclick="window.print();" title='現在の画面を印刷します:F5キー' />
	<input type="button" value="修正F6" id="F6" class="btn btn-warning" onclick="shuusei();" title='修正入力可能になります:F6キー' />
	<input type="button" value="表示F7" id="F7" class="btn btn-default" onclick="hyouji();" title='表示モードになります:F7キー' />
	<input type="button" value="参照F8" id="X8" class="btn btn-default" onclick="alert('F8');" title='参照可能の時、参照画面を開きます:F8キー' />　
	<input type="button" value="－－F9" id="F9" class="btn btn-default" onclick="alert('F9');" title='ブラウザの機能が起動:F9キー' />
	<input type="button" value="－－F10" id="F10" class="btn btn-default" onclick="alert('F10');" title='ブラウザの機能が起動:F10キー' />
	<input type="button" value="－－F11" id="F11" class="btn btn-default" onclick="alert('F11');" title='ブラウザの機能が起動:F11キー' />
	<input type="button" value="登録F12" id="F12" class="btn btn-success" onclick="ajaxSave();" title='新規登録や修正を更新します:F12キー' />
  </span>
 </div>
</div>

<script type="text/javascript">
	var kakou_irai_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('kakou_irai_dts/ajaxGet') ?>";
	var kakou_irai_dts_ajaxSave = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('kakou_irai_dts/ajaxSave') ?>";
	var shiiresaki_name_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shiiresaki_mrs/name_ajaxGet') ?>";
	var user_name_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('users/name_ajaxGet') ?>";
	var user_me={};
	user_me['name'] = "<?php echo $user_me->name ?>";
	user_me['cd'] = "<?php echo $user_me->cd ?>";
	user_me['id'] = "<?php echo $user_me->id ?>";
	user_me['tantou_cd'] = "<?php echo count($user_me->TantouMrs)?$user_me->TantouMrs[0]->cd:''; ?>";
</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/kakou_irai_dts.js'); ?>?var=000001"></script>
