<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $joukens */
/** @var array $rows */
/** @var integer $soukei */
/** @var integer $soukeiArray */
use Phalcon\Tag;
$title = '売上分析表表';
?>
<div class="page-header">
    <h2>売上分析表</h2>
</div>

<?php
//echo '<pre>', var_dump($rows), '</pre>';
?>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        [
            "report_uriage/bunseki",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        ]
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("cd", $joukens, "style" => "width: 260px;", "class" => "form-control", "id" => "fieldCd")) ?>
            </div>

            <label for="fieldHyoujiKbn" class="col-sm-2 control-label">集計</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("hyouji_kbn", array("0" => "純売上額"), "style" => "width: 130px;", "class" => "form-control", "id" => "fieldHyoujiKbn")) ?>
            </div>

            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", KikanSiteiKbns::find(["columns" => "cd , name", "order" => "cd", "conditions" => "yobidasi_tbl='jouken_uriage_geppous'"]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom", "readonly" => "readonly", "value" => $this->request->getPost('kikan_from'))); ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo", "readonly" => "readonly", "value" => $this->request->getPost('kikan_to'))); ?>
            </div>

        </div>
        <div class="col-sm-2">
            <?php /* id             */echo $this->tag->hiddenField("id") ?>
            <?php /* cd             */echo $this->tag->hiddenField("cd") ?>
            <?php /* 名称           */echo $this->tag->hiddenField("name") ?>
            <?php /* 順序           */echo $this->tag->hiddenField("junjo_kbn_cd") ?>
            <?php /* 範囲自         */echo $this->tag->hiddenField("hanni_from") ?>
            <?php /* 範囲自名       */echo $this->tag->hiddenField("hanni_from_name") ?>
            <?php /* 範囲至         */echo $this->tag->hiddenField("hanni_to") ?>
            <?php /* 範囲至名       */echo $this->tag->hiddenField("hanni_to_name") ?>
            <?php /* 順序2          */echo $this->tag->hiddenField("junjo2_kbn_cd") ?>
            <?php /* 範囲2自        */echo $this->tag->hiddenField("hanni2_from") ?>
            <?php /* 範囲2自名      */echo $this->tag->hiddenField("hanni2_from_name") ?>
            <?php /* 範囲2至        */echo $this->tag->hiddenField("hanni2_to") ?>
            <?php /* 範囲2至名      */echo $this->tag->hiddenField("hanni2_to_name") ?>
            <?php /* 降順フラグ     */echo $this->tag->hiddenField("koujun_flg") ?>
            <?php /* 明細行表示ﾌﾗグ */echo $this->tag->hiddenField("meisaigyou_flg") ?>
            <?php /* 合計行表示ﾌﾗグ */echo $this->tag->hiddenField("goukeigyou_flg") ?>
            <?php /* 取引ありフラグ */echo $this->tag->hiddenField("torihikiari_flg") ?>
            <?php /* 取引なしフラグ */echo $this->tag->hiddenField("torihikinashi_flg") ?>

            <div class="col-sm-12">
                <button class="btn btn-warning" onclick="modalstart(jouken_uriage_bunseki_modal);return false;">条件設定>8
</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <button id="dl-xlsx" class="submit btn btn-warning">EXCEL出力</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn btn-lg btn-success")) ?>
            </div>
        </div>
    </div><!-- form-group -->
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
        <tr style="background-color: lavender">
            <th colspan="2" style="text-align: center;">総計：</th>
            <th style="text-align:right; background-color: whitesmoke;"><?php echo number_format($soukeiArray['junuriage']) ?></th>
            <th style="text-align:center; background-color: whitesmoke;">-</th>
            <th style="text-align:right; background-color: whitesmoke;"><?php echo number_format($soukeiArray['suuryou'], 2) ?></th>
            <th style="text-align:right; background-color: whitesmoke;"><?php echo number_format($soukeiArray['arari']) ?></th>
            <th style="text-align:center; background-color: whitesmoke;"><?php echo number_format($soukeiArray['junuriage'] / $soukeiArray['arari'], 1) ?></th>
        </tr>
        <tr style="background-color: lavender">
            <th style="text-align: center;">コード</th>
            <th style="text-align:center;">摘要</th>
            <?php
            if ($this->request->getPost('junjo_kbn_cd') === '1816' || $this->request->getPost('junjo2_kbn_cd') === '1816') {
                echo '<th style="text-align:center;">', '色番', '</th>';
            }
            ?>
            <th style="text-align:center;">純売上額</th>
            <th style="text-align:center;">構成比</th>
            <th style="text-align:center;">売上数量</th>
            <th style="text-align:center;">粗利益</th>
            <th style="text-align:center;">粗利率</th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($rows)): ?>
            <?php foreach ($rows as $row): ?>
                <tr>
                    <?php
                        if(strpos($row['key'],'≪') !== false) {
                            if ($this->request->isPost()) {
                                $font = 'bold';
                                $color = 'blue';
                                $align = 'left';
                                $size = '16px';
                            } else {
                                continue;
                            }
                        } elseif (strpos($row['key'], '計') !== false) {
                            if ($this->request->getPost('goukeigyou_flg')) {
                                $font = 'bold';
                                $color = 'green';
                                $align = 'center';
                                $size = '16px';
                            } else {
                                continue;
                            }
                        } else {
                            if ($this->request->getPost('meisaigyou_flg')) {
                                $font = 'normal';
                                $color = 'black';
                                $align = 'center';
                                $size = '14px';
                            } else {
                                continue;
                            }
                        }
                    ?>
                    <td style="text-align:<?php echo $align; ?>;font-size:<?php echo $size;?>;color: <?php echo $color;?>;font-weight: <?php echo $font;?>;"><?php echo $row['key']; ?></td>
                    <td style="text-align: left;font-size:<?php echo $size;?>;color: <?php echo $color;?>;font-weight: <?php echo $font;?>;"><?php echo $row['name']; ?></td>
                    <?php
                    if ($this->request->getPost('junjo_kbn_cd') === '1816' || $this->request->getPost('junjo2_kbn_cd') === '1816') {
                        echo '<td style="text-align:center;">';
                        echo $row['iro'];
                        echo '</td>';
                    }
                    ?>
                    <td style="text-align:right;font-size:<?php echo $size;?>;font-weight: <?php echo $font;?>;color: <?php echo (float)$row['junuriage'] < 0 ? 'red': 'black'; ?>;"><?php echo number_format($row['junuriage']); ?></td>
                    <td style="text-align:right;">
                        <?php
                        if ($font === 'normal') {
                            echo number_format((float)$row['junuriage'] / (float)$soukei * 100,2);
                        }
                        ?>
                    </td>
                    <td style="text-align:right;font-size:<?php echo $size;?>;font-weight: <?php echo $font;?>;color: <?php echo (float)$row['suuryou'] < 0 ? 'red': 'black'; ?>;"><?php echo number_format($row['suuryou'],2); ?></td>
                    <td style="text-align:right;font-size:<?php echo $size;?>;font-weight: <?php echo $font;?>;color: <?php echo (float)$row['arari'] < 0 ? 'red': 'black'; ?>;"><?php echo number_format($row['arari']); ?></td>
                    <td style="text-align:right;">
                        <?php
                        if ($font === 'normal') {
                            if ((int)$row['junuriage'] > 0 || (int)$row['arari'] > 0) {
                                echo number_format((float)$row['arari'] / (float)$row['junuriage'] * 100,2);
                            } else {
                                echo '*****';
                            }
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle" style="width:900px; height:500px;">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        売上分析表条件設定
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    var jouken_uriage_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_uriage_bunsekis/ajaxGet') ?>";
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
    var junjo_kbns_ajaxHanni = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('junjo_kbns/ajaxHanni') ?>";
    var jouken_uriage_bunseki_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_uriage_bunsekis/modal') ?>";
    var jouken_flds = [
        "id",
        "cd",
        "name",
        "junjo_kbn_cd",
        "hanni_from",
        "hanni_to",
        "junjo2_kbn_cd",
        "hanni2_from",
        "hanni2_to",
        "kikan_sitei_kbn_cd",
        "kikan_from",
        "kikan_to",
        "koujun_flg",
        "meisaigyou_flg",
        "goukeigyou_flg",
        "torihikiari_flg",
        "torihikinashi_flg",
    ];
</script>
<script>

</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/report_uriage_bunsekis.js'); ?>?var=20191105"></script>

