<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $joukens */
/** @var array $rows */
/** @var string $month */
/** @var array $setdts */
/** @var array $tounen_kei */
/** @var array $zennen_kei */
/** @var array $wariai */
/** @var array $buff */
?>
<?php use Phalcon\Tag; ?>

<?php
//echo '<pre>';
//var_dump($buff);
//echo '</pre>';
?>
<?php $title = '売上推移表'; ?>
<div class="page-header">
    <h2>売上推移表</h2>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "report_uriage/suii",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("cd", $joukens, "style" => "width: 260px;", "class" => "form-control", "id" => "fieldCd")) ?>
            </div>

            <label for="fieldHyoujiKbn" class="col-sm-2 control-label">集計</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("hyouji_kbn", array("0" => "純売上額", "1" => "粗利益", "2" => "順売上数", "3" => "順売上量"), "style" => "width: 130px;", "class" => "form-control", "id" => "fieldHyoujiKbn")) ?>
            </div>

            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", Konnnenndo::find(["columns" => "cd , name", "order" => "cd",]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom", "readonly" => "readonly", "value" => $setdts['kikan_from'] ?? '',)) ?>
            </div>
            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo", "readonly" => "readonly", "value" => $setdts['kikan_to'] ?? '',)) ?>
            </div>
        </div>
        <div class="col-sm-2">
            <?php /* 取引区分別     */echo $this->tag->hiddenField("torihiki_kbn_betu_flg") ?>
            <?php /* 順序区分コード */echo $this->tag->hiddenField("junjo_kbn_cd") ?>
            <?php /* 順序区分テーブル */echo $this->tag->hiddenField("junjo_kbn_table") ?>
            <?php /* 降順フラグ     */echo $this->tag->hiddenField("koujun_flg") ?>
            <?php /* 前年比較フラグ */echo $this->tag->hiddenField("zennen_flg") ?>
            <?php /* 範囲自         */echo $this->tag->hiddenField("hanni_from") ?>
            <?php /* 範囲自名       */echo $this->tag->hiddenField("hanni_from_name") ?>
            <?php /* 範囲至         */echo $this->tag->hiddenField("hanni_to") ?>
            <?php /* 範囲至名       */echo $this->tag->hiddenField("hanni_to_name") ?>
            <?php /* 税込みフラグ   */echo $this->tag->hiddenField("zeikomi_flg") ?>
            <?php /* 明細行表示フラ */echo $this->tag->hiddenField("meisaigyou_flg") ?>
            <?php /* 合計行表示フラ */echo $this->tag->hiddenField("goukeigyou_flg") ?>
            <?php /* 自入力分フラグ */echo $this->tag->hiddenField("jinyuuryoku_flg") ?>
            <?php /* 期間内取引有フ */echo $this->tag->hiddenField("torihikiari_flg") ?>
            <?php /* 期間内取引無フ */echo $this->tag->hiddenField("torihikinasi_flg") ?>
            <?php /* その他計フラグ */echo $this->tag->hiddenField("hokakei_flg") ?>
            <div class="col-sm-4">
                <button class="btn btn-warning" onclick="modalstart(jouken_uriage_modal);return false;">条件設定>8</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <button id="dl-xlsx" class="submit btn btn-warning">EXCEL出力</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn btn-lg btn-success")) ?>
            </div>
        </div>
    </div><!-- form-group -->
    <?php echo $this->tag->endForm(); ?>
</div>

<?php if (!isset($setdts['hyouji_kbn'])) $setdts['hyouji_kbn'] = 0; ?>
<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <?php $total = 0; ?>
        <thead>
        <?php if (!isset($setdts['zennen_flg'])) $setdts['zennen_flg'] = '0'; ?>
        <?php if ($setdts['zennen_flg'] === '0'): ?>
            <tr style="background-color: White;">
                <th colspan="2" style="text-align:center;background-color: #fef6fe;font-weight: bold;">列計　>></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '1'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '2'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '3'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '4'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '5'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '6'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '7'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '8'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '9'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '10'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '11'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '12'));
                    if ($setdts['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                    $total += $as_total;?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($total); else echo number_format($total,2)?></th>
            </tr>
        <?php else: ?>
            <tr style="background-color: White;">
                <th colspan="2" style="text-align:center;background-color: #fef6fe;font-weight: bold;">選択年度列計　>></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['1']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['2']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['3']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['4']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['5']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['6']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['7']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['8']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['9']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['10']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['11']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($tounen_kei['12']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"></th>
            </tr>
            <tr style="background-color: White;">
                <th colspan="2" style="text-align:center;background-color: #fef6fe;font-weight: bold;color: green;">選択前年度列計　>></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['1']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['2']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['3']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['4']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['5']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['6']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['7']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['8']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['9']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['10']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['11']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"><?php echo number_format($zennen_kei['12']); ?></th>
                <th style="text-align:right;background-color: #fef6fe;color: green;"></th>
            </tr>
            <tr style="background-color: White;">
                <th colspan="2" style="text-align:center;background-color: #fef6fe;font-weight: bold;">前年比　>></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['1'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['2'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['3'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['4'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['5'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['6'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['7'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['8'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['9'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['10'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['11'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php echo number_format($wariai['12'], 1); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"></th>
            </tr>
        <?php endif; ?>

        <tr style="background-color: lavender;">
            <th style="text-align:center;">集計キー</th>
            <th style="text-align:center;">キー名称</th>
            <th style="text-align:center;"><?php echo $month . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 1 > 12) ? ((int)$month + 1 - 12) : ((int)$month + 1)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 2 > 12) ? ((int)$month + 2 - 12) : ((int)$month + 2)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 3 > 12) ? ((int)$month + 3 - 12) : ((int)$month + 3)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 4 > 12) ? ((int)$month + 4 - 12) : ((int)$month + 4)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 5 > 12) ? ((int)$month + 5 - 12) : ((int)$month + 5)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 6 > 12) ? ((int)$month + 6 - 12) : ((int)$month + 6)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 7 > 12) ? ((int)$month + 7 - 12) : ((int)$month + 7)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 8 > 12) ? ((int)$month + 8 - 12) : ((int)$month + 8)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 9 > 12) ? ((int)$month + 9 - 12) : ((int)$month + 9)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 10 > 12) ? ((int)$month + 10 - 12) : ((int)$month + 10)) . '月'; ?></th>
            <th style="text-align:center;"><?php echo (((int)$month + 11 > 12) ? ((int)$month + 11 - 12) : ((int)$month + 11)) . '月'; ?></th>
            <th style="text-align:center;">通期計</th>
        </tr>
        </thead>
        <tbody>
        <?php $shoukei = 0; ?>
        <?php if ($setdts['zennen_flg'] === '0'): ?>
            <?php foreach ($rows as $row): ?>
                <tr>
                    <td style="text-align:left;"><?php echo $row['key']; ?></td>
                    <td style="text-align:left;"><?php echo $row['key_name']; ?></td>
                    <td style="text-align:right;color:color:<?php echo (int)$row['1'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['1']); else echo number_format($row['1'],2); ?></td>
                    <?php $shoukei += (float)$row['1']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['2'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['2']); else echo number_format($row['2'],2);?></td>
                    <?php $shoukei += (float)$row['2']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['3'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['3']); else echo number_format($row['3'],2); ?></td>
                    <?php $shoukei += (float)$row['3']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['4'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['4']); else echo number_format($row['4'],2);?></td>
                    <?php $shoukei += (float)$row['4']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['5'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['5']); else echo number_format($row['5'],2); ?></td>
                    <?php $shoukei += (float)$row['5']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['6'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['6']); else echo number_format($row['6'],2); ?></td>
                    <?php $shoukei += (float)$row['6']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['7'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['7']); else echo number_format($row['7'],2);?></td>
                    <?php $shoukei += (float)$row['7']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['8'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['8']); else echo number_format($row['8'],2);?></td>
                    <?php $shoukei += (float)$row['8']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['9'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['9']); else echo number_format($row['9'],2);?></td>
                    <?php $shoukei += (float)$row['9']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['10'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['10']); else echo number_format($row['10'],2);?></td>
                    <?php $shoukei += (float)$row['10']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['11'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['11']); else echo number_format($row['11'],2);?></td>
                    <?php $shoukei += (float)$row['11']; ?>
                    <td style="text-align:right;color:<?php echo (int)$row['12'] < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['12']); else echo number_format($row['12'],2);?></td>
                    <?php $shoukei += (float)$row['12']; ?>
                    <td style="text-align:right;color:<?php echo $shoukei < 0 ? 'red' : 'black'; ?>;"><?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($shoukei); else echo number_format($shoukei,2);?></td>
                    <?php $shoukei = 0; ?>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <?php
            $counter = 0; // ループカウンター
            $tempCounter = 1; // 一つのキー毎のカウンター (前年に文字色を付けるために必要)
            $row_color = 'green';
            ?>
            <?php foreach ($buff as $row): ?>
                <?php
                    if ($tempCounter % 2 === 0) {
                        $row_color = 'green';
                    } else {
                        $row_color = 'black';
                    }
                    if ($tempCounter === 3) {
                        $tempCounter = 1;
                    } else {
                        $tempCounter++;
                    }
                ?>
                <tr>
                    <td style="text-align:left;color:<?php echo $tempCounter !== 2 ? '#eee' : $row_color; ?>;"><?php echo $row['key']; ?></td>
                    <td style="text-align:left;color:<?php echo $tempCounter !== 2 ? '#eee' : $row_color; ?>;"><?php echo $row['key_name']; ?></td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['1'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['1']); else echo number_format($row['1'],2); ?>
                            <?php $shoukei += (float)$row['1']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['2'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['2']); else echo number_format($row['2'],2); ?>
                            <?php $shoukei += (float)$row['2']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['3'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['3']); else echo number_format($row['3'],2); ?>
                            <?php $shoukei += (float)$row['3']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['4'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['4']); else echo number_format($row['4'],2); ?>
                            <?php $shoukei += (float)$row['4']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['5'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['5']); else echo number_format($row['5'],2); ?>
                            <?php $shoukei += (float)$row['5']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['6'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['6']); else echo number_format($row['6'],2); ?>
                            <?php $shoukei += (float)$row['6']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['7'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['7']); else echo number_format($row['7'],2); ?>
                            <?php $shoukei += (float)$row['7']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['8'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['8']); else echo number_format($row['8'],2); ?>
                            <?php $shoukei += (float)$row['8']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['9'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['9']); else echo number_format($row['9'],2); ?>
                            <?php $shoukei += (float)$row['9']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['10'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['10']); else echo number_format($row['10'],2); ?>
                            <?php $shoukei += (float)$row['10']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['11'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['11']); else echo number_format($row['11'],2); ?>
                            <?php $shoukei += (float)$row['11']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu')): ?>
                            <?php echo number_format($row['12'],1); ?>
                        <?php else: ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($row['12']); else echo number_format($row['12'],2); ?>
                            <?php $shoukei += (float)$row['12']; ?>
                        <?php endif; ?>
                    </td>
                    <td style="text-align:right;color:<?php echo $row_color; ?>;">
                        <?php if (strpos($row['key'], 'hiritu') === false): ?>
                            <?php if ($setdts['hyouji_kbn'] !== '3') echo number_format($shoukei); else echo number_format($shoukei,2);?>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php $shoukei = 0; ?>
                <?php $counter++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="col-sm-2">
        <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal"
                onclick="window.parent.fromModal();">中止
        </button>
    </div>
</div>
<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle" style="width:900px; height:500px;">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        売上推移表条件設定
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    var jouken_uriage_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_uriage_suiiss/ajaxGet') ?>";
    var konnnendo_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('konnnenndo/ajaxGet') ?>";
    var junjo_kbns_ajaxHanni = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('junjo_kbns/ajaxHanni') ?>";
    var jouken_uriage_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_uriage_suiiss/modal') ?>";
    var jouken_flds = [
        'torihiki_kbn_betu_flg'
        , 'junjo_kbn_cd'
        , 'torihiki_kbn_cd'
        , 'koujun_flg'
        , 'zennen_flg'
        , 'hanni_from'
        , 'hanni_from_name'
        , 'hanni_to'
        , 'hanni_to_name'
        , 'zeikomi_flg'
        , 'meisaigyou_flg'
        , 'goukeigyou_flg'
        , 'torihikiari_flg'
        , 'torihikinasi_flg'
        , 'hokakei_flg'
    ];
</script>
<script>
    $(function () {
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/report_uriage_suiis.js'); ?>?var=20191114"></script>
