<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "在庫変換区分.一覧"; ?>
<div class="page-header">
    <h3>在庫変換区分 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"zaiko_henkan_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["denpyou_mr_cd","伝票コード"],
                    ["shiire_flg","仕入在庫フラグ"],
                    ["nyuuko_flg","他入庫フラグ"],
                    ["uriage_flg","売上在庫フラグ"],
                    ["shukko_flg","他出庫フラグ"],
                    ["azuchou_flg","預り調整フラグ"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $zaiko_henkan_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/edit/" . $zaiko_henkan_kbn->id, $zaiko_henkan_kbn->id)); ?></td>
                <td><?php echo $zaiko_henkan_kbn->cd ?></td>
                <td><?php echo $zaiko_henkan_kbn->name ?></td>
                <td><?php echo $zaiko_henkan_kbn->denpyou_mr_cd ?></td>
                <td><?php echo $zaiko_henkan_kbn->shiire_flg ?></td>
                <td><?php echo $zaiko_henkan_kbn->nyuuko_flg ?></td>
                <td><?php echo $zaiko_henkan_kbn->uriage_flg ?></td>
                <td><?php echo $zaiko_henkan_kbn->shukko_flg ?></td>
                <td><?php echo $zaiko_henkan_kbn->azuchou_flg ?></td>
                <td><?php echo $zaiko_henkan_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/delete/" . $zaiko_henkan_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("zaiko_henkan_kbns/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("zaiko_henkan_kbns/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
