<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = 'ロード項目.新規'; ?>
<div class="page-header">
    <h3>ロード項目マスタ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "load_koumoku_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLoadMrCd" class="col-sm-2 control-label">ロードマスタコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("load_mr_cd", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldLoadMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJun" class="col-sm-2 control-label">並び順</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("jun", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJun")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKoumokuMrCd" class="col-sm-2 control-label">項目コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("koumoku_mr_cd", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldKoumokuMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKeys" class="col-sm-2 control-label">上書きキー項目印</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("keys", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKeys")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFusiyouKbn" class="col-sm-2 control-label">不使用区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("fusiyou_kbn", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldFusiyouKbn")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
