<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "加工流れ見出し区分.一覧"; ?>
<div class="page-header">
    <h3>加工流れ見出し区分 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"kakou_nagare_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","行番"],
                    ["name","名称"],
                    ["bikou","備考"],
                    ["naiyou_cd_table_id","内容コードのテーブル"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $kakou_nagare_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("kakou_nagare_kbns/edit/" . $kakou_nagare_kbn->id, $kakou_nagare_kbn->id)); ?></td>
                <td><?php echo $kakou_nagare_kbn->cd ?></td>
                <td><?php echo $kakou_nagare_kbn->name ?></td>
                <td><?php echo $kakou_nagare_kbn->bikou ?></td>
                <td><?php echo $kakou_nagare_kbn->naiyou_cd_table_id ?></td>
                <td><?php echo $kakou_nagare_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("kakou_nagare_kbns/delete/" . $kakou_nagare_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"kakou_nagare_kbns"]) ?>
