<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "商品分類５.修正"; ?>
<div class="page-header">
    <h3>商品分類５ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "shouhin_bunrui5_kbns/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 4, "maxlength" => 4, "style" => "width: 84px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">分類名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shouhin_bunrui5_kbns/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("shouhin_bunrui5_kbns/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("shouhin_bunrui5_kbns/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shouhin_bunrui5_kbns/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
