<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var null|string $viewsDir
 * @var closure $fileOwner Get file owner/group closure
 */
?>

<?php $title = 'List.View'; ?>
<h1 class="page-header">Search Views <?php echo $viewsDir; ?></h1>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th width="10%">Size</th>
                    <th width="15%">Updated</th>
                    <th width="10%">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php if (!$viewsDir): ?>
                <tr class="warning">
                    <td colspan="4">
                        <p class="text-center lead">
                            Sorry, WebTools doesn't know where the views directory is.<br>
                            Please add the valid path for <code>viewsDir</code> in the <code>application</code> section.
                        </p>
                    </td>
                </tr>
            <?php else: ?>
                <?php $iterator = new DirectoryIterator('../app/views/' . $viewsDir); foreach($iterator as $file): ?>
                    <?php if (!$file->isDot() && 0 !== strrpos($file->getBasename(), '.')): ?>
                        <tr>
                            <td><?php echo $file->getFileName(); ?></td>
                            <td><?php echo $file->getSize() . ' b' ?></td>
                            <td><?php echo date("Y-m-d H:i:s", $file->getMTime()); ?></td>
                            <td>
                                <?php echo $this->tag->linkTo(array('edit_views/edit/' . $viewsDir . '/'. $file->getFileName(), 'Edit', 'class' => 'btn btn-link')); ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
