<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search itomei_vws
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["itomei_vws/new", "Create itomei_vws"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "itomei_vws/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldItoshu" class="col-sm-2 control-label">Itoshu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["itoshu", "type" => "number", "class" => "form-control", "id" => "fieldItoshu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItoCode" class="col-sm-2 control-label">Ito Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ito_code", "size" => 30, "class" => "form-control", "id" => "fieldItoCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItomei1" class="col-sm-2 control-label">Itomei1</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["itomei1", "size" => 30, "class" => "form-control", "id" => "fieldItomei1"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItomei2" class="col-sm-2 control-label">Itomei2</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["itomei2", "size" => 30, "class" => "form-control", "id" => "fieldItomei2"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItomei3" class="col-sm-2 control-label">Itomei3</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["itomei3", "size" => 30, "class" => "form-control", "id" => "fieldItomei3"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKoushinKbn" class="col-sm-2 control-label">Koushin Of Kbn</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["koushin_kbn", "type" => "number", "class" => "form-control", "id" => "fieldKoushinKbn"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKousinDate" class="col-sm-2 control-label">Kousin Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kousin_date", "size" => 30, "class" => "form-control", "id" => "fieldKousinDate"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
