<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "レポート条件見出し.修正"; ?>
<div class="page-header">
    <h3>レポート条件見出し 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "report_jouken_mrs/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldTableMrCd" class="col-sm-2 control-label">テーブルコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("table_mr_cd", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldTableMrCd")) ?>
    </div>

<label for="fieldKoukaiKbn" class="col-sm-2 control-label">公開区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("koukai_kbn", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKoukaiKbn")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("report_jouken_mrs/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("report_jouken_mrs/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("report_jouken_mrs/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("report_jouken_mrs/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
