<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "レポート条件見出し.一覧"; ?>
<div class="page-header">
    <h3>レポート条件見出し 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"report_jouken_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["table_mr_cd","テーブルコード"],
                    ["koukai_kbn","公開区分"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $report_jouken_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("report_jouken_mrs/edit/" . $report_jouken_mr->id, $report_jouken_mr->id)); ?></td>
                <td><?php echo $report_jouken_mr->cd ?></td>
                <td><?php echo $report_jouken_mr->name ?></td>
                <td><?php echo $report_jouken_mr->table_mr_cd ?></td>
                <td><?php echo $report_jouken_mr->koukai_kbn ?></td>
                <td><?php echo $report_jouken_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("report_jouken_mrs/delete/" . $report_jouken_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"report_jouken_mrs"]) ?>
