<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "糸原価マスタ.一覧"; ?>
<div class="page-header">
    <h3>糸原価マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"h_itogen_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["gyou","行"],
                    ["gcd","原料糸コード"],
                    ["tani","原単位"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $h_itogen_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("h_itogen_mrs/edit/" . $h_itogen_mr->id, $h_itogen_mr->id)); ?></td>
                <td><?php echo $h_itogen_mr->cd ?></td>
                <td><?php echo $h_itogen_mr->gyou ?></td>
                <td><?php echo $h_itogen_mr->gcd ?></td>
                <td><?php echo $h_itogen_mr->tani ?></td>
                <td><?php echo $h_itogen_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("h_itogen_mrs/delete/" . $h_itogen_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"h_itogen_mrs"]) ?>
