<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["higenr_vws/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["higenr_vws/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Sasizu Of No</th>
            <th>Genryou Of Jun</th>
            <th>Itoshu</th>
            <th>Itocode</th>
            <th>Gentanni</th>
            <th>Chokuyori Of Kbn</th>
            <th>Chokuyori Of Sasizu Of No</th>
            <th>Ukeire Of Sasizu</th>
            <th>Ukeire Of Zumi</th>
            <th>Free Of Ukeire Of Sasizu</th>
            <th>Free Of Ukeire Of Zumi</th>
            <th>Shouhi Of Chousei Of Sasizu</th>
            <th>Shouhi Of Chousei Of Zumi</th>
            <th>Shouhi Of Zumi</th>
            <th>Kanryou Of Kbn</th>
            <th>Kuuhaku</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $higenr_vw): ?>
            <tr>
                <td><?php echo $higenr_vw->sasizu_no ?></td>
            <td><?php echo $higenr_vw->genryou_jun ?></td>
            <td><?php echo $higenr_vw->itoshu ?></td>
            <td><?php echo $higenr_vw->itocode ?></td>
            <td><?php echo $higenr_vw->gentanni ?></td>
            <td><?php echo $higenr_vw->chokuyori_kbn ?></td>
            <td><?php echo $higenr_vw->chokuyori_sasizu_no ?></td>
            <td><?php echo $higenr_vw->ukeire_sasizu ?></td>
            <td><?php echo $higenr_vw->ukeire_zumi ?></td>
            <td><?php echo $higenr_vw->free_ukeire_sasizu ?></td>
            <td><?php echo $higenr_vw->free_ukeire_zumi ?></td>
            <td><?php echo $higenr_vw->shouhi_chousei_sasizu ?></td>
            <td><?php echo $higenr_vw->shouhi_chousei_zumi ?></td>
            <td><?php echo $higenr_vw->shouhi_zumi ?></td>
            <td><?php echo $higenr_vw->kanryou_kbn ?></td>
            <td><?php echo $higenr_vw->kuuhaku ?></td>

                <td><?php echo $this->tag->linkTo(["higenr_vws/edit/" . $higenr_vw->sasizu_no, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["higenr_vws/delete/" . $higenr_vw->sasizu_no, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("higenr_vws/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("higenr_vws/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("higenr_vws/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("higenr_vws/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
