<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "出荷依頼データ.一覧"; ?>
<div class="page-header">
    <h3>出荷依頼データ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"shukkairai_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","依頼番号"],
                    ["tekiyou","摘要"],
                    ["nendo","年度"],
                    ["iraibi","依頼日"],
                    ["irai_kbn_cd","依頼区分"],
                    ["juchuu_dt_id","受注id"],
                    ["hacchuu_dt_id","発注id"],
                    ["souko_mr_cd","依頼先倉庫"],
                    ["gotantou","ご担当者"],
                    ["hassousaki_kbn_cd","発送先区分"],
                    ["hassousaki_mr_cd","発送先コード"],
                    ["hassousaki","発送先名"],
                    ["kidukesaki_mr_cd","気付先コード"],
                    ["kiduke","気付先名"],
                    ["shukkabi","出荷日"],
                    ["nouki_memo","納期メモ"],
                    ["tantou_mr_cd","担当者"],
                    ["assistant","アシスタント"],
                    ["shounin_joutai_flg","承認状態"],
                    ["shounin_sha_mr_cd","承認者"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shukkairai_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("shukkairai_dts/edit/" . $shukkairai_dt->id, $shukkairai_dt->id)); ?></td>
                <td><?php echo $shukkairai_dt->cd ?></td>
                <td><?php echo $shukkairai_dt->tekiyou ?></td>
                <td><?php echo $shukkairai_dt->nendo ?></td>
                <td><?php echo $shukkairai_dt->iraibi ?></td>
                <td><?php echo $shukkairai_dt->irai_kbn_cd ?></td>
                <td><?php echo $shukkairai_dt->juchuu_dt_id ?></td>
                <td><?php echo $shukkairai_dt->hacchuu_dt_id ?></td>
                <td><?php echo $shukkairai_dt->souko_mr_cd ?></td>
                <td><?php echo $shukkairai_dt->gotantou ?></td>
                <td><?php echo $shukkairai_dt->hassousaki_kbn_cd ?></td>
                <td><?php echo $shukkairai_dt->hassousaki_mr_cd ?></td>
                <td><?php echo $shukkairai_dt->hassousaki ?></td>
                <td><?php echo $shukkairai_dt->kidukesaki_mr_cd ?></td>
                <td><?php echo $shukkairai_dt->kiduke ?></td>
                <td><?php echo $shukkairai_dt->shukkabi ?></td>
                <td><?php echo $shukkairai_dt->nouki_memo ?></td>
                <td><?php echo $shukkairai_dt->tantou_mr_cd ?></td>
                <td><?php echo $shukkairai_dt->assistant ?></td>
                <td><?php echo $shukkairai_dt->shounin_joutai_flg ?></td>
                <td><?php echo $shukkairai_dt->shounin_sha_mr_cd ?></td>
                <td><?php echo $shukkairai_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("shukkairai_dts/delete/" . $shukkairai_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"shukkairai_dts"]) ?>
