<div class="panel panel-danger bg-yel">
 <div class="panel-heading pnl-hed" onclick="save_ros()">出荷依頼伝票<span id="save_ros" style="color:pink;cursor:pointer;">(click→「入力制御の保存」)</span></div>
 <div class="panel-body">
    <div  class="col-sm-2">
        <label for="fieldCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('Cd')">出荷依頼番号></label>
        <?php echo $this->tag->textField(array("cd", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['cd']??0)==1?'readonly':null, "id" => "fieldCd")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldIraibi" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('Iraibi')">発行日></label>
        <?php echo $this->tag->telField(array("iraibi", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", 'readonly'=>($readonlys['iraibi']??0)==1?'readonly':null, "id" => "fieldIraibi")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldJuchuuDtCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('JuchuuDtCd')">受注番号></label>
        <?php echo $this->tag->textField(array("juchuu_dt_cd", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['juchuu_dt_cd']??0)==1?'readonly':null, "id" => "fieldJuchuuDtCd", "list" => "JuchuuDtsOptions")) ?>
        <?php echo $this->tag->hiddenField(array("juchuu_dt_id", "id" => "fieldJuchuuDtId")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldHacchuuDtCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('HacchuuDtCd')">発注番号></label>
        <?php echo $this->tag->textField(array("hacchuu_dt_cd", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['hacchuu_dt_cd']??0)==1?'readonly':null, "id" => "fieldHacchuuDtCd", "list" => "HacchuuDtsOptions")) ?>
        <?php echo $this->tag->hiddenField(array("hacchuu_dt_id", "id" => "fieldHacchuuDtId")) ?>
    </div>
    <div class="col-sm-2">
        <!-- 出荷日がポストされていなかった。 2019/6/24-->
        <label for="fieldShukkabi" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('Shukkabi')">出荷日></label>
        <?php echo $this->tag->telField(array("shukkabi", "size" => 10, "maxlength" => 10, "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['shukkabi']??0)==1?'readonly':null, "id" => "fieldShukkabi")) ?>
    </div>
    <div class="col-sm-2">
      <label for="fieldNoukiMemo" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('NoukiMemo')">納期メモ</label>
      <div class="col-sm-12">
        <?php echo $this->tag->textField(array("nouki_memo", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-a", 'readonly'=>($readonlys['nouki_memo']??0)==1?'readonly':null, "id" => "fieldNoukiMemo")) ?>
      </div>
    </div>
     <div class="col-sm-12 pnl-hed">　</div>
  <div class="col-sm-8">
    <label for="fieldTokuisakiMrCd" class="col-sm-2 control-label lbl-grn">受注先</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("tokuisaki_mr_cd", "readonly" => "readonly", "class" => "form-control", "id" => "fieldTokuisakiMrCd")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("tokuisaki_mr_name", "readonly" => "readonly", "class" => "form-control", "id" => "fieldTokuisakiMrName")) ?>
    </div>
    <label for="fieldIraiKbnCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('IraiKbnCd')">依頼区分</label>
    <div class="col-sm-4">
        <?php echo $this->tag->selectStatic(array("irai_kbn_cd", ["1" => "1=倉庫移動" , "2" => "2=売上"], 'useEmpty' => false, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['irai_kbn_cd']??0)==1?'readonly':null, "id" => "fieldIraiKbnCd")) ?>
    </div>
	<div class="clearfix"></div>
    <label for="fieldSoukoMrCd" class="col-sm-2 control-label lbl-grn">依頼先></label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("souko_mr_cd", "size" => 14, "maxlength" => 14, "class" => "form-control ime-d", "id" => "fieldSoukoMrCd", "list" => "SoukoMrsOptions")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("souko_mr_name", "readonly" => "readonly", "class" => "form-control", "id" => "fieldSoukoMrName")) ?>
    </div>
    <label for="fieldGotantou" class="col-sm-2 control-label lbl-grn">ご担当者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("gotantou", "size" => 40, "maxlength" => 40, "class" => "form-control ime-a", 'readonly'=>($readonlys['gotantou']??0)==1?'readonly':null, "id" => "fieldGotantou")) ?>
    </div>
    <label for="fieldHassousakiKbnCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('HassousakiKbnCd');switch_roa('HassousakiMrCd')">発送先</label>
    <div class="col-sm-3">
        <?php echo $this->tag->select(array("hassousaki_kbn_cd", HassousakiKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['hassousaki_kbn_cd']??0)==1?'readonly':null, "id" => "fieldHassousakiKbnCd")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("hassousaki_mr_cd", "size" => 24, "maxlength" => 24, "class" => "form-control ime-d", 'readonly'=>($readonlys['hassousaki_kbn_cd']??0)==1?'readonly':null, "id" => "fieldHassousakiMrCd", "list" => "NounyuusakiMrsOptions")) ?>
    </div>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(array("hassousaki", "readonly" => ($readonlys['hassousaki_kbn_cd']??0)==1?'readonly':null, "class" => "form-control ime-a", "id" => "fieldHassousaki")) ?>
    </div>
	<div class="clearfix"></div>
    <label for="fieldKidukesakiMrCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('KidukesakiMrCd')">気付先></label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("kidukesaki_mr_cd", "size" => 4, "maxlength" => 4, "class" => "form-control ime-d", 'readonly'=>($readonlys['kidukesaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldKidukesakiMrCd", "list" => "KidukesakiMrsOptions")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("kiduke", "size" => 40, "maxlength" => 40, "class" => "form-control ime-a", 'readonly'=>($readonlys['kidukesaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldKiduke")) ?>
    </div>
    <label for="fieldTantouMrCd" class="col-sm-2 control-label lbl-grn">担当者</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tantou_mr_cd", TantouMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", "id" => "fieldTantouMrCd")) ?>
    </div>
    <label for="fieldAssistant" class="col-sm-2 control-label lbl-grn">アシスタント</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("assistant", "size" => 40, "maxlength" => 40, "class" => "form-control ime-a", 'readonly'=>($readonlys['assistant']??0)==1?'readonly':null, "id" => "fieldAssistant")) ?>
    </div>
    <label for="fieldTekiyou" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('Tekiyou')">摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tekiyou", "size" => 32, "maxlength" => 32, "class" => "form-control ime-a", 'readonly'=>($readonlys['tekiyou']??0)==1?'readonly':null, "id" => "fieldTekiyou")) ?>
    </div>
   </div>
   <div class="col-sm-4">
    <label for="fieldSakuseiUserName" class="col-sm-5 control-label lbl-grn">入力者</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("sakusei_user_name", "readonly" => "readonly", "class" => "form-control", "id" => "fieldSakuseiUserName")) ?>
    </div>
    <label for="fieldUpdated" class="col-sm-5 control-label lbl-grn">更新日時</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("updated", "readonly" => "readonly", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
    <label for="fieldShouninJoutaiFlg" class="col-sm-5 control-label lbl-grn" onclick="switch_roa('ShouninJoutaiFlg')">承認状態</label>
    <div class="col-sm-7">
        <?php echo $this->tag->selectStatic(array("shounin_joutai_flg", array("0" => "0=未承認", "1" => "1=承認済み"), "class" => "form-control", 'readonly'=>($readonlys['shounin_joutai_flg']??0)==1?'readonly':null, "id" => "fieldShouninJoutaiFlg")) ?>
    </div>
    <label for="fieldShouninShaMrCd" class="col-sm-5 control-label lbl-grn" onclick="switch_roa('ShouninShaMrCd')">承認者</label>
    <div class="col-sm-7">
        <?php echo $this->tag->select(array("shounin_sha_mr_cd", Users::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['shounin_sha_mr_cd']??0)==1?'readonly':null, "id" => "fieldShouninShaMrCd")) ?>
    </div>
   </div>
 </div><!-- panel-body -->
 <?php echo $this->tag->hiddenField("gaku_hasuu_shori_kbn_cd") ?>
 <?php echo $this->tag->hiddenField("zei_hasuu_shori_kbn_cd") ?>
<!--
</div>
<div class="panel panel-success bg-yel">
-->
 <div class="panel-heading pnl-hed">出荷依頼明細</div>
 <div class="panel-body" style="overflow-x: scroll;padding: 0;">
 <style scoped>
 	table{
 		table-layout:fixed;
 		width:100%;
 	}
 	th,td{
 		white-space:nowrap;
 	}
 	th{
 		border-right:1px #ccc solid;
 		font-size:x-small;
 		font-weight:normal;
 		text-align:center;
 		color: #3d773d;
 		background-color:#dff0d8;
 	}
	th.ot-fixed,td.ot-fixed{
		position:absolute;
		left:6px;
		width:<?php echo $rewidths['[cd']??'30' ?>px;
	}
 </style>
 <table id="meisaiTable">
  <thead><tr><th onclick="switch_ros('Cd')" class="ot-fixed">No
   </th><th width=<?php echo $rewidths['[utiwake_kbn_cd']??'"70"'  ?> onclick="switch_ros('UtiwakeKbnCd')">内訳
   </th><th width=<?php echo $rewidths['[shukka_kbn_cd'] ??'"20"'  ?> >出荷
   </th><th width=<?php echo $rewidths['[shouhin_mr_cd'] ??'"100"' ?> >商品>
   </th><th width=<?php echo $rewidths['[lot']           ??'"20"'  ?> onclick="switch_ros('Lot')">ロット
   </th><th width=<?php echo $rewidths['[tekiyou']       ??'"200"' ?> onclick="switch_ros('Tekiyou')">商品名／摘要
   </th><th width=<?php echo $rewidths['[iro']           ??'"20"'  ?> onclick="switch_ros('Iro')">色番
   </th><th width=<?php echo $rewidths['[iromei']        ??'"20"'  ?> onclick="switch_ros('Iromei')">色名
   </th><th width=<?php echo $rewidths['[kobetucd']     ??'"20"'  ?> onclick="switch_ros('Kobetucd')">個別
   </th><th width=<?php echo $rewidths['[hinsitu_kbn_cd']??'"20"'  ?> onclick="switch_ros('HinsituKbnCd')">品質
   </th><th width=<?php echo $rewidths['[souko_mr_cd']   ??'"100"' ?> onclick="switch_ros('SoukoMrCd')">倉庫
   </th><th width=<?php echo $rewidths['[irisuu']        ??'"20"'  ?> onclick="switch_ros('Irisuu')">入数
   </th><th width=<?php echo $rewidths['[suuryou1']      ??'"70"'  ?> onclick="switch_ros('Suuryou1')">数1
   </th><th width=<?php echo $rewidths['[tanni_mr1_cd']  ??'"50"'  ?> onclick="switch_ros('TanniMr1Cd')">単位
   </th><th width=<?php echo $rewidths['[suuryou2']      ??'"80"'  ?> >数量
   </th><th width=<?php echo $rewidths['[tanni_mr2_cd']  ??'"50"'  ?> onclick="switch_ros('TanniMr2Cd')">単位
   </th><th width=<?php echo $rewidths['[shukkairaizan']     ??'"20"'  ?> >注残
   </th><th width=<?php echo $rewidths['[gentanka']      ??'"20"'  ?> onclick="switch_ros('Gentanka')">コスト
   </th><th width=<?php echo $rewidths['[bikou']         ??'"100"' ?> onclick="switch_ros('Bikou')">備考
   </th><th width=<?php echo $rewidths['[nouki']         ??'"100"' ?> onclick="switch_ros('Nouki')">納期
   </th></tr>
  </thead>
  <tbody><style scoped>div[class^="col-sm"],div[class^="panel"]{padding:0 !important;}</style>
  <?php $kousei_oya = -1; ?>
  <?php for ($i = -1; $i < $imax; $i++): /* $imaxはcontrollerから受け取る */ ?>
  <?php
    if ($i < 0) {
      $name_head = "hidden"; // name-hedder nameの前半
      $id_head = "hidden"; // id-hedder idの前半
      echo '<tr id="tr_shukkairai_meisai_dt_hidden" style="display:none;">';
    } else {
      $name_head = "data[shukkairai_meisai_dts][".$i."]";
      $id_head = "fieldShukkairaiMeisaiDts" . $i;
      echo '<tr id="tr_shukkairai_meisai_dt_' . $i . '"'.($kousei_oya < 0 || $this->tag->getValue($name_head . "[kousei]")=='-'?'':(' class="kodomo'.$kousei_oya.'"')) .'>';
    }
  ?>
                 <td class="ot-fixed">
                     <!-- 行番 --><?php echo $this->tag->textField(array($name_head . "[cd]", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['[cd']??0)==1?'readonly':null, "id" => $id_head . "Cd")) ?>
                     <!--  ID        --><?php echo $this->tag->hiddenField(array($name_head . "[id]", "id" => $id_head . "Id")) ?>
                     <!-- 更新日時   --><?php echo $this->tag->hiddenField(array($name_head . "[updated]", "id" => $id_head . "Updated")) ?>
                     <!-- 原価額     --><?php echo $this->tag->hiddenField(array($name_head . "[genkagaku]", "id" => $id_head . "Genkagaku")) ?>
                     <!--数量小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu_shousuu]", "id" => $id_head . "SuuShousuu")) ?>
                     <!--数１小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu1_shousuu]", "id" => $id_head . "Suu1Shousuu")) ?>
                     <!--数２小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu2_shousuu]", "id" => $id_head . "Suu2Shousuu")) ?>
                     <!--単価小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[tanka_shousuu]", "id" => $id_head . "TankaShousuu")) ?>
                     <!--在庫単位区分--><?php echo $this->tag->hiddenField(array($name_head . "[zaiko_kbn]", "id" => $id_head . "ZaikoKbn")) ?>
                     <!-- 商品元単位 --><?php echo $this->tag->hiddenField(array($name_head . "[moto_tanni_mr2_cd]", "id" => $id_head . "MotoTanniMr2Cd")) ?>
                     <!-- プロ       --><?php echo $this->tag->hiddenField(array($name_head . "[project_mr_cd]", "id" => $id_head . "ProjectMrCd")) ?>

   </td>         <td><!-- 内訳 --><?php /* echo $this->tag->select(array($name_head . "[utiwake_kbn_cd]", UtiwakeKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "conditions" => "uriage_flg = 1", "order" => "cd"]) */ 
                                           echo $this->tag->selectStatic(array($name_head . "[utiwake_kbn_cd]", ["2"=>"2=倉庫移動","10"=>"10=通常","20"=>"20=製品","23"=>"23=預り","40"=>"40=摘要","41"=>"41=メモ"], 
                                           'useEmpty' => true, 'emptyText' => '', "class" => "form-control frm0c", 'readonly'=>($readonlys['[utiwake_kbn_cd']??0)==1?'readonly':null, "id" => $id_head . "UtiwakeKbnCd")) ?>
			<?php $kouseix=$this->tag->getValue($name_head . "[kousei]");$kousei_oya_class='';if ($kouseix==''){$kousei_oya=-1;}else if($kouseix=='-'||$kouseix=='+'){$kousei_oya=$i;$kousei_oya_class=' kousei_oya';} ?>
   </td>         <td><!-- 出荷 --><?php echo $this->tag->select(array($name_head . "[shukka_kbn_cd]", ShukkaKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[shukka_kbn_cd']??0)==1?'readonly':null, "id" => $id_head . "ShukkaKbnCd")) ?>
   </td>         <td><!-- 商品 --><?php echo $this->tag->textField(array($name_head . "[shouhin_mr_cd]", "maxlength" => 20, "style" => "padding: 0;", "class" => "form-control ime-a f-cent", "id" => $id_head . "ShouhinMrCd", "list" => "ShouhinMrsOptions")) ?>
   </td>         <td><!--ロット--><?php echo $this->tag->textField(array($name_head . "[lot]", "size" => 8, "maxlength" => 40, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[lot']??0)==1?'readonly':null, "id" => $id_head . "Lot")) ?>
   </td>         <td><!-- 摘要 --><?php echo $this->tag->textField(array($name_head . "[tekiyou]", "size" => 40, "maxlength" => 40, "style" => "padding: 0;", "class" => "form-control ime-a", 'readonly'=>($readonlys['[tekiyou']??0)==1?'readonly':null, "id" => $id_head . "Tekiyou")) ?>
   </td>         <td><!-- 色番 --><?php echo $this->tag->textField(array($name_head . "[iro]", "size" => 8, "maxlength" => 12, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[iro']??0)==1?'readonly':null, "id" => $id_head . "Iro")) ?>
   </td>         <td><!-- 色名 --><?php echo $this->tag->textField(array($name_head . "[iromei]", "size" => 8, "maxlength" => 16, "style" => "padding: 0;", "class" => "form-control ime-a f-cent", 'readonly'=>($readonlys['[iromei']??0)==1?'readonly':null, "id" => $id_head . "Iromei")) ?>
   </td>         <td><!-- 個別 --><?php echo $this->tag->textField(array($name_head . "[kobetucd]", "maxlength" => 20, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[kobetucd']??0)==1?'readonly':null, "id" => $id_head . "Kobetucd", "list" => "ShouhinMrsOptions")) ?>
   </td>         <td><!-- 品質 --><?php echo $this->tag->select(array($name_head . "[hinsitu_kbn_cd]", HinsituKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[hinsitu_kbn_cd']??0)==1?'readonly':null, "id" => $id_head . "HinsituKbnCd")) ?>
   </td>         <td><!-- 倉庫 --><?php echo $this->tag->select(array($name_head . "[souko_mr_cd]", SoukoMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[souko_mr_cd']??0)==1?'readonly':null, "id" => $id_head . "SoukoMrCd")) ?>
   </td>         <td><!-- 入数 --><?php echo $this->tag->textField(array($name_head . "[irisuu]", "size" => 10, "style" => "padding: 0;", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['[irisuu']??0)==1?'readonly':null, "id" => $id_head . "Irisuu")) ?>
   </td>         <td><!-- 箱数 --><?php echo $this->tag->textField(array($name_head . "[suuryou1]", "size" => 10, "style" => "padding: 0;", "class" => "form-control f-numb", 'readonly'=>($readonlys['[suuryou1']??0)==1?'readonly':null, "id" => $id_head . "Suuryou1")) ?>
   </td>         <td><!--数単位--><?php echo $this->tag->select(array($name_head . "[tanni_mr1_cd]", TanniMrs::find(["columns" => "cd , CONCAT(name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[tanni_mr1_cd']??0)==1?'readonly':null, "id" => $id_head . "TanniMr1Cd")) ?>
   </td>         <td><!-- 数量 --><?php echo $this->tag->textField(array($name_head . "[suuryou2]", "size" => 8, "maxlength" => 10, "class" => "form-control f-numb", "id" => $id_head . "Suuryou2")) ?>
   </td>         <td><!-- 単位 --><?php echo $this->tag->select(array($name_head . "[tanni_mr2_cd]", TanniMrs::find(["columns" => "cd , CONCAT(name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[tanni_mr2_cd']??0)==1?'readonly':null, "id" => $id_head . "TanniMr2Cd")) ?>
   </td>         <td><!--出荷依頼残--><?php echo $this->tag->textField(array($name_head . "[shukkairaizan]", "size" => 8, "readonly" => "readonly", "class" => "form-control f-numb", "id" => $id_head . "Shukkairaizan")) ?>
   </td>         <td><!--原単価--><?php echo $this->tag->textField(array($name_head . "[gentanka]", "size" => 8, "maxlength" => 10, "class" => "form-control f-numb", 'readonly'=>($readonlys['[gentanka']??0)==1?'readonly':null, "id" => $id_head . "Gentanka")) ?>
   </td>         <td><!-- 備考 --><?php echo $this->tag->textField(array($name_head . "[bikou]", "size" => 14, "maxlength" => 14, "style" => "padding: 0;", "class" => "form-control ime-a", 'readonly'=>($readonlys['[bikou']??0)==1?'readonly':null, "id" => $id_head . "Bikou")) ?>
   </td>         <td><!-- 納期 --><?php echo $this->tag->textField(array($name_head . "[nouki]", "size" => 10, "maxlength" => 10, "style" => "padding: 0;", "class" => "form-control ime-i", 'readonly'=>($readonlys['[nouki']??0)==1?'readonly':null, "id" => $id_head . "Nouki")) ?>
   </td></tr>
   <?php endfor; ?>
  </tbody></table>
 </div>
<!--
</div>
<div class="panel panel-success bg-yel">
-->
 <div class="panel-heading pnl-hed">情報</div>
 <div class="panel-body">

    <div class="col-sm-2">
        <label for="fieldGenzaiko" class="col-sm-12 control-label lbl-grn-up">在庫1</label>
        <?php echo $this->tag->textField(array("genzaiko1", "readonly" => "readonly", "class" => "form-control f-cent", "id" => "fieldGenzaiko1")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldGenzaiko" class="col-sm-12 control-label lbl-grn-up">在庫2</label>
        <?php echo $this->tag->textField(array("genzaiko", "readonly" => "readonly", "class" => "form-control f-cent", "id" => "fieldGenzaiko")) ?>
    </div>

    <?php echo $this->tag->hiddenField("id") ?>
    <?php echo $this->tag->hiddenField(array("chouhyou_mr_id", "id" => "fieldChouhyouMrId")) ?>

</div><!-- panel-body -->
</div><!-- panel -->
<div class="col-sm-offset-2 col-sm-10 bg-danger" id="dispErrMsg"></div>

<datalist id="JuchuuDtsOptions">
</datalist>

<datalist id="HacchuuDtsOptions">
</datalist>

<datalist id="SoukoMrsOptions">
</datalist>

<datalist id="NounyuusakiMrsOptions">
</datalist>

<datalist id="KidukesakiMrsOptions">
</datalist>

<datalist id="ShouhinMrsOptions">
</datalist>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
	<div class="modal-header" style="padding: 5px; background-color: #ddd;">
		<span id="iframe-title"></span>
		<button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
	</div>
	<div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
	</div>
</div>

<div id="PgDn"></div><div id="PgUp"></div><div id="END"></div>

<script type="text/javascript">
	var shukkairai_dts_new = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shukkairai_dts/new/') ?>";
	var shukkairai_dts_edit = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shukkairai_dts/edit/') ?>";
	var shukkairai_dts_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shukkairai_dts/modal') ?>";
	var den_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('zaiko_kakunin_azukari_vws/den_modal') ?>";
	var juchuu_dts_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('juchuu_dts/modal') ?>";
	var hacchuu_dts_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('hacchuu_dts/modal') ?>";
	var chouhyou_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('chouhyou_mrs/modal') ?>";
	var hassousaki_mrs_modal = "";
	var hassousaki_mrs_ajaxGet = "";
	var hassousaki_mrs_modals = {};
	var hassousaki_mrs_ajaxGets = {};
	var souko_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('souko_mrs/modal') ?>";
	var nounyuusaki_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('nounyuusaki_mrs/modal') ?>";
	var shouhin_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/modal') ?>";
    var lot_summary_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('report_zaiko_vws/lot_summary') ?>";
	var shukkairai_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shukkairai_dts/ajaxGet') ?>";
	var juchuu_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('juchuu_dts/ajaxGet') ?>";
	var hacchuu_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('hacchuu_dts/ajaxGet') ?>";
	var souko_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('souko_mrs/ajaxGet') ?>";
	var nounyuusaki_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('nounyuusaki_mrs/ajaxGet') ?>";
	var shouhin_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/ajaxGet') ?>";
	var report_zaiko_vws_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('report_zaiko_vws/ajaxGet') ?>";
	var readonlys_ajaxSave = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('readonly_field_kbns/ajaxSave') ?>";
    var shukkairai_meisai_dts_modal = "<?php echo "//" . $_SERVER['SERVER_NAME'] . $this->url->get('shukkairai_meisai_dts/history') ?>";
    var server_name = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shukkairai_dts/denpyou/') ?>"; //2019/12/19 Iura
	var my_id = <?php echo (int)$this->getDI()->getSession()->get('auth')['id']; ?>;
	<?php
		foreach ($hassousaki_kbns as $hassousaki_kbn) { /* $hassousaki_kbnsはcontrollerから受け取る */
			if ($hassousaki_kbn->sanshou_table == '') {
				echo "hassousaki_mrs_modals[".$hassousaki_kbn->cd."] = '';\n";
				echo "hassousaki_mrs_ajaxGets[".$hassousaki_kbn->cd."] = '';\n";
			} else {
				echo "hassousaki_mrs_modals[".$hassousaki_kbn->cd."] = '//".$_SERVER['SERVER_NAME'].$this->url->get($hassousaki_kbn->sanshou_table.'/modal')."';\n";
				echo "hassousaki_mrs_ajaxGets[".$hassousaki_kbn->cd."] = '//".$_SERVER['SERVER_NAME'].$this->url->get($hassousaki_kbn->sanshou_table.'/ajaxGet')."';\n";
			}
		}
	?>

</script>
