<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "出荷依頼データ.一覧"; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/modalkanni",["table_id"=>"shukkairai_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["tekiyou","fieldTekiyou","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["cd","依頼番号(選択)"],
                    ["tekiyou","摘要"],
                    ["iraibi","発行日"],
                    ["shukkabi","出荷日"],
                    ["souko_mr_cd","倉庫先"],
                    ["tantou_mr_cd","担当者"],
                    ["","商品1"],
                    ["","数量1"],
                ]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shukkairai_dt): ?>
            <tr>
                <td align="center"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $shukkairai_dt->cd; ?></div></td>
                <td><?php echo $shukkairai_dt->tekiyou ?></td>
                <td align="center"><?php echo $shukkairai_dt->iraibi ?></td>
                <td align="center"><?php echo $shukkairai_dt->shukkabi ?></td>
                <td><?php echo $shukkairai_dt->SoukoMrs->name ?></td>
                <td><?php echo $shukkairai_dt->TantouMrs->name ?></td>
                <td><?php echo $shukkairai_dt->ShukkairaiMeisaiDts[0]->shouhin_mr_cd ?></td>
                <td align="right"><?php echo $shukkairai_dt->ShukkairaiMeisaiDts[0]->suuryou2.$shukkairai_dt->ShukkairaiMeisaiDts[0]->TanniMr2s->name ?></td>

                <td align="center"><?php echo $this->tag->linkTo(array("shukkairai_dts/edit/" . $shukkairai_dt->id, "別タブ", "target"=>"_blank")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["index_or"=>"modal", "table_id"=>"shukkairai_dts"]) ?>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
