<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["prop_hikiate_vws/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["prop_hikiate_vws/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Sasizu Of No</th>
            <th>Sasizu Of Eda</th>
            <th>Kakou Of No</th>
            <th>Kakou Of No1</th>
            <th>Tanka</th>
            <th>Tanni</th>
            <th>Itomei</th>
            <th>Itomei2</th>
            <th>Lot</th>
            <th>Bikou</th>
            <th>Shukka Of Saki</th>
            <th>Juusho</th>
            <th>Tel</th>
            <th>Label Of Keisiki</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $prop_hikiate_vw): ?>
            <tr>
                <td><?php echo $prop_hikiate_vw->sasizu_no ?></td>
            <td><?php echo $prop_hikiate_vw->sasizu_eda ?></td>
            <td><?php echo $prop_hikiate_vw->kakou_no ?></td>
            <td><?php echo $prop_hikiate_vw->kakou_no1 ?></td>
            <td><?php echo $prop_hikiate_vw->tanka ?></td>
            <td><?php echo $prop_hikiate_vw->tanni ?></td>
            <td><?php echo $prop_hikiate_vw->itomei ?></td>
            <td><?php echo $prop_hikiate_vw->itomei2 ?></td>
            <td><?php echo $prop_hikiate_vw->lot ?></td>
            <td><?php echo $prop_hikiate_vw->bikou ?></td>
            <td><?php echo $prop_hikiate_vw->shukka_saki ?></td>
            <td><?php echo $prop_hikiate_vw->juusho ?></td>
            <td><?php echo $prop_hikiate_vw->tel ?></td>
            <td><?php echo $prop_hikiate_vw->label_keisiki ?></td>

                <td><?php echo $this->tag->linkTo(["prop_hikiate_vws/edit/" . $prop_hikiate_vw->sasizu_no, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["prop_hikiate_vws/delete/" . $prop_hikiate_vw->sasizu_no, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("prop_hikiate_vws/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("prop_hikiate_vws/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("prop_hikiate_vws/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("prop_hikiate_vws/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
