<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "条件候補マスタ.一覧"; ?>
<div class="page-header">
    <h3>条件候補マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"h_jouken_kouho_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","候補コード"],
                    ["jouken","条件値"],
                    ["name","候補名称"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $h_jouken_kouho_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("h_jouken_kouho_mrs/edit/" . $h_jouken_kouho_mr->id, $h_jouken_kouho_mr->id)); ?></td>
                <td><?php echo $h_jouken_kouho_mr->cd ?></td>
                <td><?php echo $h_jouken_kouho_mr->jouken ?></td>
                <td><?php echo $h_jouken_kouho_mr->name ?></td>
                <td><?php echo $h_jouken_kouho_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("h_jouken_kouho_mrs/delete/" . $h_jouken_kouho_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"h_jouken_kouho_mrs"]) ?>
