<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "期間指定区分.一覧"; ?>
<div class="page-header">
    <h3>期間指定区分 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"kikan_sitei_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","表示順"],
                    ["name","名称"],
                    ["yobidasi_tbl","呼出条件テーブル"],
                    ["script_from","スクリプト自"],
                    ["script_to","スクリプト至"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $kikan_sitei_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/edit/" . $kikan_sitei_kbn->id, $kikan_sitei_kbn->id)); ?></td>
                <td><?php echo $kikan_sitei_kbn->cd ?></td>
                <td><?php echo $kikan_sitei_kbn->name ?></td>
                <td><?php echo $kikan_sitei_kbn->yobidasi_tbl ?></td>
                <td><?php echo $kikan_sitei_kbn->script_from ?></td>
                <td><?php echo $kikan_sitei_kbn->script_to ?></td>
                <td><?php echo $kikan_sitei_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/delete/" . $kikan_sitei_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("kikan_sitei_kbns/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("kikan_sitei_kbns/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
