<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "加工流れ詳細データ.修正"; ?>
<div class="page-header">
    <h3>加工流れ詳細データ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "kakou_nagare_dts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">内容</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldHacchuuDtId" class="col-sm-2 control-label">発注書キー</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hacchuu_dt_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHacchuuDtId")) ?>
    </div>

<label for="fieldKakouNagareKbnId" class="col-sm-2 control-label">加工流れ見出しID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kakou_nagare_kbn_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKakouNagareKbnId")) ?>
    </div>

<label for="fieldNaiyouCd" class="col-sm-2 control-label">内容コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("naiyou_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldNaiyouCd")) ?>
    </div>

<label for="fieldBikou" class="col-sm-2 control-label">備考</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 80, "maxlength" => 100, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>

<label for="fieldKakuninKbn" class="col-sm-2 control-label">確認欄区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kakunin_kbn", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKakuninKbn")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("kakou_nagare_dts/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("kakou_nagare_dts/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("kakou_nagare_dts/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("kakou_nagare_dts/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
