<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "条件在庫一覧.一覧"; ?>
<div class="page-header">
    <h3>条件在庫一覧 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"jouken_zaiko_itiran","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","表示順"],
                    ["name","名称"],
                    ["junjo_kbn_cd","順序区分コード"],
                    ["hanni_from","範囲自"],
                    ["hanni_to","範囲至"],
                    ["junjo2_kbn_cd","順序2区分コード"],
                    ["hanni2_from","範囲2自"],
                    ["hanni2_to","範囲2至"],
                    ["koujun_flg","降順フラグ"],
                    ["kikan_tuki","期間月"],
                    ["zaiko0_flg","在庫０フラグ"],
                    ["torihikiari_flg","取引ありフラグ"],
                    ["torihikinasi_flg","取引なしフラグ"],
                    ["meisaigyou_flg","明細行表示フラグ"],
                    ["soukohyoujji_flg","倉庫表示フラグ"],
                    ["goukeigyou_flg","合計行表示フラグ"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $jouken_zaiko_itiran): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/edit/" . $jouken_zaiko_itiran->id, $jouken_zaiko_itiran->id)); ?></td>
                <td><?php echo $jouken_zaiko_itiran->cd ?></td>
                <td><?php echo $jouken_zaiko_itiran->name ?></td>
                <td><?php echo $jouken_zaiko_itiran->junjo_kbn_cd ?></td>
                <td><?php echo $jouken_zaiko_itiran->hanni_from ?></td>
                <td><?php echo $jouken_zaiko_itiran->hanni_to ?></td>
                <td><?php echo $jouken_zaiko_itiran->junjo2_kbn_cd ?></td>
                <td><?php echo $jouken_zaiko_itiran->hanni2_from ?></td>
                <td><?php echo $jouken_zaiko_itiran->hanni2_to ?></td>
                <td><?php echo $jouken_zaiko_itiran->koujun_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->kikan_tuki ?></td>
                <td><?php echo $jouken_zaiko_itiran->zaiko0_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->torihikiari_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->torihikinasi_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->meisaigyou_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->soukohyoujji_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->goukeigyou_flg ?></td>
                <td><?php echo $jouken_zaiko_itiran->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/delete/" . $jouken_zaiko_itiran->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("jouken_zaiko_itiran/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("jouken_zaiko_itiran/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
