<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "条件在庫一覧.新規"; ?>
<div class="page-header">
    <h3>条件在庫一覧 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "jouken_zaiko_itiran/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">表示順</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldJunjoKbnCd" class="col-sm-2 control-label">順序区分コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("junjo_kbn_cd", "size" => 8, "maxlength" => 8, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldJunjoKbnCd")) ?>
    </div>

<label for="fieldHanniFrom" class="col-sm-2 control-label">範囲自</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hanni_from", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldHanniFrom")) ?>
    </div>

<label for="fieldHanniTo" class="col-sm-2 control-label">範囲至</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hanni_to", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldHanniTo")) ?>
    </div>

<label for="fieldJunjo2KbnCd" class="col-sm-2 control-label">順序2区分コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("junjo2_kbn_cd", "size" => 8, "maxlength" => 8, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldJunjo2KbnCd")) ?>
    </div>

<label for="fieldHanni2From" class="col-sm-2 control-label">範囲2自</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hanni2_from", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldHanni2From")) ?>
    </div>

<label for="fieldHanni2To" class="col-sm-2 control-label">範囲2至</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hanni2_to", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldHanni2To")) ?>
    </div>

<label for="fieldKoujunFlg" class="col-sm-2 control-label">降順フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("koujun_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKoujunFlg")) ?>
    </div>

<label for="fieldKikanTuki" class="col-sm-2 control-label">期間月</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kikan_tuki", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKikanTuki")) ?>
    </div>

<label for="fieldZaiko0Flg" class="col-sm-2 control-label">在庫０フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zaiko0_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldZaiko0Flg")) ?>
    </div>

<label for="fieldTorihikiariFlg" class="col-sm-2 control-label">取引ありフラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("torihikiari_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldTorihikiariFlg")) ?>
    </div>

<label for="fieldTorihikinasiFlg" class="col-sm-2 control-label">取引なしフラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("torihikinasi_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldTorihikinasiFlg")) ?>
    </div>

<label for="fieldMeisaigyouFlg" class="col-sm-2 control-label">明細行表示フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("meisaigyou_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMeisaigyouFlg")) ?>
    </div>

<label for="fieldSoukohyoujjiFlg" class="col-sm-2 control-label">倉庫表示フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("soukohyoujji_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSoukohyoujjiFlg")) ?>
    </div>

<label for="fieldGoukeigyouFlg" class="col-sm-2 control-label">合計行表示フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("goukeigyou_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldGoukeigyouFlg")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
