<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var integer $imax
 * @var integer $id
 */
?>
<?php $title = "入金.修正"; ?>
<div class="page-header">
    <h3>入金伝票 修正</h3>
</div>
<?php echo $this->getContent(); ?>
<?php
echo $this->tag->form(
    [
        "nyuukin_dts/save",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">

    <?php $this->partial('nyuukin_dts/inputfields'); ?>

    <div class="col-sm-2" style="padding: 5px 0 0;">
        <?php echo $this->tag->linkTo(array("nyuukin_dts/prev/" . $id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("nyuukin_dts/next/" . $id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4" style="padding: 5px 0 0;">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4" style="padding: 5px 0 0;">
        <?php echo $this->tag->linkTo(array("nyuukin_dts/new/" . $id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2" style="padding: 5px 0 0;">
        <?php echo $this->tag->linkTo(array("nyuukin_dts/delete/" . $id, "削除", "id" => "del", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/nyuukin_dts.js'); ?>?var=20210210"></script>
