<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "デシテックスマスタ.一覧"; ?>
<div class="page-header">
    <h3>デシテックスマスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"h_dtex_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","デニール"],
                    ["dtex","デシテックス"],
                    ["memo","メモ"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $h_dtex_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("h_dtex_mrs/edit/" . $h_dtex_mr->id, $h_dtex_mr->id)); ?></td>
                <td><?php echo $h_dtex_mr->cd ?></td>
                <td><?php echo $h_dtex_mr->dtex ?></td>
                <td><?php echo $h_dtex_mr->memo ?></td>
                <td><?php echo $h_dtex_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("h_dtex_mrs/delete/" . $h_dtex_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"h_dtex_mrs"]) ?>
