<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "見積.一覧"; ?>
<div class="page-header">
    <h3>見積伝票 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"mitumori_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["cd","伝票番号"],
                    ["tekiyou","摘要"],
                    ["mitumoribi","見積日"],
                    ["tokuisaki_mr_cd","得意先"],
                    ["tokuisaki_mr_cd","得意先名"],
                    ["tantou_mr_cd","担当者"],
                    ["","品番1"],
                    ["","数量1"],
                    ["nounyuu_kijitu","納入期日"],
                    ["nounyuusaki_mr_cd","納入先"],
                ]]) ?>

                <th style="text-align:center;">削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $mitumori_dt): ?>
            <tr>
                <td align="center"><?php echo $this->tag->linkTo(array("mitumori_dts/edit/" . $mitumori_dt->id, $mitumori_dt->cd)); ?></td>
                <td align="center"><?php echo $mitumori_dt->tekiyou ?></td>
                <td align="center"><?php echo $mitumori_dt->mitumoribi ?></td>
                <td align="center"><?php echo $mitumori_dt->tokuisaki_mr_cd ?></td>
                <td align="left"><?php echo $mitumori_dt->TokuisakiMrs->name ?></td>
                <td align="center"><?php echo $mitumori_dt->TantouMrs->name ?></td>
                <td align="left"><?php echo $mitumori_dt->MitumoriMeisaiDts[0]->shouhin_mr_cd ?></td>
                <td align="right"><?php echo $mitumori_dt->MitumoriMeisaiDts[0]->suuryou2 ?></td>
                <td align="center"><?php echo $mitumori_dt->nounyuu_kijitu ?></td>
                <td align="center"><?php echo $mitumori_dt->nounyuusaki_mr_cd ?></td>

                <td align="center"><?php echo $this->tag->linkTo(array("mitumori_dts/delete/" . $mitumori_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"mitumori_dts"]) ?>
