<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "テーブルマスタ.一覧"; ?>
<div class="page-header">
    <h3>テーブルマスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"table_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id(表示・修正)"],
                    ["cd","コード(一覧・入力)"],
                    ["name","名称"],
                    ["menu_group_mr_cd","メニューグループ"],
                    ["jun","順"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $table_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("table_mrs/edit/" . $table_mr->id, $table_mr->id, 'target'=>'_blank')); ?></td>
                <td><?php echo $this->tag->linkTo(array($table_mr->cd, $table_mr->cd, 'target'=>'_blank')); ?></td>
                <td><?php echo $table_mr->name ?></td>
                <td><?php echo $table_mr->menu_group_mr_cd ?></td>
                <td><?php echo $table_mr->jun ?></td>
                <td><?php echo $table_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("table_mrs/delete/" . $table_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"table_mrs"]) ?>
