<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "出金消込.修正"; ?>
<div class="page-header">
    <h3>出金消込 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "shukkin_kesikomi_dts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldShiireMeisaiDtId" class="col-sm-2 control-label">仕入明細id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_meisai_dt_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireMeisaiDtId")) ?>
    </div>

<label for="fieldKesikomiGaku" class="col-sm-2 control-label">消込金額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kesikomi_gaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKesikomiGaku")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
