<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "出金消込.一覧"; ?>
<div class="page-header">
    <h3>出金消込 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"shukkin_kesikomi_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["shiire_meisai_dt_id","仕入明細id"],
                    ["kesikomi_gaku","消込金額"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shukkin_kesikomi_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/edit/" . $shukkin_kesikomi_dt->id, $shukkin_kesikomi_dt->id)); ?></td>
                <td><?php echo $shukkin_kesikomi_dt->shiire_meisai_dt_id ?></td>
                <td><?php echo $shukkin_kesikomi_dt->kesikomi_gaku ?></td>
                <td><?php echo $shukkin_kesikomi_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("shukkin_kesikomi_dts/delete/" . $shukkin_kesikomi_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"shukkin_kesikomi_dts"]) ?>
