<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "条件表見出し.一覧"; ?>
<div class="page-header">
    <h3>条件表見出し 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"joukenhyou_midasi_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["shouhin_bunrui1_kbn_cd","商品分類１"],
                    ["type_kbn_cd","タイプコード"],
                    ["ketasuu","各行桁数"],
                    ["gyousuu","画面行数"],
                    ["shousuu","数値小数桁数"],
                    ["tuika_max","追加上限"],
                    ["memo","メモ"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $joukenhyou_midasi_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("joukenhyou_midasi_kbns/edit/" . $joukenhyou_midasi_kbn->id, $joukenhyou_midasi_kbn->id)); ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->cd ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->name ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->shouhin_bunrui1_kbn_cd ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->type_kbn_cd ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->ketasuu ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->gyousuu ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->shousuu ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->tuika_max ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->memo ?></td>
                <td><?php echo $joukenhyou_midasi_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("joukenhyou_midasi_kbns/delete/" . $joukenhyou_midasi_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"joukenhyou_midasi_kbns"]) ?>
