drop VIEW `work_uriage_vws`;
CREATE VIEW `work_uriage_vws` AS select 
`a`.`shouhin_mr_cd` AS `shouhin_mr_cd`,
`b`.`tantou_mr_cd` AS `tantou_mr_cd`,
`a`.`tanni_mr1_cd` AS `tanni_mr1_cd`,
`a`.`tanni_mr2_cd` AS `tanni_mr2_cd`,
`a`.`iro` AS `iro`,
`a`.`iromei` AS `iromei`,
`a`.`lot` AS `lot`,
`a`.`kobetucd` AS `kobetucd`,
`a`.`hinsitu_kbn_cd` AS `hinsitu_kbn_cd`,
`d`.`hinsitu_hyouka_kbn_cd` AS `hinsitu_hyouka_kbn_cd`,
`a`.`souko_mr_cd` AS `souko_mr_cd`,
NULL AS `nyuukobis`,
`b`.`uriagebi` AS `shukkobis`,
`b`.`uriagebi` AS `nyuushukkobi`,
date_format(`b`.`uriagebi`,'%Y%m') AS `nyuushukkoym`,
'uriage' AS `denpyou_mr_cd`,
`b`.`id` AS `id`,
`b`.`cd` AS `cd`,
`a`.`id` AS `meisai_id`,
`a`.`cd` AS `meisai_cd`,
`a`.`utiwake_kbn_cd` AS `utiwake_kbn_cd`,
`b`.`tokuisaki_mr_cd` AS `torihikisaki_cd`,
`a`.`bikou` AS `bikou`,
(0 - `a`.`suuryou1`*`c`.`uriage_zaiko_flg`) AS `zaiko_ryou1s`,
(0 - `a`.`suuryou2`*`c`.`uriage_zaiko_flg`) AS `zaiko_ryou2s`,
if(`a`.`tanka_kbn`=1,`a`.`tanni_mr1_cd`,`a`.`tanni_mr2_cd`) AS tanka_tanni_mr_cd,
'0000-00-000' AS `shiirebi_tankas`,
0 AS `shiire_gakus`,
0 AS `shiire_ryou1s`,
0 AS `shiire_ryou2s`,
0 AS `hokanyuuko_ryou1s`,
0 AS `hokanyuuko_ryou2s`,
`a`.`suuryou1`*`c`.`uriage_zaiko_flg` AS `uriage_ryou1s`,
`a`.`suuryou2`*`c`.`uriage_zaiko_flg` AS `uriage_ryou2s`,
0 AS `hokashukko_ryou1s`,
0 AS `hokashukko_ryou2s`,
NULL AS `shiiresaki_mr_cd`,
`b`.`tokuisaki_mr_cd` AS `tokuisaki_mr_cd`,
NULL AS `nounyuu_kijitu`,
NULL AS `nouki`,
0 AS `hacchuu_dt_id`,
`b`.`juchuu_dt_id` AS `juchuu_dt_id`,
0 AS `hacchuuzan_ryou1`,
0 AS `hacchuuzan_ryou2`,
(case when (`b`.`juchuu_dt_id` > 0) then (0 - (`a`.`suuryou1` * `c`.`juchuu_zan_flg`)) else 0 end) AS `juchuuzan_ryou1`,
(case when (`b`.`juchuu_dt_id` > 0) then (0 - (`a`.`suuryou2` * `c`.`juchuu_zan_flg`)) else 0 end) AS `juchuuzan_ryou2`,
(`a`.`suuryou1` * `c`.`uriage_azukari_flg`) AS `azukari_zan1s`,
(`a`.`suuryou2` * `c`.`uriage_azukari_flg`) AS `azukari_zan2s`,
(case `c`.`uriage_azukari_flg` when 1 then `a`.`suuryou1` else 0 end) AS `azukari_tasi1s`,
(case `c`.`uriage_azukari_flg` when 1 then `a`.`suuryou2` else 0 end) AS `azukari_tasi2s`,
(case `c`.`uriage_azukari_flg` when -(1) then `a`.`suuryou1` else 0 end) AS `azukari_hiki1s`,
(case `c`.`uriage_azukari_flg` when -(1) then `a`.`suuryou2` else 0 end) AS `azukari_hiki2s`
from (((`uriage_meisai_dts` `a` 
join `uriage_dts` `b` on((`b`.`id` = `a`.`uriage_dt_id`))) 
join `utiwake_kbns` `c` on((`c`.`cd` = `a`.`utiwake_kbn_cd`))) 
join `hinsitu_kbns` `d` on((`d`.`cd` = `a`.`hinsitu_kbn_cd`))) 
where ((`c`.`uriage_zaiko_flg` <> 0) or (`c`.`juchuu_zan_flg` <> 0) or (`c`.`uriage_azukari_flg` <> 0))
