drop VIEW `work_juchuu_vws`;
CREATE VIEW `work_juchuu_vws` AS select 
`a`.`shouhin_mr_cd` AS `shouhin_mr_cd`,
`b`.`tantou_mr_cd` AS `tantou_mr_cd`,
`a`.`tanni_mr1_cd` AS `tanni_mr1_cd`,
`a`.`tanni_mr2_cd` AS `tanni_mr2_cd`,
`a`.`iro` AS `iro`,
`a`.`iromei` AS `iromei`,
`a`.`lot` AS `lot`,
`a`.`kobetucd` AS `kobetucd`,
`a`.`hinsitu_kbn_cd` AS `hinsitu_kbn_cd`,
`d`.`hinsitu_hyouka_kbn_cd` AS `hinsitu_hyouka_kbn_cd`,
'' AS `souko_mr_cd`,
NULL AS `nyuukobis`,
NULL AS `shukkobis`,
NULL AS `nyuushukkobi`,
'' AS `nyuushukkoym`,
'juchuu' AS `denpyou_mr_cd`,
`b`.`id` AS `id`,
`b`.`cd` AS `cd`,
`a`.`id` AS `meisai_id`,
`a`.`cd` AS `meisai_cd`,
`a`.`utiwake_kbn_cd` AS `utiwake_kbn_cd`,
`b`.`tokuisaki_mr_cd` AS `torihikisaki_cd`,
`a`.`bikou` AS `bikou`,
0 AS `zaiko_ryou1`,
0 AS `zaiko_ryou2`,
if(`a`.`tanka_kbn`=1,`a`.`tanni_mr1_cd`,`a`.`tanni_mr2_cd`) AS tanka_tanni_mr_cd,
'0000-00-000' AS `shiirebi_tankas`,
0 AS `shiire_gakus`,
0 AS `shiire_ryou1s`,
0 AS `shiire_ryou2s`,
0 AS `hokanyuuko_ryou1s`,
0 AS `hokanyuuko_ryou2s`,
0 AS `uriage_ryou1s`,
0 AS `uriage_ryou2s`,
0 AS `hokashukko_ryou1s`,
0 AS `hokashukko_ryou2s`,
NULL AS `shiiresaki_mr_cd`,
`b`.`tokuisaki_mr_cd` AS `tokuisaki_mr_cd`,
`b`.`nounyuu_kijitu` AS `nounyuu_kijitu`,
`a`.`nouki` AS `nouki`,
0 AS `hacchuu_dt_id`,
`b`.`id` AS `juchuu_dt_id`,
0 AS `hacchuuzan_ryou1`,
0 AS `hacchuuzan_ryou2`,
(`a`.`suuryou1` * `c`.`juchuu_zan_flg`) AS `juchuuzan_ryou1`,
(`a`.`suuryou2` * `c`.`juchuu_zan_flg`) AS `juchuuzan_ryou2`,
0 AS `azukari_zan1s`,
0 AS `azukari_zan2s`,
0 AS `azukari_tasi1s`,
0 AS `azukari_tasi2s`,
0 AS `azukari_hiki1s`,
0 AS `azukari_hiki2s`
from (((`juchuu_meisai_dts` `a` 
join `juchuu_dts` `b` on((`b`.`id` = `a`.`juchuu_dt_id`))) 
join `utiwake_kbns` `c` on((`c`.`cd` = `a`.`utiwake_kbn_cd`))) 
join `hinsitu_kbns` `d` on((`d`.`cd` = `a`.`hinsitu_kbn_cd`))) 
where (`c`.`juchuu_zan_flg` <> 0)
