<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "単価種類区分.検索"; ?>
<div class="page-header">
    <h3>単価種類区分 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "tanka_shurui_kbns/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKoumokumei" class="col-sm-2 control-label">項目名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("koumokumei", "size" => 30, "maxlength" => 30, "style" => "width: 396px;", "class" => "form-control", "id" => "fieldKoumokumei")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUriageFlg" class="col-sm-2 control-label">売上フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriage_flg", "size" => 1, "maxlength" => 1, "style" => "width: 40px;", "class" => "form-control", "id" => "fieldUriageFlg")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiireFlg" class="col-sm-2 control-label">仕入フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_flg", "size" => 1, "maxlength" => 1, "style" => "width: 40px;", "class" => "form-control", "id" => "fieldShiireFlg")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
