<div class="panel panel-primary bg-yel">
 <div class="panel-heading pnl-hed" onclick="save_ros()">受注伝票<span id="save_ros" style="color:pink;cursor:pointer;">(click→「入力制御の保存」)</span></div>
 <div class="panel-body">
    <div  class="col-sm-2">
        <label for="fieldCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('Cd')">受注番号></label>
        <?php echo $this->tag->textField(array("cd", "class" => "form-control f-cent", 'readonly'=>($readonlys['cd']??0)==1?'readonly':null, "id" => "fieldCd")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldJuchuubi" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('Juchuubi')">受注日></label>
        <?php echo $this->tag->telField(array("juchuubi", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", 'readonly'=>($readonlys['juchuubi']??0)==1?'readonly':null, "id" => "fieldJuchuubi")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldNounyuuKijitu" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('NounyuuKijitu')">納入期日></label>
        <?php echo $this->tag->telField(array("nounyuu_kijitu", "size" => 10, "maxlength" => 10, "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['nounyuu_kijitu']??0)==1?'readonly':null, "id" => "fieldNounyuuKijitu")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldMitumoriDtCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('MitumoriDtCd')">見積番号></label>
        <?php echo $this->tag->textField(array("mitumori_dt_cd", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['mitumori_dt_cd']??0)==1?'readonly':null, "id" => "fieldMitumoriDtCd", "list" => "MitumoriDtsOptions")) ?>
        <?php echo $this->tag->hiddenField(array("mitumori_dt_id", "id" => "fieldMitumoriDtId")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldSakiHacchuuCd" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('SakiHacchuuCd')">得意先発注CD</label>
        <?php echo $this->tag->textField(array("saki_hacchuu_cd", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['saki_hacchuu_cd']??0)==1?'readonly':null, "id" => "fieldSakiHacchuuCd")) ?>
    </div>
    <div class="col-sm-2">
      <label for="fieldZeirituTekiyoubi" class="col-sm-12 control-label lbl-grn-up" onclick="switch_roa('ZeirituTekiyoubi')">指定税率日></label>
      <div class="col-sm-12">
        <?php echo $this->tag->telField(array("zeiritu_tekiyoubi", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", 'readonly'=>($readonlys['zeiritu_tekiyoubi']??0)==1?'readonly':null, "id" => "fieldZeirituTekiyoubi", "tabindex" => "-1"
        ,'title' => '受注日と違う税率にする場合「指定税率日」時点の税率を初期値にする。')) ?>
      </div>
    </div>
     <div class="col-sm-12 pnl-hed">　</div>
  <div class="col-sm-8">
    <label for="fieldTokuisakiMrCd" class="col-sm-2 control-label lbl-grn">得意先></label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("tokuisaki_mr_cd", "size" => 14, "maxlength" => 14, "class" => "form-control ime-d", "id" => "fieldTokuisakiMrCd", "list" => "TokuisakiMrsOptions")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("tokuisaki_mr_name", "readonly" => "readonly", "class" => "form-control", "id" => "rdonlyTokuisakiMrName")) ?>
    </div>
    <label for="fieldTorihikiKbnCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('TorihikiKbnCd')">取引区分</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("torihiki_kbn_cd", TorihikiKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['torihiki_kbn_cd']??0)==1?'readonly':null, "id" => "fieldTorihikiKbnCd")) ?>
    </div>
    <label for="fieldTankaShuruiKbnCd" class="col-sm-2 control-label lbl-grn">単価種類</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("tanka_shurui_kbn_name", "readonly" => "readonly", "class" => "form-control f-cent", "id" => "fieldTankaShuruiKbnName")) ?>
        <?php echo $this->tag->hiddenField(array("tanka_shurui_kbn_koumokumei", "id" => "fieldTankaShuruiKbnKoumokumei")) ?>
    </div>
    <label for="fieldZeiTenkaKbnCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('ZeiTenkaKbnCd')">税転嫁</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("zei_tenka_kbn_cd", ZeitenkaKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['zei_tenka_kbn_cd']??0)==1?'readonly':null, "id" => "fieldZeiTenkaKbnCd")) ?>
    </div>
    <label for="fieldKakeritu" class="col-sm-2 control-label lbl-grn">掛率％</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("kakeritu", "readonly" => "readonly", "class" => "form-control ime-d f-cent", "id" => "fieldKakeritu")) ?>
    </div>
    <label for="fieldNounyuusakiMrCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('NounyuusakiMrCd')">納入先F8</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("nounyuusaki_mr_cd", "size" => 4, "maxlength" => 4, "class" => "form-control ime-d", 'readonly'=>($readonlys['nounyuusaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldNounyuusakiMrCd", "list" => "NounyuusakiMrsOptions")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("nounyuusaki", "size" => 40, "maxlength" => 40, "class" => "form-control ime-a", 'readonly'=>($readonlys['nounyuusaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldNounyuusaki")) ?>
    </div>
    <label for="fieldKidukesakiMrCd" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('KidukesakiMrCd')">気付先F8</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("kidukesaki_mr_cd", "size" => 4, "maxlength" => 4, "class" => "form-control ime-i", 'readonly'=>($readonlys['kidukesaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldKidukesakiMrCd", "list" => "KidukesakiMrsOptions")) ?>
    </div>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("kiduke", "size" => 40, "maxlength" => 40, "class" => "form-control ime-a", 'readonly'=>($readonlys['kidukesaki_mr_cd']??0)==1?'readonly':null, "id" => "fieldKiduke")) ?>
    </div>
    <label for="fieldTantouMrCd" class="col-sm-2 control-label lbl-grn">担当者</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tantou_mr_cd", TantouMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", "id" => "fieldTantouMrCd")) ?>
    </div>
	<div class="clearfix"></div>
    <label for="fieldTekiyou" class="col-sm-2 control-label lbl-grn" onclick="switch_roa('Tekiyou')">摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tekiyou", "size" => 32, "maxlength" => 32, "class" => "form-control ime-a", 'readonly'=>($readonlys['tekiyou']??0)==1?'readonly':null, "id" => "fieldTekiyou")) ?>
    </div>
   </div>
   <div class="col-sm-4">
    <label for="fieldSakuseiUserName" class="col-sm-5 control-label lbl-grn">入力者</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("sakusei_user_name", "readonly" => "readonly", "class" => "form-control", "id" => "fieldSakuseiUserName")) ?>
    </div>
    <label for="fieldUpdated" class="col-sm-5 control-label lbl-grn">更新日時</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("updated", "readonly" => "readonly", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
    <label for="fieldHassousakiKbnCd" class="col-sm-5 control-label lbl-grn" onclick="switch_roa('HassousakiKbnCd')">発送直送先</label>
    <div class="col-sm-7">
        <?php echo $this->tag->select(array("hassousaki_kbn_cd", HassousakiKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", 'readonly'=>($readonlys['hassousaki_kbn_cd']??0)==1?'readonly':null, "id" => "fieldHassousakiKbnCd")) ?>
    </div>
    <label for="fieldUrikakeZandaka" class="col-sm-5 control-label lbl-grn">売掛残高</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("urikake_zandaka", "readonly" => "readonly",  "class" => "form-control f-numb", "id" => "fieldUrikakeZandaka")) ?>
    </div>
    <label for="fieldTokuisakiMrYoshingendogaku" class="col-sm-5 control-label lbl-grn">与信限度額</label>
    <div class="col-sm-7">
        <?php echo $this->tag->textField(array("tokuisaki_mr_yosingendogaku", "readonly" => "readonly",  "class" => "form-control f-numb", "id" => "fieldTokuisakiMrYosingendogaku")) ?>
    </div>
    <div class="col-sm-3"><button class="btn btn-success" id="F7" onclick="tenkai(1);return false;", tabindex="-1">単展開f7</button></div>
    <div class="col-sm-3"><button class="btn btn-success" onclick="tenkai(0);return false;", tabindex="-1">全展開</button></div>
    <label for="fieldSekisanGoukeigaku" class="col-sm-2 control-label lbl-grn">積算@</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("sekisan_goukeugaku", "readonly" => "readonly",  "class" => "form-control f-numb", "id" => "fieldSekisanGoukeigaku")) ?>
    </div>
   </div>
 </div><!-- panel-body -->
 <?php echo $this->tag->hiddenField("gaku_hasuu_shori_kbn_cd") ?>
 <?php echo $this->tag->hiddenField("zei_hasuu_shori_kbn_cd") ?>
<!--
</div>
<div class="panel panel-success bg-yel">
-->
 <div class="panel-heading pnl-hed">受注明細</div>
 <div class="panel-body" style="overflow-x: scroll;padding: 0;">
 <style scoped>
 	table{
 		table-layout:fixed;
 		width:100%;
 	}
 	th,td{
 		white-space:nowrap;
 	}
 	th{
 		border-right:1px #ccc solid;
 		font-size:x-small;
 		font-weight:normal;
 		text-align:center;
 		color: #3d773d;
 		background-color:#dff0d8;
 	}
	th.ot-fixed,td.ot-fixed{
		position:absolute;
		left:6px;
		width:<?php echo $rewidths['[cd']??'30' ?>px;
	}
 </style>
 <table id="meisaiTable">
  <thead><tr><th onclick="switch_ros('Cd')" class="ot-fixed">No
   </th><th width=<?php echo $rewidths['[utiwake_kbn_cd']??'"70"'  ?> onclick="switch_ros('UtiwakeKbnCd')">内訳
   </th><th width=<?php echo $rewidths['[kousei']        ??'"20"'  ?> >構造
   </th><th width=<?php echo $rewidths['[shukka_kbn_cd'] ??'"20"'  ?> >出荷
   </th><th width=<?php echo $rewidths['[shouhin_mr_cd'] ??'"100"' ?> >商品>
   </th><th width=<?php echo $rewidths['[lot']           ??'"20"'  ?> onclick="switch_ros('Lot')">ロット
   </th><th width=<?php echo $rewidths['[tekiyou']       ??'"200"' ?> onclick="switch_ros('Tekiyou')">商品名／摘要
   </th><th width=<?php echo $rewidths['[iro']           ??'"20"'  ?> onclick="switch_ros('Iro')">色番
   </th><th width=<?php echo $rewidths['[iromei']        ??'"20"'  ?> onclick="switch_ros('Iromei')">色名
   </th><th width=<?php echo $rewidths['[kobetucd']     ??'"20"'  ?> onclick="switch_ros('Kobetucd')">個別
   </th><th width=<?php echo $rewidths['[hinsitu_kbn_cd']??'"20"'  ?> onclick="switch_ros('HinsituKbnCd')">品質
   </th><th width=<?php echo $rewidths['[souko_mr_cd']   ??'"100"' ?> onclick="switch_ros('SoukoMrCd')">倉庫
  </th><th width=<?php echo $rewidths['[juchuuzan']     ??'"20"'  ?> >注残
  </th><th width=<?php echo $rewidths['[suuryou']       ??'"20"'  ?> onclick="switch_ros('Suuryou')">元数
   </th><th width=<?php echo $rewidths['[keisu']         ??'"20"'  ?> onclick="switch_ros('Keisu')">係数
   </th><th width=<?php echo $rewidths['[irisuu']        ??'"20"'  ?> onclick="switch_ros('Irisuu')">入数
   </th><th width=<?php echo $rewidths['[suuryou1']      ??'"70"'  ?> onclick="switch_ros('Suuryou1')">数量1
   </th><th width=<?php echo $rewidths['[tanni_mr1_cd']  ??'"50"'  ?> onclick="switch_ros('TanniMr1Cd')">単位
   </th><th width=<?php echo $rewidths['[suuryou2']      ??'"80"'  ?> >数量2
   </th><th width=<?php echo $rewidths['[tanni_mr2_cd']  ??'"50"'  ?> onclick="switch_ros('TanniMr2Cd')">単位
   </th><th width=<?php echo $rewidths['[gentanka']      ??'"20"'  ?> onclick="switch_ros('Gentanka')">コスト
   </th><th width=<?php echo $rewidths['[tanka']         ??'"80"'  ?> onclick="switch_ros('Tanka')">単価
   </th><th width=<?php echo $rewidths['[tanka_kbn']     ??'"50"'  ?> onclick="switch_ros('TankaKbn')">単位
   </th><th width=<?php echo $rewidths['[kingaku']       ??'"100"' ?> >金額
   </th><th width=<?php echo $rewidths['[zeiritu_mr_cd'] ??'"20"'  ?> onclick="switch_ros('ZeirituMrCd')">課税
   </th><th width=<?php echo $rewidths['[bikou']         ??'"100"' ?> onclick="switch_ros('Bikou')">備考
   </th></tr>
  </thead>
  <tbody><style scoped>div[class^="col-sm"],div[class^="panel"]{padding:0 !important;}</style>
  <?php $kousei_oya = -1; ?>
  <?php for ($i = -1; $i < $imax; $i++): /* $imaxはcontrollerから受け取る */ ?>
  <?php
    if ($i < 0) {
      $name_head = "hidden"; // name-hedder nameの前半
      $id_head = "hidden"; // id-hedder idの前半
      echo '<tr id="tr_juchuu_meisai_dt_hidden" style="display:none;">';
    } else {
      $name_head = "data[juchuu_meisai_dts][".$i."]";
      $id_head = "fieldJuchuuMeisaiDts" . $i;
      echo '<tr id="tr_juchuu_meisai_dt_' . $i . '"'.($kousei_oya < 0 || $this->tag->getValue($name_head . "[kousei]")=='-'?'':(' class="kodomo'.$kousei_oya.'"')) .'>';
    }
  ?>
                 <td class="ot-fixed">
                     <!-- 行番 --><?php echo $this->tag->textField(array($name_head . "[cd]", "class" => "form-control ime-d f-cent", 'readonly'=>($readonlys['[cd']??0)==1?'readonly':null, "id" => $id_head . "Cd")) ?>
                     <!--  ID        --><?php echo $this->tag->hiddenField(array($name_head . "[id]", "id" => $id_head . "Id")) ?>
                     <!-- 更新日時   --><?php echo $this->tag->hiddenField(array($name_head . "[updated]", "id" => $id_head . "Updated")) ?>
                     <!-- 原価額     --><?php echo $this->tag->hiddenField(array($name_head . "[genkagaku]", "id" => $id_head . "Genkagaku")) ?>
                     <!-- 税抜額     --><?php echo $this->tag->hiddenField(array($name_head . "[zeinukigaku]", "id" => $id_head . "Zeinukigaku")) ?>
                     <!-- 消費税額   --><?php echo $this->tag->hiddenField(array($name_head . "[zeigaku]", "id" => $id_head . "Zeigaku")) ?>
                     <!-- 課税区分   --><?php echo $this->tag->hiddenField(array($name_head . "[kazei_kbn_cd]", "id" => $id_head . "KazeiKbnCd")) ?>
                     <!--数量小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu_shousuu]", "id" => $id_head . "SuuShousuu")) ?>
                     <!--数１小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu1_shousuu]", "id" => $id_head . "Suu1Shousuu")) ?>
                     <!--数２小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[suu2_shousuu]", "id" => $id_head . "Suu2Shousuu")) ?>
                     <!--単価小数桁数--><?php echo $this->tag->hiddenField(array($name_head . "[tanka_shousuu]", "id" => $id_head . "TankaShousuu")) ?>
                     <!--在庫単位区分--><?php echo $this->tag->hiddenField(array($name_head . "[zaiko_kbn]", "id" => $id_head . "ZaikoKbn")) ?>
                     <!-- 商品元単位 --><?php echo $this->tag->hiddenField(array($name_head . "[moto_tanni_mr2_cd]", "id" => $id_head . "MotoTanniMr2Cd")) ?>
                     <!-- プロ       --><?php echo $this->tag->hiddenField(array($name_head . "[project_mr_cd]", "id" => $id_head . "ProjectMrCd")) ?>

   </td>         <td><!-- 内訳 --><?php echo $this->tag->select(array($name_head . "[utiwake_kbn_cd]", UtiwakeKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "conditions" => "uriage_flg = 1", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control frm0c", 'readonly'=>($readonlys['[utiwake_kbn_cd']??0)==1?'readonly':null, "id" => $id_head . "UtiwakeKbnCd")) ?>
			<?php $kouseix=$this->tag->getValue($name_head . "[kousei]");$kousei_oya_class='';if ($kouseix==''){$kousei_oya=-1;}else if($kouseix=='-'||$kouseix=='+'){$kousei_oya=$i;$kousei_oya_class=' kousei_oya';} ?>
   </td>         <td><!-- 構造 --><tt><?php echo $this->tag->textField(array($name_head . "[kousei]", "readonly" => "readonly", "class" => "form-control".$kousei_oya_class, "id" => $id_head . "Kousei")) ?></tt>
   </td>         <td><!-- 出荷 --><?php echo $this->tag->select(array($name_head . "[shukka_kbn_cd]", ShukkaKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>'readonly', "id" => $id_head . "ShukkaKbnCd")) ?>
   </td>         <td><!-- 商品 --><?php echo $this->tag->textField(array($name_head . "[shouhin_mr_cd]", "maxlength" => 20, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", "id" => $id_head . "ShouhinMrCd", "list" => "ShouhinMrsOptions")) ?>
   </td>         <td><!--ロット--><?php echo $this->tag->textField(array($name_head . "[lot]", "size" => 8, "maxlength" => 40, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[lot']??0)==1?'readonly':null, "id" => $id_head . "Lot")) ?>
   </td>         <td><!-- 摘要 --><?php echo $this->tag->textField(array($name_head . "[tekiyou]", "size" => 40, "maxlength" => 40, "style" => "padding: 0;", "class" => "form-control ime-a", 'readonly'=>($readonlys['[tekiyou']??0)==1?'readonly':null, "id" => $id_head . "Tekiyou")) ?>
   </td>         <td><!-- 色番 --><?php echo $this->tag->textField(array($name_head . "[iro]", "size" => 8, "maxlength" => 12, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[iro']??0)==1?'readonly':null, "id" => $id_head . "Iro")) ?>
   </td>         <td><!-- 色名 --><?php echo $this->tag->textField(array($name_head . "[iromei]", "size" => 8, "maxlength" => 16, "style" => "padding: 0;", "class" => "form-control ime-a f-cent", 'readonly'=>($readonlys['[iromei']??0)==1?'readonly':null, "id" => $id_head . "Iromei")) ?>
   </td>         <td><!-- 個別 --><?php echo $this->tag->textField(array($name_head . "[kobetucd]", "maxlength" => 20, "style" => "padding: 0;", "class" => "form-control ime-i f-cent", 'readonly'=>($readonlys['[kobetucd']??0)==1?'readonly':null, "id" => $id_head . "Kobetucd", "list" => "ShouhinMrsOptions")) ?>
   </td>         <td><!-- 品質 --><?php echo $this->tag->select(array($name_head . "[hinsitu_kbn_cd]", HinsituKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[hinsitu_kbn_cd']??0)==1?'readonly':null, "id" => $id_head . "HinsituKbnCd")) ?>
   </td>         <td><!-- 倉庫 --><?php echo $this->tag->select(array($name_head . "[souko_mr_cd]", SoukoMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "order" => "cd"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[souko_mr_cd']??0)==1?'readonly':null, "id" => $id_head . "SoukoMrCd")) ?>
  </td>         <td><!--受注残--><?php echo $this->tag->textField(array($name_head . "[juchuuzan]", "size" => 8, "readonly" => "readonly", "class" => "form-control f-numb", "id" => $id_head . "Juchuuzan")) ?>

  </td>         <td><!-- 元数 --><?php echo $this->tag->textField(array($name_head . "[suuryou]", "size" => 10, "style" => "padding: 0;", "class" => "form-control f-numb", 'readonly'=>($readonlys['[suuryou']??0)==1?'readonly':null, "id" => $id_head . "Suuryou")) ?>
   </td>         <td><!-- 係数 --><?php echo $this->tag->textField(array($name_head . "[keisu]", "size" => 10, "style" => "padding: 0;", "class" => "form-control f-cen ime-dt", 'readonly'=>($readonlys['[keisu']??0)==1?'readonly':null, "id" => $id_head . "Keisu")) ?>
   </td>         <td><!-- 入数 --><?php echo $this->tag->textField(array($name_head . "[irisuu]", "size" => 10, "style" => "padding: 0;", "class" => "form-control f-cent ime-d", 'readonly'=>($readonlys['[irisuu']??0)==1?'readonly':null, "id" => $id_head . "Irisuu")) ?>
   </td>         <td><!-- 箱数 --><?php echo $this->tag->textField(array($name_head . "[suuryou1]", "size" => 10, "style" => "padding: 0;", "class" => "form-control f-numb", 'readonly'=>($readonlys['[suuryou1']??0)==1?'readonly':null, "id" => $id_head . "Suuryou1")) ?>
   </td>         <td><!--数単位--><?php echo $this->tag->select(array($name_head . "[tanni_mr1_cd]", TanniMrs::find(["columns" => "cd , CONCAT(name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[tanni_mr1_cd']??0)==1?'readonly':null, "id" => $id_head . "TanniMr1Cd")) ?>
   </td>         <td><!-- 数量 --><?php echo $this->tag->textField(array($name_head . "[suuryou2]", "size" => 8, "maxlength" => 10, "class" => "form-control f-numb", "id" => $id_head . "Suuryou2")) ?>
   </td>         <td><!-- 単位 --><?php echo $this->tag->select(array($name_head . "[tanni_mr2_cd]", TanniMrs::find(["columns" => "cd , CONCAT(name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[tanni_mr2_cd']??0)==1?'readonly':null, "id" => $id_head . "TanniMr2Cd")) ?>
   </td>         <td><!--原単価--><?php echo $this->tag->textField(array($name_head . "[gentanka]", "size" => 8, "maxlength" => 10, "class" => "form-control f-numb", 'readonly'=>($readonlys['[gentanka']??0)==1?'readonly':null, "id" => $id_head . "Gentanka")) ?>
   </td>         <td><!-- 単価 --><?php echo $this->tag->textField(array($name_head . "[tanka]", "size" => 8, "maxlength" => 10, "class" => "form-control f-numb", 'readonly'=>($readonlys['[tanka']??0)==1?'readonly':null, "id" => $id_head . "Tanka")) ?>
   </td>         <td><!--価単位--><?php echo $this->tag->selectStatic(array($name_head . "[tanka_kbn]", array("1" => "1", "2" => "2"), "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[tanka_kbn']??0)==1?'readonly':null, "id" => $id_head . "TankaKbn")) ?>
   </td>         <td><!-- 金額 --><?php echo $this->tag->textField(array($name_head . "[kingaku]", "size" => 10, "class" => "form-control f-numb", 'readonly'=>'readonly', "id" => $id_head . "Kingaku")) ?>
   </td>         <td><!-- 課税 --><?php echo $this->tag->select(array($name_head . "[zeiritu_mr_cd]", ZeirituMrs::find(["columns" => "cd , CONCAT(cd , '=' , ryakushou , zeiritu , '%') as disp", "order"=>"kazei_kbn_cd, kijunbi DESC"]), "using" => array("cd", "disp"), 'useEmpty' => true, 'emptyText' => '', "style" => "padding: 0;", "class" => "form-control f-cent", 'readonly'=>($readonlys['[zeiritu_mr_cd']??0)==1?'readonly':null, "id" => $id_head . "ZeirituMrCd")) ?>
   </td>         <td><!-- 備考 --><?php echo $this->tag->textField(array($name_head . "[bikou]", "size" => 14, "maxlength" => 14, "style" => "padding: 0;", "class" => "form-control ime-a", 'readonly'=>($readonlys['[bikou']??0)==1?'readonly':null, "id" => $id_head . "Bikou")) ?>
   </td></tr>
   <?php endfor; ?>
  </tbody></table>
 </div>
<!--
</div>
<div class="panel panel-success bg-yel">
-->
 <div class="panel-heading pnl-hed">情報</div>
 <div class="panel-body">

    <div class="col-sm-2">
        <label for="fieldGenzaiko" class="col-sm-12 control-label lbl-grn-up">現在在庫</label>
        <?php echo $this->tag->textField(array("genzaiko", "readonly" => "readonly", "class" => "form-control f-cent", "id" => "fieldGenzaiko")) ?>
    </div>
    <div  class="col-sm-2">
        <label for="fieldArarieki" class="col-sm-12 control-label lbl-grn-up">粗利益</label>
        <?php echo $this->tag->textField(array("ararieki", "readonly" => "readonly",  "class" => "form-control f-cent", "id" => "fieldArarieki")) ?>
    </div>
    <div  class="col-sm-2">
        <label for="fieldArariekiritu" class="col-sm-12 control-label lbl-grn-up">粗利益率%</label>
        <?php echo $this->tag->textField(array("arariekiritu", "readonly" => "readonly",  "class" => "form-control f-cent", "id" => "fieldArariekiritu")) ?>
    </div>
    <div  class="col-sm-2">
        <label for="fieldZeinukigaku" class="col-sm-12 control-label lbl-grn-up">税抜額</label>
        <?php echo $this->tag->textField(array("zeinukigaku", "readonly" => "readonly",  "class" => "form-control f-cent", "id" => "fieldZeinukigaku")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldShouhizeigaku" class="col-sm-12 control-label lbl-grn-up">消費税額</label>
        <?php echo $this->tag->textField(array("shouhizeigaku", "readonly" => "readonly",  "class" => "form-control f-cent", "id" => "fieldShouhizeigaku")) ?>
    </div>
    <div class="col-sm-2">
        <label for="fieldGoukeigaku" class="col-sm-12 control-label lbl-grn-up" onclick="denpyou_goukei_saikeisan()">合計</label>
        <?php echo $this->tag->textField(array("goukeigaku", "readonly" => "readonly",  "class" => "form-control f-cent", "id" => "fieldGoukeigaku")) ?>
    </div>

    <?php echo $this->tag->hiddenField("zei_chousei_gaku") ?><!-- 消費税調整額（Controllerへ調整額を渡す用）   -->
    <?php echo $this->tag->hiddenField("zeinuki_chousei_gaku") ?><!-- 税抜き額調整   -->

    <?php echo $this->tag->hiddenField("id") ?>

</div><!-- panel-body -->
</div><!-- panel -->
<div class="col-sm-offset-2 col-sm-10 bg-danger" id="dispErrMsg"></div>

<datalist id="MitumoriDtsOptions">
</datalist>

<datalist id="TokuisakiMrsOptions">
</datalist>

<datalist id="NounyuusakiMrsOptions">
</datalist>

<datalist id="KidukesakiMrsOptions">
</datalist>

<datalist id="ShouhinMrsOptions">
</datalist>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
	<div class="modal-header" style="padding: 5px; background-color: #ddd;">
		<span id="iframe-title"></span>
		<button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
	</div>
	<div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
	</div>
</div>

<div id="PgDn"></div><div id="PgUp"></div><div id="END"></div>

<script type="text/javascript">
	var juchuu_dts_edit = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('juchuu_dts/edit/') ?>";
	var juchuu_dts_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('juchuu_dts/modal') ?>";
	var den_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('zaiko_kakunin_azukari_vws/den_modal') ?>";
	var mitumori_dts_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('mitumori_dts/modal') ?>";
	var tokuisaki_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/modal') ?>";
	var nounyuusaki_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('nounyuusaki_mrs/modal') ?>";
	var shouhin_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/modal') ?>";
    var lot_summary_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('report_zaiko_vws/lot_summary') ?>";
	var juchuu_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('juchuu_dts/ajaxGet') ?>";
	var mitumori_dts_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('mitumori_dts/ajaxGet') ?>";
	var tokuisaki_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/ajaxGet') ?>";
	var nounyuusaki_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('nounyuusaki_mrs/ajaxGet') ?>";
	var shouhin_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/ajaxGet') ?>";
	var report_zaiko_vws_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('report_zaiko_vws/ajaxGet') ?>";
	var kousei_buhin_mrs_ajaxTenkai = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('kousei_buhin_mrs/ajaxTenkai') ?>";
	var readonlys_ajaxSave = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('readonly_field_kbns/ajaxSave') ?>";
    var juchuu_meisai_dts_modal = "<?php echo "//" . $_SERVER['SERVER_NAME'] . $this->url->get('juchuu_meisai_dts/history') ?>";
	var my_id = <?php echo (int)$this->getDI()->getSession()->get('auth')['id']; ?>;

    var get_tokuisaki_tanka = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('tokuisaki_tanka_dts/ajaxGet'); ?>";

    var zeiritu_mrs = {};
	var cd_zeiritu = {};
	var tanka_shurui_kbns = {};
	<?php
		$i=0;
		foreach ($zeiritu_mrs as $zeiritu_mr) { /* $zeiritu_mrsはcontrollerから受け取る */
			echo "zeiritu_mrs[".$i."] = {cd: '".$zeiritu_mr->cd
				."', disp: '".$zeiritu_mr->cd."=".$zeiritu_mr->ryakushou.$zeiritu_mr->zeiritu."%', kijunbi: '".$zeiritu_mr->kijunbi
				."', kazei_kbn_cd: '".$zeiritu_mr->kazei_kbn_cd."'};\n";
			echo "cd_zeiritu['".$zeiritu_mr->cd."'] = ".$zeiritu_mr->zeiritu.";\n";
			$i++;
		}
		foreach ($tanka_shurui_kbns as $tanka_shurui_kbn) { /* $tanka_shurui_kbnsはcontrollerから受け取る */
			echo "tanka_shurui_kbns[".$tanka_shurui_kbn->cd."] = '".$tanka_shurui_kbn->koumokumei."';\n";
		}
	?>

</script>
