<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "受注伝票参照"; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/modalkanni",["table_id"=>"juchuu_dts","flds"=>[
        ["cd","fieldCd","伝票番号",14,14],["tekiyou","fieldTekiyou","摘要",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["cd","伝票番号"],
                    ["tekiyou","摘要"],
                    ["juchuubi","受注日"],
                    ["tokuisaki_mr_cd","得意先"],
                    ["tantou_mr_cd","担当者"],
                    ["mitumori_dt_cd","見積番号"],
                    ["","商品1"],
                    ["","数量1"],
                ]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $juchuu_dt): ?>
            <tr>
                <td align="center"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $juchuu_dt->cd; ?></div></td>
                <td><?php echo $juchuu_dt->tekiyou ?></td>
                <td align="center"><?php echo $juchuu_dt->juchuubi ?></td>
                <td><?php echo $juchuu_dt->TokuisakiMrs->name ?></td>
                <td><?php echo $juchuu_dt->TantouMrs->name ?></td>
                <td align="center"><?php echo $juchuu_dt->mitumori_dt_cd ?></td>
                <td><?php echo isset($juchuu_dt->JuchuuMeisaiDts[0])?$juchuu_dt->JuchuuMeisaiDts[0]->shouhin_mr_cd:"" ?></td>
                <td align="right"><?php echo isset($juchuu_dt->JuchuuMeisaiDts[0])?$juchuu_dt->JuchuuMeisaiDts[0]->suuryou2.$juchuu_dt->JuchuuMeisaiDts[0]->TanniMr2s->name:"" ?></td>

                <td align="center"><?php echo $this->tag->linkTo(array("juchuu_dts/edit/" . $juchuu_dt->id, "別タブ", "target"=>"_blank")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/modaltail",["table_id"=>"juchuu_dts"]) ?>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
