<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "受注.新規"; ?>
<div class="page-header">
    <h3>受注伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "juchuu_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "id" => "formTouroku",
        )
    );
?>

<div class="form-group">

    <?php $this->partial('juchuu_dts/inputfields'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("juchuu_dts/prev", "最終F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("juchuu_dts/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return final_check();')) ?>
    </div>
</div>
<!--<div>-->
<!--    <label for="zoom_text">zoom:</label>-->
<!--    <input type="text" id="zoom_text" size="50">-->
<!--</div>-->
<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/juchuu_dts.js'); ?>?var=20200513"></script>
