<div class="panel panel-default">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">基本情報</div>
 <div class="panel-body">
    <label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldCd","required" => "required")) ?>
    </div>
    <label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>
    <label for="fieldKana" class="col-sm-2 control-label">フリガナ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kana", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldKana")) ?>
    </div>
    <label for="fieldRyakushou" class="col-sm-2 control-label">略称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ryakushou", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldRyakushou")) ?>
    </div>
 </div>
</div>
<div class="panel panel-success">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">
  <a data-toggle="collapse" href="#atesaki">宛先情報…</a>
 </div>
 <div class="panel-body collapse in" id="atesaki">
    <label for="fieldYuubinBangou" class="col-sm-2 control-label">郵便番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("yuubin_bangou", "size" => 8, "maxlength" => 8, "style" => "width: 120px;", "class" => "form-control", "id" => "fieldYuubinBangou")) ?>
    </div>
    <label for="fieldJuusho1" class="col-sm-2 control-label">住所1</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juusho1", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldJuusho1")) ?>
    </div>
    <label for="fieldJuusho2" class="col-sm-2 control-label">住所2</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juusho2", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldJuusho2")) ?>
    </div>
    <label for="fieldBushomei" class="col-sm-2 control-label">部署名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bushomei", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldBushomei")) ?>
    </div>
    <label for="fieldYakushoku" class="col-sm-2 control-label">役職名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("yakushoku", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldYakushoku")) ?>
    </div>
    <label for="fieldGotantousha" class="col-sm-2 control-label">ご担当者</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("gotantousha", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldGotantousha")) ?>
    </div>
    <label for="fieldKeishou" class="col-sm-2 control-label">敬称</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("keishou", "size" => 4, "maxlength" => 4, "style" => "width: 84px;", "class" => "form-control", "id" => "fieldKeishou", "list" => "Keishous")) ?>
        <datalist id="Keishous"><option value="様"><option value="殿"><option value="御中"></datalist>
    </div>
    <label for="fieldTel" class="col-sm-2 control-label">TEL</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tel", "size" => 16, "maxlength" => 16, "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTel")) ?>
    </div>
    <label for="fieldFax" class="col-sm-2 control-label">FAX</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("fax", "size" => 16, "maxlength" => 16, "style" => "width: 228px;", "class" => "form-control", "id" => "fieldFax")) ?>
    </div>
    <label for="fieldEmail" class="col-sm-2 control-label">メールアドレス</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("email", "size" => 80, "maxlength" => 100, "class" => "form-control", "id" => "fieldEmail")) ?>
    </div>
    <label for="fieldHomepage" class="col-sm-2 control-label">ホームページ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("homepage", "size" => 80, "maxlength" => 100, "class" => "form-control", "id" => "fieldHomepage")) ?>
    </div>
    <label for="fieldTantouMrCd" class="col-sm-2 control-label">担当者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("tantou_mr_cd", TantouMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTantouMrId")) ?>
    </div>
 </div>
</div>
<div class="panel panel-info">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">
  <a data-toggle="collapse" href="#urikake">売掛情報…</a>
 </div>
 <div class="panel-body collapse" id="urikake">
  <div class="col-sm-6">
    <label for="fieldTorihikiKbnCd" class="col-sm-4 control-label">取引区分</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("torihiki_kbn_cd", TorihikiKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTorihikiKbnId")) ?>
    </div>
    <label for="fieldTankaShuruiKbnCd" class="col-sm-4 control-label">単価種類</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("tanka_shurui_kbn_cd", TankaShuruiKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name", "conditions" => "uriage_flg = 1"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTankaShuruiKbnCd")) ?>
    </div>
    <label for="fieldKakeritu" class="col-sm-4 control-label">掛率</label>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("kakeritu", "type" => "number", "style" => "width: 156px; display: inline;", "class" => "form-control f-numb", "id" => "fieldKakeritu")) ?> ％
    </div>
    <label for="fieldSeikyuusakiMrCd" class="col-sm-4 control-label">請求先</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(array("seikyuusaki_mr_cd", "size" => 14, "maxlength" => 14, "class" => "form-control", "id" => "fieldSeikyuusakiMrCd")) ?>
    </div>
    <div class="col-sm-5">
        <?php echo $this->tag->textField(array("seikyuusaki_mr_name", "readonly" => "readonly", "class" => "form-control", "id" => "fieldSeikyuusakiMrName")) ?>
    </div>
    <label for="fieldShimegrpKbnCd" class="col-sm-4 control-label">締グループ</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("shimegrp_kbn_cd", ShimegrpKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldShimegrpKbnCd")) ?>
    </div>
  </div>
  <div class="col-sm-6">
    <label for="fieldGakuHasuuShoriKbnCd" class="col-sm-4 control-label">金額端数処理</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("gaku_hasuu_shori_kbn_cd", HasuushoriKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldGakuHasuuShoriKbnCd")) ?>
    </div>
    <label for="fieldZeiHasuuShoriKbnCd" class="col-sm-4 control-label">税端数処理</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("zei_hasuu_shori_kbn_cd", HasuushoriKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '',"style" => "width: 228px;", "class" => "form-control", "id" => "fieldZeiHasuuShoriKbnCd")) ?>
    </div>
    <label for="fieldZeiTenkaKbnCd" class="col-sm-4 control-label">税転嫁</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("zei_tenka_kbn_cd", ZeitenkaKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldZeiTenkaKbnCd")) ?>
    </div>
    <label for="fieldYoshinGendogaku" class="col-sm-4 control-label">与信限度額</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(array("yoshin_gendogaku", "size" => 10, "maxlength" => 10, "class" => "form-control f-numb", "id" => "fieldYoshinGendogaku")) ?>
    </div>
	<div class="clearfix"></div>
    <label for="fieldUrikakeZandaka" class="col-sm-4 control-label">売掛残高</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(array("urikake_zandaka", "size" => 10, "maxlength" => 10, "class" => "form-control f-numb", "readonly" => "readonly", "id" => "fieldUrikakeZandaka")) ?>
    </div>
    <label for="fieldKakeZandaka" class="col-sm-2 control-label">導入時</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(array("kake_zandaka", "size" => 10, "maxlength" => 10, "class" => "form-control f-numb", "id" => "fieldKakeZandaka")) ?>
    </div>
  </div>
 </div>
</div>
<div class="panel panel-info">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">
  <a data-toggle="collapse" href="#kaishuu">回収情報…</a>
 </div>
 <div class="panel-body collapse" id="kaishuu">
  <div class="col-sm-6">
    <label for="fieldHaraiHouhouKbnCd" class="col-sm-4 control-label">回収方法</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("harai_houhou_kbn_cd", NyuukinKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldHaraiHouhouKbnCd")) ?>
    </div>
    <label for="fieldHaraiSaikuruKbnCd" class="col-sm-4 control-label">回収サイクル</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("harai_saikuru_kbn_cd", KaishuuSaikuruKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldHaraiSaikuruKbnCd")) ?>
    </div>
    <label for="fieldHaraibi" class="col-sm-4 control-label">回収日</label>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("haraibi", "type" => "number", "style" => "width: 156px; display: inline;", "class" => "form-control", "id" => "fieldHaraibi")) ?> 日
    </div>
    <label for="fieldTesuuryouHutanKbnCd" class="col-sm-4 control-label">手数料負担区分</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("tesuuryou_hutan_kbn_cd", TesuuryouHutanKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTesuuryouHutanFlg")) ?>
    </div>
    <label for="fieldTegataSight" class="col-sm-4 control-label">手形サイト</label>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("tegata_sight", "type" => "number", "style" => "width: 156px; display: inline;", "class" => "form-control", "id" => "fieldTegataSight")) ?> 日
    </div>
  </div>
  <div class="col-sm-6">
    <label for="fieldShiteiUridenKbnCd" class="col-sm-4 control-label">指定売上伝票</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("shitei_uriden_kbn_cd", ChouhyouMrs::find(["columns" => "id , CONCAT(id , '=' , name) as id_name", "conditions" => "chouhyou_kbn_cd = 6"]), "using" => array("id", "id_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldShiteiUridenKbnCd")) ?>
    </div>
    <label for="fieldShiteiSeikyuushoKbnCd" class="col-sm-4 control-label">指定請求書</label>
    <div class="col-sm-8">
        <?php echo $this->tag->select(array("shitei_seikyuusho_kbn_cd", ChouhyouMrs::find(["columns" => "id , CONCAT(id , '=' , name) as id_name", "conditions" => "chouhyou_kbn_cd = 7"]), "using" => array("id", "id_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldShiteiSeikyuushoKbnCd")) ?>
    </div>
    <label for="fieldAtenaLavel" class="col-sm-4 control-label">宛名ラベル</label>
    <div class="col-sm-8">
        <?php echo $this->tag->checkField(array('atena_lavel', 'value' => '1', "style" => "width: 40px;", "class" => "form-control", "id" => "fieldAtenaLavel")) ?>
    </div>
    <label for="fieldKigyouCode" class="col-sm-4 control-label">企業コード</label>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("kigyou_code", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldKigyouCode")) ?>
    </div>
    <label for="fieldSeikyuushoGassanMrCd" class="col-sm-4 control-label">請求書合算</label>
    <div class="col-sm-8">
        <?php echo $this->tag->textField(array("seikyuusho_gassan_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldSeikyuushoGassanMrCd")) ?>
    </div>
  </div>
 </div>
</div>
<div class="panel panel-warning">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">
  <a data-toggle="collapse" href="#bunrui">分類情報…</a>
 </div>
 <div class="panel-body collapse in" id="bunrui">
    <label for="fieldTokuisakiBunrui1KbnCd" class="col-sm-2 control-label">分類１</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tokuisaki_bunrui1_kbn_cd", TokuisakiBunrui1Kbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTokuisakiBunrui1KbnCd")) ?>
    </div>
    <label for="fieldTokuisakiBunrui2KbnCd" class="col-sm-2 control-label">分類２</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tokuisaki_bunrui2_kbn_cd", TokuisakiBunrui2Kbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTokuisakiBunrui2KbnCd")) ?>
    </div>
    <label for="fieldTokuisakiBunrui3KbnCd" class="col-sm-2 control-label">分類３</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tokuisaki_bunrui3_kbn_cd", TokuisakiBunrui3Kbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTokuisakiBunrui3KbnCd")) ?>
    </div>
    <label for="fieldTokuisakiBunrui4KbnCd" class="col-sm-2 control-label">分類４</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tokuisaki_bunrui4_kbn_cd", TokuisakiBunrui4Kbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTokuisakiBunrui4KbnCd")) ?>
    </div>
    <label for="fieldTokuisakiBunrui5KbnCd" class="col-sm-2 control-label">分類５</label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("tokuisaki_bunrui5_kbn_cd", TokuisakiBunrui5Kbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTokuisakiBunrui5KbnCd")) ?>
    </div>
    <label for="fieldSanshouHyouji" class="col-sm-2 control-label">参照表示</label>
    <div class="col-sm-4">
        <?php echo $this->tag->selectStatic(array("sanshou_hyouji", array("1" => "1=表示する", "0" => "2=表示しない"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 200px;", "class" => "form-control", "id" => "fieldSanshouHyouji")) ?>
    </div>
    <label for="fieldMemo" class="col-sm-2 control-label">メモ欄</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("memo", "size" => 50, "maxlength" => 50, "class" => "form-control", "id" => "fieldMemo")) ?>
    </div>
 </div>
</div>

<datalist id="ShiiresakiMrsOptions">
</datalist>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
	<div class="modal-header" style="padding: 5px; background-color: #ddd;">
		<span id="iframe-title"></span>
		<button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
	</div>
	<div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
	</div>
</div>

<script src="<?php echo $this->url->get('js/jquery/jquery.jpostal.js') ?>"></script>
<script>
    //Add By Nishiyama 2019-10-23
    $(function () {
        $('#fieldYuubinBangou').jpostal({
            postcode : [
                '#fieldYuubinBangou'
            ],
            address : {
                '#fieldJuusho1' : '%3%4%5',
            }
        });
    });
</script>
<script type="text/javascript">
	var tokuisaki_mrs_edit = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/edit/') ?>";
	var tokuisaki_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/modal') ?>";
	var tokuisaki_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/ajaxGet') ?>";
	var tokuisakimrs_ajaxKana = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/ajaxGetHurigana') ?>";
	var shiiresaki_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shiiresaki_mrs/modal') ?>";
	var shiiresaki_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shiiresaki_mrs/ajaxGet') ?>";
</script>
