<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '得意先.新規'; ?>
<div class="page-header">
    <h3>得意先台帳 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "tokuisaki_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group" style="padding: 0px 10px 0px 10px;">

    <?php $this->partial('tokuisaki_mrs/inputfields'); ?>

	<div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("tokuisaki_mrs/prev", "最終F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("tokuisaki_mrs/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>

    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-lg btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div><!-- class="form-group" -->

<?php echo $this->tag->endForm(); ?>
<script type="text/javascript" src="<?php echo $this->url->get('js/lib.js'); ?>?var=20191023"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/tokuisaki_mrs.js'); ?>?var=20191023"></script>
