<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search zaiko_kakunin_tbl
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["zaiko_kakunin_tbl/new", "Create zaiko_kakunin_tbl"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "zaiko_kakunin_tbl/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldShouhinMrCd" class="col-sm-2 control-label">Shouhin Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shouhin_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldShouhinMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTantouMrCd" class="col-sm-2 control-label">Tantou Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tantou_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldTantouMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanniMr1Cd" class="col-sm-2 control-label">Tanni Of Mr1 Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tanni_mr1_cd", "size" => 30, "class" => "form-control", "id" => "fieldTanniMr1Cd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanniMr2Cd" class="col-sm-2 control-label">Tanni Of Mr2 Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tanni_mr2_cd", "size" => 30, "class" => "form-control", "id" => "fieldTanniMr2Cd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIro" class="col-sm-2 control-label">Iro</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["iro", "size" => 30, "class" => "form-control", "id" => "fieldIro"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIromei" class="col-sm-2 control-label">Iromei</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["iromei", "size" => 30, "class" => "form-control", "id" => "fieldIromei"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLot" class="col-sm-2 control-label">Lot</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lot", "size" => 30, "class" => "form-control", "id" => "fieldLot"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKobetucd" class="col-sm-2 control-label">Kobetucd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kobetucd", "size" => 30, "class" => "form-control", "id" => "fieldKobetucd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHinsituKbnCd" class="col-sm-2 control-label">Hinsitu Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hinsitu_kbn_cd", "size" => 30, "class" => "form-control", "id" => "fieldHinsituKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHinsituHyoukaKbnCd" class="col-sm-2 control-label">Hinsitu Of Hyouka Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hinsitu_hyouka_kbn_cd", "type" => "number", "class" => "form-control", "id" => "fieldHinsituHyoukaKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSoukoMrCd" class="col-sm-2 control-label">Souko Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["souko_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldSoukoMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNyuukobis" class="col-sm-2 control-label">Nyuukobis</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nyuukobis", "size" => 30, "class" => "form-control", "id" => "fieldNyuukobis"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShukkobis" class="col-sm-2 control-label">Shukkobis</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shukkobis", "size" => 30, "class" => "form-control", "id" => "fieldShukkobis"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNyuushukkobi" class="col-sm-2 control-label">Nyuushukkobi</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nyuushukkobi", "type" => "date", "class" => "form-control", "id" => "fieldNyuushukkobi"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNyuushukkoym" class="col-sm-2 control-label">Nyuushukkoym</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nyuushukkoym", "size" => 30, "class" => "form-control", "id" => "fieldNyuushukkoym"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDenpyouMrCd" class="col-sm-2 control-label">Denpyou Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["denpyou_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldDenpyouMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cd", "type" => "number", "class" => "form-control", "id" => "fieldCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMeisaiId" class="col-sm-2 control-label">Meisai</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["meisai_id", "type" => "number", "class" => "form-control", "id" => "fieldMeisaiId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMeisaiCd" class="col-sm-2 control-label">Meisai Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["meisai_cd", "type" => "number", "class" => "form-control", "id" => "fieldMeisaiCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUtiwakeKbnCd" class="col-sm-2 control-label">Utiwake Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["utiwake_kbn_cd", "size" => 30, "class" => "form-control", "id" => "fieldUtiwakeKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTorihikisakiCd" class="col-sm-2 control-label">Torihikisaki Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["torihikisaki_cd", "size" => 30, "class" => "form-control", "id" => "fieldTorihikisakiCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBikou" class="col-sm-2 control-label">Bikou</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bikou", "size" => 30, "class" => "form-control", "id" => "fieldBikou"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZaikoRyou1s" class="col-sm-2 control-label">Zaiko Of Ryou1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zaiko_ryou1s", "size" => 30, "class" => "form-control", "id" => "fieldZaikoRyou1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZaikoRyou2s" class="col-sm-2 control-label">Zaiko Of Ryou2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zaiko_ryou2s", "size" => 30, "class" => "form-control", "id" => "fieldZaikoRyou2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTankaTanniMrCd" class="col-sm-2 control-label">Tanka Of Tanni Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tanka_tanni_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldTankaTanniMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiirebiTankas" class="col-sm-2 control-label">Shiirebi Of Tankas</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shiirebi_tankas", "size" => 30, "class" => "form-control", "id" => "fieldShiirebiTankas"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiireGakus" class="col-sm-2 control-label">Shiire Of Gakus</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shiire_gakus", "type" => "number", "class" => "form-control", "id" => "fieldShiireGakus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiireRyou1s" class="col-sm-2 control-label">Shiire Of Ryou1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shiire_ryou1s", "size" => 30, "class" => "form-control", "id" => "fieldShiireRyou1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiireRyou2s" class="col-sm-2 control-label">Shiire Of Ryou2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shiire_ryou2s", "size" => 30, "class" => "form-control", "id" => "fieldShiireRyou2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHokanyuukoRyou1s" class="col-sm-2 control-label">Hokanyuuko Of Ryou1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hokanyuuko_ryou1s", "size" => 30, "class" => "form-control", "id" => "fieldHokanyuukoRyou1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHokanyuukoRyou2s" class="col-sm-2 control-label">Hokanyuuko Of Ryou2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hokanyuuko_ryou2s", "size" => 30, "class" => "form-control", "id" => "fieldHokanyuukoRyou2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUriageRyou1s" class="col-sm-2 control-label">Uriage Of Ryou1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uriage_ryou1s", "size" => 30, "class" => "form-control", "id" => "fieldUriageRyou1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUriageRyou2s" class="col-sm-2 control-label">Uriage Of Ryou2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uriage_ryou2s", "size" => 30, "class" => "form-control", "id" => "fieldUriageRyou2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHokashukkoRyou1s" class="col-sm-2 control-label">Hokashukko Of Ryou1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hokashukko_ryou1s", "size" => 30, "class" => "form-control", "id" => "fieldHokashukkoRyou1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHokashukkoRyou2s" class="col-sm-2 control-label">Hokashukko Of Ryou2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hokashukko_ryou2s", "size" => 30, "class" => "form-control", "id" => "fieldHokashukkoRyou2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiiresakiMrCd" class="col-sm-2 control-label">Shiiresaki Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shiiresaki_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldShiiresakiMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTokuisakiMrCd" class="col-sm-2 control-label">Tokuisaki Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tokuisaki_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldTokuisakiMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNounyuuKijitu" class="col-sm-2 control-label">Nounyuu Of Kijitu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nounyuu_kijitu", "type" => "date", "class" => "form-control", "id" => "fieldNounyuuKijitu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNouki" class="col-sm-2 control-label">Nouki</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nouki", "type" => "date", "class" => "form-control", "id" => "fieldNouki"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHacchuuDtId" class="col-sm-2 control-label">Hacchuu Of Dt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hacchuu_dt_id", "type" => "number", "class" => "form-control", "id" => "fieldHacchuuDtId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJuchuuDtId" class="col-sm-2 control-label">Juchuu Of Dt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["juchuu_dt_id", "type" => "number", "class" => "form-control", "id" => "fieldJuchuuDtId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHacchuuzanRyou1" class="col-sm-2 control-label">Hacchuuzan Of Ryou1</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hacchuuzan_ryou1", "size" => 30, "class" => "form-control", "id" => "fieldHacchuuzanRyou1"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHacchuuzanRyou2" class="col-sm-2 control-label">Hacchuuzan Of Ryou2</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hacchuuzan_ryou2", "size" => 30, "class" => "form-control", "id" => "fieldHacchuuzanRyou2"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJuchuuzanRyou1" class="col-sm-2 control-label">Juchuuzan Of Ryou1</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["juchuuzan_ryou1", "size" => 30, "class" => "form-control", "id" => "fieldJuchuuzanRyou1"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJuchuuzanRyou2" class="col-sm-2 control-label">Juchuuzan Of Ryou2</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["juchuuzan_ryou2", "size" => 30, "class" => "form-control", "id" => "fieldJuchuuzanRyou2"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariZan1s" class="col-sm-2 control-label">Azukari Of Zan1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_zan1s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariZan1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariZan2s" class="col-sm-2 control-label">Azukari Of Zan2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_zan2s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariZan2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariTasi1s" class="col-sm-2 control-label">Azukari Of Tasi1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_tasi1s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariTasi1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariTasi2s" class="col-sm-2 control-label">Azukari Of Tasi2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_tasi2s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariTasi2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariHiki1s" class="col-sm-2 control-label">Azukari Of Hiki1s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_hiki1s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariHiki1s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAzukariHiki2s" class="col-sm-2 control-label">Azukari Of Hiki2s</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["azukari_hiki2s", "size" => 30, "class" => "form-control", "id" => "fieldAzukariHiki2s"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKousinUserId" class="col-sm-2 control-label">Kousin Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kousin_user_id", "type" => "number", "class" => "form-control", "id" => "fieldKousinUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updated", "size" => 30, "class" => "form-control", "id" => "fieldUpdated"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSakuseiUserId" class="col-sm-2 control-label">Sakusei Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sakusei_user_id", "type" => "number", "class" => "form-control", "id" => "fieldSakuseiUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created", "size" => 30, "class" => "form-control", "id" => "fieldCreated"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
