<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["hisasip2_dts/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["hisasip2_dts/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>指図番号2</th>
            <th>指図本数</th>
            <th>合格本数</th>
            <th>小玉本数</th>
            <th>納品本数</th>
            <th>ワインダ行</th>
            <th>小玉量</th>
            <th>指図量</th>
            <th>生産量</th>
            <th>納品量</th>
            <th>先造り指図分</th>
            <th>フリー払出量</th>
            <th>在庫調整量</th>
            <th>空白</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $hisasip2_dt): ?>
            <tr>
                <td><?php echo $hisasip2_dt->指図番号2 ?></td>
            <td><?php echo $hisasip2_dt->指図本数 ?></td>
            <td><?php echo $hisasip2_dt->合格本数 ?></td>
            <td><?php echo $hisasip2_dt->小玉本数 ?></td>
            <td><?php echo $hisasip2_dt->納品本数 ?></td>
            <td><?php echo $hisasip2_dt->ワインダ行 ?></td>
            <td><?php echo $hisasip2_dt->小玉量 ?></td>
            <td><?php echo $hisasip2_dt->指図量 ?></td>
            <td><?php echo $hisasip2_dt->生産量 ?></td>
            <td><?php echo $hisasip2_dt->納品量 ?></td>
            <td><?php echo $hisasip2_dt->先造り指図分 ?></td>
            <td><?php echo $hisasip2_dt->フリー払出量 ?></td>
            <td><?php echo $hisasip2_dt->在庫調整量 ?></td>
            <td><?php echo $hisasip2_dt->空白 ?></td>

                <td><?php echo $this->tag->linkTo(["hisasip2_dts/edit/" . $hisasip2_dt->指図番号2, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["hisasip2_dts/delete/" . $hisasip2_dt->指図番号2, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("hisasip2_dts/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("hisasip2_dts/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("hisasip2_dts/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("hisasip2_dts/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
