<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "VIEW.一覧"; ?>
<div class="page-header">
    <h3>VIEW 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"zaiko_cost_vws","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["shouhin_mr_cd","Shouhin Of Mr Of Cd"],
                    ["cost","Cost"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $zaiko_cost_vw): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("zaiko_cost_vws/edit/" . $zaiko_cost_vw->id, $zaiko_cost_vw->shouhin_mr_cd)); ?></td>
                <td><?php echo $zaiko_cost_vw->cost ?></td>

                <td><?php echo $this->tag->linkTo(array("zaiko_cost_vws/delete/" . $zaiko_cost_vw->shouhin_mr_cd, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"zaiko_cost_vws"]) ?>
