<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = 'ロード変換.一覧'; ?>
<div class="page-header">
    <h3>ロード変換マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>コード</th>
            <th>名称</th>
            <th>ロードマスタコード</th>
            <th>ロード項目コード</th>
            <th>更新日時</th>

                <th><a href=# onclick="$('#F10').focus();return false;" id="F10">修正*10</a></th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $load_henkan_mr): ?>
            <tr>
                <td><?php echo $load_henkan_mr->id ?></td>
            <td><?php echo $load_henkan_mr->cd ?></td>
            <td><?php echo $load_henkan_mr->name ?></td>
            <td><?php echo $load_henkan_mr->load_mr_cd ?></td>
            <td><?php echo $load_henkan_mr->load_koumoku_mr_cd ?></td>
            <td><?php echo $load_henkan_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("load_henkan_mrs/edit/" . $load_henkan_mr->id, "修正")); ?></td>
                <td><?php echo $this->tag->linkTo(array("load_henkan_mrs/delete/" . $load_henkan_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("load_henkan_mrs/index", "<<最初*11") ?></li>
                <li><?php echo $this->tag->linkTo("load_henkan_mrs/index?page=" . $page->before, "<前頁*1") ?></li>
                <li><?php echo $this->tag->linkTo("load_henkan_mrs/index?page=" . $page->next, " 次頁*2>") ?></li>
                <li><?php echo $this->tag->linkTo("load_henkan_mrs/index?page=" . $page->last, "最後*12>>") ?></li>
            </ul>
        </nav>
    </div>
</div>
