<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "事業所.選択"; ?>
<div class="page-header">
    <h3>事業所データの選択</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered table-hover table-condensed" style="width:300px;" align="center">
        <thead>
            <tr>
                <th style="text-align:center;" bgcolor="lightgrey">事業所データ</th>
            </tr>
        </thead>
        <tbody bgcolor="white" align="center">
            <tr>
            </tr>
        </tbody>
    </table>
</div>
