<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = '売上.一覧'; ?>
<div class="page-header">
    <h3>売上伝票 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
	<?php $this->partial("common/indexkanni",["table_id"=>"uriage_dts","flds"=>[
		["cd","fieldCd","伝票番号",14,14],["tekiyou","fieldTekiyou","摘要",24,24]
	]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
				<?php $this->partial("common/indexsort",["flds"=>[
					["cd","伝票番号"],
					["tekiyou","摘要"],
					["uriagebi","売上日"],
					["tokuisaki_mr_cd","得意先"],
					["tantou_mr_cd","担当者"],
					["","商品1"],
					["","数量"]
				]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $uriage_dt): ?>
            <tr>
                <td align="center"><?php echo $this->tag->linkTo(array("uriage_dts/edit/" . $uriage_dt->id, $uriage_dt->cd)); ?></td>
                <td><?php echo $uriage_dt->tekiyou ?></td>
                <td align="center"><?php echo $uriage_dt->uriagebi ?></td>
                <td><?php echo $uriage_dt->tokuisaki_mr_cd."=".$uriage_dt->TokuisakiMrs->name ?></td>
                <td><?php echo $uriage_dt->tantou_mr_cd."=".$uriage_dt->TantouMrs->name ?></td>
                <td><?php echo $uriage_dt->UriageMeisaiDts[0]->shouhin_mr_cd ?></td>
                <td align="right"><?php	$tanka_kbn=$uriage_dt->UriageMeisaiDts[0]->tanka_kbn;$suufld='suuryou'.$tanka_kbn;$tannitb='TanniMr'.$tanka_kbn.'s';
                						echo $uriage_dt->UriageMeisaiDts[0]->$suufld.$uriage_dt->UriageMeisaiDts[0]->$tannitb->name ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"uriage_dts"]) ?>
