<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '売上.新規'; ?>
<div class="page-header">
    <h3>売上伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "uriage_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "id" => "formTouroku",
        )
    );
?>

<div class="form-group">

    <?php $this->partial('uriage_dts/inputfields'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("uriage_dts/prev", "最終F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("uriage_dts/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-3">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return final_check();')) ?>
    </div>
    <div class="col-sm-7">
        <button class="btn btn-warning" type="button" id='F5' onclick="final_check_test()">
            伝票印刷F5
        </button>
    </div>

</div><!-- form-group -->


<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/uriage_dts.js'); ?>?var=20200522"></script>
