<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '売上.検索'; ?>
<div class="page-header">
    <h3>売上伝票 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "uriage_dts/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
    <label for="fieldCd" class="col-sm-2 control-label">伝票番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
    <label for="fieldTekiyou" class="col-sm-2 control-label">摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tekiyou", "size" => 32, "maxlength" => 32, "style" => "width: 420px;", "class" => "form-control", "id" => "fieldTekiyou")) ?>
    </div>
    <label for="fieldUriagebi" class="col-sm-2 control-label">売上日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriagebi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldUriagebi")) ?>
    </div>
    <label for="fieldJuchuuCd" class="col-sm-2 control-label">受注番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juchuu_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJuchuuCd")) ?>
    </div>
    <label for="fieldMitumoriCd" class="col-sm-2 control-label">見積番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("mitumori_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMitumoriCd")) ?>
    </div>
    <label for="fieldShouninJoutaiFlg" class="col-sm-2 control-label">承認状態</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shounin_joutai_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShouninJoutaiFlg")) ?>
    </div>
    <label for="fieldShouninShaMrCd" class="col-sm-2 control-label">承認者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shounin_sha_mr_cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShouninShaMrCd")) ?>
    </div>
    <label for="fieldZeirituTekiyoubi" class="col-sm-2 control-label">税率適用日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zeiritu_tekiyoubi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldZeirituTekiyoubi")) ?>
    </div>
    <label for="fieldTokuisakiMrCd" class="col-sm-2 control-label">得意先</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tokuisaki_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldTokuisakiMrCd")) ?>
    </div>
    <label for="fieldTorihikiKbnCd" class="col-sm-2 control-label">取引区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("torihiki_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldTorihikiKbnCd")) ?>
    </div>
    <label for="fieldZeiTenkaKbnCd" class="col-sm-2 control-label">税転嫁</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zei_tenka_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldZeiTenkaKbnCd")) ?>
    </div>
    <label for="fieldNounyuusakiMrCd" class="col-sm-2 control-label">納入先</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nounyuusaki_mr_cd", "size" => 4, "maxlength" => 4, "style" => "width: 84px;", "class" => "form-control", "id" => "fieldNounyuusakiMrCd")) ?>
    </div>
    <label for="fieldTantouMrCd" class="col-sm-2 control-label">担当者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tantou_mr_cd", "size" => 3, "maxlength" => 3, "style" => "width: 72px;", "class" => "form-control", "id" => "fieldTantouMrCd")) ?>
    </div>
    <label for="fieldShimekiriFlg" class="col-sm-2 control-label">締切</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shimekiri_flg", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShimekiriFlg")) ?>
    </div>
    <label for="fieldTankaShuruiKbnCd" class="col-sm-2 control-label">単価種類</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tanka_shurui_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldTankaShuruiKbnCd")) ?>
    </div>
    <label for="fieldKaishuuYoteibi" class="col-sm-2 control-label">回収予定日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kaishuu_yoteibi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKaishuuYoteibi")) ?>
    </div>
    <label for="fieldSeikyuushoDtCd" class="col-sm-2 control-label">請求書番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("seikyuusho_dt_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSeikyuushoDtCd")) ?>
    </div>
    <label for="fieldKeshikomiFlg" class="col-sm-2 control-label">消込状態</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("keshikomi_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKeshikomiFlg")) ?>
    </div>
    <label for="fieldNounyuuKijitu" class="col-sm-2 control-label">納入期日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nounyuu_kijitu", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldNounyuuKijitu")) ?>
    </div>
    <label for="fieldBunruiCd" class="col-sm-2 control-label">分類コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bunrui_cd", "size" => 7, "maxlength" => 7, "style" => "width: 120px;", "class" => "form-control", "id" => "fieldBunruiCd")) ?>
    </div>
    <label for="fieldDenpyouKbn" class="col-sm-2 control-label">伝票区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("denpyou_kbn", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldDenpyouKbn")) ?>
    </div>
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
