<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "ユーザーマスタ.修正"; ?>
<div class="page-header">
    <h3>ユーザーマスタ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "users/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">ユーザーコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">ユーザー名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "maxlength" => 30, "style" => "width: 396px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldUserGroupMrCd" class="col-sm-2 control-label">ユーザーグループ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("user_group_mr_cd", UserGroupMrs::find(["columns" => "cd , CONCAT(cd , ':' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 396px;", "class" => "form-control", "id" => "fieldUserGroupMrCd")) ?>
    </div>

<label for="fieldKaisiBi" class="col-sm-2 control-label">適用開始日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kaisi_bi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKaisiBi")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("users/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("users/new/".$id, "複写で新規", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("users/editpw/".$id, "パスワードf6", "id" => "F6", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("users/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
