<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "ユーザーマスタ.新規"; ?>
<div class="page-header">
    <h3>ユーザーマスタ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">ユーザーコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldPassword" class="col-sm-2 control-label">パスワード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("password", "size" => 80, "maxlength" => 128, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldPassword")) ?>
    </div>

    <label for="fieldRepeatPassword" class="col-sm-2 control-label">パスワード再入力</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(array("repeatPassword", "size" => 30, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldRepeatPassword")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">ユーザー名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "maxlength" => 30, "style" => "width: 396px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldUserGroupMrCd" class="col-sm-2 control-label">ユーザーグループ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("user_group_mr_cd", UserGroupMrs::find(["columns" => "cd , CONCAT(cd , ':' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 60px;", "class" => "form-control", "id" => "fieldUserGroupMrCd")) ?>
    </div>

<label for="fieldKaisiBi" class="col-sm-2 control-label">適用開始日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kaisi_bi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKaisiBi")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
