<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "機種マスタ.一覧"; ?>
<div class="page-header">
    <h3>機種マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"h_kishu_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["h_kouteimei_mr_cd","工程名コード"],
                    ["daisuu","台数"],
                    ["sou_suisuu","総錘数"],
                    ["kaitensuu","回転数"],
                    ["kadouritu","稼働率"],
                    ["kadouhun_aday","分稼働毎日"],
                    ["seisansei","生産性"],
                    ["max_haba","最大巾"],
                    ["max_kei","最大径"],
                    ["max_makiryou","最大巻量"],
                    ["max_yorisuu","最大撚り数"],
                    ["ryakushou","機種略名"],
                    ["bikou","備考"],
                    ["h_calendar_patan_dt_cd","カレンダーパタン"],
                    ["irowake","色分け"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $h_kishu_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("h_kishu_mrs/edit/" . $h_kishu_mr->id, $h_kishu_mr->id)); ?></td>
                <td><?php echo $h_kishu_mr->cd ?></td>
                <td><?php echo $h_kishu_mr->name ?></td>
                <td><?php echo $h_kishu_mr->h_kouteimei_mr_cd ?></td>
                <td><?php echo $h_kishu_mr->daisuu ?></td>
                <td><?php echo $h_kishu_mr->sou_suisuu ?></td>
                <td><?php echo $h_kishu_mr->kaitensuu ?></td>
                <td><?php echo $h_kishu_mr->kadouritu ?></td>
                <td><?php echo $h_kishu_mr->kadouhun_aday ?></td>
                <td><?php echo $h_kishu_mr->seisansei ?></td>
                <td><?php echo $h_kishu_mr->max_haba ?></td>
                <td><?php echo $h_kishu_mr->max_kei ?></td>
                <td><?php echo $h_kishu_mr->max_makiryou ?></td>
                <td><?php echo $h_kishu_mr->max_yorisuu ?></td>
                <td><?php echo $h_kishu_mr->ryakushou ?></td>
                <td><?php echo $h_kishu_mr->bikou ?></td>
                <td><?php echo $h_kishu_mr->h_calendar_patan_dt_cd ?></td>
                <td <?php echo 'style="background-color:#'.$h_kishu_mr->irowake.';"' ?>><?php echo $h_kishu_mr->irowake ?></td>
                <td><?php echo $h_kishu_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("h_kishu_mrs/delete/" . $h_kishu_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"h_kishu_mrs"]) ?>
