<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "機種マスタ.検索"; ?>
<div class="page-header">
    <h3>機種マスタ 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "h_kishu_mrs/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldId")) ?>
    </div>

<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldHKouteimeiMrCd" class="col-sm-2 control-label">工程名コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("h_kouteimei_mr_cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHKouteimeiMrCd")) ?>
    </div>

<label for="fieldDaisuu" class="col-sm-2 control-label">台数</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("daisuu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldDaisuu")) ?>
    </div>

<label for="fieldSouSuisuu" class="col-sm-2 control-label">総錘数</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sou_suisuu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSouSuisuu")) ?>
    </div>

<label for="fieldKaitensuu" class="col-sm-2 control-label">回転数</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kaitensuu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKaitensuu")) ?>
    </div>

<label for="fieldKadouritu" class="col-sm-2 control-label">稼働率</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kadouritu", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKadouritu")) ?>
    </div>

<label for="fieldKadouhunAday" class="col-sm-2 control-label">分稼働毎日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kadouhun_aday", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKadouhunAday")) ?>
    </div>

<label for="fieldSeisansei" class="col-sm-2 control-label">生産性</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("seisansei", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSeisansei")) ?>
    </div>

<label for="fieldMaxHaba" class="col-sm-2 control-label">最大巾</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_haba", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxHaba")) ?>
    </div>

<label for="fieldMaxKei" class="col-sm-2 control-label">最大径</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_kei", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxKei")) ?>
    </div>

<label for="fieldMaxMakiryou" class="col-sm-2 control-label">最大巻量</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_makiryou", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxMakiryou")) ?>
    </div>

<label for="fieldMaxYorisuu" class="col-sm-2 control-label">最大撚り数</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_yorisuu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxYorisuu")) ?>
    </div>

<label for="fieldRyakushou" class="col-sm-2 control-label">機種略名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ryakushou", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldRyakushou")) ?>
    </div>

<label for="fieldBikou" class="col-sm-2 control-label">備考</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>

<label for="fieldHCalendarPatnDtCd" class="col-sm-2 control-label">カレンダーパタン</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("h_calendar_patan_dt_cd", "size" => 4, "maxlength" => 4, "style" => "width: 51px;", "class" => "form-control", "id" => "fieldHCalendarPatnDtCd")) ?>
    </div>

<label for="fieldIrowake" class="col-sm-2 control-label">色分け</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("irowake", "size" => 6, "maxlength" => 6, "style" => "width: 116px;", "class" => "form-control", "id" => "fieldIrowake")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
