<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "加工条件項目登録"; ?>
<div class="page-header">
    <h3>加工条件定義・新規</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    array(
        "kakou_jouken_kbns_mrs/save",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    )
);
?>
<div class="form-group">

    <?php $this->partial('kakou_jouken_kbns_mrs/inputfields'); ?>

    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return final_check();')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/kakou_jouken_kbns.js'); ?>?var=20191217"></script>
