<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "条件台帳.一覧"; ?>
<div class="page-header">
    <h3>条件台帳 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"joukenhyou_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","内容"],
                    ["suuti","内容数値"],
                    ["shouhin_mr_cd","商品コード"],
                    ["midasi_cd","見出し行番"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $joukenhyou_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("joukenhyou_mrs/edit/" . $joukenhyou_mr->id, $joukenhyou_mr->id)); ?></td>
                <td><?php echo $joukenhyou_mr->cd ?></td>
                <td><?php echo $joukenhyou_mr->name ?></td>
                <td><?php echo $joukenhyou_mr->suuti ?></td>
                <td><?php echo $joukenhyou_mr->shouhin_mr_cd ?></td>
                <td><?php echo $joukenhyou_mr->midasi_cd ?></td>
                <td><?php echo $joukenhyou_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("joukenhyou_mrs/delete/" . $joukenhyou_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"joukenhyou_mrs"]) ?>
