<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Cd</th>
            <th>Name</th>
            <th>Junjo Of Kbn Of Cd</th>
            <th>Hanni Of From</th>
            <th>Hanni Of To</th>
            <th>Junjo2 Of Kbn Of Cd</th>
            <th>Hanni2 Of From</th>
            <th>Hanni2 Of To</th>
            <th>Kikan Of Sitei Of Kbn Of Cd</th>
            <th>Kikan Of From</th>
            <th>Kikan Of To</th>
            <th>Koujun Of Flg</th>
            <th>Meisaigyou Of Flg</th>
            <th>Goukeigyou Of Flg</th>
            <th>Torihikiari Of Flg</th>
            <th>Torihikinashi Of Flg</th>
            <th>Id Of Moto</th>
            <th>Hikae Of Dltflg</th>
            <th>Hikae Of User</th>
            <th>Hikae Of Nichiji</th>
            <th>Sakusei Of User</th>
            <th>Created</th>
            <th>Kousin Of User</th>
            <th>Updated</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $jouken_shiire_bunseki): ?>
            <tr>
                <td><?php echo $jouken_shiire_bunseki->id ?></td>
            <td><?php echo $jouken_shiire_bunseki->cd ?></td>
            <td><?php echo $jouken_shiire_bunseki->name ?></td>
            <td><?php echo $jouken_shiire_bunseki->junjo_kbn_cd ?></td>
            <td><?php echo $jouken_shiire_bunseki->hanni_from ?></td>
            <td><?php echo $jouken_shiire_bunseki->hanni_to ?></td>
            <td><?php echo $jouken_shiire_bunseki->junjo2_kbn_cd ?></td>
            <td><?php echo $jouken_shiire_bunseki->hanni2_from ?></td>
            <td><?php echo $jouken_shiire_bunseki->hanni2_to ?></td>
            <td><?php echo $jouken_shiire_bunseki->kikan_sitei_kbn_cd ?></td>
            <td><?php echo $jouken_shiire_bunseki->kikan_from ?></td>
            <td><?php echo $jouken_shiire_bunseki->kikan_to ?></td>
            <td><?php echo $jouken_shiire_bunseki->koujun_flg ?></td>
            <td><?php echo $jouken_shiire_bunseki->meisaigyou_flg ?></td>
            <td><?php echo $jouken_shiire_bunseki->goukeigyou_flg ?></td>
            <td><?php echo $jouken_shiire_bunseki->torihikiari_flg ?></td>
            <td><?php echo $jouken_shiire_bunseki->torihikinashi_flg ?></td>
            <td><?php echo $jouken_shiire_bunseki->id_moto ?></td>
            <td><?php echo $jouken_shiire_bunseki->hikae_dltflg ?></td>
            <td><?php echo $jouken_shiire_bunseki->hikae_user_id ?></td>
            <td><?php echo $jouken_shiire_bunseki->hikae_nichiji ?></td>
            <td><?php echo $jouken_shiire_bunseki->sakusei_user_id ?></td>
            <td><?php echo $jouken_shiire_bunseki->created ?></td>
            <td><?php echo $jouken_shiire_bunseki->kousin_user_id ?></td>
            <td><?php echo $jouken_shiire_bunseki->updated ?></td>

                <td><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/edit/" . $jouken_shiire_bunseki->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/delete/" . $jouken_shiire_bunseki->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["jouken_shiire_bunsekis/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
