<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["juchuu_dts", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create juchuu_dts
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "juchuu_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cd", "type" => "number", "class" => "form-control", "id" => "fieldCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNendo" class="col-sm-2 control-label">Nendo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nendo", "type" => "number", "class" => "form-control", "id" => "fieldNendo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTekiyou" class="col-sm-2 control-label">Tekiyou</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tekiyou", "size" => 30, "class" => "form-control", "id" => "fieldTekiyou"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJuchuubi" class="col-sm-2 control-label">Juchuubi</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["juchuubi", "type" => "date", "class" => "form-control", "id" => "fieldJuchuubi"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZeirituTekiyoubi" class="col-sm-2 control-label">Zeiritu Of Tekiyoubi</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zeiritu_tekiyoubi", "type" => "date", "class" => "form-control", "id" => "fieldZeirituTekiyoubi"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTokuisakiMrCd" class="col-sm-2 control-label">Tokuisaki Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tokuisaki_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldTokuisakiMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTorihikiKbnCd" class="col-sm-2 control-label">Torihiki Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["torihiki_kbn_cd", "type" => "number", "class" => "form-control", "id" => "fieldTorihikiKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZeiTenkaKbnCd" class="col-sm-2 control-label">Zei Of Tenka Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["zei_tenka_kbn_cd", "type" => "number", "class" => "form-control", "id" => "fieldZeiTenkaKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTantouMrCd" class="col-sm-2 control-label">Tantou Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tantou_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldTantouMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShimekiriFlg" class="col-sm-2 control-label">Shimekiri Of Flg</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shimekiri_flg", "size" => 30, "class" => "form-control", "id" => "fieldShimekiriFlg"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNounyuuKijitu" class="col-sm-2 control-label">Nounyuu Of Kijitu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nounyuu_kijitu", "type" => "date", "class" => "form-control", "id" => "fieldNounyuuKijitu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMitumoriDtId" class="col-sm-2 control-label">Mitumori Of Dt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["mitumori_dt_id", "type" => "number", "class" => "form-control", "id" => "fieldMitumoriDtId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSakiHacchuuCd" class="col-sm-2 control-label">Saki Of Hacchuu Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["saki_hacchuu_cd", "size" => 30, "class" => "form-control", "id" => "fieldSakiHacchuuCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNounyuusakiMrCd" class="col-sm-2 control-label">Nounyuusaki Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nounyuusaki_mr_cd", "size" => 30, "class" => "form-control", "id" => "fieldNounyuusakiMrCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNounyuusaki" class="col-sm-2 control-label">Nounyuusaki</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nounyuusaki", "size" => 30, "class" => "form-control", "id" => "fieldNounyuusaki"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldChokusousakiKbnCd" class="col-sm-2 control-label">Chokusousaki Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["chokusousaki_kbn_cd", "size" => 30, "class" => "form-control", "id" => "fieldChokusousakiKbnCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdMoto" class="col-sm-2 control-label">Id Of Moto</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_moto", "type" => "number", "class" => "form-control", "id" => "fieldIdMoto"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHikaeDltflg" class="col-sm-2 control-label">Hikae Of Dltflg</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hikae_dltflg", "type" => "number", "class" => "form-control", "id" => "fieldHikaeDltflg"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHikaeUserId" class="col-sm-2 control-label">Hikae Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hikae_user_id", "type" => "number", "class" => "form-control", "id" => "fieldHikaeUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHikaeNichiji" class="col-sm-2 control-label">Hikae Of Nichiji</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hikae_nichiji", "size" => 30, "class" => "form-control", "id" => "fieldHikaeNichiji"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSakuseiUserId" class="col-sm-2 control-label">Sakusei Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sakusei_user_id", "type" => "number", "class" => "form-control", "id" => "fieldSakuseiUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created", "size" => 30, "class" => "form-control", "id" => "fieldCreated"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKousinUserId" class="col-sm-2 control-label">Kousin Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kousin_user_id", "type" => "number", "class" => "form-control", "id" => "fieldKousinUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updated", "size" => 30, "class" => "form-control", "id" => "fieldUpdated"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
