<div class="modal-header" style="padding:0px 15px;">
    <h4>仕入先参照</h4>
</div><!-- /modal-header -->
<div class="modal-body" style="padding:0px 15px;">
  <?php echo $this->tag->form(array("shiiresaki_mrs_modal/index", "autocomplete" => "off", "class" => "form-horizontal"));?>
  <div class="form-group">
    <table class="table table-condensed">
      <tr>
        <td align="right" style="border-style:none;">
          <label for="fieldCd" class="control-label">コード</label>
        </td>
        <td style="border-style:none;">
          <?php echo $this->tag->textField(array("cd", "size" => 14, "maxlength" => 14, "class" => "form-control", "id" => "fieldCd")) ?>
        </td>
        <td align="right" style="border-style:none;">
          <label for="fieldRyakushou" class="control-label">略称</label>
        </td>
        <td style="border-style:none;">
          <?php echo $this->tag->textField(array("ryakushou", "size" => 24, "maxlength" => 24, "class" => "form-control", "id" => "fieldRyakushou")) ?>
        </td>
        <td style="border-style:none;">
          <?php echo $this->tag->submitButton(array("簡易検索*12", "id" => "F12", "class" => "btn btn-success")) ?>
        </td>
        <td style="border-style:none;">
          <?php echo $this->tag->linkTo(array("shiiresaki_mrs_modal/search", "検索条件入力*3", "id" => "F3", "class" => "btn btn-info")) ?>
        </td>
        <td style="border-style:none;">
          <?php echo $this->tag->linkTo(array("shiiresaki_mrs/new", "新規登録*5", "id" => "F5", "class" => "btn btn-warning", "target" => "_blank")) ?>
        </td>
      </tr>
    </table>
  </div><!-- class="form-group" -->
  <?php echo $this->tag->endForm(); ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
            <th><a href="?<?php echo TableSort\Sort::sortLink('cd'); ?>">コード</a> <?php echo TableSort\Sort::sortIcon('cd'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('ryakushou'); ?>">略称</a> <?php echo TableSort\Sort::sortIcon('ryakushou'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('juusho2'); ?>">住所2</a> <?php echo TableSort\Sort::sortIcon('juusho2'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('bushomei'); ?>">部署名</a> <?php echo TableSort\Sort::sortIcon('bushomei'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('yakushoku'); ?>">役職名</a> <?php echo TableSort\Sort::sortIcon('yakushoku'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('gotantousha'); ?>">ご担当者</a> <?php echo TableSort\Sort::sortIcon('gotantousha'); ?></th>
            <th><a href="?<?php echo TableSort\Sort::sortLink('memo'); ?>">メモ欄</a> <?php echo TableSort\Sort::sortIcon('memo'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shiiresaki_mr): ?>
            <tr>
            <td><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $shiiresaki_mr->cd; ?></div></td>
            <td><?php echo $shiiresaki_mr->ryakushou ?></td>
            <td><?php echo $shiiresaki_mr->juusho2 ?></td>
            <td><?php echo $shiiresaki_mr->bushomei ?></td>
            <td><?php echo $shiiresaki_mr->yakushoku ?></td>
            <td><?php echo $shiiresaki_mr->gotantousha ?></td>
            <td><?php echo $shiiresaki_mr->memo ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div><!-- /modal-body -->
<div class="modal-footer">
    <div class="col-sm-10" align="center">
            <ul class="pagination">
                <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("shiiresaki_mrs_modal/index", "<<最初*11", "id"=>"F11")) ?></li>
                <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("shiiresaki_mrs_modal/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
                <li class="active"><?php echo $this->tag->linkTo("shiiresaki_mrs_modal/index?page=" . $page->current, $page->current . "頁") ?></li>
                <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("shiiresaki_mrs_modal/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
                <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("shiiresaki_mrs_modal/index?page=" . $page->last, $page->total_pages."頁最後*12>>", "id"=>"F12")) ?></li>
            </ul>
    </div>
    <div class="col-sm-2">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
    </div>
</div><!-- /modal-footer -->
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>

