<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("shiiresaki_mrs", "戻る*3", "id" => "F3")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h3>仕入先マスタ 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "shiiresaki_mrs/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">

    <?php $this->partial('shiiresaki_mrs/inputfields'); ?>

    <?php $this->partial('common/panel_search_bottom'); ?>

    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>

</div><!-- class="form-group" -->

<?php echo $this->tag->endForm(); ?>
