<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $joukens */
/** @var array $rows */
?>
<?php use Phalcon\Tag; ?>
<?php $title = '支払状況一覧表'; ?>
<div class="page-header">
    <h3>支払状況一覧表</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        [
            "shiiresaki_sime_dts/shiharai_joukyou",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        ]);
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <span>支払状況一覧表</span>
            </div>
            <br /><br />

            <div class="col-sm-12">
                <label for="getsudo" class="col-sm-3 control-label">対象期間</label>
                <div class="col-sm-2">
                    <?php echo $this->tag->textField(["getsudo", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "getsudo"]) ?>
                </div>
            </div>
            <br /><br />
            <div class="col-sm-12 form-inline">
                <label for="range_from" class="col-sm-3 control-label">仕入先範囲</label>
                <div class="col-sm-2">
                    <?php echo $this->tag->textField(["range_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "range_from"]) ?>
                </div>
                <label for="range_to" class="col-sm-1">～</label>
                <div class="col-sm-2">
                    <?php echo $this->tag->textField(["range_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "range_to"]) ?>
                </div>
                <div class="col-sm-4">
                    <?php echo $this->tag->submitButton(["集計f12", "id" => "F12", "class" => "btn btn-lg btn-success"]) ?>
                </div>
            </div>

        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="container-fluid">
    <div class="row">
        <table class="table table-striped table-bordered">
            <thead style="background-color: lavender;">
                <tr>
                    <th colspan="2"></th>
                    <th colspan="3" style="text-align: center;">支払実績</th>
                    <th colspan="1" style="text-align: center;">滞納額</th>
                    <th colspan="2" style="text-align: center;">支払予定 </th>
                </tr>
                <tr>
                    <th style="text-align: center;">仕入先コード</th>
                    <th style="text-align: center;">仕入先名</th>
                    <th style="text-align: center;">当月要支払額</th>
                    <th style="text-align: center;">当月支払額</th>
                    <th style="text-align: center;">支払率</th>
<!--                    <th style="text-align: center;">前月以前分</th> -->
                    <th style="text-align: center;">当月分</th>
<!--                    <th style="text-align: center;">当月末時点</th>  -->
                    <th style="text-align: center;">当月予定</th>
                    <th style="text-align: center;">翌月予定</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($rows as $row): ?>
                    <tr>
                        <td style="text-align: center;"><?php echo $row['shiiresaki_mr_cd']; ?></td><!-- 仕入先コード -->
                        <td><?php echo $row['shiiresaki_name']; ?></td><!-- 名称 -->
                        <td style="text-align: right; color: <?php echo (int)$row['tougetsu_you_shiharaigaku'] < 0 ? 'red' : 'black'; ?>"><?php echo number_format($row['tougetsu_you_shiharaigaku']); ?></td><!-- 当月要支払額 -->
                        <td style="text-align: right; color: <?php echo (int)$row['tougetsu_shiharaigaku'] < 0 ? 'red' : 'black'; ?>"><?php echo number_format($row['tougetsu_shiharaigaku']); ?></td><!-- 当月支払額 -->
                        <td style="text-align: right"><?php echo ((int)$row['tougetsu_shiharaigaku'] === 0 || (int)$row['tougetsu_you_shiharaigaku'] === 0) ? 0.0 : number_format($row['tougetsu_shiharaigaku'] / $row['tougetsu_you_shiharaigaku'] * 100, 1 ); ?></td>
<!--                        <td style="text-align: right;">--><?php //echo number_format($row['kurikoshigaku'] + $row['konkai_siiregaku']);  ?><!--</td> -->
                        <td style="text-align: right; color: <?php echo (int)$row['tougetsu_bun'] < 0 ? 'red' : 'black'; ?>"><?php echo number_format( $row['tougetsu_bun']); ?></td><!-- 当月（滞納） -->
<!--                        <td style="text-align: right;"></td> -->
                        <td style="text-align: right; color: <?php echo (int)$row['tougetsu_shiharai_yotei'] < 0 ? 'red' : 'black'; ?>"><?php echo number_format($row['tougetsu_shiharai_yotei']); ?></td><!-- 当月（予定） -->
                        <td style="text-align: right; color: <?php echo (int)$row['yokugetsu_shiharai_yotei'] < 0 ? 'red' : 'black'; ?>"><?php echo number_format($row['yokugetsu_shiharai_yotei']); ?></td><!-- 翌月（予定） -->
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        <span id="iframe-title"></span>
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script>
    const shiiresaki_dts_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shiiresaki_mrs/modal') ?>";
</script>

<script src="<?php echo $this->url->get('js/views/shiharai_joukyou.js'); ?>?var=20210303"></script>