<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "ハウツーデータ.修正"; ?>
<div class="page-header">
    <h3>ハウツーデータ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "howto_dts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">疑問</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 80, "maxlength" => 200, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldBikou" class="col-sm-2 control-label">解決</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 80, "maxlength" => 500, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "readonly" => "readonly", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

<label for="fieldKousinUserName" class="col-sm-2 control-label">更新者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kousin_user_name", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "readonly" => "readonly", "class" => "form-control", "id" => "fieldKousinUserName")) ?>
    </div>

<label for="fieldCreated" class="col-sm-2 control-label">作成日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("created", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "readonly" => "readonly", "class" => "form-control", "id" => "fieldCreated")) ?>
    </div>

<label for="fieldSakuseiUserName" class="col-sm-2 control-label">作成者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sakusei_user_name", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "readonly" => "readonly", "class" => "form-control", "id" => "fieldSakuseiUserName")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("howto_dts/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("howto_dts/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("howto_dts/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
