<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "見積り明細データ.一覧"; ?>
<div class="page-header">
    <h3>見積り明細データ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"mitumori_meisai_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","行番"],
                    ["utiwake_kbn_cd","内訳"],
                    ["mitumori_dt_id","見積りデータID"],
                    ["shouhin_mr_cd","商品コード"],
                    ["tanni_mr_cd","単位"],
                    ["suu_tanni_mr_cd","数単位"],
                    ["irisuu","入数"],
                    ["keisu","ケース"],
                    ["tekiyou","商品名/摘要"],
                    ["lot","ロット"],
                    ["kobetucd","個別コード"],
                    ["hinsitu_kbn_cd","品質コード"],
                    ["kikaku","規格型番"],
                    ["iro","色"],
                    ["size","サイズ"],
                    ["suuryou","数量"],
                    ["gentanka","原単価"],
                    ["tanka","単価"],
                    ["kingaku","金額"],
                    ["genkagaku","原価額"],
                    ["project_mr_cd","プロジェクトコード"],
                    ["zeiritu_mr_cd","税率コード"],
                    ["bikou","備考"],
                    ["hacchuurendou_flg","発注連動"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $mitumori_meisai_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/edit/" . $mitumori_meisai_dt->id, $mitumori_meisai_dt->id)); ?></td>
                <td><?php echo $mitumori_meisai_dt->cd ?></td>
                <td><?php echo $mitumori_meisai_dt->utiwake_kbn_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->mitumori_dt_id ?></td>
                <td><?php echo $mitumori_meisai_dt->shouhin_mr_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->tanni_mr_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->suu_tanni_mr_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->irisuu ?></td>
                <td><?php echo $mitumori_meisai_dt->keisu ?></td>
                <td><?php echo $mitumori_meisai_dt->tekiyou ?></td>
                <td><?php echo $mitumori_meisai_dt->lot ?></td>
                <td><?php echo $mitumori_meisai_dt->kobetucd ?></td>
                <td><?php echo $mitumori_meisai_dt->hinsitu_kbn_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->kikaku ?></td>
                <td><?php echo $mitumori_meisai_dt->iro ?></td>
                <td><?php echo $mitumori_meisai_dt->size ?></td>
                <td><?php echo $mitumori_meisai_dt->suuryou ?></td>
                <td><?php echo $mitumori_meisai_dt->gentanka ?></td>
                <td><?php echo $mitumori_meisai_dt->tanka ?></td>
                <td><?php echo $mitumori_meisai_dt->kingaku ?></td>
                <td><?php echo $mitumori_meisai_dt->genkagaku ?></td>
                <td><?php echo $mitumori_meisai_dt->project_mr_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->zeiritu_mr_cd ?></td>
                <td><?php echo $mitumori_meisai_dt->bikou ?></td>
                <td><?php echo $mitumori_meisai_dt->hacchuurendou_flg ?></td>
                <td><?php echo $mitumori_meisai_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/delete/" . $mitumori_meisai_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("mitumori_meisai_dts/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("mitumori_meisai_dts/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
