<?php use Phalcon\Tag; ?>

<?php $title1 = 'グラ.売上'; ?>
<div class="chartarea">
<canvas id="chartreport" height="600" width="300"></canvas>
</div>
<script type="text/javascript" src="<?= $this->url->get('js/chart272/Chart.min.js') ?>"></script>

<script>

var charts_uriage1_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('charts/uriage1_ajaxGet') ?>";

function uriage1(){
	$.ajax({
		type:"POST",
		url:charts_uriage1_ajaxGet,
		data:{},
		async:true,
		dataType:'json',
		success: function (data) {
			$("canvas#chartreport").remove();
			$("div.chartarea").append('<canvas id="chartreport" height="500" width="300"></canvas>');
			var ctx = document.getElementById("chartreport").getContext("2d");
			var config = {
				type: data.type,
				data: {
					datasets: data.datasets,
					labels: data.labels
				},
				options:  {
					responsive: true,
					title: {
						display: true,
						text: data.title
					},
					scales: {
						yAxes: [{
							ticks: {
								beginAtZero: true,
								callback: function(label, index, labels) {
									return label/1000000;
								}
							},
							scaleLabel: {
								display: true,
								labelString: '(百万円)',
							},
						}]
					}
				}
			};
			chartreport = new Chart(ctx, config);
			//参考：https://stackoverflow.com/questions/47121429/chart-js-ajax-with-multiple-dataset
		},
		error: function(xhr, status, err) {
			alert('エラー charts_uriage1_ajax '+status+'/'+err);
		},
	});
}

setTimeout(function(){
	uriage1();
}, 2000); // 2秒後にグラフを表示する。

</script>
