<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = 'ユーザ.修正'; ?>
<div class="page-header">
    <h3>ユーザーマスタ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "users/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">ユーザーコード</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("cd", "size" => 10, "maxlength" => 10, "style" => "width: 120px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">ユーザー名</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("name", "size" => 30, "maxlength" => 30, "style" => "width: 360px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserGroupMrCd" class="col-sm-2 control-label"><?php echo $this->tag->linkTo(array("user_group_mrs", "ユーザーグループ…*8", "id" => "fieldUserGroupMrCdF8")); ?></label>
    <div class="col-sm-4">
        <?php echo $this->tag->select(array("user_group_mr_cd", userGroupMrs::find(["columns" => "cd , CONCAT(cd , ':' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 390px;", "class" => "form-control", "id" => "fieldUserGroupMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">作成日時</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("created", "size" => 30, "class" => "form-control", "readonly" => "readonly", "id" => "fieldCreated")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array("updated", "size" => 30, "readonly" => "readonly", "class" => "form-control", "readonly" => "readonly", "id" => "fieldUpdated")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
