<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = 'ユーザ.一覧'; ?>
<div class="page-header">
    <h3>ユーザーマスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>ユーザーコード</th>
            <th>ユーザー名</th>
            <th><?php echo $this->tag->linkTo(array("user_group_mrs", "ユーザーグループ…*5", "id" => "F5")); ?></th>
            <th>作成日時</th>

                <th><a href=# onclick="$('#F10').focus();return false;" id="F10">修正*10</a></th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->id ?></td>
            <td><?php echo $user->cd ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->userGroupMrs->name ?></td>
            <td><?php echo $user->created ?></td>

                <td><?php echo $this->tag->linkTo(array("users/edit/" . $user->id, "修正")); ?></td>
                <td><?php echo $this->tag->linkTo(array("users/delete/" . $user->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("users/index", "<<最初*11"); ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->before, "<前頁*1"); ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->next, "次頁*2>"); ?></li>
                <li><?php echo $this->tag->linkTo("users/index?page=" . $page->last, "最後*12>>"); ?></li>
            </ul>
        </nav>
    </div>
</div>
