<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = 'ユーザ.新規'; ?>
<div class="page-header">
    <h3>ユーザーマスタ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">ユーザーコード</label>
    <div class="col-sm-2">
        <?php echo $this->tag->textField(array("cd", "size" => 30, "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">パスワード</label>
    <div class="col-sm-4">
        <?php echo $this->tag->passwordField(array("password", "size" => 30, "class" => "form-control", "id" => "fieldPassword")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRepeatPassword" class="col-sm-2 control-label">パスワード再入力</label>
    <div class="col-sm-4">
        <?php echo $this->tag->passwordField(array("repeatPassword", "size" => 30, "class" => "form-control", "id" => "fieldRepeatPassword")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">ユーザー名</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserGroupMrCd" class="col-sm-2 control-label"><?php echo $this->tag->linkTo(array("user_group_mrs", "ユーザーグループ…*8", "id" => "fieldUserGroupMrCdF8")); ?></label>
    <div class="col-sm-3">
        <?php echo $this->tag->select(array("user_group_mr_cd", userGroupMrs::find(["columns" => "cd , CONCAT(cd , ':' , name) as cd_name"]), "using" => array("cd", "cd_name"), "class" => "form-control", "id" => "fieldUserGroupMrCd")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
