<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = '仕入先.一覧'; ?>
<div class="page-header">
    <h3>仕入先台帳 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
	<?php $this->partial("common/indexkanni",["table_id"=>"shiiresaki_mrs","flds"=>[
		["cd","fieldCd","コード",14,14],
		["name","fieldName","名称",24,24]
	]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
				<?php $this->partial("common/indexsort",["flds"=>[
					["cd","コード(修正)"],
					["name","名称"],
					["juusho1","住所1"],
					["bushomei","部署名"],
					["yakushoku","役職名"],
					["gotantousha","ご担当者"]
				]]) ?>

                <th style="text-align:center;">削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shiiresaki_mr): ?>
            <tr>
				<td align="center"><?php echo $this->tag->linkTo(array("shiiresaki_mrs/edit/" . $shiiresaki_mr->id, $shiiresaki_mr->cd)); ?></td>
				<td><?php echo $shiiresaki_mr->name ?></td>
				<td><?php echo $shiiresaki_mr->juusho1 ?></td>
				<td><?php echo $shiiresaki_mr->bushomei ?></td>
				<td><?php echo $shiiresaki_mr->yakushoku ?></td>
				<td><?php echo $shiiresaki_mr->gotantousha ?></td>

				<td align="center"><?php echo $this->tag->linkTo(array("shiiresaki_mrs/delete/" . $shiiresaki_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"shiiresaki_mrs"]) ?>
