<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var Object $shiire_rows
 * @var array $shukkin_rows
 * @var Object $shiiresaki_mr
 * @var array $setdts
 */

use Phalcon\Tag;

$title = '仕入・元帳'
?>

<div class="page-header">
    <h3>仕入先元帳</h3>
</div>

<?php echo $this->getContent(); ?>

<style>
    .cs_checkbox {
        display: none;
    }

    .cs_checkbox+.checkbox-icon {
        position: relative;
        vertical-align: middle;
    }

    .cs_checkbox+.checkbox-icon:before {
        content: "\f372";
        font-family: "Ionicons";
        color: #ccc;
        font-size: 1.35em;
        vertical-align: middle;
    }

    .cs_checkbox:checked+.checkbox-icon:before {
        content: "\f374";
        color: #17bcdf;
    }
</style>
<div class="panel panel-info bg-yel">
    <br>
    <?php
    echo $this->tag->form([
        "shiiresaki_mrs/motochou",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "id" => "form_motochou",
        "name" => "form_motochou",
    ]);
    ?>
    <div class="form-group">
        <div class="col-sm-8">
            <label for="fieldShiiresakiMrCd" class="col-sm-2 control-label">仕入先</label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("shiiresaki_mr_cd", "class" => "form-control ime-i", "id" => "fieldShiiresakiMrCd", "list" => "ShiiresakiMrsOptions")) ?>
            </div>
            <div class="col-sm-7">
                <?php echo $this->tag->textField(array("shiiresaki_mr_name", "readonly" => "readonly", "class" => "form-control ime-i", "id" => "fieldShiiresakiMrName")) ?>
            </div>
            <label for="fieldHyoujiFlg" class="col-sm-2 control-label">表示</label>
            <div class="col-sm-3">
                <?php echo $this->tag->selectStatic(array("hyouji_flg", ["1" => "1=月次計", "2" => "2=伝票計", "3" => "3=明細表", "4" => "4=明細2行表"], "class" => "form-control", "id" => "fieldHyoujiFlg")) ?>
            </div>
            <label for="fieldShouhinMrCd" class="col-sm-1 control-label">商品</label>
            <div class="col-sm-2">
                <?php echo $this->tag->textField(array("shouhin_mr_cd", "class" => "form-control ime-i", "id" => "fieldShouhinMrCd")) ?>
            </div>
            <label for="fieldShouhinTekiyou" class="col-sm-1 control-label">摘要</label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("shouhin_tekiyou", "class" => "form-control ime-i", "id" => "fieldShouhinTekiyou")) ?>
            </div>
            <div class="clearfix"></div>
            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-3">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", KikanSiteiKbns::find(["columns" => "cd , name", "order" => "cd"]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom")) ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-3">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo")) ?>
            </div>
            <div class="clearfix"></div>
            <br />
            <label for="hanni_from" class="col-sm-2 control-label">金額範囲</label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("hanni_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "hanni_from")) ?>
            </div>
            <label for="hanni_to" class="col-sm-1 control-label">～</label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(array("hanni_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "hanni_to")) ?>
            </div>
            <div class="clearfix"></div>
            <label for="joutai" class="col-sm-2 control-label">伝票状態</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("joutai", ['0' => '指定なし', '1' => '未締切', '2' => '締切済'], "style" => "width: 132px;", "class" => "form-control", "id" => "joutai")) ?>
            </div>
            <div class="clearfix"></div>
            <label for="keshikomi_joutai" class="col-sm-2 control-label">出金消込</label>
            <div class="col-sm-3">
                <?php echo $this->tag->select(array("keshikomi_joutai", ['0' => '指定なし', '1' => '消込無', '2' => '消込有'], "style" => "width: 132px;", "class" => "form-control", "id" => "keshikomi_joutai")) ?>
            </div>

            <div class="col-lg-offset-2 col-sm-4">
                <div class="col-sm-4">
                    <?php echo $this->tag->submitButton(array("集計F12", "id" => "F12", "class" => "btn btn-info", "onclick" => "$('#fieldToExcel').val('')")) ?>
                </div>
                <div class="col-sm-6">
                    <?php echo $this->tag->submitButton(array("EXCEL出力", "class" => "btn btn-warning", "onclick" => "$('#fieldToExcel').val('1')")) ?>
                </div>
            </div>
        </div>
        <?php echo $this->tag->hiddenField(array("to_excel", "id" => 'fieldToExcel')) ?>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div><!-- panel-infop -->

<?php
if ($this->request->isPost()) {
    $joutai = $this->request->getPost('joutai');
    $keshikomi_joutai = $this->request->getPost('keshikomi_joutai');
} else {
    $joutai = '0';
    $keshikomi_joutai = '0';
}
?>
<?php
$count1_rows = count($shiire_rows);
$count2_rows = count($shukkin_rows);
$count_rows = $count1_rows + $count2_rows;
$shiiregaku = $shiiresaki_mr->kake_zandaka;
$kesikomizumi_shiiregaku = 0; // 消込状態指定の場合、前残高を計算する
for ($i1 = 0; $i1 < $count1_rows && $shiire_rows[$i1]["denpyoubi"] < $setdts["kikan_from"]; $i1++) {
    $shiiregaku += $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"];
    $kesikomizumi_shiiregaku += $shiire_rows[$i1]["kesikomi_gaku"];
}
$kesikomizumi_kurikoshigaku = $shiiregaku - $kesikomizumi_shiiregaku; // 消込状態指定の場合、前残高を計算する
$shukkingaku = 0;
$dummyShukkingaku = 0;
if ($keshikomi_joutai !== '1') {
    for ($i2 = 0; $i2 < $count2_rows && $shukkin_rows[$i2]["denpyoubi"] < $setdts["kikan_from"]; $i2++) {
        $shukkingaku += $shukkin_rows[$i2]["kingaku"];
    }
} else {
    for ($i2 = 0; $i2 < $count2_rows && $shukkin_rows[$i2]["denpyoubi"] < $setdts["kikan_from"]; $i2++) {
        $dummyShukkingaku += $shukkin_rows[$i2]["kingaku"];
    }
}

if ($keshikomi_joutai !== '1') {
    $zandaka = $shiiregaku - $shukkingaku;
} else {
    $zandaka = $shiiregaku - $dummyShukkingaku;
}

$shiiregaku = 0;
$kesi_kei = 0;
for ($i1a = $i1; $i1a < $count1_rows && $shiire_rows[$i1a]["denpyoubi"] <= $setdts["kikan_to"]; $i1a++) {
    $shiiregaku += $shiire_rows[$i1a]["zeinukigaku"] + $shiire_rows[$i1a]["zeigaku"];
    $kesi_kei += $shiire_rows[$i1a]["kesikomi_gaku"];
}
$shukkingaku = 0;
if ($keshikomi_joutai !== '1') {
    for ($i2a = $i2; $i2a < $count2_rows && $shukkin_rows[$i2a]["denpyoubi"] <= $setdts["kikan_to"]; $i2a++) {
        $shukkingaku += $shukkin_rows[$i2a]["kingaku"];
    }
} else {
    for ($i2a = $i2; $i2a < $count2_rows && $shukkin_rows[$i2a]["denpyoubi"] <= $setdts["kikan_to"]; $i2a++) {
        $dummyShukkingaku += $shukkin_rows[$i2a]["kingaku"];
    }
}

$count1_rows = $i1a;
$count2_rows = $i2a;
$count_rows = $count1_rows + $count2_rows;
$kesi_txt1 = ["", "一部消込", "消込済"];
?>


<div class="row">
    <table bgcolor="white" class="table table-bordered table-hover table-condens-0 head_fix">
        <thead>
            <tr>
                <td colspan=25 bgcolor="whitesmoke">
                    <div class="col-sm-4">
                        <table class="table-bordered table-condens-0" width="100%">
                            <thead>
                                <tr class="tr-blu">
                                    <th style="width:33%; text-align:center;">仕入消込計</th>
                                    <th style="width:33%; text-align:center;">出金消込計</th>
                                    <th style="width:33%; text-align:center;">差異</th>
                                </tr>
                                <tr>
                                    <td align="right" id="tmpKesikomi">0</td>
                                    <td align="right" id="tmpShukkinKesikomi">0</td>
                                    <td align="right" id="tmpSai">0</td>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="col-sm-6">
                        <table class="table-bordered table-condens-0" width="100%">
                            <thead>
                                <tr class="tr-blu">
                                    <th style="width:25%; text-align:center;">前月繰越</th>
                                    <th style="width:25%; text-align:center;">仕入額計</th>
                                    <th style="width:25%; text-align:center;">出金額計</th>
                                    <th style="width:25%; text-align:center;">残高金額</th>
                                </tr>
                                <tr>
                                    <?php if ($this->request->getPost('keshikomi_joutai') === '1') : ?>
                                        <td align="right"><?php echo number_format(0) ?></td>
                                        <td align="right" style="color: <?php echo ($shiiregaku - $kesi_kei < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiiregaku - $kesi_kei) ?></td>
                                        <td align="right" style="color: <?php echo ($shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkingaku) ?></td>
                                        <td align="right" style="color: <?php echo ($shiiregaku - $kesi_kei < 0 ? 'red': 'black') ?>;"><?php echo number_format($kesikomizumi_shiiregaku + $shiiregaku - $kesi_kei) ?></td>
                                    <?php elseif ($this->request->getPost('keshikomi_joutai') === '2') : ?>
                                        <td align="right"><?php echo number_format(0) ?></td>
                                        <td align="right" style="color: <?php echo ($kesi_kei < 0 ? 'red': 'black') ?>;"><?php echo number_format($kesi_kei) ?></td>
                                        <td align="right" style="color: <?php echo ($shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkingaku) ?></td>
                                        <td align="right" style="color: <?php echo ($kesi_kei < 0 ? 'red': 'black') ?>;"><?php echo number_format($kesikomizumi_shiiregaku + $kesi_kei - $shukkingaku) ?></td>
                                    <?php else : ?>
                                        <td align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) ?></td>
                                        <td id="shi_kei" align="right" style="color: <?php echo ($shiiregaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiiregaku) ?></td>
                                        <td id="shu_kei" align="right" style="color: <?php echo ($shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkingaku) ?></td>
                                        <td id="zan_kei" align="right" style="color: <?php echo ($zandaka + $shiiregaku - $shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka + $shiiregaku - $shukkingaku) ?></td>
                                    <?php endif; ?>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </td>
            </tr>
            <?php if ($setdts["hyouji_flg"] == "4") : /* 明細2行表 */ ?>
                <tr bgcolor="Lavender">
                    <th nowrap style="text-align:center;">伝票日付</th>
                    <th nowrap style="text-align:center;">取引区分</th>
                    <th nowrap style="text-align:center;">内訳</th>
                    <th nowrap style="text-align:center;">商品コード</th>
                    <th nowrap style="text-align:center;">課税区分</th>
                    <th nowrap style="text-align:center;">手形期日</th>
                    <th nowrap style="text-align:center;">単位</th>
                    <th nowrap style="text-align:center;">数量</th>
                    <th nowrap style="text-align:center;">仕入額</th>
                    <th nowrap style="text-align:center;">消込</th>
                    <th nowrap style="text-align:center;">出金額</th>
                    <th nowrap style="text-align:center;">消込</th>
                    <th nowrap style="text-align:center;">残高</th>
                </tr>
                <tr bgcolor="Lavender">
                    <th nowrap style="text-align:center;">伝票番号</th>
                    <th nowrap style="text-align:center;">伝票状態</th>
                    <th nowrap style="text-align:center;">消込状態</th>
                    <th colspan="3" nowrap style="text-align:center;">商品/摘要</th>
                    <th nowrap style="text-align:center;">　</th>
                    <th nowrap style="text-align:center;">単価</th>
                    <th nowrap style="text-align:center;">　</th>
                    <th nowrap style="text-align:center;">　</th>
                    <th nowrap style="text-align:center;">　</th>
                    <th nowrap style="text-align:center;">　</th>
                    <th nowrap style="text-align:center;">備考</th>
                </tr>
        </thead>
        <tbody>
            <tr bgcolor="#fffcf8">
                <td></td>
                <td>　</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
            </tr>
            <tr bgcolor="#fffcf8">
                <td></td>
                <td></td>
                <td></td>
                <td colspan="3" nowrap>　繰越</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <?php
                $denpyoubi = "";
                $denpyou_bangou = 0;
                $cntSimeDts = count($shiiresaki_mr->ShiiresakiSimeDts);
                if ($cntSimeDts > 0) {
                    $sime0 = $shiiresaki_mr->ShiiresakiSimeDts[0]->sime_hiduke;
                }
                if ($cntSimeDts > 1) {
                    $sime1 = $shiiresaki_mr->ShiiresakiSimeDts[1]->sime_hiduke;
                }
                for (; $i1 + $i2 < $count_rows;) :
                    if (
                        $i2 >= $count2_rows
                        || $i1 < $count1_rows
                        && $shiire_rows[$i1]["denpyoubi"] <= $shukkin_rows[$i2]["denpyoubi"]
                    ) : // 仕入明細
                        $zandaka += $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"];
                        //$kesi_kbn = $shiire_rows[$i1]["kesikomi_gaku"] == 0 ? 0 : (($shiire_rows[$i1]["kesikomi_gaku"] == $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"]) ? 2 : 1); // 0=未,1=一部,2=済
                        $kesi_kbn = $shiire_rows[$i1]["kesikomi_gaku"] == 0 ? 0 : (($shiire_rows[$i1]["kesikomi_gaku"] == $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"]) ? 2 : 1); // 0=未,1=一部,2=済
                        // 0円の消込データを判別できない為（3項演算子の中に含めると見にくいので分ける）
                        if (isset($shiire_rows[$i1]['kesi_id'])) {
                            if ($kesi_kbn === 0 && !is_null($shiire_rows[$i1]['kesi_id'])) {
                                $kesi_kbn = 2;
                            }
                        }

                        $simekiri_flg = 0; // 0=未締切,1=締切済み
                        if ($cntSimeDts > 0) {
                            if ($shiire_rows[$i1]->shimekiri_flg == 0) { // 0=今回
                                if ($shiire_rows[$i1]->denpyoubi <= $sime0) {
                                    $simekiri_flg = 1;
                                }
                            } else { // 1=次回
                                if ($cntSimeDts > 1) {
                                    if ($shiire_rows[$i1]->denpyoubi <= $sime1) {
                                        $simekiri_flg = 1;
                                    }
                                }
                            }
                        }
                        // 伝票状態フラグで表示を分ける
                        if ($joutai === '1') {
                            if ($simekiri_flg === 1) {
                                $i1++;
                                continue;
                            }
                        } else if ($joutai === '2') {
                            if ($simekiri_flg === 0) {
                                $i1++;
                                continue;
                            }
                        }
                        // 仕入消込状態フラグで表示を分ける
                        if ($keshikomi_joutai === '1') {
                            if ($kesi_kbn === 2) {
                                $i1++;
                                continue;
                            }
                        } else if ($keshikomi_joutai === '2') {
                            if ($kesi_kbn === 0) {
                                $i1++;
                                continue;
                            }
                        }
            ?>
                    <tr bgcolor="#fffcf8">
                        <td nowrap><?php echo $shiire_rows[$i1]["denpyoubi"] == $denpyoubi ? "" : $shiire_rows[$i1]["denpyoubi"] /* 伝票日付 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["torihiki_kbn_name"] /* 取引区分名 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["utiwake_kbn_name"] /* 内訳 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["shouhin_mr_cd"] /* 商品コード */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["zeiritu_mr_name"] . mb_substr($shiire_rows[$i1]["zei_tenka_kbn_name"], 0, 1) /* 課税区分=税率台帳+税転嫁区分 */ ?></td>
                        <td nowrap align="center"></td>
                        <td nowrap align="center"><?php echo $shiire_rows[$i1]["tanni_mr_name"] /* 単位 */ ?></td>
                        <td nowrap align="right" style="color: <?php echo ($shiire_rows[$i1]["suuryou"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiire_rows[$i1]["suuryou"], 2) /* 数量*/ ?></td>
                        <td nowrap align="right" style="color: <?php echo ($shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"], 0) /* 仕入額 */ ?></td>
                        <td nowrap align="center">
                            <div class="custom-control custom-checkbox">
                                <?php echo $this->tag->checkField(array("kesuchk", "class" => "form-control kesuchk", "value" => $shiire_rows[$i1]["id"], "checked" => [null, true, true][$kesi_kbn], "style" => "height:14px !important;"))/* ["","△","＊"][$kesi_kbn] */ ?><?php /* 消込 */ ?>
                                <label for="kesuchk" class="checkbox-icon"></label>
                            </div>
                        </td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                    </tr>
                    <tr bgcolor="#fffcf8">
                        <td nowrap align="right"><?php echo $shiire_rows[$i1]["denpyou_bangou"] == $denpyou_bangou ? ""
                                                        : $this->tag->linkTo(array(
                                                            "shiire_dts/edit/" . $shiire_rows[$i1]["shiire_dt_id"], $shiire_rows[$i1]["denpyou_bangou"], "target" => "_blank"
                                                        )); /* 伝票番号 */ ?></td>
                        <td nowrap align="center" style="color: <?php echo $simekiri_flg == 1 ? 'green' : 'red'; ?>"><?php echo $simekiri_flg == 1 ? "締切済" : ($shiire_rows[$i1]->shimekiri_flg == 1 ? "次回" : "未締切") /* 伝票状態 */ ?></td>
                        <td nowrap align="center"><?php echo ["", "一部消込", "消込済"][$kesi_kbn] /* 消込状態 */ ?></td>
                        <td colspan="3" nowrap><?php echo $shiire_rows[$i1]["tekiyou"] /* 商品/摘要 */ ?></td>
                        <td nowrap></td>
                        <td nowrap align="right"><?php echo number_format($shiire_rows[$i1]["tanka"], 2) /* 単価 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["bikou"] /* 備考 */ ?></td>
                    </tr>
                <?php
                        $denpyoubi = $shiire_rows[$i1]["denpyoubi"];
                        $denpyou_bangou = $shiire_rows[$i1]["denpyou_bangou"];
                        $i1++;
                    else : // 出金明細
                        // 仕入消込状態フラグで表示を分ける
                        if ($keshikomi_joutai === '1') {
                            if ($kesi_kbn === 2) {
                                $i1++;
                                continue;
                            }
                        } else if ($keshikomi_joutai === '2') {
                            if ($kesi_kbn === 0) {
                                $i1++;
                                continue;
                            }
                        }
                        $zandaka -= $shukkin_rows[$i2]["kingaku"];
                ?>
                        <?php
//                        if ($keshikomi_joutai === '1') {
//                            $i2++;
//                            continue;
//                        }
                        ?>
                    <tr bgcolor="#fffcf8">
                        <td nowrap><?php echo $shukkin_rows[$i2]["denpyoubi"] == $denpyoubi ? "" : $shukkin_rows[$i2]["denpyoubi"] /* 伝票日付 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap><?php echo $shukkin_rows[$i2]["tegata_kijitu"] === '0000-00-00' ? '' : $shukkin_rows[$i2]["tegata_kijitu"];/* 手形期日 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap class="tmp_syu" align="right" style="color: <?php echo ($shukkin_rows[$i2]["kingaku"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkin_rows[$i2]["kingaku"], 0) /* 出金額 */ ?></td>
<!--                        <td nowrap align="center">--><?php //echo $shukkin_rows[$i2]["zenkai_kesikomi_gaku"] == 0 ? "" : "＊" /* 消込 */ ?><!--</td>-->
                        <td nowrap align="center"><?php echo $shukkin_rows[$i2]["zenkai_kesikomi_gaku"] == 0 ? "" : "" /* 消込 */ ?></td>
                        <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                    </tr>
                    <tr bgcolor="#fffcf8">
                        <td nowrap align="right"><?php echo $shukkin_rows[$i2]["denpyou_bangou"] == $denpyou_bangou ? ""
                                                        : $this->tag->linkTo(array(
                                                            "shukkin_dts/edit/" . $shukkin_rows[$i2]["shukkin_dt_id"], $shukkin_rows[$i2]["denpyou_bangou"], "target" => "_blank"
                                                        )); /* 伝票番号 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td colspan="3" nowrap><?php echo $shukkin_rows[$i2]["tekiyou"] /* 摘要 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap><?php echo $shukkin_rows[$i2]["bikou"] /* 備考 */ ?></td>
                    </tr>
            <?php
                        $denpyoubi = $shukkin_rows[$i2]["denpyoubi"];
                        $denpyou_bangou = $shukkin_rows[$i2]["denpyou_bangou"];
                        $i2++;
                    endif;
                endfor;
            ?>
        </tbody>
    <?php elseif ($setdts["hyouji_flg"] == "3") : /* 明細表示 */ ?>
        <tr bgcolor="Lavender">
            <th style="text-align:center;">伝票日付</th>
            <th style="text-align:center;">伝票番号</th>
            <th style="text-align:center;">取引区分</th>
            <th style="text-align:center;">伝票状態</th>
            <th style="text-align:center;">内訳</th>
            <th style="text-align:center;">消込状態</th>
            <th style="text-align:center;">商品コード</th>
            <th style="text-align:center;">商品/摘要</th>
            <th style="text-align:center;">課税区分</th>
            <th style="text-align:center;">手形期日</th>
            <th style="text-align:center;">数量</th>
            <th style="text-align:center;">単位</th>
            <th style="text-align:center;">単価</th>
            <th style="text-align:center;">仕入税抜額</th>
            <th style="text-align:center;">税額</th>
            <th style="text-align:center;">消込</th>
            <th style="text-align:center;">出金額</th>
            <th style="text-align:center;">消込</th>
            <th style="text-align:center;">残高</th>
            <th style="text-align:center;">備考</th>
        </tr>
        </thead>
        <tbody>
            <tr bgcolor="#fffcf8">
                <td></td>
                <td>　</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>　繰越</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <?php if ($keshikomi_joutai === '1'): ?>
                    <td nowrap align="right" class="tmp_zan" style="padding:0 4px; color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($kesikomizumi_kurikoshigaku) /* 消し込み残高 */ ?></td>
                <?php elseif ($keshikomi_joutai === '2'): ?>
                    <td nowrap align="right" class="tmp_zan" style="padding:0 4px; color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($kesikomizumi_kurikoshigaku) /* 消し込み残高 */ ?></td>
                <?php else: ?>
                    <td nowrap align="right" class="tmp_zan" style="padding:0 4px; color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                <?php endif; ?>
<!--                <td nowrap align="right" class="tmp_zan" style="padding:0 4px; color: -->
                <td></td>
            </tr>
            <?php
                if ($keshikomi_joutai === '1') {
                    $zandaka = $kesikomizumi_kurikoshigaku;
                } else if ($keshikomi_joutai === '2') {
                    $zandaka = $kesikomizumi_kurikoshigaku;
                }
                $denpyoubi = "";
                $denpyou_bangou = 0;
                $cntSimeDts = count($shiiresaki_mr->ShiiresakiSimeDts);
                if ($cntSimeDts > 0) {
                    $sime0 = $shiiresaki_mr->ShiiresakiSimeDts[0]->sime_hiduke;
                }
                if ($cntSimeDts > 1) {
                    $sime1 = $shiiresaki_mr->ShiiresakiSimeDts[1]->sime_hiduke;
                }
                for (; $i1 + $i2 < $count_rows;) :
                    if (
                        $i2 >= $count2_rows
                        || $i1 < $count1_rows
                        && $shiire_rows[$i1]["denpyoubi"] <= $shukkin_rows[$i2]["denpyoubi"]
                    ) : // 仕入明細
                        $zandaka += $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"];
                        //$kesi_kbn = $shiire_rows[$i1]["kesikomi_gaku"] == 0 ? 0 : (($shiire_rows[$i1]["kesikomi_gaku"] == $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"]) ? 2 : 1); // 0=未,1=一部,2=済
                        $kesi_kbn = $shiire_rows[$i1]["kesikomi_gaku"] == 0 ? 0 : (($shiire_rows[$i1]["kesikomi_gaku"] == $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"]) ? 2 : 1); // 0=未,1=一部,2=済
                        // 0円の消込データを判別できない為（3項演算子の中に含めると見にくいので分ける）
                        if (isset($shiire_rows[$i1]['kesi_id'])) {
                            if ($kesi_kbn === 0 && !is_null($shiire_rows[$i1]['kesi_id'])) {
                                $kesi_kbn = 2;
                            }
                        }
                        $simekiri_flg = 0; // 0=未締切,1=締切済み
                        if ($cntSimeDts > 0) {
                            if ($shiire_rows[$i1]->shimekiri_flg == 0) { // 0=今回
                                if ($shiire_rows[$i1]->denpyoubi <= $sime0) {
                                    $simekiri_flg = 1;
                                }
                            } else { // 1=次回
                                if ($cntSimeDts > 1) {
                                    if ($shiire_rows[$i1]->denpyoubi <= $sime1) {
                                        $simekiri_flg = 1;
                                    }
                                }
                            }
                        }
                        // 伝票状態フラグで表示を分ける
                        if ($joutai === '1') {
                            if ($simekiri_flg === 1) {
                                $i1++;
                                continue;
                            }
                        } else if ($joutai === '2') {
                            if ($simekiri_flg === 0) {
                                $i1++;
                                continue;
                            }
                        }
                        // 仕入消込状態フラグで表示を分ける
                        if ($keshikomi_joutai === '1') {
                            if ((int)$kesi_kbn === 2) {
                                $i1++;
                                continue;
                            }
                        } else if ($keshikomi_joutai === '2') {
                            if ((int)$kesi_kbn === 0) {
                                $i1++;
                                continue;
                            }
                        }
            ?>
                    <tr bgcolor="#fffcf8">
                        <td nowrap align="center"><?php echo $shiire_rows[$i1]["denpyoubi"] == $denpyoubi ? "<span style='color:#eee;'>" . $shiire_rows[$i1]["denpyoubi"] . "</span>" : $shiire_rows[$i1]["denpyoubi"] /* 伝票日付 */ ?></td>
                        <td nowrap align="center"><?php echo $shiire_rows[$i1]["denpyou_bangou"] == $denpyou_bangou ?
                                                        "<span style='color:#eee;'>" . $shiire_rows[$i1]["denpyou_bangou"] . "</span>"
                                                        : $this->tag->linkTo(array(
                                                            "shiire_dts/edit/" . $shiire_rows[$i1]["shiire_dt_id"], $shiire_rows[$i1]["denpyou_bangou"], "target" => "_blank"
                                                        )); /* 伝票番号 */ ?></td>
                        <td nowrap align="center"><?php echo $shiire_rows[$i1]["torihiki_kbn_name"] /* 取引区分名 */ ?></td>
                        <td nowrap align="center" style="color: <?php echo $simekiri_flg == 1 ? 'green' : 'red'; ?>"><?php echo $simekiri_flg == 1 ? "締切済" : ($shiire_rows[$i1]->shimekiri_flg == 1 ? "次回" : "未締切") /* 伝票状態 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["utiwake_kbn_name"] /* 内訳 */ ?></td>
                        <td nowrap align="center"><?php echo ["", "一部消込", "消込済"][$kesi_kbn] /* 消込状態 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["shouhin_mr_cd"] /* 商品コード */ ?></td>
                        <td><?php echo $shiire_rows[$i1]["tekiyou"] /* 商品/摘要 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1]["zeiritu_mr_name"] . mb_substr($shiire_rows[$i1]["zei_tenka_kbn_name"], 0, 1) /* 課税区分=税率台帳+税転嫁区分 */ ?></td>
                        <td nowrap align="center"></td>
                        <td nowrap align="right" style="color: <?php echo ($shiire_rows[$i1]["suuryou"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiire_rows[$i1]["suuryou"], 2) /* 数量*/ ?></td>
                        <td nowrap align="center"><?php echo $shiire_rows[$i1]["tanni_mr_name"] /* 単位 */ ?></td>
                        <td nowrap align="right"><?php echo number_format($shiire_rows[$i1]["tanka"], 2) /* 単価 */ ?></td>
                        <td nowrap align="right" style="padding:0 4px; color: <?php echo ($shiire_rows[$i1]["zeinukigaku"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiire_rows[$i1]["zeinukigaku"], 0) /* 仕入税抜額 */ ?></td>
                        <td nowrap align="right" style="padding:0 4px; color: <?php echo ($shiire_rows[$i1]["zeigaku"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiire_rows[$i1]["zeigaku"], 0) /* 税額 */ ?></td>
                        <td nowrap align="center">
                            <div class="custom-control custom-checkbox">
                                <?php echo $this->tag->checkField(array("kesuchk", "class" => "form-control kesuchk", "value" => $shiire_rows[$i1]["id"], "checked" => [null, true, true][$kesi_kbn], "style" => "height:14px !important;"))/* ["","△","＊"][$kesi_kbn] */ ?><?php /* 消込 */ ?>
                                <label for="kesuchk" class="checkbox-icon"></label>
                            </div>
                        </td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <?php
                        $denpyou_last_flg = 1;
                        $bikou = $shiire_rows[$i1]["bikou"];
                        $denpyoubi = $shiire_rows[$i1]["denpyoubi"];
                        $denpyou_bangou = $shiire_rows[$i1]["denpyou_bangou"];
                        $i1++;
                        if ($i1 < $count1_rows) {
                            if ($shiire_rows[$i1]["denpyou_bangou"] == $denpyou_bangou) {
                                $denpyou_last_flg = 0;
                            }
                        }
                        ?>
                        <td nowrap class="tmp_zan" align="right" style="padding:0 4px; color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo $denpyou_last_flg == 0 ?
                                                                            "<span style='color:#eee;'>" . number_format($zandaka, 0) . "</span>" :
                                                                            number_format($zandaka, 0) /* 残高 */ ?></td>
                        <td nowrap><?php echo $bikou /* 備考 */ ?></td>
                    </tr>
                <?php
                    else : // 出金明細
                        // 仕入消込状態フラグで表示を分ける
                        if ($keshikomi_joutai === '1') {
                            if ((int)$kesi_kbn === 2) {
                                $i2++;
                                continue;
                            }
//                        } else if ($keshikomi_joutai === '2') {
//                            if ((int)$kesi_kbn === 0) {
//                                $i2++;
//                                continue;
//                            }
                        }
                        $zandaka -= $shukkin_rows[$i2]["kingaku"];
                ?>
                    <?php if ($keshikomi_joutai !== '1'): ?>
                        <tr bgcolor="#fffcf8">
                            <td nowrap align="center"><?php echo $shukkin_rows[$i2]["denpyoubi"] == $denpyoubi ? "" : $shukkin_rows[$i2]["denpyoubi"] /* 伝票日付 */ ?></td>
                            <td nowrap align="center"><?php echo $shukkin_rows[$i2]["denpyou_bangou"] == $denpyou_bangou ? ""
                                                            : $this->tag->linkTo(array(
                                                                "shukkin_dts/edit/" . $shukkin_rows[$i2]["shukkin_dt_id"], $shukkin_rows[$i2]["denpyou_bangou"], "target" => "_blank"
                                                            )); /* 伝票番号 */ ?></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td><?php echo $shukkin_rows[$i2]["tekiyou"] /* 摘要 */ ?></td>
                            <td nowrap></td>
                            <td nowrap><?php echo $shukkin_rows[$i2]["tegata_kijitu"] === '0000-00-00' ? '' : $shukkin_rows[$i2]["tegata_kijitu"]; /* 手形期日 */ ?></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap></td>
                            <td nowrap class="tmp_syu" align="right" id="<?php echo 'shukkingaku' . $i2 ?>" style="padding:0 4px; color: <?php echo ($shukkin_rows[$i2]["kingaku"] < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkin_rows[$i2]["kingaku"], 0) /* 出金額 */ ?></td>
    <!--                        <td nowrap id="--><?php //echo 'kesikomi' . $i2 ?><!--" class="kesikomi" align="center">--><?php //echo $shukkin_rows[$i2]["zenkai_kesikomi_gaku"] == 0 ? "" : "＊" /* 消込 */ ?><!--</td>-->
                            <td nowrap id="<?php echo 'kesikomi' . $i2 ?>" class="kesikomi" align="center"><?php echo $shukkin_rows[$i2]["zenkai_kesikomi_gaku"] == 0 ? "" : "" /* 消込 */ ?></td>
                            <td nowrap class="tmp_zan" align="right"
                                style="padding:0 4px; color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>"><?php
                                try {
                                    if ($i2 === 0) {
                                        echo "<span style='color:#eee;'>" . number_format($zandaka) . "</span>";/* 残高 */
                                    } else {
                                        if ($shukkin_rows[$i2]["denpyou_bangou"] === $shukkin_rows[$i2 -1]["denpyou_bangou"]) {
                                            if ($i2 < count($shukkin_rows)) {
                                                if ($shukkin_rows[$i2]["denpyou_bangou"] === $shukkin_rows[$i2 + 1]["denpyou_bangou"]) {
                                                    echo "<span style='color:#eee;'>" . number_format($zandaka) . "</span>";/* 残高 */
                                                } else {
                                                    echo number_format($zandaka);/* 残高 */
                                                }
                                            }  else {
                                                echo number_format($zandaka);/* 残高 */
                                            }
                                        } else {
                                            if ($i2 < count($shukkin_rows)) {
                                                if ($shukkin_rows[$i2]["denpyou_bangou"] === $shukkin_rows[$i2 + 1]["denpyou_bangou"]) {
                                                    echo "<span style='color:#eee;'>" . number_format($zandaka) . "</span>";/* 残高 */
                                                } else {
                                                    echo number_format($zandaka);/* 残高 */
                                                }
                                            }
                                        }
                                    }
                                } catch (Exception $e) {
                                    echo number_format($zandaka);/* 残高 */
                                }

                                ?></td>
                            <td nowrap><?php echo $shukkin_rows[$i2]["bikou"] /* 備考 */ ?></td>
                        </tr>
                    <?php endif; ?>
            <?php
                        $denpyoubi = $shukkin_rows[$i2]["denpyoubi"];
                        $denpyou_bangou = $shukkin_rows[$i2]["denpyou_bangou"];
                        $i2++;
                    endif;
                endfor;
            ?>
        </tbody>
    <?php elseif ($setdts["hyouji_flg"] == "2") : /* 伝票計 */ ?>
        <tr bgcolor="Lavender">
            <th nowrap style="text-align:center;">伝票日付</th>
            <th nowrap style="text-align:center;">取引区分</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">仕入額</th>
            <th nowrap style="text-align:center;">消込</th>
            <th nowrap style="text-align:center; width: 30px;">　</th>
            <th nowrap style="text-align:center;">出金額</th>
            <th nowrap style="text-align:center;">消込</th>
            <th nowrap style="text-align:center;">残高</th>
        </tr>
        <tr bgcolor="Lavender">
            <th nowrap style="text-align:center;">伝票番号</th>
            <th nowrap style="text-align:center;">伝票状態</th>
            <th nowrap style="text-align:center;">消込状態</th>
            <th colspan="3" nowrap style="text-align:center;">伝票種別</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
            <th nowrap style="text-align:center;">　</th>
        </tr>
        </thead>
        <tbody>
            <tr bgcolor="#fffcf8">
                <td></td>
                <td>　</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
            </tr>
            <tr bgcolor="#fffcf8">
                <td></td>
                <td></td>
                <td></td>
                <td colspan="3" nowrap>　繰越</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <?php
//            echo '<pre>';
//            var_dump($shiire_rows->toArray());
//            echo '</pre>';
            ?>
            <?php
                $denpyoubi = "";
                $denpyou_bangou = 0;
                $cntSimeDts = count($shiiresaki_mr->ShiiresakiSimeDts);
                if ($cntSimeDts > 0) {
                    $sime0 = $shiiresaki_mr->ShiiresakiSimeDts[0]->sime_hiduke;
                }
                if ($cntSimeDts > 1) {
                    $sime1 = $shiiresaki_mr->ShiiresakiSimeDts[1]->sime_hiduke;
                }
                for (; $i1 + $i2 < $count_rows;) :
                    if (
                        $i2 >= $count2_rows
                        || $i1 < $count1_rows
                        && $shiire_rows[$i1]["denpyoubi"] <= $shukkin_rows[$i2]["denpyoubi"]
                    ) : // 仕入明細
                        $i1a = $i1; // 控え
                        $shiiregaku = 0;
                        $kesikomigaku = 0;
                        $kesiFlg = false;
                        for (; $i1 < $count1_rows && $shiire_rows[$i1]["denpyou_bangou"] == $shiire_rows[$i1a]["denpyou_bangou"]; $i1++) {
                            $shiiregaku += $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"];
                            $kesikomigaku += $shiire_rows[$i1]["kesikomi_gaku"];
                            // 消込状態取得
                            if ($kesiFlg === false && $shiire_rows[$i1]['kesi_id']) {
                                $kesiFlg = true;
                            }

                        }
                        $zandaka += $shiiregaku;
                        $simekiri_flg = 0; // 0=未締切,1=締切済み
                        if ($cntSimeDts > 0) {
                            if ($shiire_rows[$i1a]->shimekiri_flg == 0) { // 0=今回
                                if ($shiire_rows[$i1a]->denpyoubi <= $sime0) {
                                    $simekiri_flg = 1;
                                }
                            } else { // 1=次回
                                if ($cntSimeDts > 1) {
                                    if ($shiire_rows[$i1a]->denpyoubi <= $sime1) {
                                        $simekiri_flg = 1;
                                    }
                                }
                            }
                        }
            ?>
                    <tr bgcolor="#fffcf8">
                        <td nowrap><?php echo $shiire_rows[$i1a]["denpyoubi"] == $denpyoubi ? "" : $shiire_rows[$i1a]["denpyoubi"] /* 伝票日付 */ ?></td>
                        <td nowrap><?php echo $shiire_rows[$i1a]["torihiki_kbn_name"] /* 取引区分名 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap align="center"></td>
                        <td nowrap align="right" id="<?php echo 'shi_gaku_' . $shiire_rows[$i1a]["shiire_dt_id"] ?>" style="color: <?php echo ($shiiregaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiiregaku, 0) /* 仕入額 */ ?></td>
                        <td nowrap align="center">
                            <span id="<?php echo 'den_kesi_' . $shiire_rows[$i1a]["shiire_dt_id"] ?>"><?php echo $kesikomigaku == 0 ? "" : ($kesikomigaku == $shiiregaku ? "＊" : "△") /* 消込 */ ?></span>
                        </td>
                        <td align="center" id="<?php echo $shiire_rows[$i1a]["shiire_dt_id"] ?>" class="den_kesi">
                            <input type="checkbox" id="<?php echo 'kesikomi_' . $shiire_rows[$i1a]["shiire_dt_id"] ?>" <?php echo $kesiFlg ? 'checked' : '';?> />
                        </td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                    </tr>
                    <tr bgcolor="#fffcf8">
                        <td nowrap align="right"><?php echo $this->tag->linkTo(array("shiire_dts/edit/" . $shiire_rows[$i1a]["shiire_dt_id"], $shiire_rows[$i1a]["denpyou_bangou"], "target" => "_blank")); /* 伝票番号 */ ?></td>
                        <td nowrap align="center" style="color: <?php echo $simekiri_flg == 1 ? 'green' : 'red'; ?>"><?php echo $simekiri_flg == 1 ? "締切済" : ($shiire_rows[$i1a]->shimekiri_flg == 1 ? "次回" : "未締切") /* 伝票状態 */ ?></td>
                        <td nowrap align="center">
                            <?php echo $kesikomigaku == 0 ? "" : ($kesikomigaku == $shiiregaku ? "消込済" : "一部消込") /* 消込状態 */ ?>
                        </td>
                        <td colspan="3" nowrap>仕入伝票</td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                    </tr>
                <?php
                        $denpyoubi = $shiire_rows[$i1a]["denpyoubi"];
                    else : // 出金明細
                        if ($keshikomi_joutai === '1') {
                            $i2++;
                            continue;
                        }
                        $i2a = $i2; // 控え
                        $shukkingaku = 0;
                        $kesikomigaku = $shukkin_rows[$i2]["zenkai_kesikomi_gaku"];
                        for (; $i2 < $count2_rows && $shukkin_rows[$i2]["denpyou_bangou"] == $shukkin_rows[$i2a]["denpyou_bangou"]; $i2++) {
                            $shukkingaku += $shukkin_rows[$i2]["kingaku"];
                        }
                        $zandaka -= $shukkingaku;
                ?>
                    <tr bgcolor="#fffcf8">
                        <td nowrap><?php echo $shukkin_rows[$i2a]["denpyoubi"] == $denpyoubi ? "" : $shukkin_rows[$i2a]["denpyoubi"] /* 伝票日付 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap class="tmp_syu" align="right" id="<?php echo 'shukkingaku' . $i2a ?>" align="right" style="color: <?php echo ($shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkingaku) /* 出金額 */ ?></td>
                        <td nowrap id="<?php echo 'kesikomi' . $i2a ?>" class="kesikomi" align="center">
<!--                            <span>--><?php //echo $kesikomigaku == 0 ? "" : "＊" /* 消込 */ ?><!--</span>-->
                            <span><?php echo $kesikomigaku == 0 ? "" : "" /* 消込 */ ?></span>
                        </td>
                        <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                    </tr>
                    <tr bgcolor="#fffcf8">
                        <td nowrap align="right"><?php echo $this->tag->linkTo(array("shukkin_dts/edit/" . $shukkin_rows[$i2a]["shukkin_dt_id"], $shukkin_rows[$i2a]["denpyou_bangou"], "target" => "_blank")); /* 伝票番号 */ ?></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td colspan="3" nowrap>出金伝票</td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                        <td nowrap></td>
                    </tr>
            <?php
                        $denpyoubi = $shukkin_rows[$i2a]["denpyoubi"];
                    endif;
                endfor;
            ?>
        </tbody>
    <?php elseif ($setdts["hyouji_flg"] == "1") : /* 月次計 */ ?>
        <tr bgcolor="Lavender">
            <th nowrap style="text-align:center;">月度</th>
            <th nowrap style="text-align:center;"></th>
            <th nowrap style="text-align:center;"></th>
            <th nowrap style="text-align:center;"></th>
            <th nowrap style="text-align:center;">仕入額</th>
            <th nowrap style="text-align:center;">出金額</th>
            <th nowrap style="text-align:center;">残高</th>
        </tr>
        <tr bgcolor="Lavender">
            <th nowrap style="text-align:center;"></th>
            <th colspan="3" nowrap style="text-align:center;">期間</th>
            <th nowrap style="text-align:center;"></th>
            <th nowrap style="text-align:center;"></th>
            <th nowrap style="text-align:center;"></th>
        </tr>
        </thead>
        <tbody>
            <?php
                for (
                    $kikan = $setdts["kikan_from"];
                    $kikan <= $setdts["kikan_to"];
                    $kikan = date('Y-m-d', strtotime($kikan . ' +1 month'))
                ) :
                    $ym = date('Ym', strtotime($kikan));
                    $y_m = date('Y-m', strtotime($kikan));

                    // 仕入
                    $shiiregaku = 0;
                    for (; $i1 < $count1_rows && substr($shiire_rows[$i1]["denpyoubi"], 0, 7) == $y_m; $i1++) {
                        $shiiregaku += $shiire_rows[$i1]["zeinukigaku"] + $shiire_rows[$i1]["zeigaku"];
                    }
                    // 出金
                    $shukkingaku = 0;
                    for (; $i2 < $count2_rows && substr($shukkin_rows[$i2]["denpyoubi"], 0, 7) == $y_m; $i2++) {
                        $shukkingaku += $shukkin_rows[$i2]["kingaku"];
                    }
                    $zandaka += $shiiregaku - $shukkingaku;
            ?>
                <tr bgcolor="#fffcf8">
                    <td nowrap><?php echo $y_m ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td nowrap class="tmp_shi" align="right" style="color: <?php echo ($shiiregaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shiiregaku) /* 仕入額 */ ?></td>
                    <td nowrap class="tmp_syu" align="right" style="color: <?php echo ($shukkingaku < 0 ? 'red': 'black') ?>;"><?php echo number_format($shukkingaku) /* 出金額 */ ?></td>
                    <td nowrap class="tmp_zan" align="right" style="color: <?php echo ($zandaka < 0 ? 'red': 'black') ?>;"><?php echo number_format($zandaka) /* 残高 */ ?></td>
                </tr>
                <tr bgcolor="#fffcf8">
                    <td></td>
                    <td colspan="3" nowrap class="zoom_meisai cursor_pointer"><?php echo date('Y-m-01', strtotime($kikan)) . '　～　' . date('Y-m-t', strtotime($kikan)) /* 期間 */ ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php
                endfor;
            ?>
        </tbody>
    <?php endif ?>
    </table>
</div>

<?php /* 明細表を別タブで表示するためのリンク部分 */
echo $this->tag->form(
    array(
        "shiiresaki_mrs/motochou",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "target" => "_blank",
        "id" => "hidden_form"
    )
);
?>
<input id="hiddenShiiresakiMrCd" name="shiiresaki_mr_cd" hidden>
<input id="hiddenShiiresakiMrCd" name="shiiresaki_mr_cd" hidden>
<input id="hiddenHyoujiFlg" name="hyouji_flg" hidden>
<input id="hiddenKikanSiteiKbnCd" name="kikan_sitei_kbn_cd" hidden>
<input id="hiddenKikanFrom" name="kikan_from" hidden>
<input id="hiddenKikanTo" name="kikan_to" hidden>
<?php echo $this->tag->endForm(); ?>

<datalist id="ShiiresakiMrsOptions">
</datalist>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        <span id="iframe-title"></span>
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    const shiiresaki_mrs_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shiiresaki_mrs/modal') ?>";
    const shiiresaki_mrs_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shiiresaki_mrs/ajaxGet') ?>";
    const shouhin_mrs_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/modal') ?>";
    const shouhin_mrs_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shouhin_mrs/ajaxGet') ?>";
    const kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
    const shukkin_kesikomi_dts_ajaxSet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shukkin_kesikomi_dts/ajaxSet') ?>";
    const shukkin_kesikomi_dts_ajaxAllSet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('shukkin_kesikomi_dts/ajaxAllSet') ?>";
</script>

<script type="text/javascript" src="<?php echo $this->url->get('js/views/shiiresaki_mrs_motochou.js'); ?>?var=20210125"></script>