<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "仕入明細データ.新規"; ?>
<div class="page-header">
    <h3>仕入明細データ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "shiire_meisai_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCd" class="col-sm-2 control-label">行番</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUtiwakeKbnCd" class="col-sm-2 control-label">内訳</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("utiwake_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldUtiwakeKbnCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShiireDtId" class="col-sm-2 control-label">仕入データID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_dt_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireDtId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNyuukaKbnCd" class="col-sm-2 control-label">入荷</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuuka_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldNyuukaKbnCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShouhinMrCd" class="col-sm-2 control-label">商品コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shouhin_mr_cd", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldShouhinMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanniMrCd" class="col-sm-2 control-label">単位</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tanni_mr_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldTanniMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIrisuu" class="col-sm-2 control-label">入数</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("irisuu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldIrisuu")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKeisu" class="col-sm-2 control-label">ケース</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("keisu", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKeisu")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTekiyou" class="col-sm-2 control-label">商品名/摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tekiyou", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldTekiyou")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSoukoMrCd" class="col-sm-2 control-label">倉庫コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("souko_mr_cd", "size" => 4, "maxlength" => 4, "style" => "width: 84px;", "class" => "form-control", "id" => "fieldSoukoMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSuuryou" class="col-sm-2 control-label">数量</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("suuryou", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSuuryou")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanka" class="col-sm-2 control-label">単価</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tanka", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldTanka")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKingaku" class="col-sm-2 control-label">金額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kingaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKingaku")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProjectMrCd" class="col-sm-2 control-label">プロジェクトコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("project_mr_cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldProjectMrCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKazeiKbnCd" class="col-sm-2 control-label">課税区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kazei_kbn_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKazeiKbnCd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBikou" class="col-sm-2 control-label">備考</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
