<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "出金明細.一覧"; ?>
<div class="page-header">
    <h3>出金明細 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"shukkin_meisai_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","行"],
                    ["name","出金内容"],
                    ["shukkin_dt_id","出金伝票id"],
                    ["shiharai_kbn_cd","支払区分"],
                    ["tegata_kijitu","手形期日"],
                    ["kingaku","金額"],
                    ["bikou","備考"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shukkin_meisai_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("shukkin_meisai_dts/edit/" . $shukkin_meisai_dt->id, $shukkin_meisai_dt->id)); ?></td>
                <td><?php echo $shukkin_meisai_dt->cd ?></td>
                <td><?php echo $shukkin_meisai_dt->name ?></td>
                <td><?php echo $shukkin_meisai_dt->shukkin_dt_id ?></td>
                <td><?php echo $shukkin_meisai_dt->shiharai_kbn_cd ?></td>
                <td><?php echo $shukkin_meisai_dt->tegata_kijitu ?></td>
                <td><?php echo $shukkin_meisai_dt->kingaku ?></td>
                <td><?php echo $shukkin_meisai_dt->bikou ?></td>
                <td><?php echo $shukkin_meisai_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("shukkin_meisai_dts/delete/" . $shukkin_meisai_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"shukkin_meisai_dts"]) ?>
