<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "prop_hikiate_mrs.新規"; ?>
<div class="page-header">
    <h3>prop_hikiate_mrs 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "prop_hikiate_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="field指図番号" class="col-sm-2 control-label">指図番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("指図番号", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "field指図番号")) ?>
    </div>

<label for="field指図枝番" class="col-sm-2 control-label">指図枝番</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("指図枝番", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "field指図枝番")) ?>
    </div>

<label for="field加工№" class="col-sm-2 control-label">加工№</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("加工№", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "field加工№")) ?>
    </div>

<label for="field加工no" class="col-sm-2 control-label">加工NO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("加工NO", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "field加工no")) ?>
    </div>

<label for="field単価" class="col-sm-2 control-label">単価</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("単価", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "field単価")) ?>
    </div>

<label for="field単価単位" class="col-sm-2 control-label">単価単位</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("単価単位", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "field単価単位")) ?>
    </div>

<label for="field糸名" class="col-sm-2 control-label">糸名</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("糸名", "size" => 80, "maxlength" => 100, "style" => "width: 996px;", "class" => "form-control", "id" => "field糸名")) ?>
    </div>

<label for="field糸名２" class="col-sm-2 control-label">糸名２</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("糸名２", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "field糸名２")) ?>
    </div>

<label for="fieldロット" class="col-sm-2 control-label">ロット</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ロット", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "fieldロット")) ?>
    </div>

<label for="field備考" class="col-sm-2 control-label">備考</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("備考", "size" => 70, "maxlength" => 70, "style" => "width: 876px;", "class" => "form-control", "id" => "field備考")) ?>
    </div>

<label for="field出荷先" class="col-sm-2 control-label">出荷先</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("出荷先", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "field出荷先")) ?>
    </div>

<label for="field住所" class="col-sm-2 control-label">住所</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("住所", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "field住所")) ?>
    </div>

<label for="field電話" class="col-sm-2 control-label">電話</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("電話", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "field電話")) ?>
    </div>

<label for="fieldラベル形式" class="col-sm-2 control-label">ラベル形式</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ラベル形式", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldラベル形式")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
