<?php /* 一覧表の簡易検索部分 $table_id,[["cd","fieldCd","コード",14,14],[項目コード,項目ID,項目名,画面サイズ,入力サイズ],…] */
	if (empty($index_or)) {$index_or = "index";} // $index_or に 'index1'などと入れるとindex以外のアクションで使える。
	echo $this->tag->form(array($table_id."/".$index_or, "autocomplete" => "off", "class" => "form-horizontal"));
?>
	<table class="table table-condensed">
		<tr>
			<?php foreach ($flds as $fld): ?>
				<td align="right" style="border-style:none;">
					<label for=<?php echo $fld[1] ?> class="control-label"><?php echo $fld[2] ?></label>
				</td>
				<td style="border-style:none;">
					<?php echo $this->tag->textField(array($fld[0], "size" => $fld[3], "maxlength" => $fld[4], "class" => "form-control", "id" => $fld[1])) ?>
				</td>
			<?php endforeach; ?>
			<td style="border-style:none;">
				<?php echo $this->tag->submitButton(array("簡易検索F12", "id" => "F12", "class" => "btn btn-success")) ?>
			</td>
			<td style="border-style:none; vertical-align:middle;">
				
			</td>
			<td align="right" style="border-style:none;">
				<label for="fieldPagelimit" class="control-label">行数</label>
			</td>
			<td style="border-style:none;">
				<?php echo $this->tag->textField(array("pagelimit", "size" => 4, "maxlength" => 4, "class" => "form-control", "id" => "fieldPagelimit")) ?>
			</td>
		</tr>
	</table>
<?php echo $this->tag->endForm(); ?>
