<div class="panel panel-danger">
 <div class="panel-heading" style="height: 20px;padding:0px 15px;">
  <a data-toggle="collapse" href="#updates">更新情報…</a>
 </div>
 <div class="panel-body collapse" id="updates">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "readonly" => "readonly", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
    <label for="fieldSakuseiUserId" class="col-sm-2 control-label">作成者</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array('sakusei_user_id', 'type' => 'numeric', "readonly" => "readonly", 'class' => 'form-control', 'id' => 'fieldSakuseiUserId')); ?>
    </div>
    <label for="fieldCreated" class="col-sm-2 control-label">作成日時</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array('created', 'size' => 17, "readonly" => "readonly", 'class' => 'form-control', 'id' => 'fieldCreated')); ?>
    </div>
    <label for="fieldKousinUserId" class="col-sm-2 control-label">更新者</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array('kousin_user_id', 'type' => 'numeric', "readonly" => "readonly", 'class' => 'form-control', 'id' => 'fieldKousinUserId')); ?>
    </div>
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(array('updated', 'size' => 17, "readonly" => "readonly", 'class' => 'form-control', 'id' => 'fieldUpdated')); ?>
    </div>
 </div>
</div>
