<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "担当者マスタ.一覧"; ?>
<div class="page-header">
    <h3>担当者マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"tantou_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","担当コード"],
                    ["name","担当者名"],
                    ["kana_mei","フリガナ"],
                    ["bumon_mr_cd","部門"],
                    ["bumon_mr_cd","部門名"],
                    ["updated","更新日時"],
                ]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tantou_mr): ?>
            <tr>
                <td align="center"><?php echo $this->tag->linkTo(array("tantou_mrs/edit/" . $tantou_mr->id, $tantou_mr->id)); ?></td>
                <td align="center"><?php echo $tantou_mr->cd ?></td>
                <td align="center"><?php echo $tantou_mr->name ?></td>
                <td align="center"><?php echo $tantou_mr->kana_mei ?></td>
                <td align="center"><?php echo $tantou_mr->bumon_mr_cd ?></td>
                <td align="center"><?php echo $tantou_mr->BumonMrs->name ?></td>
                <td align="center"><?php echo $tantou_mr->updated ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("tantou_mrs/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("tantou_mrs/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("tantou_mrs/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("tantou_mrs/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("tantou_mrs/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
