<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = '納入先.一覧'; ?>
<div class="page-header">
    <h3>納入先台帳 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
	<?php $this->partial("common/indexkanni",["table_id"=>"nounyuusaki_mrs","flds"=>[
		["cd","fieldCd","コード",14,14],
		["name","fieldName","名称",24,24]
	]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
				<?php $this->partial("common/indexsort",["flds"=>[
					["cd","コード(修正)"],
					["name","名称"],
					["juusho1","住所1"],
					["bushomei","部署名"],
					["yakushoku","役職名"],
					["gotantousha","ご担当者"]
				]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $nounyuusaki_mr): ?>
            <tr>
				<td align="center"><?php echo $this->tag->linkTo(array("nounyuusaki_mrs/edit/" . $nounyuusaki_mr->id, $nounyuusaki_mr->cd)); ?></td>
				<td><?php echo $nounyuusaki_mr->name ?></td>
				<td><?php echo $nounyuusaki_mr->juusho1 ?></td>
				<td><?php echo $nounyuusaki_mr->bushomei ?></td>
				<td><?php echo $nounyuusaki_mr->yakushoku ?></td>
				<td><?php echo $nounyuusaki_mr->gotantousha ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"nounyuusaki_mrs"]) ?>
