<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '商品.修正'; ?>
<div class="page-header">
    <h3>商品台帳 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "shouhin_mrs/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>
<div class="form-group">

    <?php $this->partial('shouhin_mrs/inputfields'); ?>

    <?php $this->partial('common/panel_updates'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shouhin_mrs/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("shouhin_mrs/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return final_check();')) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shouhin_mrs/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("joukenhyou_mrs/editg/".$id, "条件表", "class" => "btn btn-primary", "target"=>"_blank")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("kousei_buhin_mrs/buhin/".$id, "構成部品", "class" => "btn btn-primary", "target"=>"_blank")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shouhin_mrs/delete/".$id, "台帳削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div><!-- class="form-group" -->

<?php echo $this->tag->endForm(); ?>
<script type="text/javascript" src="<?php echo $this->url->get('js/lib.js'); ?>?var=20191023"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/shouhin_mrs.js'); ?>?var=20191023"></script>
