<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var Object $page
 */
?>
<?php

use Phalcon\Tag; ?>
<?php $title = '商品.一覧'; ?>
<div class="page-header">
    <h3>商品台帳 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni", ["table_id" => "shouhin_mrs", "flds" => [
        ["cd", "fieldCd", "商品コード", 14, 14], ["name", "fieldName", "商品名", 40, 40]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <?php $this->partial("common/indexsort", ["flds" => [
                    ["cd", "コード(修正)"],
                    ["name", "名称"],
                    ["updated", "更新日"],
                    ["tanni_mr1_cd", "単位1"],
                    ["tanni_mr2_cd", "単位2"],
                    ["memo", "メモ"],
                    ["shouhin_bunrui1_kbn_cd", "商品分類1"]
                ]]) ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($page->items as $shouhin_mr) : ?>
                <tr>
                    <td align="center"><?php echo $this->tag->linkTo(array("shouhin_mrs/edit/" . $shouhin_mr->id, $shouhin_mr->cd)); ?></td>
                    <td><?php echo $shouhin_mr->name ?></td>
                    <td align="center"><?php echo $shouhin_mr->updated ?></td>
                    <td align="center"><?php echo $shouhin_mr->TanniMr1s->name ?></td>
                    <td align="center"><?php echo $shouhin_mr->TanniMr2s->name ?></td>
                    <td align="left"><?php echo $shouhin_mr->memo ?></td>
                    <td align="center"><?php echo $shouhin_mr->shouhin_bunrui1_kbn_cd ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail", ["table_id" => "shouhin_mrs"]) ?>