<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '仕入.新規'; ?>

<div class="page-header">
    <h3>仕入伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    array(
        "shiire_dts/create",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "post_form",
        "id" => "post_form",
    )
);
?>

<div class="form-group">

    <?php $this->partial('shiire_dts/inputfields'); ?>

    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("shiire_dts/prev", "最終F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("shiire_dts/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return final_check();')) ?>
    </div>

</div><!-- form-group -->

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">
    var imax = <?php echo $imax ?>;
</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/shiire_dts.js'); ?>?var=20210115"></script>