<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '仕入.検索'; ?>
<div class="page-header">
    <h3>仕入データ 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "shiire_dts/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
    <label for="fieldCd" class="col-sm-2 control-label">伝票番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>
    <label for="fieldTekiyou" class="col-sm-2 control-label">摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tekiyou", "size" => 32, "maxlength" => 32, "style" => "width: 420px;", "class" => "form-control", "id" => "fieldTekiyou")) ?>
    </div>
    <label for="fieldShiirebi" class="col-sm-2 control-label">仕入日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiirebi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldShiirebi")) ?>
    </div>
    <label for="fieldHacchuuCd" class="col-sm-2 control-label">発注番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hacchuu_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHacchuuCd")) ?>
    </div>
    <label for="fieldShouninJoutaiFlg" class="col-sm-2 control-label">承認状態</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shounin_joutai_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShouninJoutaiFlg")) ?>
    </div>
    <label for="fieldShouninShaMrCd" class="col-sm-2 control-label">承認者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shounin_sha_mr_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShouninShaMrCd")) ?>
    </div>
    <label for="fieldZeirituTekiyoubi" class="col-sm-2 control-label">税率適用日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zeiritu_tekiyoubi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldZeirituTekiyoubi")) ?>
    </div>
    <label for="fieldShiiresakiMrCd" class="col-sm-2 control-label">仕入先</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiiresaki_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldShiiresakiMrCd")) ?>
    </div>
    <label for="fieldTorihikiKbnCd" class="col-sm-2 control-label">取引区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("torihiki_kbn_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldTorihikiKbnCd")) ?>
    </div>
    <label for="fieldZeiTenkaKbnCd" class="col-sm-2 control-label">税転嫁</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zei_tenka_kbn_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldZeiTenkaKbnCd")) ?>
    </div>
    <label for="fieldTantouMrId" class="col-sm-2 control-label">担当者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tantou_mr_id", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldTantouMrId")) ?>
    </div>
    <label for="fieldShimekiriFlg" class="col-sm-2 control-label">締切</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shimekiri_flg", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShimekiriFlg")) ?>
    </div>
    <label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
