<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "倉庫.一覧"; ?>
<div class="page-header">
    <h3>倉庫台帳 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"souko_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["yuubin_bangou","郵便番号"],
                    ["juusho1","住所１"],
                    ["juusho2","住所２"],
                    ["tantou_mr_cd","担当者"],
                    ["tel","TEL"],
                    ["fax","FAX"],
                    ["memo","メモ欄"],
                    ["updated","更新日時"],
                ]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $souko_mr): ?>
            <tr>
                <td align="center"><?php echo $this->tag->linkTo(array("souko_mrs/edit/" . $souko_mr->id, $souko_mr->id)); ?></td>
                <td align="center"><?php echo $souko_mr->cd ?></td>
                <td><?php echo $souko_mr->name ?></td>
                <td align="center"><?php echo $souko_mr->yuubin_bangou ?></td>
                <td><?php echo $souko_mr->juusho1 ?></td>
                <td><?php echo $souko_mr->juusho2 ?></td>
                <td><?php echo $souko_mr->tantou_mr_cd ?></td>
                <td align="center"><?php echo $souko_mr->tel ?></td>
                <td align="center"><?php echo $souko_mr->fax ?></td>
                <td><?php echo $souko_mr->memo ?></td>
                <td align="center"><?php echo $souko_mr->updated ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("souko_mrs/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("souko_mrs/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("souko_mrs/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("souko_mrs/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("souko_mrs/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
