<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "倉庫.検索"; ?>
<div class="page-header">
    <h3>倉庫台帳 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    if (strpos($_SERVER['HTTP_REFERER'], '/souko_mrs/modal')) {
        $formurl = "souko_mrs/modal";
    } else {
        $formurl = "souko_mrs/index";
    }

    echo $this->tag->form(
        array(
            $formurl,
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldId")) ?>
    </div>

<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 12, "maxlength" => 12, "style" => "width: 180px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "maxlength" => 30, "style" => "width: 396px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldYuubinBangou" class="col-sm-2 control-label">郵便番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("yuubin_bangou", "size" => 8, "maxlength" => 8, "style" => "width: 120px;", "class" => "form-control", "id" => "fieldYuubinBangou")) ?>
    </div>

<label for="fieldJuusho1" class="col-sm-2 control-label">住所１</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juusho1", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldJuusho1")) ?>
    </div>

<label for="fieldJuusho2" class="col-sm-2 control-label">住所２</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juusho2", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldJuusho2")) ?>
    </div>

<label for="fieldTantouMrCd" class="col-sm-2 control-label">担当者</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tantou_mr_cd", "size" => 3, "maxlength" => 3, "style" => "width: 72px;", "class" => "form-control", "id" => "fieldTantouMrCd")) ?>
    </div>

<label for="fieldTel" class="col-sm-2 control-label">TEL</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tel", "size" => 16, "maxlength" => 16, "style" => "width: 228px;", "class" => "form-control", "id" => "fieldTel")) ?>
    </div>

<label for="fieldFax" class="col-sm-2 control-label">FAX</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("fax", "size" => 16, "maxlength" => 16, "style" => "width: 228px;", "class" => "form-control", "id" => "fieldFax")) ?>
    </div>

<label for="fieldMemo" class="col-sm-2 control-label">メモ欄</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("memo", "size" => 46, "maxlength" => 46, "style" => "width: 588px;", "class" => "form-control", "id" => "fieldMemo")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
