<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "帳票種別.一覧"; ?>
<div class="page-header">
    <h3>帳票種別 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"chouhyou_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["denpyou_mr_cd","伝票コード"],
                    ["jun","順"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $chouhyou_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("chouhyou_kbns/edit/" . $chouhyou_kbn->id, $chouhyou_kbn->id)); ?></td>
                <td><?php echo $chouhyou_kbn->cd ?></td>
                <td><?php echo $chouhyou_kbn->name ?></td>
                <td><?php echo $chouhyou_kbn->denpyou_mr_cd ?></td>
                <td><?php echo $chouhyou_kbn->jun ?></td>
                <td><?php echo $chouhyou_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("chouhyou_kbns/delete/" . $chouhyou_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"chouhyou_kbns"]) ?>
