<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "帳票種別.新規"; ?>
<div class="page-header">
    <h3>帳票種別 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "chouhyou_kbns/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldDenpyouMrCd" class="col-sm-2 control-label">伝票コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("denpyou_mr_cd", DenpyouMrs::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 276px;", "class" => "form-control", "id" => "fieldDenpyouMrCd")) ?>
    </div>

<label for="fieldJun" class="col-sm-2 control-label">順</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("jun", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJun")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("chouhyou_kbns/prev", "最新F3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("chouhyou_kbns/search", "検索F4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
