<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "取引内訳区分.修正"; ?>
<div class="page-header">
    <h3>取引内訳区分 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "utiwake_kbns/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldBikou" class="col-sm-2 control-label">備考</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>

<label for="fieldJuchuuFlg" class="col-sm-2 control-label">受注フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juchuu_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJuchuuFlg")) ?>
    </div>

<label for="fieldHacchuuFlg" class="col-sm-2 control-label">発注フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hacchuu_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHacchuuFlg")) ?>
    </div>

<label for="fieldUriageFlg" class="col-sm-2 control-label">売上フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriage_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldUriageFlg")) ?>
    </div>

<label for="fieldShiireFlg" class="col-sm-2 control-label">仕入フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireFlg")) ?>
    </div>

<label for="fieldUriageZaikoFlg" class="col-sm-2 control-label">売上在庫フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriage_zaiko_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldUriageZaikoFlg")) ?>
    </div>

<label for="fieldShiireZaikoFlg" class="col-sm-2 control-label">仕入在庫フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_zaiko_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireZaikoFlg")) ?>
    </div>

<label for="fieldUriageAzukariFlg" class="col-sm-2 control-label">売上預りフラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriage_azukari_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldUriageAzukariFlg")) ?>
    </div>

<label for="fieldShiireAzukariFlg" class="col-sm-2 control-label">仕入預りフラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_azukari_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireAzukariFlg")) ?>
    </div>

<label for="fieldJuchuuZanFlg" class="col-sm-2 control-label">受注残フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("juchuu_zan_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJuchuuZanFlg")) ?>
    </div>

<label for="fieldHacchuuZanFlg" class="col-sm-2 control-label">発注残フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hacchuu_zan_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHacchuuZanFlg")) ?>
    </div>

<label for="fieldYayoiKbn" class="col-sm-2 control-label">弥生区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("yayoi_kbn", "style" => "width: 60px;", "class" => "form-control", "id" => "fieldYayoiKbn")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("utiwake_kbns/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("utiwake_kbns/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("utiwake_kbns/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("utiwake_kbns/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
