<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = '納入先.検索'; ?>
<div class="modal-header" style="padding:0px 15px;">
    <h4>納入先マスタ 検索条件</h4>
</div>

<?php echo $this->getContent() ?>
<div class="modal-body" style="padding:0px 15px;">
<?php
    echo $this->tag->form(
        array(
            "nounyuusaki_mrs_modal/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">

    <?php $this->partial('nounyuusaki_mrs/inputfields'); ?>

    <?php $this->partial('common/panel_search_bottom'); ?>

    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div><!-- class="form-group" -->

<?php echo $this->tag->endForm(); ?>
