<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "前回加工時申し送りデータ.一覧"; ?>
<div class="page-header">
    <h3>前回加工時申し送りデータ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"kakou_zenkai_mokuri_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","行番"],
                    ["name","内容"],
                    ["hacchuu_dt_id","発注書キー"],
                    ["hiduke","日付"],
                    ["tantou_mr_cd","記入者コード"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $kakou_zenkai_mokuri_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("kakou_zenkai_mokuri_dts/edit/" . $kakou_zenkai_mokuri_dt->id, $kakou_zenkai_mokuri_dt->id)); ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->cd ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->name ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->hacchuu_dt_id ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->hiduke ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->tantou_mr_cd ?></td>
                <td><?php echo $kakou_zenkai_mokuri_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("kakou_zenkai_mokuri_dts/delete/" . $kakou_zenkai_mokuri_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"kakou_zenkai_mokuri_dts"]) ?>
