<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "商品条件マスタ.新規"; ?>
<div class="page-header">
    <h3>商品条件マスタ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "h_shouhin_jouken_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldShouhinMrCd" class="col-sm-2 control-label">商品cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shouhin_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldShouhinMrCd")) ?>
    </div>

<label for="fieldHKishuMrCd" class="col-sm-2 control-label">機種cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("h_kishu_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldHKishuMrCd")) ?>
    </div>

<label for="fieldHJoukenMidasiMrId" class="col-sm-2 control-label">条件見出しid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("h_jouken_midasi_mr_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldHJoukenMidasiMrId")) ?>
    </div>

<label for="fieldJouken3" class="col-sm-2 control-label">条件摘要</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("jouken", "size" => 80, "maxlength" => 250, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldJouken3")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
