<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

/** @var Array $tokuisaki_list */

use Phalcon\Tag;

$title = '商品別売上単価表';
?>
<div class="page-header">
    <h2>商品別売上単価表</h2>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br/>
    <?php
    echo $this->tag->form(
        [
            "tokuisaki_tanka_dts/shouhin_index",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        ]
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="shouhin_mr_cd" class="col-sm-2 control-label">商品 : </label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(["shouhin_mr_cd", "class" => "form-control", "id" => "shouhin_mr_cd", "required" => "required"]); ?>
            </div>
        </div>
        <div class="col-sm-10">
            <label for="shouhin_name" class="col-sm-2 control-label">商品名称 : </label>
            <div class="col-sm-3">
                <?php echo $this->tag->textField(["shouhin_name", "class" => "form-control", "id" => "shouhin_name", "readonly" => "readonly"]); ?>
            </div>
            <div><br/></div>
        </div>
        <div class="col-sm-10">
            <label for="joudai" class="col-sm-2 control-label">上代 > </label>
            <div class="col-sm-2">
                <?php echo $this->tag->textField(["joudai", "class" => "form-control text-right", "id" => "joudai", "readonly" => "readonly"]); ?>
            </div>
            <label for="uri_tanka" class="col-sm-2 control-label">販売単価 > </label>
            <div class="col-sm-2">
                <?php echo $this->tag->textField(["uri_tanka", "class" => "form-control text-right", "id" => "uri_tanka", "readonly" => "readonly"]); ?>
            </div>
            <div><br/></div>
        </div>
        <div class="col-sm-10">
            <label for="shouhin_tani" class="col-sm-2 control-label">単価単位 ></label>
            <div class="col-sm-2">
                <?php echo $this->tag->textField(["shouhin_tani", "class" => "form-control f-cent ime-d", "id" => "shouhin_tani", "readonly" => "readonly"]) ?>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="col-sm-12">
                <button id="dl-xlsx" class="submit btn btn-warning">EXCEL*出力</button>
            </div>
            <br/><br/>
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(["集計*F12", "id" => "F12", "class" => "btn  btn-success"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="row">
    <table id="target-table" class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
        <tr style="background-color: lavender;">
            <input type="hidden" id="dummy" />
            <th style="text-align: center;">得意先コード</th>
            <th style="text-align:center;">得意先名称</th>
            <th style="text-align:center;">得意先単価</th>
        </tr>
        </thead>
        <?php $i = 0; ?>
        <tbody>
        <?php foreach ($tokuisaki_list as $list): ?>
            <tr>
                <input type="hidden" id="tokuisaki_id<?php echo $i; ?>" class="tokuisaki_id"  value="<?php if (isset($list['id'])) echo $list['id']; ?>"/>
                <td id="cd<?php echo $i ?>" class="tokuisaki_mr_cd"
                    style="text-align: center; color: blue; cursor: pointer;"><?php if (isset($list['cd'])) echo $list['cd']; ?></td>
                <td style="text-align:left;"><?php if (isset($list['name'])) echo $list['name']; ?></td>
                <td id="tanka<?php echo $i ?>" class="tanka" style="text-align:right;" contenteditable=true>
                    <?php if (isset($list['tokuisaki_betsu_tanka'])) {
                        echo $list['tokuisaki_betsu_tanka'] === '' ?: $list['tokuisaki_betsu_tanka'];
                    } else {
                        echo 0;
                    } ?>
                </td>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>

    <!-- Modal -->
    <div id="iframe-bg" class="bgStyle"></div>
    <div id="iframe-wrap" class="wrapStyle">
        <div class="modal-header" style="padding: 5px; background-color: #ddd;">
            <span id="iframe-title"></span>
            <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
        </div>
        <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
        </div>
    </div>
    <!-- end modal -->
    <script>
        var tokuisaki_tanka_save_ajax = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('tokuisaki_tanka_dts/saveAjax') ?>";
        var shouhin_mrs_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/modal') ?>";
        var shouhin_mrs_ajaxGet = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('shouhin_mrs/ajaxGet') ?>";
        var tokuisaki_edit = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('tokuisaki_mrs/edit/') ?>";
    </script>
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
    <script type="text/javascript"
            src="<?php echo $this->url->get('js/views/tokuisaki_tanka_shouhin_betsu.js'); ?>?var=20200410"></script>
