<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["kakou_jouken_meisai/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["kakou_jouken_meisai/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Cd</th>
            <th>Shouhin Of Mr Of Cd</th>
            <th>Kakou Of Jouken Of Midashi Of Cd</th>
            <th>Kakou Of Jouken Of Kbn Of Cd</th>
            <th>Naiyou</th>
            <th>Version</th>
            <th>Hikae Of Dltflg</th>
            <th>Hikae Of User</th>
            <th>Hikae Of Nichiji</th>
            <th>Sakusei Of User</th>
            <th>Created</th>
            <th>Kousin Of User</th>
            <th>Updated</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $kakou_jouken_meisai): ?>
            <tr>
                <td><?php echo $kakou_jouken_meisai->id ?></td>
            <td><?php echo $kakou_jouken_meisai->cd ?></td>
            <td><?php echo $kakou_jouken_meisai->shouhin_mr_cd ?></td>
            <td><?php echo $kakou_jouken_meisai->kakou_jouken_midashi_cd ?></td>
            <td><?php echo $kakou_jouken_meisai->kakou_jouken_kbn_cd ?></td>
            <td><?php echo $kakou_jouken_meisai->naiyou ?></td>
            <td><?php echo $kakou_jouken_meisai->version ?></td>
            <td><?php echo $kakou_jouken_meisai->hikae_dltflg ?></td>
            <td><?php echo $kakou_jouken_meisai->hikae_user_id ?></td>
            <td><?php echo $kakou_jouken_meisai->hikae_nichiji ?></td>
            <td><?php echo $kakou_jouken_meisai->sakusei_user_id ?></td>
            <td><?php echo $kakou_jouken_meisai->created ?></td>
            <td><?php echo $kakou_jouken_meisai->kousin_user_id ?></td>
            <td><?php echo $kakou_jouken_meisai->updated ?></td>

                <td><?php echo $this->tag->linkTo(["kakou_jouken_meisai/edit/" . $kakou_jouken_meisai->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["kakou_jouken_meisai/delete/" . $kakou_jouken_meisai->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["kakou_jouken_meisai/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["kakou_jouken_meisai/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["kakou_jouken_meisai/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["kakou_jouken_meisai/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
