<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "VIEW.新規"; ?>
<div class="page-header">
    <h3>VIEW 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "report_azukari_vws/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldShouhinMrCd" class="col-sm-2 control-label">Shouhin Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shouhin_mr_cd", "size" => 20, "maxlength" => 20, "style" => "width: 276px;", "class" => "form-control", "id" => "fieldShouhinMrCd")) ?>
    </div>

<label for="fieldTantouMrCd" class="col-sm-2 control-label">Tantou Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tantou_mr_cd", "size" => 3, "maxlength" => 3, "style" => "width: 72px;", "class" => "form-control", "id" => "fieldTantouMrCd")) ?>
    </div>

<label for="fieldTanniMrCd" class="col-sm-2 control-label">Tanni Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tanni_mr_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldTanniMrCd")) ?>
    </div>

<label for="fieldLot" class="col-sm-2 control-label">Lot</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("lot", "size" => 50, "maxlength" => 50, "style" => "width: 636px;", "class" => "form-control", "id" => "fieldLot")) ?>
    </div>

<label for="fieldKobetucd" class="col-sm-2 control-label">Kobetucd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kobetucd", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldKobetucd")) ?>
    </div>

<label for="fieldZaikoRyous" class="col-sm-2 control-label">Zaiko Of Ryous</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zaiko_ryous", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldZaikoRyous")) ?>
    </div>

<label for="fieldNyuukoRyous" class="col-sm-2 control-label">Nyuuko Of Ryous</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuuko_ryous", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldNyuukoRyous")) ?>
    </div>

<label for="fieldShukkoRyous" class="col-sm-2 control-label">Shukko Of Ryous</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shukko_ryous", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShukkoRyous")) ?>
    </div>

<label for="fieldNyuukobis" class="col-sm-2 control-label">Nyuukobis</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuukobis", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldNyuukobis")) ?>
    </div>

<label for="fieldShukkobis" class="col-sm-2 control-label">Shukkobis</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shukkobis", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldShukkobis")) ?>
    </div>

<label for="fieldNyuushukkobi" class="col-sm-2 control-label">Nyuushukkobi</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuushukkobi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldNyuushukkobi")) ?>
    </div>

<label for="fieldNyuushukkoym" class="col-sm-2 control-label">Nyuushukkoym</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuushukkoym", "size" => 6, "maxlength" => 6, "style" => "width: 108px;", "class" => "form-control", "id" => "fieldNyuushukkoym")) ?>
    </div>

<label for="fieldDenpyouMrCd" class="col-sm-2 control-label">Denpyou Of Mr Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("denpyou_mr_cd", "size" => 6, "maxlength" => 6, "style" => "width: 108px;", "class" => "form-control", "id" => "fieldDenpyouMrCd")) ?>
    </div>

<label for="fieldOyaId" class="col-sm-2 control-label">Oya</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("oya_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldOyaId")) ?>
    </div>

<label for="fieldOyaCd" class="col-sm-2 control-label">Oya Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("oya_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldOyaCd")) ?>
    </div>

<label for="fieldGyouCd" class="col-sm-2 control-label">Gyou Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("gyou_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldGyouCd")) ?>
    </div>

<label for="fieldUtiwakeKbnCd" class="col-sm-2 control-label">Utiwake Of Kbn Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("utiwake_kbn_cd", "size" => 2, "maxlength" => 2, "style" => "width: 60px;", "class" => "form-control", "id" => "fieldUtiwakeKbnCd")) ?>
    </div>

<label for="fieldTorihikisakiCd" class="col-sm-2 control-label">Torihikisaki Of Cd</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("torihikisaki_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldTorihikisakiCd")) ?>
    </div>

<label for="fieldBikou" class="col-sm-2 control-label">Bikou</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("bikou", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldBikou")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
