<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "VIEW.修正"; ?>
<div class="page-header">
    <h3>VIEW 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "max_juchuu_id_vws/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldMaxId" class="col-sm-2 control-label">Max</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxId")) ?>
    </div>

<label for="fieldSubCd" class="col-sm-2 control-label">伝票番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sub_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSubCd")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("max_juchuu_id_vws/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("max_juchuu_id_vws/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("max_juchuu_id_vws/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("max_juchuu_id_vws/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
