<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "VIEW.一覧"; ?>
<div class="page-header">
    <h3>VIEW 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"max_juchuu_id_vws","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["max_id","Max"],
                    ["sub_cd","伝票番号"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $max_juchuu_id_vw): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("max_juchuu_id_vws/edit/" . $max_juchuu_id_vw->id, $max_juchuu_id_vw->max_id)); ?></td>
                <td><?php echo $max_juchuu_id_vw->sub_cd ?></td>

                <td><?php echo $this->tag->linkTo(array("max_juchuu_id_vws/delete/" . $max_juchuu_id_vw->max_id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"max_juchuu_id_vws"]) ?>
