<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "VIEW.新規"; ?>
<div class="page-header">
    <h3>VIEW 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "max_juchuu_id_vws/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldMaxId" class="col-sm-2 control-label">Max</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("max_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldMaxId")) ?>
    </div>

<label for="fieldSubCd" class="col-sm-2 control-label">伝票番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sub_cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldSubCd")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
