<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "会計年度.修正"; ?>
<div class="page-header">
    <h3>会計年度 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "konnnenndo/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">年度西暦</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称和暦</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldToukiFlg" class="col-sm-2 control-label">当期フラグ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("touki_flg", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldToukiFlg")) ?>
    </div>

<label for="fieldKikanFrom" class="col-sm-2 control-label">期間開始日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(array("kikan_from", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKikanFrom")) ?>
    </div>

<label for="fieldKikanTo" class="col-sm-2 control-label">期間終了日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(array("kikan_to", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKikanTo")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("konnnenndo/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("konnnenndo/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("konnnenndo/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
