<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "会計年度.一覧"; ?>
<div class="page-header">
    <h3>年度 一覧表</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"konnnenndo","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","年度西暦"],
                    ["name","名称和暦"],
                    ["touki_flg","当期フラグ"],
                    ["kikan_from","期間開始日"],
                    ["kikan_to","期間終了日"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $konnnenndo): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("konnnenndo/edit/" . $konnnenndo->id, $konnnenndo->id)); ?></td>
                <td><?php echo $konnnenndo->cd ?></td>
                <td><?php echo $konnnenndo->name ?></td>
                <td><?php echo $konnnenndo->touki_flg ?></td>
                <td><?php echo $konnnenndo->kikan_from ?></td>
                <td><?php echo $konnnenndo->kikan_to ?></td>
                <td><?php echo $konnnenndo->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("konnnenndo/delete/" . $konnnenndo->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("konnnenndo/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("konnnenndo/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("konnnenndo/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("konnnenndo/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("konnnenndo/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
