<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $rows */
?>

<?php $title = 'プロジェクト一覧' ;?>
<?php use Phalcon\Tag; ?>
<div class="page-header">
    <h3>プロジェクト一覧</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
            <tr style="background-color: lavender;">
                <th style="text-align: center;">コード</th>
                <th style="text-align: center;">副コード</th>
                <th style="text-align: center;">名称</th>
                <th style="text-align: center;">売上予算</th>
                <th style="text-align: center;">開始日</th>
                <th style="text-align: center;">終了予定日</th>
                <th style="text-align: center;">ステータス</th>
                <th style="text-align: center;">メモ</th>
                <th style="text-align: center;">削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($rows as $row): ?>
            <?php if ($row['id'] !== ''): ?>
                <tr>
                    <td style="text-align: center;"><?php echo $this->tag->linkTo(["project_mrs/edit/" . $row['id'], $row['cd']]); ?></td>
                    <td>　</td>
                    <td><?php echo $row['name'] ?></td>
                    <td style="text-align: right;"><?php echo $row['uriage_yosan'] ?></td>
                    <td style="text-align: center;"><?php echo $row['kaishibi'] ?></td>
                    <td style="text-align: center;"><?php echo $row['shuuryoubi'] ?></td>
                    <td style="text-align: center;"><?php echo $row['status'] ?></td>
                    <td><?php echo $row['memo'] ?></td>
                    <td style="text-align: center;"><?php echo $this->tag->linkTo(["project_sub_mrs/delete/" . $row['id'], "削除"]); ?></td>
                </tr>
            <?php else: ?>
                <tr>
                    <td></td>
                    <td style="text-align: center;"><?php echo $this->tag->linkTo(["project_sub_mrs/edit/" . $row['sub_id'], $row['sub_cd']]); ?></td>
                    <td style="color: grey;"><?php echo $row['name'] ?></td>
                    <td style="text-align: right;color: grey;"><?php echo $row['uriage_yosan'] ?></td>
                    <td style="text-align: center;color: grey;"><?php echo $row['kaishibi'] ?></td>
                    <td style="text-align: center;color: grey;"><?php echo $row['shuuryoubi'] ?></td>
                    <td style="text-align: center;color: grey;"><?php echo $row['status'] ?></td>
                    <td><?php echo $row['memo'] ?></td>
                    <td style="text-align: center;"><?php echo $this->tag->linkTo(["project_sub_mrs/delete/" . $row['sub_id'], "削除"]); ?></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
