<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/**@var array $rows */
?>
<?php use Phalcon\Tag; ?>

<?php $title = 'プロジェクト実績一覧'; ?>
<div class="page-header">
    <h3>プロジェクト実績一覧</h3>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <?php
    echo $this->tag->form(
        array(
            "project_mrs/summary",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <br /><br />
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(array("cd", "style" => "width:160px;","class" => "form-control", "id" => "fieldCd","value" => "プロジェクト実績一覧","readonly" => "readonly")) ?>
            </div>
            <br /><br />
            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", KikanSiteiKbns::find(["columns" => "cd , name", "order" => "cd", "conditions" => "yobidasi_tbl='jouken_uriage_geppous'"]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom")) ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo")) ?>
            </div>
        </div>
        <div class="col-sm-2">
            <br/><br/>
            <div class="col-sm-12">
                <button id="dl-xlsx" class="btn btn-warning">EXCEL出力</button>
            </div>
            <br/><br/>
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn  btn-success")) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>
<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped">
        <thead>
            <tr style="background-color: lightgray;">
                <th style="text-align: center;">コード</th>
                <th style="text-align: center;">名称</th>
                <th style="text-align: center;">開始日</th>
                <th style="text-align: center;">終了予定日</th>
                <th style="text-align: center;">売上予算</th>
                <th style="text-align: center;">順売上額</th>
                <th style="text-align: center;">差異</th>
                <th style="text-align: center;">達成率</th>
                <th style="text-align: center;">順仕入額</th>
                <th style="text-align: center;">売上仕入差額</th>
                <th style="text-align: center;">粗利率</th>
            </tr>
        </thead>
        <tbody>
        <?php if (isset($rows)): ?>
            <?php foreach($rows as $row): ?>
                <tr style="background-color: #fffcf8;">
                    <td style="text-align: center;"><?php echo $row['cd']; ?></td>
                    <td style="text-align: center;"><?php echo $row['name']; ?></td>
                    <td style="text-align: center;"><?php echo $row['kaishibi']; ?></td>
                    <td style="text-align: center;"><?php echo $row['shuuryoubi']; ?></td>
                    <td style="text-align: right;"><?php echo number_format($row['yosan']); ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['junuriage'] < 0 ? 'red' : 'black';?>"><?php echo number_format($row['junuriage']); ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['sai'] < 0 ? 'red' : 'black';?>"><?php echo number_format($row['sai']); ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['tasseiritsu'] < 0 ? 'red' : 'black';?>"><?php echo $row['tasseiritsu']; ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['junshiire'] < 0 ? 'red' : 'black';?>"><?php echo number_format($row['junshiire']); ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['sagaku'] < 0 ? 'red' : 'black';?>"><?php echo number_format($row['sagaku']); ?></td>
                    <td style="text-align: right; color:<?php echo (int)$row['riekiritsu'] < 0 ? 'red' : 'black';?>"><?php echo $row['riekiritsu']; ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/project_mrs.js'); ?>?var=20191105"></script>
