<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "糸縮率マスタ.修正"; ?>
<div class="page-header">
    <h3>糸縮率マスタ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "h_itsyuk_mrs/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldGrtm" class="col-sm-2 control-label">原料縮み率</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("grtm", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldGrtm")) ?>
    </div>

<label for="fieldJden" class="col-sm-2 control-label">実デニール</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("jden", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldJden")) ?>
    </div>

<label for="fieldGden" class="col-sm-2 control-label">合糸後実デニール</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("gden", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldGden")) ?>
    </div>

<label for="fieldGstm" class="col-sm-2 control-label">合糸後縮み率</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("gstm", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldGstm")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("h_itsyuk_mrs/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("h_itsyuk_mrs/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("h_itsyuk_mrs/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("h_itsyuk_mrs/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
