<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "$nplural$.新規"; ?>
<div class="page-header">
    <h3>$nplural$ 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "$plural$/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

$captureFields$
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
