<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["itomei_mrs/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["itomei_mrs/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>糸種</th>
            <th>糸コード</th>
            <th>糸名１</th>
            <th>糸名２</th>
            <th>糸名３</th>
            <th>更新区分</th>
            <th>更新日付</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $itomei_mr): ?>
            <tr>
                <td><?php echo $itomei_mr->糸種 ?></td>
            <td><?php echo $itomei_mr->糸コード ?></td>
            <td><?php echo $itomei_mr->糸名１ ?></td>
            <td><?php echo $itomei_mr->糸名２ ?></td>
            <td><?php echo $itomei_mr->糸名３ ?></td>
            <td><?php echo $itomei_mr->更新区分 ?></td>
            <td><?php echo $itomei_mr->更新日付 ?></td>

                <td><?php echo $this->tag->linkTo(["itomei_mrs/edit/" . $itomei_mr->糸種, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["itomei_mrs/delete/" . $itomei_mr->糸種, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("itomei_mrs/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("itomei_mrs/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("itomei_mrs/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("itomei_mrs/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
