<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["ukeire_vws/index", "Go Back"]); ?></li>
            <li><?php echo $this->tag->linkTo(["ukeire_vws/copyfrom", "複写親"]); ?></li>
            <li><?php echo $this->tag->linkTo(["ukeire_vws/copymeisai", "複写子"]); ?></li>
            <li><a href="#" onclick="window.close()">閉じる</a></li>
            <li class="next"><?php echo $this->tag->linkTo(["ukeire_vws/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Itomei</th>
            <th>Hinmei</th>
            <th>Niukebi</th>
            <th>Shukka Of Moto</th>
            <th>Suuryou</th>
            <th>Honsuu</th>
            <th>Hakosuu</th>
            <th>Lot</th>
            <th>Kakou Of No</th>
            <th>Sasizu Of No</th>
            <th>Bikou</th>
            <th>Kishu</th>
            <th>Seihin Of Code</th>
            <th>Genryou Of Code</th>
            <th>Henkyaku</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $ukeire_vw): ?>
            <tr>
                <td><?php echo $ukeire_vw->itomei ?></td>
            <td><?php echo $ukeire_vw->hinmei ?></td>
            <td><?php echo $ukeire_vw->niukebi ?></td>
            <td><?php echo $ukeire_vw->shukka_moto ?></td>
            <td><?php echo $ukeire_vw->suuryou ?></td>
            <td><?php echo $ukeire_vw->honsuu ?></td>
            <td><?php echo $ukeire_vw->hakosuu ?></td>
            <td><?php echo $ukeire_vw->lot ?></td>
            <td><?php echo $ukeire_vw->kakou_no ?></td>
            <td><?php echo $ukeire_vw->sasizu_no ?></td>
            <td><?php echo $ukeire_vw->bikou ?></td>
            <td><?php echo $ukeire_vw->kishu ?></td>
            <td><?php echo $ukeire_vw->seihin_code ?></td>
            <td><?php echo $ukeire_vw->genryou_code ?></td>
            <td><?php echo $ukeire_vw->henkyaku ?></td>

                <td><?php echo $this->tag->linkTo(["ukeire_vws/edit/" . $ukeire_vw->itomei, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["ukeire_vws/delete/" . $ukeire_vw->itomei, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("ukeire_vws/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("ukeire_vws/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("ukeire_vws/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("ukeire_vws/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
