<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "読取専用項目制御.一覧"; ?>
<div class="page-header">
    <h3>読取専用項目制御 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"readonly_field_kbns","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["controller_cd","コントローラ"],
                    ["gamen_cd","画面"],
                    ["riyou_user_id","ユーザ"],
                    ["field_cd","項目"],
                    ["readonly_flg","読取専用フラグ"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $readonly_field_kbn): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("readonly_field_kbns/edit/" . $readonly_field_kbn->id, $readonly_field_kbn->id)); ?></td>
                <td><?php echo $readonly_field_kbn->cd ?></td>
                <td><?php echo $readonly_field_kbn->name ?></td>
                <td><?php echo $readonly_field_kbn->controller_cd ?></td>
                <td><?php echo $readonly_field_kbn->gamen_cd ?></td>
                <td><?php echo $readonly_field_kbn->riyou_user_id ?></td>
                <td><?php echo $readonly_field_kbn->field_cd ?></td>
                <td><?php echo $readonly_field_kbn->readonly_flg ?></td>
                <td><?php echo $readonly_field_kbn->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("readonly_field_kbns/delete/" . $readonly_field_kbn->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-12" align="center">
        <ul class="pagination">
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("readonly_field_kbns/index", "<<最初*11", "id"=>"F11")) ?></li>
            <li <?php if($page->current==1){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("readonly_field_kbns/index?page=" . $page->before, "<前頁F3", "id"=>"F3")) ?></li>
            <li class="active"><?php echo $this->tag->linkTo("readonly_field_kbns/index?page=" . $page->current, $page->current . "頁") ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("readonly_field_kbns/index?page=" . $page->next, " 次頁F4>", "id"=>"F4")) ?></li>
            <li <?php if($page->current==$page->total_pages){echo "class='disabled'";} ?> ><?php echo $this->tag->linkTo(array("readonly_field_kbns/index?page=" . $page->last, "(".$page->total_pages."頁)最後*12>>", "id"=>"F12")) ?></li>
        </ul>
</div>
