<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "項目幅制御.一覧"; ?>
<div class="page-header">
    <h3>項目幅制御 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"rewidth_field_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["controller_cd","コントローラ"],
                    ["gamen_cd","画面"],
                    ["riyou_user_id","ユーザーID"],
                    ["field_cd","項目"],
                    ["haba","幅"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $rewidth_field_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("rewidth_field_mrs/edit/" . $rewidth_field_mr->id, $rewidth_field_mr->id)); ?></td>
                <td><?php echo $rewidth_field_mr->cd ?></td>
                <td><?php echo $rewidth_field_mr->name ?></td>
                <td><?php echo $rewidth_field_mr->controller_cd ?></td>
                <td><?php echo $rewidth_field_mr->gamen_cd ?></td>
                <td><?php echo $rewidth_field_mr->riyou_user_id ?></td>
                <td><?php echo $rewidth_field_mr->field_cd ?></td>
                <td><?php echo $rewidth_field_mr->haba ?></td>
                <td><?php echo $rewidth_field_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("rewidth_field_mrs/delete/" . $rewidth_field_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"rewidth_field_mrs"]) ?>
