<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search uri_vws
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["uri_vws/new", "Create uri_vws"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "uri_vws/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldHiduke" class="col-sm-2 control-label">Hiduke</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hiduke", "size" => 30, "class" => "form-control", "id" => "fieldHiduke"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUriagesaki" class="col-sm-2 control-label">Uriagesaki</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uriagesaki", "size" => 30, "class" => "form-control", "id" => "fieldUriagesaki"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUriageNo" class="col-sm-2 control-label">Uriage Of No</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uriage_no", "size" => 30, "class" => "form-control", "id" => "fieldUriageNo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGyou" class="col-sm-2 control-label">Gyou</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["gyou", "size" => 30, "class" => "form-control", "id" => "fieldGyou"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHinban" class="col-sm-2 control-label">Hinban</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["hinban", "size" => 30, "class" => "form-control", "id" => "fieldHinban"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTantou" class="col-sm-2 control-label">Tantou</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tantou", "size" => 30, "class" => "form-control", "id" => "fieldTantou"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKibataNo" class="col-sm-2 control-label">Kibata Of No</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kibata_no", "size" => 30, "class" => "form-control", "id" => "fieldKibataNo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItoCode" class="col-sm-2 control-label">Ito Of Code</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ito_code", "size" => 30, "class" => "form-control", "id" => "fieldItoCode"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIraiNo" class="col-sm-2 control-label">Irai Of No</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["irai_no", "size" => 30, "class" => "form-control", "id" => "fieldIraiNo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSasizuNo" class="col-sm-2 control-label">Sasizu Of No</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sasizu_no", "size" => 30, "class" => "form-control", "id" => "fieldSasizuNo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSuuryouMeisai" class="col-sm-2 control-label">Suuryou Of Meisai</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["suuryou_meisai", "size" => 30, "class" => "form-control", "id" => "fieldSuuryouMeisai"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSuuryouGoukei" class="col-sm-2 control-label">Suuryou Of Goukei</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["suuryou_goukei", "size" => 30, "class" => "form-control", "id" => "fieldSuuryouGoukei"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanka" class="col-sm-2 control-label">Tanka</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tanka", "size" => 30, "class" => "form-control", "id" => "fieldTanka"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTanni" class="col-sm-2 control-label">Tanni</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tanni", "size" => 30, "class" => "form-control", "id" => "fieldTanni"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldItomei" class="col-sm-2 control-label">Itomei</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["itomei", "size" => 30, "class" => "form-control", "id" => "fieldItomei"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLot" class="col-sm-2 control-label">Lot</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lot", "size" => 30, "class" => "form-control", "id" => "fieldLot"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKishu" class="col-sm-2 control-label">Kishu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["kishu", "size" => 30, "class" => "form-control", "id" => "fieldKishu"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
