<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $page */
?>

<?php $title = "商品分類4参照"; ?>

<?php echo $this->getContent(); ?>

<div class="row">
	<?php $this->partial("common/modalkanni",["table_id"=>"shouhin_bunrui4","flds"=>[
		["cd","fieldCd","分類コード",14,14],["name","fieldName","分類名称",40,40]
	]]) ?>
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <thead>
            <tr>
				<?php $this->partial("common/indexsort",["flds"=>[
					["cd","コード"],
					["","選択"],
					["name","名称"],
				]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php $i = 1000; ?>
        <?php foreach ($page->items as $shouhin_bunrui4): ?>
            <tr>
	            <td align="center"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $shouhin_bunrui4->cd; ?></div></td>
                <td align='center'><?php echo "<input type='checkbox' class='returnto' id='fieldI".$i."' value='".$shouhin_bunrui4->cd."'>" ?></td>
                <td><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $shouhin_bunrui4->name ?></div></td>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>

	<div class="col-sm-2">
	    <br><button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
	</div>
	<div class="col-sm-8">
		<?php $this->partial("common/indextail",["index_or"=>"modal","table_id"=>"shouhin_bunrui4_kbns"]) ?>
    </div>
</div><!-- end class="row" -->

<div id="PgDn"></div><div id="PgUp"></div>

<script type="text/javascript">
	$(function(){
	  $('table.head_fix').floatThead({
	  	top: 0
	  });
	});

    $('.returnto').on('click change', function () {
        window.parent.fromModal($("td",$(this).closest('tr')).eq(0).text());
    });
	$('#PgUp').click(function() { //上矢キー(↑)を押したら
		if ($("#"+lastfocusin).attr('type').toLowerCase() === 'checkbox') {
			ix = -1 + $("input:checkbox").index($("#"+lastfocusin));
			if (ix >= 0) {
				$("input:checkbox").eq(ix).focus();
			} else {
				$("input").first().focus();
			}
		} else {
			$("input:checkbox").last().focus();
		}
	});

	$('#PgDn').click(function() { //下矢キー(↓)を押したら
		if ($("#"+lastfocusin).attr('type').toLowerCase() === 'checkbox') {
			ix = 1 + $("input:checkbox").index($("#"+lastfocusin));
			if (ix < $("input:checkbox").length) {
				$("input:checkbox").eq(ix).focus();
			} else {
				$("input").first().focus();
			}
		} else {
			$("input:checkbox").first().focus();
		}
	});

	$("input:checkbox").focusin(function() {
		$(this).parent().css('background-color', '#f88');
	});

	$("input:checkbox").focusout(function() {
		$(this).parent().css('background-color', '');
	});
</script>
