<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "帳票レイアウト名.一覧"; ?>
<div class="page-header">
    <h3>帳票レイアウト名 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"chouhyou_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["chouhyou_kbn_cd","帳票種別"],
                    ["chouhyou_tool_kbn_cd","帳票ツール区分"],
                    ["hinagata","雛型"],
                    ["comment","コメント"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $chouhyou_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("chouhyou_mrs/edit/" . $chouhyou_mr->id, $chouhyou_mr->id)); ?></td>
                <td><?php echo $chouhyou_mr->cd ?></td>
                <td><?php echo $chouhyou_mr->name ?></td>
                <td><?php echo $chouhyou_mr->chouhyou_kbn_cd ?></td>
                <td><?php echo $chouhyou_mr->chouhyou_tool_kbn_cd ?></td>
                <td><?php echo $chouhyou_mr->hinagata ?></td>
                <td><?php echo $chouhyou_mr->comment ?></td>
                <td><?php echo $chouhyou_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("chouhyou_mrs/delete/" . $chouhyou_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"chouhyou_mrs"]) ?>
