<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "帳票レイアウト名.新規"; ?>
<div class="page-header">
    <h3>帳票レイアウト名 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "chouhyou_mrs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 8, "maxlength" => 8, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldChouhyouKbnCd" class="col-sm-2 control-label">帳票種別</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("chouhyou_kbn_cd", ChouhyouKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 200px;", "class" => "form-control", "id" => "fieldChouhyouKbnCd")) ?>
    </div>

<label for="fieldChouhyouToolKbnCd" class="col-sm-2 control-label">帳票ツール区分</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("chouhyou_tool_kbn_cd", ChouhyouToolKbns::find(["columns" => "cd , CONCAT(cd , '=' , name) as cd_name"]), "using" => array("cd", "cd_name"), "style" => "width: 200px;", "class" => "form-control", "id" => "fieldChouhyouToolKbnCd")) ?>
    </div>

<label for="fieldHinagata" class="col-sm-2 control-label">雛型</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hinagata", "size" => 80, "maxlength" => 80, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldHinagata")) ?>
    </div>

<label for="fieldComment" class="col-sm-2 control-label">コメント</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("comment", "size" => 40, "maxlength" => 40, "style" => "width: 516px;", "class" => "form-control", "id" => "fieldComment")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn btn-lg btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
