<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "VIEW.検索"; ?>
<div class="page-header">
    <h3>VIEW 検索条件</h3>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "shiiregaku_vws/index",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldShiireDtId" class="col-sm-2 control-label">仕入データID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiire_dt_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldShiireDtId")) ?>
    </div>

<label for="fieldKingaku" class="col-sm-2 control-label">Kingaku</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kingaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKingaku")) ?>
    </div>

<label for="fieldKesikomiGaku" class="col-sm-2 control-label">Kesikomi Of Gaku</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kesikomi_gaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKesikomiGaku")) ?>
    </div>

<label for="fieldShiiresakiMrCd" class="col-sm-2 control-label">仕入先</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiiresaki_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldShiiresakiMrCd")) ?>
    </div>

<label for="fieldShiirebi" class="col-sm-2 control-label">仕入日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("shiirebi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldShiirebi")) ?>
    </div>

<label for="fieldCd" class="col-sm-2 control-label">伝票番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
