<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "加工場調整事項データ.一覧"; ?>
<div class="page-header">
    <h3>加工場調整事項データ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"kakoujou_chousei_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","行番"],
                    ["name","内容"],
                    ["hacchuu_dt_id","発注書キー"],
                    ["hiduke","日付"],
                    ["tantou_mr_cd","連絡者コード"],
                    ["kakunin_kbn","確認欄区分"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $kakoujou_chousei_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("kakoujou_chousei_dts/edit/" . $kakoujou_chousei_dt->id, $kakoujou_chousei_dt->id)); ?></td>
                <td><?php echo $kakoujou_chousei_dt->cd ?></td>
                <td><?php echo $kakoujou_chousei_dt->name ?></td>
                <td><?php echo $kakoujou_chousei_dt->hacchuu_dt_id ?></td>
                <td><?php echo $kakoujou_chousei_dt->hiduke ?></td>
                <td><?php echo $kakoujou_chousei_dt->tantou_mr_cd ?></td>
                <td><?php echo $kakoujou_chousei_dt->kakunin_kbn ?></td>
                <td><?php echo $kakoujou_chousei_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("kakoujou_chousei_dts/delete/" . $kakoujou_chousei_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"kakoujou_chousei_dts"]) ?>
