<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = '出金.一覧'; ?>

<?php echo $this->getContent(); ?>

<div class="row">
	<?php $this->partial("common/modalkanni",["table_id"=>"shukkin_dts","flds"=>[
		["cd","fieldCd","伝票番号",14,14],["name","fieldName","摘要",24,24]
	]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
				<?php $this->partial("common/indexsort",["flds"=>[
					["cd","伝票番号"],
					["name","摘要"],
					["shukkinbi","出金日"],
                    ["shiiresaki_mr_cd","仕入先"],
					["tantou_mr_cd","担当者"],
					["","出金区分1"],
					["","出金額1"],
					["zenkai_kesikomi_gaku","前回消込額"],
				]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shukkin_dt): ?>
            <tr>
                <td align="center" id="<?php echo $shukkin_dt->id; ?>"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $shukkin_dt->cd ?></td>
                <td><?php echo $shukkin_dt->name ?></td>
                <td align="center"><?php echo $shukkin_dt->shukkinbi ?></td>
                <td><?php echo $shukkin_dt->shiiresaki_mr_cd."=".$shukkin_dt->SeikyuusakiMrs->name ?></td>
                <td><?php echo $shukkin_dt->tantou_mr_cd."=".$shukkin_dt->TantouMrs->name ?></td>
                <td><?php echo $shukkin_dt->NyuukinMeisaiDts[0]->shukkin_kbn_cd."=".$shukkin_dt->NyuukinMeisaiDts[0]->NyuukinKbns->name ?></td>
                <td align="right"><?php echo number_format($shukkin_dt->NyuukinMeisaiDts[0]->kingaku) ?></td>
                <td align="right"><?php echo number_format($shukkin_dt->zenkai_kesikomi_gaku) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["index_or"=>"modal", "table_id"=>"shukkin_dts"]) ?>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
