<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "出金.新規"; ?>
<div class="page-header">
    <h3>出金伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "shukkin_dts/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">

    <?php $this->partial('shukkin_dts/inputfields'); ?>

    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-lg btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/shukkin_dts.js'); ?>?var=20210210"></script>
