<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["shime_tankas_dts/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["shime_tankas_dts/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Nyuushukkoym</th>
            <th>Shouhin Of Mr Of Cd</th>
            <th>Zengetsu Of Tanka</th>
            <th>Tougetsu Of Tanka</th>
            <th>Tanka Of Kbn</th>
            <th>Zaiko Of Hyouka Of Kbn Of Cd</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shime_tankas_dt): ?>
            <tr>
                <td><?php echo $shime_tankas_dt->id ?></td>
            <td><?php echo $shime_tankas_dt->nyuushukkoym ?></td>
            <td><?php echo $shime_tankas_dt->shouhin_mr_cd ?></td>
            <td><?php echo $shime_tankas_dt->zengetsu_tanka ?></td>
            <td><?php echo $shime_tankas_dt->tougetsu_tanka ?></td>
            <td><?php echo $shime_tankas_dt->tanka_kbn ?></td>
            <td><?php echo $shime_tankas_dt->zaiko_hyouka_kbn_cd ?></td>

                <td><?php echo $this->tag->linkTo(["shime_tankas_dts/edit/" . $shime_tankas_dt->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["shime_tankas_dts/delete/" . $shime_tankas_dt->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["shime_tankas_dts/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["shime_tankas_dts/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["shime_tankas_dts/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["shime_tankas_dts/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
