<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "仕入先締内容データ.一覧"; ?>
<div class="page-header">
    <h3>仕入先締内容データ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"shiiresaki_sime_naiyou_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","順"],
                    ["name","メモ"],
                    ["shiharai_kbn_cd","支払区分"],
                    ["kingaku","金額"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $shiiresaki_sime_naiyou_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("shiiresaki_sime_naiyou_dts/edit/" . $shiiresaki_sime_naiyou_dt->id, $shiiresaki_sime_naiyou_dt->id)); ?></td>
                <td><?php echo $shiiresaki_sime_naiyou_dt->cd ?></td>
                <td><?php echo $shiiresaki_sime_naiyou_dt->name ?></td>
                <td><?php echo $shiiresaki_sime_naiyou_dt->shiharai_kbn_cd ?></td>
                <td><?php echo $shiiresaki_sime_naiyou_dt->kingaku ?></td>
                <td><?php echo $shiiresaki_sime_naiyou_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("shiiresaki_sime_naiyou_dts/delete/" . $shiiresaki_sime_naiyou_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"shiiresaki_sime_naiyou_dts"]) ?>
