<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "織設計工費算出マスタ.一覧"; ?>
<div class="page-header">
    <h3>織設計工費算出マスタ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"h_kohisan_mrs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["kono","工程番号　　　　"],
                    ["gyou","条件行番　　　　"],
                    ["kote","工程名　　　　　"],
                    ["komk","項目名　　　　　"],
                    ["levl","原料レベル　　　"],
                    ["hika","比較記号　　　　"],
                    ["atai","比較値　　　　　"],
                    ["keta","比較桁数　　　　"],
                    ["andk","アンド　　　　　"],
                    ["errf","エラーフラグ　　"],
                    ["fugo","加算符号　　　　"],
                    ["kohi","工費係数　　　　"],
                    ["expt","名前例外区分　　"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $h_kohisan_mr): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("h_kohisan_mrs/edit/" . $h_kohisan_mr->id, $h_kohisan_mr->id)); ?></td>
                <td><?php echo $h_kohisan_mr->cd ?></td>
                <td><?php echo $h_kohisan_mr->name ?></td>
                <td><?php echo $h_kohisan_mr->kono ?></td>
                <td><?php echo $h_kohisan_mr->gyou ?></td>
                <td><?php echo $h_kohisan_mr->kote ?></td>
                <td><?php echo $h_kohisan_mr->komk ?></td>
                <td><?php echo $h_kohisan_mr->levl ?></td>
                <td><?php echo $h_kohisan_mr->hika ?></td>
                <td><?php echo $h_kohisan_mr->atai ?></td>
                <td><?php echo $h_kohisan_mr->keta ?></td>
                <td><?php echo $h_kohisan_mr->andk ?></td>
                <td><?php echo $h_kohisan_mr->errf ?></td>
                <td><?php echo $h_kohisan_mr->fugo ?></td>
                <td><?php echo $h_kohisan_mr->kohi ?></td>
                <td><?php echo $h_kohisan_mr->expt ?></td>
                <td><?php echo $h_kohisan_mr->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("h_kohisan_mrs/delete/" . $h_kohisan_mr->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"h_kohisan_mrs"]) ?>
