<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "順序区分.新規"; ?>
<div class="page-header">
    <h3>順序区分 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "junjo_kbns/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">表示順</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 8, "maxlength" => 8, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldTablecd" class="col-sm-2 control-label">テーブルコード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tablecd", "size" => 80, "maxlength" => 100, "style" => "width: 996px;", "class" => "form-control", "id" => "fieldTablecd")) ?>
    </div>

<label for="fieldYobidasiTbl" class="col-sm-2 control-label">呼出条件テーブル</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("yobidasi_tbl", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldYobidasiTbl")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行*12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
