<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "コントローラーログ.一覧"; ?>
<div class="page-header">
    <h3>コントローラーログ 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"ctrl_logs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","コード"],
                    ["name","名称"],
                    ["updated","更新日時"],
                    ["kousin_user_id","更新者"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $ctrl_log): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("ctrl_logs/edit/" . $ctrl_log->id, $ctrl_log->id)); ?></td>
                <td><?php echo $ctrl_log->cd ?></td>
                <td><?php echo $ctrl_log->name ?></td>
                <td><?php echo $ctrl_log->updated ?></td>
                <td><?php echo $ctrl_log->KousinUsers->name ?></td>

                <td><?php echo $this->tag->linkTo(array("ctrl_logs/delete/" . $ctrl_log->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"ctrl_logs"]) ?>
