<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "得意先締データ.修正"; ?>
<div class="page-header">
    <h3>得意先締データ 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "tokuisaki_sime_dts/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">請求書番号</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">名称</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 24, "maxlength" => 24, "style" => "width: 324px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldTokuisakiMrCd" class="col-sm-2 control-label">得意先ＣＤ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("tokuisaki_mr_cd", "size" => 14, "maxlength" => 14, "style" => "width: 204px;", "class" => "form-control", "id" => "fieldTokuisakiMrCd")) ?>
    </div>

<label for="fieldSimeHiduke" class="col-sm-2 control-label">締日付</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sime_hiduke", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldSimeHiduke")) ?>
    </div>

<label for="fieldNendo" class="col-sm-2 control-label">年度</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nendo", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldNendo")) ?>
    </div>

<label for="fieldKaishuuYoteibi" class="col-sm-2 control-label">回収予定日</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kaishuu_yoteibi", "type" => "date", "size" => 10, "maxlength" => 10, "style" => "width: 132px;", "class" => "form-control", "id" => "fieldKaishuuYoteibi")) ?>
    </div>

<label for="fieldZenkaiSeikyuugaku" class="col-sm-2 control-label">前回請求額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("zenkai_seikyuugaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldZenkaiSeikyuugaku")) ?>
    </div>

<label for="fieldNyuukingaku" class="col-sm-2 control-label">入金額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nyuukingaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldNyuukingaku")) ?>
    </div>

<label for="fieldKurikosigaku" class="col-sm-2 control-label">繰越金額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kurikosigaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKurikosigaku"
        										"readonly" => "readonly", "value" => $this->tag->getValue("zenkai_seikyuugaku") - $this->tag->getValue("nyuukingaku"))) ?>
    </div>

<label for="fieldKonkaiUriagegaku" class="col-sm-2 control-label">今回売上額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("konkai_uriagegaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKonkaiUriagegaku")) ?>
    </div>

<label for="fieldUtiShouhizeigaku" class="col-sm-2 control-label">内消費税額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uti_shouhizeigaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldUtiShouhizeigaku")) ?>
    </div>

<label for="fieldKonkaiSeikyuugaku" class="col-sm-2 control-label">今回請求額</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("konkai_seikyuugaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKonkaiSeikyuugaku"
        										"readonly" => "readonly", "value" => $this->tag->getValue("zenkai_seikyuugaku") - $this->tag->getValue("nyuukingaku") + $this->tag->getValue("konkai_uriagegaku"))) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("tokuisaki_sime_dts/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("tokuisaki_sime_dts/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("登録F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("tokuisaki_sime_dts/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("tokuisaki_sime_dts/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
