<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var array $rows
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = '支払締切履歴'; ?>

<?php echo $this->getContent(); ?>

<?php
if (!isset($rows)) {
    echo '<h3>締切履歴がありません。</h3>';
    exit;
}
?>
<div class="row">
    <div class="page-header">
        <h3>仕入先: <?php echo $rows[0]['name'] ?>(<?php echo $this->request->getQuery('tokuisaki_mr_cd');?>)</h3>
    </div>

    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr bgcolor="Lavender">
            <th style="text-align:center;">請求書番号</th>
            <th style="text-align:center;">年度</th>
            <th style="text-align:center;">締日付</th>
            <th style="text-align:center;">回収予定日</th>
            <th style="text-align:center;">前回請求額</th>
            <th style="text-align:center;">入金額</th>
            <th style="text-align:center;">繰越金額</th>
            <th style="text-align:center;">今回売上額</th>
            <th style="text-align:center;">今回請求額</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($rows as $row): ?>
            <tr>
                <td style="text-align:right;"><?php if (isset($row['cd'])) echo $row['cd'] ?></td>
                <td style="text-align:center;"><?php if (isset($row['nendo'])) echo $row['nendo'] ?></td>
                <td style="text-align:center;"><?php if (isset($row['sime_hiduke'])) echo $row['sime_hiduke'] ?></td>
                <td style="text-align:center;"><?php if (isset($row['kaishuu_yoteibi'])) echo $row['kaishuu_yoteibi'] ?></td>
                <td style="text-align:right;color: <?php echo (int)$row['zenkai_seikyuugaku'] > -0.1 ? 'black' : 'red'; ?>"><?php if (isset($row['zenkai_seikyuugaku'])) echo number_format($row['zenkai_seikyuugaku']) ?></td>
                <td style="text-align:right;color: <?php echo (int)$row['zenkai_seikyuugaku'] > -0.1 ? 'black' : 'red'; ?>"><?php if (isset($row['nyuukingaku'])) echo number_format($row['nyuukingaku']) ?></td>
                <td style="text-align:right;color: <?php echo ((int)$row['zenkai_seikyuugaku'] - (int)$row['nyuukingaku']) > -0.1 ? 'black' : 'red'; ?>"><?php if (isset($row['zenkai_seikyuugaku'])) echo number_format($row['zenkai_seikyuugaku'] - $row['nyuukingaku']) ?></td>
                <td style="text-align:right;color: <?php echo (int)$row['konkai_uriagegaku'] > -0.1 ? 'black' : 'red'; ?>"><?php if (isset($row['konkai_uriagegaku'])) echo number_format($row['konkai_uriagegaku']) ?></td>
                <td style="text-align:right;color: <?php echo ((int)$row['zenkai_seikyuugaku'] - (int)$row['nyuukingaku'] + (int)$row['konkai_uriagegaku']) > -0.1 ? 'black' : 'red'; ?>"><?php if (isset($row['zenkai_seikyuugaku'])) echo number_format($row['zenkai_seikyuugaku'] - $row['nyuukingaku'] + $row['konkai_uriagegaku']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
