<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "VIEW.修正"; ?>
<div class="page-header">
    <h3>VIEW 修正</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "uriagegaku_vws/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldUriageDtId" class="col-sm-2 control-label">売上データID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("uriage_dt_id", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldUriageDtId")) ?>
    </div>

<label for="fieldKingaku" class="col-sm-2 control-label">Kingaku</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kingaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKingaku")) ?>
    </div>

<label for="fieldKesikomiGaku" class="col-sm-2 control-label">Kesikomi Of Gaku</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("kesikomi_gaku", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldKesikomiGaku")) ?>
    </div>

</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("uriagegaku_vws/prev/".$id, "前へF3", "id" => "F3", "class" => "btn btn-default")) ?>
        <?php echo $this->tag->linkTo(array("uriagegaku_vws/next/".$id, "次へF4", "id" => "F4", "class" => "btn btn-info")) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
    <div class="col-sm-4">
        <?php echo $this->tag->linkTo(array("uriagegaku_vws/new/".$id, "複写で新規へ", "class" => "btn btn-warning")) ?>
    </div>
    <div class="col-sm-2">
        <?php echo $this->tag->linkTo(array("uriagegaku_vws/delete/".$id, "削除", "class" => "btn btn-danger", "onclick" => 'return confirm("削除してよいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
