<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "発注データ.一覧"; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/modalkanni",["table_id"=>"hacchuu_dts","flds"=>[
        ["cd","fieldCd","コード",14,14],["tekiyou","fieldTekiyou","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["cd","発注番号(選択)"],
                    ["tekiyou","摘要"],
                    ["hacchuubi","発注日"],
                    ["nounyuu_kijitu","納入期日"],
                    ["shiiresaki_mr_cd","仕入先"],
                    ["tantou_mr_cd","担当者"],
                    ["","商品1"],
                    ["","数量1"],
                ]]) ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $hacchuu_dt): ?>
            <tr>
                <td align="center"><div class="returnto" data-dismiss="modal" style="cursor: pointer;"><?php echo $hacchuu_dt->cd; ?></div></td>
                <td><?php echo $hacchuu_dt->tekiyou ?></td>
                <td align="center"><?php echo $hacchuu_dt->hacchuubi ?></td>
                <td align="center"><?php echo $hacchuu_dt->nounyuu_kijitu ?></td>
                <td><?php echo $hacchuu_dt->ShiiresakiMrs->name ?></td>
                <td><?php echo $hacchuu_dt->TantouMrs->name ?></td>
                <td><?php echo $hacchuu_dt->HacchuuMeisaiDts[0]->shouhin_mr_cd ?></td>
                <td align="right"><?php echo $hacchuu_dt->HacchuuMeisaiDts[0]->suuryou.$hacchuu_dt->HacchuuMeisaiDts[0]->TanniMrs->name ?></td>

                <td align="center"><?php echo $this->tag->linkTo(array("hacchuu_dts/edit/" . $hacchuu_dt->id, "別タブ", "target"=>"_blank")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["index_or"=>"modal", "table_id"=>"hacchuu_dts"]) ?>

<div class="col-sm-2">
    <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal" onclick="window.parent.fromModal();">中止</button>
</div>
<script type="text/javascript">
	$('.returnto').click(function () {//alert($(this).text());
		window.parent.fromModal($(this).text());
	});
</script>
