<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
//@TODO 作成中
?>
<!--Add By Yuusuke Nishiyama 2019/8/30 -->
<?php use Phalcon\Tag; ?>

<?php $title = 'レポ.在庫順位表'; ?>
<div class="page-header">
    <h3>在庫順位表</h3>
</div>

<?php echo $this->getContent(); ?>
<?php// var_dump($_POST); //debug ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "report_zaiko_vws/juni",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
<!--                --><?php //echo $this->tag->selectStatic(array("cd", $joukens, "style" => "width: 260px;", "class" => "form-control", "id" => "fieldCd")) ?>
                <?php echo $this->tag->selectStatic(array("cd", array("0" => "在庫推移"), "style" => "width: 130px;", "class" => "form-control", "id" => "fieldCd")) ?>
            </div>
            <br/>
            <br>
            <label for="fieldHyoujiKbn" class="col-sm-2 control-label">集計</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("hyouji_kbn", array("0" => "在庫数量"), "style" => "width: 130px;", "class" => "form-control", "id" => "fieldHyoujiKbn")) ?>
            </div>

<!--            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>-->
<!--            <div class="col-sm-3">-->
<!--                --><?php //echo $this->tag->select(array("kikan_sitei_kbn_cd", KikanSiteiKbns::find(["columns" => "cd , name", "order" => "cd", "conditions" => "yobidasi_tbl='jouken_uriage_geppous'"]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
<!--            </div>-->
<!--            <div class="col-sm-3">-->
<!--                --><?php ////echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom", "readonly" => "readonly")) ?>
<!--            </div>-->
<!--            -->
<!--            <div class="col-sm-3">-->
<!--                --><?php //echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo", "readonly" => "readonly")) ?>
<!--            </div>-->

        </div>
        <div class="col-sm-2">
            <?php /* 取引区分別     */
            echo $this->tag->hiddenField("torihiki_kbn_betu_flg") ?>
            <?php /* 順序区分コード */
            echo $this->tag->hiddenField("junjo_kbn_cd") ?>
            <?php /* 順序区分テーブル */
            echo $this->tag->hiddenField("junjo_kbn_table") ?>
            <?php /* 降順フラグ     */
            echo $this->tag->hiddenField("koujun_flg") ?>
            <?php /* 範囲自         */
            echo $this->tag->hiddenField("hanni_from") ?>
            <?php /* 範囲自名       */
            echo $this->tag->hiddenField("hanni_from_name") ?>
            <?php /* 範囲至         */
            echo $this->tag->hiddenField("hanni_to") ?>
            <?php /* 範囲至名       */
            echo $this->tag->hiddenField("hanni_to_name") ?>
            <?php /* 税込みフラグ   */
            echo $this->tag->hiddenField("zeikomi_flg") ?>
            <?php /* 明細行表示フラ */
            echo $this->tag->hiddenField("meisaigyou_flg") ?>
            <?php /* 合計行表示フラ */
            echo $this->tag->hiddenField("goukeigyou_flg") ?>
            <?php /* 自入力分フラグ */
            echo $this->tag->hiddenField("jinyuuryoku_flg") ?>
            <?php /* 期間内取引有フ */
            echo $this->tag->hiddenField("torihikiari_flg") ?>
            <?php /* 期間内取引無フ */
            echo $this->tag->hiddenField("torihikinasi_flg") ?>
            <?php /* その他計フラグ */
            echo $this->tag->hiddenField("hokakei_flg") ?>
            <?php /* 前年比較フラグ */
            echo $this->tag->hiddenField("zennnen_flg") ?>

            <div class="col-sm-12">
                <button class="btn btn-warning" onclick="modalstart(jouken_shiire_modal);return false;">条件設定>8
                </button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <button id="dl-xlsx" class="btn btn-warning">EXCEL出力</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn  btn-success")) ?>
            </div>
        </div>
    </div><!-- form-group -->
    <?php echo $this->tag->endForm(); ?>
</div>
<?php //var_dump($_POST); //debug?>
<?php if (!isset($_POST['hyouji_kbn'])) $_POST['hyouji_kbn'] = 0; ?>
<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <?php $total = 0; ?>
        <thead>
        <tr bgcolor="White">
            <!-- header1行目は小計 -->
            <th style="text-align:center;background-color: #fef6fe;"></th>
            <th style="text-align:center;background-color: #fef6fe;"></th>
            <th style="text-align:center;background-color: #fef6fe;font-weight: bold;">列計　>></th>
            <th style="text-align:right;"><?php echo number_format($rows[0]['suuryou1']); ?></th>
            <th style="text-align:right;"></th>
            <th style="text-align:right;"></th>
            <th style="text-align:right;"></th>
            <th style="text-align:right;"><?php echo number_format($rows[0]['suuryou2'],2); ?></th>
            <th style="text-align:right;"></th>
            <th style="text-align:right;"></th>
            <th style="text-align:right;"></th>
        </tr>
        <tr bgcolor="Lavender">
            <th style="text-align: center;">順位</th>
            <th style="text-align:center;">集計キー</th>
            <th style="text-align:center;">キー名称</th>
            <th style="text-align:center;">在庫数</th>
            <th style="text-align:center;">構成比</th>
            <th style="text-align:center;">累計数</th>
            <th style="text-align:center;">累計比</th>
            <th style="text-align:center;">在庫量</th>
            <th style="text-align:center;">構成比</th>
            <th style="text-align:center;">累計量</th>
            <th style="text-align:center;">累計比</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $gyou = 1;
        $i = 0;
        $ruikei = 0;
        $ruikeihi = 0;
        $ruikei2 = 0;
        $ruikeihi2 = 0;
        ?>
        <?php foreach ($rows as $row): ?>
            <?php
            //1週目は総計行の為飛ばす
            if ($i === 0) {
                $i++;
                continue;
            }
            ?>
            <tr>
                <td style="text-align: center;"><?php echo $gyou; ?></td>
                <td style="text-align:center;"><?php if (!isset($row[$i]['集計キー'])) echo $row['集計キー']; ?></td>
                <td style="text-align:left;"><?php if (!isset($row[$i]['キー名称'])) echo $row['キー名称']; ?></td>
                <td style="text-align:right;"><?php if (!isset($row[$i]['suuryou1'])) echo number_format($row['suuryou1']); ?></td>
                <?php $ruikei += (float)$row['suuryou1']; ?>
                <td style="text-align:right;"><?php
                    if (!isset($row[$i]['suuryou1'])) {
                        echo number_format((float)$row['suuryou1'] / (float)$rows[0]['suuryou1'] * 100,2);
                    }
                    $ruikeihi += (float)$row['suuryou1'] / (float)$rows[0]['suuryou1'] * 100
                    ?></td>
                <td style="text-align:right;"><?php echo number_format($ruikei); ?></td>
                <td style="text-align:right;"><?php echo number_format($ruikeihi,2); ?></td>
                <td style="text-align:right;"><?php if (!isset($row[$i]['suuryou2'])) echo number_format($row['suuryou2'],2); ?></td>
                <?php $ruikei2 += (float)$row['suuryou2']; ?>
                <td style="text-align:right;"><?php
                    if (!isset($row[$i]['suuryou2'])) {
                        echo number_format((float)$row['suuryou2'] / (float)$rows[0]['suuryou2'] * 100,2);
                    }
                    $ruikeihi2 += (float)$row['suuryou2'] / (float)$rows[0]['suuryou2'] * 100
                    ?></td>
                <td style="text-align:right;"><?php echo number_format($ruikei2,2); ?></td>
                <td style="text-align:right;"><?php echo number_format($ruikeihi2,2); ?></td>
            </tr>
            <?php
            $i++;
            $gyou++;
            ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="col-sm-2">
        <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal"
                onclick="window.parent.fromModal();">中止
        </button>
    </div>
</div>
<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle" style="width:900px; height:500px;">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        在庫順位表条件設定
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    var jouken_shiire_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_shiire_junis/ajaxGet') ?>";
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
    var junjo_kbns_ajaxHanni = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('junjo_kbns/ajaxHanni') ?>";
    var jouken_shiire_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_shiire_junis/modal') ?>";
    var jouken_flds = ['torihiki_kbn_betu_flg'
        , 'junjo_kbn_cd'
        , 'torihiki_kbn_cd'
        , 'koujun_flg'
        , 'hanni_from'
        , 'hanni_from_name'
        , 'hanni_to'
        , 'hanni_to_name'
        , 'zeikomi_flg'
        , 'meisaigyou_flg'
        , 'goukeigyou_flg'
        , 'torihikiari_flg'
        , 'torihikinasi_flg'
        , 'hokakei_flg'
        , 'zennnen_flg'
    ];
</script>
<script>
    $(function () {
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/report_shiire_junis.js'); ?>?var=20191105"></script>
