<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
//debug
ini_set('display_errors', 'On');
error_reporting(E_ALL | E_NOTICE);
?>
<?php use Phalcon\Tag; ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.blue.min.css">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
<script>
    $(document).ready(function () {
            $("#zaiko_table").tablesorter();
        }
    );
</script>
<?php $title = '倉庫在庫一覧'; ?>
<div class="page-header">
    <h2>倉庫別在庫一覧</h2>
</div>
<?php echo $this->getContent(); ?>

<?php
$result_suu1 = 0.0; //総計
$result_suu2 = 0.0; //総計
?>
<div class="row">
    <table id="zaiko_table" class="tablesorter tablesorter-blue head_fix">
        <thead>
        <tr>
            <th nowrap style="text-align:center;">倉庫コード</th>
            <th nowrap style="text-align:center;">倉庫名称</th>
            <th nowrap style="text-align:center;">在庫数量1</th>
            <th nowrap style="text-align:center;">単位1</th>
            <th nowrap style="text-align:center;">在庫数量2</th>
            <th nowrap style="text-align:center;">単位2</th>
        </tr>
        </thead>
        <?php foreach ($rows as $row): ?>
            <tr>
                <td nowrap class="zoom_nyuushukko souko_mr_cd"
                    style="cursor:pointer;text-align:center;color:blue;"><?php echo $row['souko_mr_cd']; ?></td>
                <td nowrap style="text-align:left;"><?php echo $row['souko_name']; ?></td>
                <?php
                if ((round((float)$row['zaikoryou1'],4)) < 0.00) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td nowrap
                    style="text-align:right;color:<?php echo $color; ?>;"><?php echo number_format(round((float)$row['zaikoryou1'],4), 2); ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['tanni1']; ?></td>
                <?php
                if ((round((float)$row['zaikoryou2'],4)) < 0.00) {
                    $color1 = 'red';
                } else {
                    $color1 = 'black';
                }
                ?>
                <td nowrap
                    style="text-align:right;color:<?php echo $color1; ?>;"><?php echo number_format(round((float)$row['zaikoryou2'],4), 2); ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['tanni2']; ?></td>
                <?php
                $result_suu1 += round((float)$row['zaikoryou1'],4); //総計
                $result_suu2 += round((float)$row['zaikoryou2'],4); //総計
                ?>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td nowrap style="text-align:right;background-color: #FFFFEF;!important;font-weight: bold;">総計：</td>
            <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
            <td nowrap style="text-align:right;background-color: #FFFFEF;!important;font-weight: bold;"><?php echo number_format(round($result_suu1,4),2); ?></td>
            <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
            <td nowrap style="text-align:right;background-color: #FFFFEF;!important;font-weight: bold;"><?php echo number_format(round($result_suu2,4),2); ?></td>
            <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        </tr>
    </table>

    <!-- 移動先へのsubmit_form -->
    <?php echo $this->tag->form(array("report_zaiko_vws/souko_shouhin_lot", "id" => "souko_shouhin_lot", "method" => "post", "target" => "_blank")); ?>
    <input type='hidden' name="souko_cd" id="souko_cd"/>
    <input type="hidden" name="souko_name" id="souko_name"/>
    <?php echo $this->tag->endForm(); ?>

    <script type="text/javascript">
        $(function () {
            $('table.head_fix').floatThead({
                top: 50
            });
        });
    </script>

    <script type="text/javascript"
            src="<?php echo $this->url->get('js/views/souko_zaiko.js'); ?>?var=20160723"></script>
