<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL | E_NOTICE);
?>
<?php use Phalcon\Tag; ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.blue.min.css">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
<script>
    $(document).ready(function () {
            $("#zaiko_table").tablesorter();
        }
    );
</script>
<?php $title = $souko_name .' 在庫一覧'; ?>
<div class="page-header">
    <h2><?php echo $souko_name;?> 倉庫別在庫一覧</h2>
</div>
<?php echo $this->getContent(); ?>

<?php
$result_suu1 = 0.0; //総計
$result_suu2 = 0.0; //総計
?>
<div class="row">
    <table id="zaiko_table" class="tablesorter tablesorter-blue head_fix">
        <thead>
        <tr>
            <th nowrap style="text-align:center">No</th>
            <th nowrap style="text-align:center">倉庫コード</th>
            <th nowrap style="text-align:center">倉庫名</th>
            <th nowrap style="text-align:center;">商品コード</th>
            <th nowrap style="text-align:center;">商品名称</th>
            <th nowrap style="text-align:center;">ロット</th>
            <th nowrap style="text-align:center;">色番</th>
            <th nowrap style="text-align:center;">色名</th>
            <th nowrap style="text-align:center;">個別コード</th>
            <th nowrap style="text-align:center;">品質</th>
            <th nowrap style="text-align:center;">在庫数量1</th>
            <th nowrap style="text-align:center;">単位1</th>
            <th nowrap style="text-align:center;">在庫数量2</th>
            <th nowrap style="text-align:center;">単位2</th>
            <th nowrap style="text-align:center;">最終出入日</th>
        </tr>
        </thead>
        <?php $i = 1; ?>
        <?php foreach ($rows as $row): ?>
            <tr>
                <td nowrap style="text-align: center"><?php echo $i; ?></td>
                <td nowrap style="text-align: center"><?php echo $row['souko_mr_cd']; ?></td>
                <td nowrap style="text-align: center"><?php echo $row['souko_name']; ?></td>
                <td nowrap class="zoom_nyuushukko shouhin_cd" style="text-align:center;cursor: pointer;color:blue;"><?php echo $row['shouhin_mr_cd']; ?></td>
                <td nowrap style="text-align:left;"><?php echo $row['shouhin_name']; ?></td>
                <td nowrap style="text-align:left;"><?php echo $row['lot']; ?></td>
                <td nowrap style="text-align:left;"><?php echo $row['iro']; ?></td>
                <td nowrap style="text-align:left;"><?php echo $row['iromei']; ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['kobetucd']; ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['hinshitu_name']; ?></td>
                <?php
                if ((round((float)$row['zaikoryou1'],3)) < 0.00) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td nowrap style="text-align:right;color:<?php echo $color; ?>;"><?php echo number_format(round($row['zaikoryou1'],3),2); ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['tanni1']; ?></td>
                <?php
                if ((round((float)$row['zaikoryou2'],3)) < 0.00) {
                    $color1 = 'red';
                } else {
                    $color1 = 'black';
                }
                ?>
                <td nowrap style="text-align:right;color:<?php echo $color1; ?>;"><?php echo number_format(round($row['zaikoryou2'],3),2); ?></td>
                <td nowrap style="text-align:center;"><?php echo $row['tanni2']; ?></td>
                <td nowrap style="text-align:right;"><?php echo $row['saisyuudeiri']; ?></td>
                <?php
                $result_suu1 += round((float)$row['zaikoryou1'],3); //総計
                $result_suu2 += round((float)$row['zaikoryou2'],3); //総計
                ?>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        <td nowrap style="text-align: right;background-color: #FFFFEF;!important;font-weight: bold;">総計：</td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="text-align:right;background-color: #FFFFEF;!important;font-weight: bold;"><?php echo number_format($result_suu1,2); ?></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="text-align:right;background-color: #FFFFEF;!important;font-weight: bold;"><?php echo number_format($result_suu2,2); ?></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
        <td nowrap style="background-color: #FFFFEF;!important;font-weight: bold;"></td>
    </table>
    <!--モーダル部分-->
    <div id="iframe-bg" class="bgStyle"></div>
    <div id="iframe-wrap" class="wrapStyle">
        <div class="modal-header" style="padding: 5px; background-color: #ddd;">
            <span id="iframe-title"></span>
            <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
        </div>
        <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
        </div>
    </div>

    <script>
        var shouhin_lot_modal = "<?php echo '//'.$_SERVER['SERVER_NAME'].$this->url->get('report_zaiko_vws/shouhin_lot_modal') ?>";
    </script>
    <script>
        $(function(){
            $('table.head_fix').floatThead({
                top: 50
            });
        });
    </script>
    <script
            src="<?php echo $this->url->get('js/views/shouhin_lot_modal.js'); ?>"></script>
