<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<!--Add By Yuusuke Nishiyama 2019/8/29 -->
<?php use Phalcon\Tag; ?>

<?php $title = 'レポ.在庫入出庫推移表'; ?>
<div class="page-header">
    <h3>在庫(入出庫)推移</h3>
</div>
<?php echo $this->getContent(); ?>
<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "report_zaiko_vws/suii",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("cd", $joukens, "style" => "width: 260px;", "class" => "form-control", "id" => "fieldCd")) ?>
            </div>

            <label for="fieldHyoujiKbn" class="col-sm-2 control-label">集計</label>
            <div class="col-sm-10">
                <!--在庫推移のロジックが作れれば、"0" => "在庫数","1"=>"在庫量",を選択肢に入れる-->
                <?php echo $this->tag->selectStatic(array("hyouji_kbn", array("0" => "在庫数","1"=>"在庫量","2" => "入出庫数", "3" => "入出庫量"), "style" => "width: 130px;", "class" => "form-control", "id" => "fieldHyoujiKbn")) ?>
            </div>

            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", Konnnenndo::find(["columns" => "cd , name", "order" => "cd",]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom", "readonly" => "readonly")) ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo", "readonly" => "readonly")) ?>
            </div>

        </div>
        <div class="col-sm-2">
            <?php /* 取引区分別     */
            echo $this->tag->hiddenField("torihiki_kbn_betu_flg") ?>
            <?php /* 順序区分コード */
            echo $this->tag->hiddenField("junjo_kbn_cd") ?>
            <?php /* 順序区分テーブル */
            echo $this->tag->hiddenField("junjo_kbn_table") ?>
            <?php /* 降順フラグ     */
            echo $this->tag->hiddenField("koujun_flg") ?>
            <?php /* 範囲自         */
            echo $this->tag->hiddenField("hanni_from") ?>
            <?php /* 範囲自名       */
            echo $this->tag->hiddenField("hanni_from_name") ?>
            <?php /* 範囲至         */
            echo $this->tag->hiddenField("hanni_to") ?>
            <?php /* 範囲至名       */
            echo $this->tag->hiddenField("hanni_to_name") ?>
            <?php /* 税込みフラグ   */
            echo $this->tag->hiddenField("zeikomi_flg") ?>
            <?php /* 明細行表示フラ */
            echo $this->tag->hiddenField("meisaigyou_flg") ?>
            <?php /* 合計行表示フラ */
            echo $this->tag->hiddenField("goukeigyou_flg") ?>
            <?php /* 自入力分フラグ */
            echo $this->tag->hiddenField("jinyuuryoku_flg") ?>
            <?php /* 期間内取引有フ */
            echo $this->tag->hiddenField("torihikiari_flg") ?>
            <?php /* 期間内取引無フ */
            echo $this->tag->hiddenField("torihikinasi_flg") ?>
            <?php /* その他計フラグ */
            echo $this->tag->hiddenField("hokakei_flg") ?>
            <?php /* 前年比較フラグ */
            echo $this->tag->hiddenField("zennnen_flg") ?>

            <div class="col-sm-12">
                <button class="btn btn-warning" onclick="modalstart(jouken_zaiko_modal);return false;">条件設定>8
                </button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <button id="dl-xlsx" class="btn btn-warning">EXCEL出力</button>
            </div>
            <br /><br />
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn  btn-success")) ?>
            </div>
        </div>
    </div><!-- form-group -->
    <?php echo $this->tag->endForm(); ?>
</div>
<?php //var_dump($_POST); //debug?>
<?php if (!isset($_POST['hyouji_kbn'])) $_POST['hyouji_kbn'] = 0; ?>
<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <?php $total = 0; ?>
        <thead>
        <tr bgcolor="White">
            <!-- header1行目は小計 -->
            <th style="text-align:center;background-color: #fef6fe;"></th>
            <th style="text-align:center;background-color: #fef6fe;font-weight: bold;">列計　>></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '11月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '12月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '1月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '2月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '3月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '4月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '5月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '6月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '7月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '8月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '9月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, '10月'));
                if ($_POST['hyouji_kbn'] !== '3') echo number_format($as_total);else echo number_format($as_total,2);
                $total += $as_total;?></th>
            <th style="text-align:right;background-color: #fef6fe;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($total); else echo number_format($total,2)?></th>
        </tr>
        <tr style="background-color: lavender;">
            <th style="text-align:center;">集計キー</th>
            <th style="text-align:center;">キー名称</th>
            <th style="text-align:center;">11月</th>
            <th style="text-align:center;">12月</th>
            <th style="text-align:center;">1月</th>
            <th style="text-align:center;">2月</th>
            <th style="text-align:center;">3月</th>
            <th style="text-align:center;">4月</th>
            <th style="text-align:center;">5月</th>
            <th style="text-align:center;">6月</th>
            <th style="text-align:center;">7月</th>
            <th style="text-align:center;">8月</th>
            <th style="text-align:center;">9月</th>
            <th style="text-align:center;">10月</th>
            <th style="text-align:center;">通期計</th>
        </tr>
        </thead>
        <tbody>
        <?php $shoukei = 0; ?>
        <?php foreach ($rows as $row): ?>
            <tr>
                <td style="text-align:left;"><?php echo $row['集計キー']; ?></td>
                <td style="text-align:left;"><?php echo $row['キー名称']; ?></td>

                <?php
                if ((round((float)$row['11月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['11月']); else echo number_format($row['11月'],2); ?></td>
                <?php $shoukei += (float)$row['11月']; ?>
                <?php
                if ((round((float)$row['12月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['12月']); else echo number_format($row['12月'],2);?></td>
                <?php $shoukei += (float)$row['12月']; ?>
                <?php
                if ((round((float)$row['1月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['1月']); else echo number_format($row['1月'],2); ?></td>
                <?php $shoukei += (float)$row['1月']; ?>
                <?php
                if ((round((float)$row['2月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['2月']); else echo number_format($row['2月'],2);?></td>
                <?php $shoukei += (float)$row['2月']; ?>
                <?php
                if ((round((float)$row['3月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['3月']); else echo number_format($row['3月'],2); ?></td>
                <?php $shoukei += (float)$row['3月']; ?>
                <?php
                if ((round((float)$row['4月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['4月']); else echo number_format($row['4月'],2); ?></td>
                <?php $shoukei += (float)$row['4月']; ?>
                <?php
                if ((round((float)$row['5月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['5月']); else echo number_format($row['5月'],2);?></td>
                <?php $shoukei += (float)$row['5月']; ?>
                <?php
                if ((round((float)$row['6月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['6月']); else echo number_format($row['6月'],2);?></td>
                <?php $shoukei += (float)$row['6月']; ?>
                <?php
                if ((round((float)$row['7月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['7月']); else echo number_format($row['7月'],2);?></td>
                <?php $shoukei += (float)$row['7月']; ?>
                <?php
                if ((round((float)$row['8月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['8月']); else echo number_format($row['8月'],2);?></td>
                <?php $shoukei += (float)$row['8月']; ?>
                <?php
                if ((round((float)$row['9月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['9月']); else echo number_format($row['9月'],2);?></td>
                <?php $shoukei += (float)$row['9月']; ?>
                <?php
                if ((round((float)$row['10月'], 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($row['10月']); else echo number_format($row['10月'],2);?></td>
                <?php $shoukei += (float)$row['10月']; ?>
                <?php
                if ((round((float)$shoukei, 4)) < 0.000) {
                    $color = 'red';
                } else {
                    $color = 'black';
                }
                ?>
                <td style="text-align:right;color:<?php echo $color; ?>;"><?php if ($_POST['hyouji_kbn'] !== '3') echo number_format($shoukei); else echo number_format($shoukei,2);?></td>
                <?php $shoukei = 0; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="col-sm-2">
        <button type="button" class="btn btn-default" id="ESC" data-dismiss="modal"
                onclick="window.parent.fromModal();">中止
        </button>
    </div>
</div>
<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle" style="width:900px; height:500px;">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        在庫推移表条件設定
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    var jouken_zaiko_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_zaiko_suiis/ajaxGet') ?>";
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
    var junjo_kbns_ajaxHanni = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('junjo_kbns/ajaxHanni') ?>";
    var jouken_zaiko_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_zaiko_suiis/modal') ?>";
    var jouken_flds = ['torihiki_kbn_betu_flg'
        , 'junjo_kbn_cd'
        , 'torihiki_kbn_cd'
        , 'koujun_flg'
        , 'hanni_from'
        , 'hanni_from_name'
        , 'hanni_to'
        , 'hanni_to_name'
        , 'zeikomi_flg'
        , 'meisaigyou_flg'
        , 'goukeigyou_flg'
        , 'torihikiari_flg'
        , 'torihikinasi_flg'
        , 'hokakei_flg'
        , 'zennnen_flg'
    ];
</script>
<script>
    $(function () {
        $('table.head_fix').floatThead({
            top: 50
        });
    });
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/report_zaiko_suiis.js'); ?>?var=20191105"></script>
