<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "移出記録.一覧"; ?>
<div class="page-header">
    <h3>移出記録 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"export_yy_logs","flds"=>[
        ["cd","fieldCd","コード",14,14],["name","fieldName","名称",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","対象コード"],
                    ["name","弥生伝票番号最終"],
                    ["time_from","前回日時"],
                    ["time_to","今回日時"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $export_yy_log): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("export_yy_logs/edit/" . $export_yy_log->id, $export_yy_log->id)); ?></td>
                <td><?php echo $export_yy_log->cd ?></td>
                <td><?php echo $export_yy_log->name ?></td>
                <td><?php echo $export_yy_log->time_from ?></td>
                <td><?php echo $export_yy_log->time_to ?></td>
                <td><?php echo $export_yy_log->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("export_yy_logs/delete/" . $export_yy_log->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"export_yy_logs"]) ?>
