<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "移出記録.新規"; ?>
<div class="page-header">
    <h3>移出記録 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "export_yy_logs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
<label for="fieldCd" class="col-sm-2 control-label">対象コード</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cd", "size" => 10, "maxlength" => 10, "style" => "width: 156px;", "class" => "form-control", "id" => "fieldCd")) ?>
    </div>

<label for="fieldName" class="col-sm-2 control-label">弥生伝票番号最終</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "type" => "number", "style" => "width: 156px;", "class" => "form-control", "id" => "fieldName")) ?>
    </div>

<label for="fieldTimeFrom" class="col-sm-2 control-label">前回日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("time_from", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldTimeFrom")) ?>
    </div>

<label for="fieldTimeTo" class="col-sm-2 control-label">今回日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("time_to", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldTimeTo")) ?>
    </div>

<label for="fieldUpdated" class="col-sm-2 control-label">更新日時</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 17, "maxlength" => 17, "style" => "width: 240px;", "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>

</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
