<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php $title = "移出.新規"; ?>
<div class="page-header">
    <h3>エクスポート 実行</h3>
</div>

<?php echo $this->getContent(); ?>
 <style scoped>
 	th,td{
 		text-align:center;
	}
 </style>

<div class="row">
 <div class="col-sm-6">
	<?php
	    echo $this->tag->form(
	        array(
	            "exports/index/shiire",
	            "autocomplete" => "off",
	            "class" => "form-horizontal"
	        )
	    );
	?>
	<h1>仕入エクスポート</h1>

	<div class="form-group">
	<label for="fieldYayoiDenNo" class="col-sm-4 control-label">弥生伝票番号最終</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("yayoi_den_no", "size" => 9, "maxlength" => 9, "style" => "width: 100px;", "class" => "form-control ime-d f-cent", "id" => "fieldYayoiDenNo")) ?>
	    </div>

	<label for="fieldTimeFrom" class="col-sm-4 control-label">前回出力日時</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("time_from", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldTimeFrom")) ?>
	    </div>

	<label for="fieldTimeTo" class="col-sm-4 control-label">今回出力日時</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("time_to", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldTimeTo")) ?>
	    </div>

	</div>

	<div class="form-group">
	    <div class="col-sm-offset-4 col-sm-8">
	        <?php echo $this->tag->submitButton(array("移出実行F11", "id" => "F11", "disabled"=>"true", "class" => "btn  btn-info", "onclick" => 'return confirm("よろしいですか？");')) ?>
	    </div>
	</div>

	<?php echo $this->tag->endForm(); ?>
 </div>
 <div class="col-sm-6">
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>入力弥生伝票番号</th>
                <th>前回日時</th>
                <th>今回日時</th>
                <th>移出日時</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($export_yy_logs as $export_yy_log): ?>
            <tr>
                <td><?php echo $export_yy_log->name ?></td>
                <td><?php echo $export_yy_log->time_from ?></td>
                <td><?php echo $export_yy_log->time_to ?></td>
                <td><?php echo $export_yy_log->updated ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
 </div>
</div>
<p>

<div class="row">
 <div class="col-sm-6">
	<?php
	    echo $this->tag->form(
	        array(
	            "exports/index/uriage",
	            "autocomplete" => "off",
	            "class" => "form-horizontal"
	        )
	    );
	?>
	<h1>売上エクスポート</h1>

	<div class="form-group">
	<label for="fieldUriYayoiDenNo" class="col-sm-4 control-label">弥生伝票番号最終</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("uri_yayoi_den_no", "size" => 9, "maxlength" => 9, "style" => "width: 100px;", "class" => "form-control ime-d f-cent", "id" => "fieldUriYayoiDenNo")) ?>
	    </div>

	<label for="fieldUriTimeFrom" class="col-sm-4 control-label">前回出力日時</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("uri_time_from", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldUriTimeFrom")) ?>
	    </div>

	<label for="fieldUriTimeTo" class="col-sm-4 control-label">今回出力日時</label>
	    <div class="col-sm-8">
	        <?php echo $this->tag->textField(array("uri_time_to", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldUriTimeTo")) ?>
	    </div>

	</div>

	<div class="form-group">
	    <div class="col-sm-offset-4 col-sm-8">
	        <?php echo $this->tag->submitButton(array("移出実行F12", "id" => "F12", "disabled"=>"true", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
	    </div>
	</div>

	<?php echo $this->tag->endForm(); ?>
 </div>
 <div class="col-sm-6">
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>入力弥生伝票番号</th>
                <th>前回日時</th>
                <th>今回日時</th>
                <th>移出日時</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($uri_export_yy_logs as $export_yy_log): ?>
            <tr>
                <td><?php echo $export_yy_log->name ?></td>
                <td><?php echo $export_yy_log->time_from ?></td>
                <td><?php echo $export_yy_log->time_to ?></td>
                <td><?php echo $export_yy_log->updated ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
 </div>
</div>

<script>
	$('#fieldYayoiDenNo').change(function() {
		$("#F11").prop("disabled", !( $(this).val().match(/^[0-9]+$/) ));
	});
	$('#fieldUriYayoiDenNo').change(function() {
		$("#F12").prop("disabled", !( $(this).val().match(/^[0-9]+$/) ));
	});
</script>
