<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var array $export_yy_logs
 * @var array $nyuukin_export_yy_logs
 * @var array $nyuukin_export_yy_logs
 */
$title = "入金・出金エクスポートデータ作成";
?>
<div class="page-header">
    <h2>入金・出金エクスポートデータ作成</h2>
</div>
<?php echo $this->getContent(); ?>
<style scoped>
    th, td {
        text-align: center;
    }
</style>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->tag->form(
            array(
                "exports/nyuushu_exports/shukkin",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            )
        );
        ?>
        <h4>出金エクスポートデータ作成</h4>
        <div class="form-group">
            <label for="fieldShukkinTimeFrom" class="col-sm-4 control-label">前回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("shukkin_time_from", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldShukkinTimeFrom")) ?>
            </div>

            <label for="fieldShukkinTimeTo" class="col-sm-4 control-label">今回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("shukkin_time_to", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldShukkinTimeTo")) ?>
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <?php echo $this->tag->submitButton(array("移出実行F11", "id" => "F11", "class" => "btn  btn-info", "onclick" => 'return confirm("よろしいですか？");')) ?>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>
    </div>
    <div class="col-sm-6">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>隼伝票番号</th>
                <th>～番号</th>
                <th>前回日時</th>
                <th>今回日時</th>
                <th>移出日時</th>
            </tr>
            </thead>
            <tbody>
            <?php if (isset($export_yy_logs)): ?>
                <?php foreach ($export_yy_logs as $export_yy_log): ?>
                    <tr>
                        <td><?php echo $export_yy_log->name ?></td>
                        <td><?php echo $export_yy_log->den_no_to ?></td>
                        <td><?php echo $export_yy_log->time_from ?></td>
                        <td><?php echo $export_yy_log->time_to ?></td>
                        <td><?php echo $export_yy_log->updated ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
<p>

<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->tag->form(
            array(
                "exports/nyuushu_exports/nyuukin",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            )
        );
        ?>
        <h4>入金エクスポートデータ作成</h4>
        <div class="form-group">
            <label for="fieldNyuukinTimeFrom" class="col-sm-4 control-label">前回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("nyuukin_time_from", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldNyuukinTimeFrom")) ?>
            </div>

            <label for="fieldNyuukinTimeTo" class="col-sm-4 control-label">今回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("nyuukin_time_to", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldNyuukinTimeTo")) ?>
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <?php echo $this->tag->submitButton(array("移出実行F12", "id" => "F12", "class" => "btn  btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
            </div>
        </div>
        <?php echo $this->tag->endForm(); ?>
    </div>
    <div class="col-sm-6">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>隼伝票番号</th>
                <th>～番号</th>
                <th>前回日時</th>
                <th>今回日時</th>
                <th>移出日時</th>
            </tr>
            </thead>
            <tbody>
            <?php if (isset($nyuukin_export_yy_logs)): ?>
                <?php foreach ($nyuukin_export_yy_logs as $export_yy_log): ?>
                    <tr>
                        <td><?php echo $export_yy_log->name ?></td>
                        <td><?php echo $export_yy_log->den_no_to ?></td>
                        <td><?php echo $export_yy_log->time_from ?></td>
                        <td><?php echo $export_yy_log->time_to ?></td>
                        <td><?php echo $export_yy_log->updated ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

