<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var array $export_sagawa_logs
 */
$title = "送り状データ作成";
?>

<div class="page-header">
    <h2>送り状データ作成</h2>
</div>
<?php echo $this->getContent(); ?>
<style scoped>
    th, td {
        text-align: center;
    }
</style>
<div class="row">
    <div class="col-sm-6">
        <?php
        echo $this->tag->form(
            array(
                "exports/okurijou/sagawa",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            )
        );
        ?>
        <h3>佐川送り状データ作成</h3>

        <div class="form-group">
            <label for="fieldTimeFrom" class="col-sm-4 control-label">前回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("time_from", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldTimeFrom")) ?>
            </div>

            <label for="fieldTimeTo" class="col-sm-4 control-label">今回出力日時</label>
            <div class="col-sm-8">
                <?php echo $this->tag->textField(array("time_to", "size" => 30, "maxlength" => 30, "style" => "width: 160px;", "class" => "form-control ime-d f-cent", "id" => "fieldTimeTo")) ?>
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <?php echo $this->tag->submitButton(array("移出実行F11", "id" => "F11", "class" => "btn  btn-info", "onclick" => 'return confirm("よろしいですか？");')) ?>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>
    </div>
    <div class="col-sm-6">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>隼伝票番号</th>
                <th>～番号</th>
                <th>前回日時</th>
                <th>今回日時</th>
                <th>移出日時</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($export_sagawa_logs as $export_sagawa_log): ?>
                <tr>
                    <td><?php echo $export_sagawa_log->name ?></td>
                    <td><?php echo $export_sagawa_log->den_no_to ?></td>
                    <td><?php echo $export_sagawa_log->time_from ?></td>
                    <td><?php echo $export_sagawa_log->time_to ?></td>
                    <td><?php echo $export_sagawa_log->updated ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

