<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $title = "入金伝票.一覧"; ?>
<div class="page-header">
    <h3>入金伝票 一覧表（検索結果）</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <?php $this->partial("common/indexkanni",["table_id"=>"nyuukin_dts","flds"=>[
        ["cd","fieldCd","伝票番号",14,14],["name","fieldName","摘要",24,24]
    ]]) ?>
    <table class="table table-bordered table-hover table-condensed">
        <thead>
            <tr>
<?php $this->partial("common/indexsort",["flds"=>[
                    ["id","Id"],
                    ["cd","伝票番号"],
                    ["name","摘要"],
                    ["nyuukinbi","入金日"],
                    ["seikyuusaki_mr_cd","請求先"],
                    ["tantou_mr_cd","担当者"],
                    ["updated","更新日時"],
                ]]) ?>

                <th>削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $nyuukin_dt): ?>
            <tr>
                <td><?php echo $this->tag->linkTo(array("nyuukin_dts/edit/" . $nyuukin_dt->id, $nyuukin_dt->id)); ?></td>
                <td><?php echo $nyuukin_dt->cd ?></td>
                <td><?php echo $nyuukin_dt->name ?></td>
                <td><?php echo $nyuukin_dt->nyuukinbi ?></td>
                <td><?php echo $nyuukin_dt->seikyuusaki_mr_cd ?></td>
                <td><?php echo $nyuukin_dt->tantou_mr_cd ?></td>
                <td><?php echo $nyuukin_dt->updated ?></td>

                <td><?php echo $this->tag->linkTo(array("nyuukin_dts/delete/" . $nyuukin_dt->id, "削除", "onclick" => 'return confirm("よろしいですか？");')); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->partial("common/indextail",["table_id"=>"nyuukin_dts"]) ?>
