<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var integer $imax
 */
?>

<?php $title = "入金.新規"; ?>
<div class="page-header">
    <h3>入金伝票 新規登録</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "nyuukin_dts/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">

    <?php $this->partial('nyuukin_dts/inputfields'); ?>

    <div class="col-sm-offset-2 col-sm-10" style="padding: 5px 0 0;">
        <?php echo $this->tag->submitButton(array("実行f12", "id" => "F12", "class" => "btn btn-success", "onclick" => 'return confirm("よろしいですか？");')) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<script type="text/javascript">var imax = <?php echo $imax ?>;</script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/nyuukin_dts.js'); ?>?var=20210210"></script>
