<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
/** @var array $joukens */
/** @var array $rows */
?>
<?php use Phalcon\Tag; ?>
<?php $title = '売掛残高一覧表'; ?>
<div class="page-header">
    <h3>売掛残高一覧表</h3>
</div>

<?php echo $this->getContent(); ?>

<div class="panel panel-success bg-yel">
    <br>
    <?php
    echo $this->tag->form(
        array(
            "nyuukin_dts/urikake_zandaka",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "name" => "form_jouken"
        )
    );
    ?>
    <div class="form-group">
        <div class="col-sm-10">
            <label for="fieldCd" class="col-sm-2 control-label">条件名</label>
            <div class="col-sm-10">
                <?php echo $this->tag->selectStatic(array("cd", $joukens, "style" => "width: 260px;", "class" => "form-control", "id" => "fieldCd")) ?>
            </div>
            <br /><br />
            <label for="fieldKikanSiteiKbnCd" class="col-sm-2 control-label">期間</label>
            <div class="col-sm-2">
                <?php echo $this->tag->select(array("kikan_sitei_kbn_cd", KikanSiteiKbns::find(["columns" => "cd , name", "order" => "cd", "conditions" => "yobidasi_tbl='jouken_urikake_zandakas'"]), "using" => array("cd", "name"), 'useEmpty' => true, 'emptyText' => '', "style" => "width: 130px;", "class" => "form-control", "id" => "fieldKikanSiteiKbnCd")) ?>
            </div>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_from", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanFrom")) ?>
            </div>

            <label for="fieldKikanTo" class="col-sm-1 control-label">～</label>
            <div class="col-sm-2">
                <?php echo $this->tag->telField(array("kikan_to", "size" => 10, "maxlength" => 10, "class" => "form-control f-cent ime-d", "id" => "fieldKikanTo")) ?>
            </div>

        </div>
        <div class="col-sm-2">
            <?php /* 取引区分別     */
            echo $this->tag->hiddenField("torihiki_kbn_betu_flg") ?>
            <?php /* 順序区分コード */
            echo $this->tag->hiddenField("junjo_kbn_cd") ?>
            <?php /* 順序区分テーブル */
            echo $this->tag->hiddenField("junjo_kbn_table") ?>
            <?php /* 降順フラグ     */
            echo $this->tag->hiddenField("koujun_flg") ?>
            <?php /* 範囲自         */
            echo $this->tag->hiddenField("hanni_from") ?>
            <?php /* 範囲自名       */
            echo $this->tag->hiddenField("hanni_from_name") ?>
            <?php /* 範囲至         */
            echo $this->tag->hiddenField("hanni_to") ?>
            <?php /* 範囲至名       */
            echo $this->tag->hiddenField("hanni_to_name") ?>
            <?php /* 税込みフラグ   */
            echo $this->tag->hiddenField("zeikomi_flg") ?>
            <?php /* 明細行表示フラ */
            echo $this->tag->hiddenField("meisaigyou_flg") ?>
            <?php /* 合計行表示フラ */
            echo $this->tag->hiddenField("goukeigyou_flg") ?>
            <?php /* 自入力分フラグ */
            echo $this->tag->hiddenField("jinyuuryoku_flg") ?>
            <?php /* 期間内取引有フ */
            echo $this->tag->hiddenField("torihikiari_flg") ?>
            <?php /* 期間内取引無フ */
            echo $this->tag->hiddenField("torihikinasi_flg") ?>
            <?php /* その他計フラグ */
            echo $this->tag->hiddenField("hokakei_flg") ?>
            <div class="col-sm-12">
                <button class="btn btn-warning" onclick="modalstart(jouken_urikake_zandakas_modal);return false;">条件設定>8</button>
            </div>
            <br/><br/>
            <div class="col-sm-12">
                <button id="dl-xlsx" class="btn btn-warning">EXCEL出力</button>
            </div>
            <br/><br/>
            <div class="col-sm-12">
                <?php echo $this->tag->submitButton(array("集計f12", "id" => "F12", "class" => "btn btn-lg btn-success")) ?>
            </div>
        </div>
    </div><!-- form-group -->

    <?php echo $this->tag->endForm(); ?>
</div><!-- panel-successp -->

<div class="row">
    <table class="table table-bordered table-hover table-condens-0 table-striped head_fix">
        <?php $total = 0; ?>
        <thead>
        <?php if ($this->request->getPost('goukeigyou_flg') === '1'): ?>
            <tr style="background-color: White;">
                <th colspan="2" style="text-align:center;background-color: #fef6fe;font-weight: bold;">列計　>></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'zengetsumatsu_zan')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_tou_nyuukingaku')); echo number_format($as_total); ?></th>
                <th style="text-align:center;background-color: #fef6fe;">-</th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'tougetu_kakeuriage')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'um_tou_zeigaku')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'tougetsumatsu_zan')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_genkin')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_hurikomi')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_tesuuryou')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_tegata')); echo number_format($as_total); ?></th>
                <th style="text-align:right;background-color: #fef6fe;"><?php $as_total = array_sum(array_column($rows, 'nm_sonota')); echo number_format($as_total); ?></th>
            </tr>
        <?php endif; ?>
        <tr style="background-color: lavender;">
            <th style="text-align:center;">請求先コード</th>
            <th style="text-align:center;">請求先名称</th>
            <th style="text-align:center;">前月末残高</th>
            <th style="text-align:center;">当月回収額</th>
            <th style="text-align:center;">回収率(%)</th>
            <th style="text-align:center;">当月掛売上</th>
            <th style="text-align:center;">内消費税額</th>
            <th style="text-align:center;">当月末残高</th>
            <th style="text-align:center;">現金</th>
            <th style="text-align:center;">振込</th>
            <th style="text-align:center;">手数料</th>
            <th style="text-align:center;">手形</th>
            <th style="text-align:center;">その他</th>
        </tr>
        </thead>
        <tbody>
            <?php if ($this->request->getPost('meisaigyou_flg') === '1'): ?>
                <?php $i = 0; ?>
                <?php foreach ($rows as $row): ?>
                <?php
                    // 取引無を表示しない
                    if ($this->request->getPost('torihikinasi_flg') === '0' && (int)$row['nm_tou_nyuukingaku'] === 0 && (int)$row['tougetu_kakeuriage'] === 0 && (int)$row['tougetsumatsu_zan'] === 0) {
                        continue;
                    }
                    // 取引ありを表示しない
                    if ($this->request->getPost('torihikiari_flg') === '0' && ((int)$row['nm_tou_nyuukingaku'] !== 0 || (int)$row['tougetu_kakeuriage'] !== 0)) {
                        continue;
                    }
                    ?>
                    <tr>
                        <td style="text-align: center;cursor: pointer;color: blue;" id="tokuisaki_cd<?php echo $i;?>" class="tokuisaki_cd"><?php echo $row['tokuisaki_mr_cd']; ?></td>
                        <td style="text-align:left;"><?php echo $row['name']; ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['zengetsumatsu_zan'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['zengetsumatsu_zan']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_tou_nyuukingaku'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_tou_nyuukingaku']); ?></td>
                        <td style="text-align:right;"><?php
                            if ((int)$row['zengetsumatsu_zan'] != 0 && (int)$row['nm_tou_nyuukingaku'] != 0) {
                                echo number_format((((int)$row['nm_tou_nyuukingaku']/(int)$row['zengetsumatsu_zan']) * 100), 1);
                            } else {
                                echo 0.0;
                            } ?>
                        </td>
                        <td style="text-align:right;color:<?php echo (int)$row['tougetu_kakeuriage'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['tougetu_kakeuriage']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['um_tou_zeigaku'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['um_tou_zeigaku']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['tougetsumatsu_zan'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['tougetsumatsu_zan']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_genkin'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_genkin']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_hurikomi'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_hurikomi']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_tesuuryou'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_tou_nyuukingaku']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_tegata'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_tegata']); ?></td>
                        <td style="text-align:right;color:<?php echo (int)$row['nm_sonota'] < 0 ? 'red' : 'black'; ?>;"><?php echo number_format($row['nm_sonota']); ?></td>
                    </tr>
                <?php $i++; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>

<div id="iframe-bg" class="bgStyle"></div>
<div id="iframe-wrap" class="wrapStyle" style="width:900px; height:500px;">
    <div class="modal-header" style="padding: 5px; background-color: #ddd;">
        売掛残高一覧表・条件設定
        <button type="button" class="close" data-dismiss="modal"><span>　×　</span></button>
    </div>
    <div id="iframe-body" class="modal-body" style="width: 100%; height: 97%; padding: 0;">
    </div>
</div>

<script type="text/javascript">
    var tokuisaki_motochou = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('tokuisaki_mrs/motochou') ?>";
    var jouken_urikake_zandakas_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_urikake_zandakas/ajaxGet') ?>";
    var kikan_sitei_kbns_ajaxGet = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('kikan_sitei_kbns/ajaxGet') ?>";
    var junjo_kbns_ajaxHanni = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('junjo_kbns/ajaxHanni') ?>";
    var jouken_urikake_zandakas_modal = "<?php echo '//' . $_SERVER['SERVER_NAME'] . $this->url->get('jouken_urikake_zandakas/modal') ?>";
    var jouken_flds = ['torihiki_kbn_betu_flg'
        , 'junjo_kbn_cd'
        , 'torihiki_kbn_cd'
        , 'koujun_flg'
        , 'hanni_from'
        , 'hanni_from_name'
        , 'hanni_to'
        , 'hanni_to_name'
        , 'zeikomi_flg'
        , 'meisaigyou_flg'
        , 'goukeigyou_flg'
        , 'torihikiari_flg'
        , 'torihikinasi_flg'
        , 'hokakei_flg'
    ];
</script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script type="text/javascript" src="<?php echo $this->url->get('js/views/urikake_zandakas.js'); ?>?var=20200929"></script>
